### ISSUE TITLE
state machine crashes when background is selected

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#10]
On 'dev' branch.
- launch i-score.
- click outside the main box (e.g.  in the area at the bottom). The border should disappear.
- then try to change edition mode (e.g. from select to move)
- SEGFAULT

0   QMetaObject::activate(QObject_, int, int, void__)   /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Core.so.5     0x7ffff6518d66  
1   ScenarioStateMachine::exitState moc_ScenarioStateMachine.cpp    230 0x7fffd84a0e8d  
2   ScenarioStateMachine::changeTool    ScenarioStateMachine.cpp    155 0x7fffd840b361  
3   ScenarioControl::<lambda()>::operator()(void) const ScenarioControl.cpp 324 0x7fffd8423154  
4   QtPrivate::FunctorCallQtPrivate::IndexesList<, QtPrivate::List<>, void, ScenarioControl::makeToolbars()::<lambda()>>::call(ScenarioControl::<lambda()>, void *_)  qobjectdefs_impl.h  494 0x7fffd8426d87  
5   QtPrivate::FunctorScenarioControl::makeToolbars()::<lambda(), 0>::callQtPrivate::List<, void>(ScenarioControl::<lambda()> &, void _, void *_)   qobjectdefs_impl.h  551 0x7fffd8426a1a  
6   QtPrivate::QFunctorSlotObjectScenarioControl::makeToolbars()::<lambda(), 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase _, QObject *, void *_, bool _) qobject_impl.h  192 0x7fffd8426595  
7   QMetaObject::activate(QObject_, int, int, void**)   /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Core.so.5     0x7ffff65191d5  
8   QAction::triggered(bool)    /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff73826b2  
9   QAction::activate(QAction::ActionEvent) /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff73844d7  
10  ??  /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff748e8c5  
11  QAbstractButton::mouseReleaseEvent(QMouseEvent_)    /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff748eb84  
12  QToolButton::mouseReleaseEvent(QMouseEvent_)    /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff75531fa  
13  QWidget::event(QEvent_) /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff73cab9c  
14  QToolButton::event(QEvent_) /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff7554090  
15  QApplicationPrivate::notify_helper(QObject_, QEvent_)   /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff738f2b4  
16  QApplication::notify(QObject_, QEvent_) /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff7392a4c  
17  QCoreApplication::notifyInternal(QObject_, QEvent_) /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Core.so.5     0x7ffff64e6e24  
18  QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget**, QPointer<QWidget>&, bool)    /home/nicolas/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5      0x7ffff7391978  
... <plus>

**Comment by jcelerier** [comment]
f38de89821e9ba5098c7f46ddb69a57637aabad0 should fix this
