### ISSUE TITLE
2.5 series will not start on win10 pro 64 bit

### ISSUE THREAD

**Issue by rcrath** [ossia/score#1001]
Hi, I can start 2.4.1 with no issues, but neither 2.5.2 nor 2.5.2 will load.  They just fail silently.  I have not been able to locate any startup options or log files so can't provide more info at this time. 3.0 alpha also starts fine.

**Comment by jcelerier** [comment]
Hello,
this is strange, starts fine here. Do you think you could enable crashdumps and send me one ? 

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

thanks !

**Comment by rcrath** [comment]
sure.

**Comment by rcrath** [comment]
no support for .dmp files here, so go to http://way.net/temp2/ossia .  I'll keep files there for the time being.

**Comment by jcelerier** [comment]
thanks, I downloaded it, you can free your disk space :p

**Comment by tarnith** [comment]
Can confirm, on Windows 10 Pro x64 

Let me know if you need a .dmp

[ossia 2.5.2 error.txt](https://github.com/OSSIA/score/files/4365413/ossia.2.5.2.error.txt)

**Comment by rcrath** [comment]
I downloaded 3 alpha and it works on wondows.  I don't have any previous stuff so I'll go with the version 3 and see if it crashes much as I learn it. a release or two before this works on windows as a workaround, so I'm closing this as I assume your energies are going to v. 3 at this point.

**Comment by jcelerier** [comment]
sorry, I've been trying to pinpoint this issue but couldn't so far - I even reinstalled a clean win10 pro in a VM to check but could not get it to crash (and inspecting the crash log only yielded a stack trace that was "not in my code")

**Comment by rcrath** [comment]
I'm keeping 2.4X around.  and taking my chances with 3. Maybe dmp from @tarnith would help for comparison?
