### ISSUE TITLE
The painting of conditions is ugly

### ISSUE THREAD

**Issue by aklevy** [ossia/score#1002]
The painting of conditions is ugly as there is no antialiasing.

**Comment by bltzr** [comment]
<div class="tenor-gif-embed" data-postid="4949558" data-share-method="host" data-width="100%" data-aspect-ratio="1.78494623655914"><a href="https://tenor.com/view/shame-go-t-game-of-thrones-walk-of-shame-shameful-gif-4949558">Shame Go T GIF</a> from <a href="https://tenor.com/search/shame-gifs">Shame GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by jcelerier** [comment]
should be fixed now
