### ISSUE TITLE
Does not play

### ISSUE THREAD

**Issue by ataut** [ossia/score#1004]
Dear Ossia, 
I'm sorry for this issue from a new user. I have downloaded v. 2.5.2 and am running on MacOS 10.14.4 on 2017 MB Pro 15" (3.1GHz i7, 16GB RAM). I have started up the software and am following the First Steps, Time Approach (https://ossia.github.io/score/first_steps/time_approach/index.html), however, contrary to what is stated in Let the Time Flow, clicking on Play does not start the sequencer. The green bar in the timeline does not progress.
Strangely, I have been able to record incoming data, following Tutorial 5 Recording External Parameters (https://ossia.io/2016/04/10/5-recording-external-parameters-with-score/
). I successfully get a graphic representation of two incoming OSC messages and they draw into a box. However, I have no way to play it back.

Meanwhile, I have downloaded v. 1.00-b38 onto another machine (MacOS 10.11.6 running on an old MacBook Air 11" 1.7GHz i7, 8GM RAM). Here the software works as advertised - I run the application, and hit the space bar, and the green progress bar moves to the right. 

Is there a problem is v. 2.5.2 on 10.14.4? Thank you and I hope all is ok in the pandemic.
Cordialement,
Atau TANAKA
Londres

**Comment by jcelerier** [comment]
Hello ! 
The main reason for playback to not work is for the soundcard detection to have failed. 
There should be an on-off icon on the bottom right of the software next to the volume control - it should be on the "on" state, like this : 

![ok](https://user-images.githubusercontent.com/2772730/78187147-33a69080-746e-11ea-8dd7-49198a4f7e98.png)

If it's not the case then could you check the settings, "audio" tab ? there it should list CoreAudio and your sound card if everything is fine.

**Comment by ataut** [comment]
That was it! I had no external audio interface, but I have been playing around with Blackhole and making Aggregated Audio devices in the system. Still at the time I launched Score, my system default was set to Built In Mic and Output. The audio settings showed a blank for the drop down menu (not even Dummy). I selected Core Audio and all is fine. Thanks for the quick response!

**Comment by ataut** [comment]
Hello again,
I hope it's ok, but I had a few more beginner's remarks.
I'm following "[Write your first scenario](https://ossia.github.io/score/first_steps/first_scenario/index.html)" and have successfully added a device. however, where you speak of a "load" button in the device edit window, I don't have this button (screenshot here)
<img width="408" alt="Screenshot 2020-04-02 at 22 32 55" src="https://user-images.githubusercontent.com/32303621/78302039-fb688600-7531-11ea-8568-5feccb6bd4da.png">

 That's ok, I manually added a child (a float) and set it's initial state. I am able to drag the float into the timeline, set values, and create Processes to fade between values. I successfully received these values in my MaxMSP patch on Port 9996. 

I then moved to the [Record tutorial ](https://ossia.io/2016/04/10/5-recording-external-parameters-with-score/), and moved a slider in Max, sending on port 9997, and successfully did a "Record Automation from here" in the middle of the timeline and see a curve. I would now like to play this back on the same float child from above.  But I cannot figure out how to connect the recorded block to the running time. There's nothing I do that makes the green progress bar grow into this recorded block. How do I make this connection?

thanks in advance and apologies for these very basic questions.
Atau

**Comment by jcelerier** [comment]
> however, where you speak of a "load" button in the device edit window, I don't have this button (screenshot here)

oops, the tutorial should be updated...  now loading is done by double-clicking on the device file on the library (or dropping it from the outside on the explorer iirc).
@thibaudk or @jln- do you think you could update it if you have some time ?


![device](https://user-images.githubusercontent.com/2772730/78339512-dd803d00-7594-11ea-8b40-77aca41f057a.gif)

> I then moved to the Record tutorial , and moved a slider in Max, sending on port 9997, and successfully did a "Record Automation from here" in the middle of the timeline and see a curve. I would now like to play this back on the same float child from above. But I cannot figure out how to connect the recorded block to the running time. There's nothing I do that makes the green progress bar grow into this recorded block. How do I make this connection?

So I guess you are now in this situation : 
![image](https://user-images.githubusercontent.com/2772730/78339716-351ea880-7595-11ea-898d-8e2bd5f02161.png)

What has to be done to link something to the timeline is to choose the "create" tool in the top bar (shortcut "C") and drag from it like this : 

![screen2](https://user-images.githubusercontent.com/2772730/78340026-b5450e00-7595-11ea-8027-456b1b27e36d.gif)

Another possibility which is I think not in the tutorial is triggering things out-of-time. This is done by adding a trigger which allows to trigger it by hand (or with an OSC message) :

![screen3](https://user-images.githubusercontent.com/2772730/78340281-1bca2c00-7596-11ea-9e71-bdf83e7a92ba.gif)
 

But the user experience for this could clearly be improved as you are definitely not the first to stumble on this and we aim for good accessibility :) 

(The UI will be a bit different in your version vs my screenshots as I did them with the latest alpha, hope that's ok.)

**Comment by ataut** [comment]
That works, thank you! Next, to synch an audio track...
