### ISSUE TITLE
Setting pretty names for JACK ports?

### ISSUE THREAD

**Issue by mxmilkiib** [ossia/score#1007]
Using JACK [pretty-name](https://jackaudio.org/metadata/pretty-name/) [metadata](https://jackaudio.org/metadata/).

**Comment by thibaudk** [comment]
regarding #1006 & #982 also,
I think score, and the projects crated with it, would greatly benefit
from beeing "Jack Aware" like Ardour is, alowing to save a jack patcbay with the scenario
