### ISSUE TITLE
This score project has issues / will crash

### ISSUE THREAD

**Issue by maybites** [ossia/score#1012]
Hi

consider following score project with 2.5.2 and OSX 10.15.4

[sparckScore2.score.zip](https://github.com/OSSIA/score/files/4645615/sparckScore2.score.zip)

1. it is not possible to remove a process / any element / anymore. 
2. when entering Interval.bras55 one will notice that the curve is not complete anymore. Once one tries to edit the curve, score will crash
2.1. this curve happend when I dragged a curvepoint with surpressed on overlap switched on.

here the crashed thread:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.score                     	0x000000010a806c41 void multi_index::detail::allocator::destroy<Curve::SegmentData>(Curve::SegmentData const*) + 97
1   org.score                     	0x000000010a7f1279 Curve::MovePointCommandObject::move() + 601
2   org.qt-project.QtCore         	0x000000011102de34 QMetaObject::activate(QObject*, int, int, void**) + 4276
3   org.qt-project.QtCore         	0x00000001110ca066 QStateMachinePrivate::enterStates(QEvent*, QList<QAbstractState*> const&, QList<QAbstractState*> const&, QSet<QAbstractState*> const&, QHash<QAbstractState*, QVector<QPropertyAssignment> >&, QList<QAbstractAnimation*> const&) + 918
4   org.qt-project.QtCore         	0x00000001110d28e1 QStateMachinePrivate::microstep(QEvent*, QList<QAbstractTransition*> const&, CalculationCache*) + 1041
5   org.qt-project.QtCore         	0x00000001110d1627 QStateMachinePrivate::_q_process() + 823
6   org.qt-project.QtCore         	0x000000011102b8ba QObject::event(QEvent*) + 426
7   org.qt-project.QtCore         	0x00000001110e5691 QStateMachine::event(QEvent*) + 785
8   org.qt-project.QtWidgets      	0x00000001114a79b4 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 324
9   org.qt-project.QtWidgets      	0x00000001114a43cb QApplication::notify(QObject*, QEvent*) + 587
10  org.score                     	0x000000010a6e4125 SafeQApplication::notify(QObject*, QEvent*) + 21
11  org.qt-project.QtCore         	0x0000000110ffcb2c QCoreApplication::notifyInternal2(QObject*, QEvent*) + 188
12  org.qt-project.QtCore         	0x0000000110ffd515 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 1189
13  libqcocoa.dylib               	0x0000000113833c79 0x1137fa000 + 236665
14  libqcocoa.dylib               	0x0000000113834263 0x1137fa000 + 238179
15  com.apple.CoreFoundation      	0x00007fff36dd8f12 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
16  com.apple.CoreFoundation      	0x00007fff36dd8eb1 __CFRunLoopDoSource0 + 103
17  com.apple.CoreFoundation      	0x00007fff36dd8ccb __CFRunLoopDoSources0 + 209
18  com.apple.CoreFoundation      	0x00007fff36dd79fa __CFRunLoopRun + 927
19  com.apple.CoreFoundation      	0x00007fff36dd6ffe CFRunLoopRunSpecific + 462
20  com.apple.HIToolbox           	0x00007fff35a0aabd RunCurrentEventLoopInMode + 292
21  com.apple.HIToolbox           	0x00007fff35a0a7d5 ReceiveNextEventCommon + 584
22  com.apple.HIToolbox           	0x00007fff35a0a579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
23  com.apple.AppKit              	0x00007fff34055c99 _DPSNextEvent + 883
24  com.apple.AppKit              	0x00007fff340544e0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
25  com.apple.AppKit              	0x00007fff340461ee -[NSApplication run] + 658
26  libqcocoa.dylib               	0x000000011383324b 0x1137fa000 + 234059
27  org.qt-project.QtCore         	0x0000000110ff4c3e QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 462
28  org.qt-project.QtCore         	0x0000000110ffce92 QCoreApplication::exec() + 130
29  org.score                     	0x000000010a669399 main + 729
30  libdyld.dylib                 	0x00007fff70d1fcc9 start + 1

**Comment by jcelerier** [comment]
lots of curve-related issues have been fixed recently in v3 which should include this one, closing
