### ISSUE TITLE
Crash on startup: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mgunyho** [ossia/score#1013]
On Kubuntu 19.04, when trying to launch v3.0.0-a4 AppImage (also tried a3), the program simply exits with
```
Illegal instruction (core dumped)
```
Based on a quick google search, this might have something to do with my CPU (very old AMD Phenom) and/or possibly related to boost. [Here](https://github.com/OSSIA/score/files/4662003/cpuinfo.txt) is the output of `cat /proc/cpuinfo/` if it helps. Version 2.5.2 runs okay.

**Comment by jcelerier** [comment]
hello ! damn, indeed - the current build targets more recent CPUs (requires at least AVX basically).
Though it shouldn't be *too* hard to make a build to target older machines. won't be able to right now but will try to think about a way to automate it.

**Comment by jcelerier** [comment]
only SSE2, wow :-) old indeed. but should be doable though.

**Comment by mgunyho** [comment]
Thanks! No hurry, I can live with v2.5 for now.

**Comment by ghost** [comment]
For me under Debian 10 it crashed without `(core dumped)`

```
$ ./score-v3.0.0-a4-Linux.AppImage
Illegal instruction
```

**Comment by jcelerier** [comment]
thanks, can you also report your /proc/cpuinfo ?

**Comment by ghost** [comment]
Intel Pentium Dual T2330 (2) @ 1.600GHz

**Comment by jcelerier** [comment]
thanks, decidedly no way to go past SSE2 :-) next release will work on those older CPUs

**Comment by jcelerier** [comment]
Hello, @Symbian9  @mgunyho  can you try the alpha8 appimage ? this one should work again on older CPUs.

**Comment by mgunyho** [comment]
Hi, sorry for the belated reply. Sorry, looks like it still doesn't work. The binary in the release is named just `Score.AppImage`, are you certain that you've uploaded the correct version?

If it's of any help, here's a backtrace from gdb:
```
Program received signal SIGILL, Illegal instruction.
0x00000000055298de in ?? ()
(gdb) bt
#0  0x00000000055298de in ?? ()
#1  0x0000000008f46e3d in ?? ()
#2  0x00007ffff5b8016e in __libc_start_main (main=0x25af270, argc=1, argv=0x7fffffffd298, init=0x8f46df0,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd288) at ../csu/libc-start.c:264
#3  0x00000000025a8029 in ?? ()
```

Let me know if I can help with investigating further.

**Comment by jcelerier** [comment]
hm, it looks like one library was introduced in v3 added a -march=native somewhere - can you try with the following ?
 
https://file.io/kiI7gJOUx7EJ

**Comment by jcelerier** [comment]
(yes for the name, it's because I built them by hand instead of relying on the CI)

**Comment by mgunyho** [comment]
Yes, with this binary I am able to start it.

**Comment by jcelerier** [comment]
great ! thanks :-) 

@Symbian9 could you also confirm that it works for you ?

**Comment by mgunyho** [comment]
I tried to add a device and got a crash with
```
libc++abi: terminating with uncaught exception of type std::runtime_error: Error: documents.currentDocument()
 #0 0x00000000054f22ef (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x54f22ef)
 #1 0x00000000054f03c2 (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x54f03c2)
 #2 0x00000000054f2745 (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x54f2745)
 #3 0x00007f4da4598540 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x15540)
 #4 0x00007f4da230b3eb raise /build/glibc-5mDdLG/glibc-2.30/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f4da22ea899 abort /build/glibc-5mDdLG/glibc-2.30/stdlib/abort.c:81:7
 #6 0x0000000008f38fd6 (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x8f38fd6)
 #7 0x0000000008f38a1f (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x8f38a1f)
 #8 0x0000000008f387a3 (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x8f387a3)
 #9 0x0000000008f38739 (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x8f38739)
#10 0x00000000025c26eb (/tmp/.mount_Score.f44tsf/usr/bin/ossia-score+0x25c26eb)
Aborted (core dumped)
```

Should I open a separate issue for that?

**Comment by mgunyho** [comment]
Hm yeah looks like that's a separate issue.

**Comment by jcelerier** [comment]
yep please

**Comment by mgunyho** [comment]
Silly question, where can I find the crash log?

**Comment by jcelerier** [comment]
On Linux it is generally coredumpctl which is used for that but you need to install & enable systemd-coredump on some distros.

**Comment by jcelerier** [comment]
hello, if you have time could you check that one ? 

https://github.com/ossia/score/releases/tag/v3.0.0-a13

it was autogenerated from the Ci, i'd like to know if the whole pipeline is finally fine

**Comment by mgunyho** [comment]
Seems to work fine!

**Comment by jcelerier** [comment]
oaky, I'll close the issue and hope for the best :)

**Comment by jcelerier** [comment]
thanks for testing, this helps a lot !
