### ISSUE TITLE
Settings / Effects layout

### ISSUE THREAD

**Issue by mxmilkiib** [ossia/score#1015]
The working plugin indentation isn't aligned, and it would be handy to alter the horizontal split on this page.

![image](https://user-images.githubusercontent.com/108225/82742672-fcab7780-9d58-11ea-9b62-b8bf374915b5.png)

**Comment by jcelerier** [comment]
Thanks for the report ! 

@aklevy if you want to look into that. Relevant code is in `src/plugins/score-plugin-media/Media/Effect/Settings/View.cpp`.
To alter the horizontal split it should simply be putting the two parts in a QSplitter (and set a stretch factor of say 1:4 for the top vs bottom, as the top part should always be smaller)

**Comment by aklevy** [comment]
A horizontal split was added and the plugin name and path are now in a separate column : 
![settings](https://user-images.githubusercontent.com/9166925/82911612-66e83600-9f6c-11ea-902a-f7b743fa4c4f.png)
