### ISSUE TITLE
Edition of a score while playing

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#103]
Continuation of discussion in #99

**Comment by nvuaille** [comment]
Commit f55100c7b9727f45899fb79263447385ca7e0222 allow a part of it : 
- it's only on i-score part (nothing send to the execution engine)
- no modification of temporal 

Any wishes ?
@bltzr @reno- @theod @jln- @blueyeti

**Comment by reno-** [comment]
I suggest to forbid edition when i-score is playing for now.

**Comment by pach** [comment]
I would say so only in release. Good to have it for testing in bêta.

Thomas Pachoud 
www.creapach.fr

**Comment by bltzr** [comment]
that's seem to be quite free for now, and I like it.... opinions, folks ?

**Comment by jcelerier** [comment]
quite free ?

**Comment by bltzr** [comment]
Well more or less everytime I've edited stuff while playing it was immediately taken into account

**Comment by jcelerier** [comment]
let's close this and reopen new issues if problems arise.
