### ISSUE TITLE
shaders parameters lost after unpausing

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1038]
the example below shows a video going through a shader, and score switched between play and pause.
Playing again after the pause brings a lot of artifacts, and looses the current parameter states.
If a parameter is then modulated, the entire shader state seems to be brought back. A least until we pause and playback again.

hope this is clear. It's tricky to explain.

![vokoscreen-2020-06-02_21-01-30](https://user-images.githubusercontent.com/26526517/83559080-41cb6880-a514-11ea-8c45-23c5e74f1c66.gif)

**Comment by jcelerier** [comment]
huh, interesting ! thanks
