### ISSUE TITLE
"Show" Window Device after closing leads to intresting results

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1039]
![vokoscreen-2020-06-02_21-18-28](https://user-images.githubusercontent.com/26526517/83564413-f9647880-a51c-11ea-8b6f-8c6e56bd5ac0.gif)

Here is my resulting Window Device after I manually closed it and attempt to reopen it with the show function of the Device

![scoreWindow](https://user-images.githubusercontent.com/26526517/83560887-3463ad80-a517-11ea-8e68-2f58f2d7564c.png)

**Comment by jcelerier** [comment]
fixed
