### ISSUE TITLE
Play from here first starts from the beginning

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1045]
Here you can see the first click and the time bar starting at the biginig.
On the second click the time bar jumps to the correct spot. But maybe that is what was intended ?

![vokoscreen-2020-06-17_09-25-04](https://user-images.githubusercontent.com/26526517/84868297-c2de4000-b07c-11ea-884a-a7862af16df2.gif)

**Comment by thibaudk** [comment]
the little play head next to the mouth is a really nice touch !
It used to be often forgotten witch mode was selected.

**Comment by jcelerier** [comment]
you can thank @aklevy for that :p

**Comment by thibaudk** [comment]
GG @aklevy !!

**Comment by jcelerier** [comment]
I just fixed something related to play from here, can you try again ?

**Comment by thibaudk** [comment]
Yes, no double tap required anymore apparently.

Nice One !
