### ISSUE TITLE
error compiling on arch linux

### ISSUE THREAD

**Issue by underdoeg** [ossia/score#1048]
I get the following error when trying to compile the recent git version:

```
score_plugin_media_commands.hpp:17:33: error: ‘LV2EffectModel’ is not a member of ‘Media::LV2’
   17 | InsertGenericEffect<Media::LV2::LV2EffectModel>,
```

If I disable LV2 support by commenting this line, it compiles (https://github.com/OSSIA/score/blob/master/src/plugins/score-plugin-media/CMakeLists.txt#L18)

**Comment by jcelerier** [comment]
I tried to do a fresh build and it seems to work, with only `pacman -S base-devel ffmpeg boost  qt5-base qt5-declarative qt5-websockets` on a virgin container so I think this has been fixed. Thanks for the report !
