### ISSUE TITLE
Crash when reinitializing scenario

### ISSUE THREAD

**Issue by jln-** [ossia/score#1052]
Using Score 3.0.0 a5 and latest libossia for Max, I get a crash when clicking the reinitialize button.

Steps to reproduce:

- Open ossia.device.maxhelp
- create new scenario and add device
- Store an init state
- hit Reinitialize button (or cmd+return shortcut)
=> Crash

Note: it does not crash if init state is empty

Crash log: https://gist.github.com/jln-/c57d6d2e28f48be40ff589301885bf3f

**Comment by jcelerier** [comment]
can confirm, on it

**Comment by jln-** [comment]
Re-opening the issue as I had a crash when reinitializing scenario. (not totally sure init state had some content, though)

https://gist.github.com/jln-/57ae90006c9970374f22e3b2513258d7

**Comment by jcelerier** [comment]
do you happen to have the score file ?

**Comment by jln-** [comment]
Unfortunately not. I just reopened in case crash log wad meaningful. If not, feel free to close the issue: I could not replicate the crash so far.

**Comment by jcelerier** [comment]
tried a lot but cannot reproduce either :/

**Comment by jcelerier** [comment]
for good this time
