### ISSUE TITLE
JS in v3

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1053]
Values from a vector fed into an JS inlet are tricky to retrieve.   

calling value on an inlet receiving an array of 2 value returns
```
Debug: QVariant(QVector2D, QVector2D(0.5, 0.283333))
```
But neither .x or [0] returns anything

**Comment by jcelerier** [comment]
any chance you can tell me the last score version this worked ? I strongly believe this would be a change of behaviour in qt 5.15...

**Comment by thibaudk** [comment]
I only ever had it working in v2.

**Comment by jcelerier** [comment]
ah, found it, we actually need to include QtQuick for that to work. -_-

**Comment by thibaudk** [comment]
Cool ! 
will do, 

Cheeres !

**Comment by jcelerier** [comment]
wait no :-)
I'd like for this to work without needing to include QtQuick at all
