### ISSUE TITLE
ConstrolSurface error after reloading the scenario

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1054]
This is exemplified in this tiny score, also relating to #1053.

After opening this score a first time, closing it and reloading it returns an error.
Further more, trying to manipulate the control slider after the creation error will show
a pop up window for "internal error"

[jsArray.score.zip](https://github.com/ossia/score/files/5163317/jsArray.score.zip)

**Comment by jcelerier** [comment]
fixed... but the issue is, it was never saved correctly. Now it is but older scenarios... well they never worked anyways -_-
