### ISSUE TITLE
Icon for preset dragging

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1068]
It would be useful to have an icon to allow to drag a preset from a process & interval.

the icon would be at two places (indicated by a red cross) so different sizes may be needed ? 

The idea is that when you drag from it to the score, this saves a preset of either a given process or the whole interval in a state in that point
![here](https://user-images.githubusercontent.com/2772730/94360395-1e24c300-00ad-11eb-9e23-c37cbfb3fd32.png)

**Comment by jcelerier** [comment]
@aklevy if you fancy that one ?

**Comment by aklevy** [comment]
I do ! But I am not sure I understand correctly: the icon for the issue #1069 is a different one ..?

**Comment by jcelerier** [comment]
yep - for this one it should be something that indicates that you can drag from it in some way. Maybe it should be similar to the "state" (the white dot with the blue dot inside) asthe idea is that it creates a cue on the timeline when you drag'n'drop from it.

for the record one, well I guess it should be a red circle, but the problem is that it is already used by the audio output ports..maybe an orange or white circle to follow the colour of the surrounding eleemnts ?

**Comment by jcelerier** [comment]
@aklevy  I can't find where you put these icons, do you remember ?  ^^'
