### ISSUE TITLE
Icon for recording

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1069]
The idea for recording is to be able to mark a process as "recordable". 
This would follow exactly the same pattern UI-wise than #1068, except with a "record" icon. 
Not all processes will have that one - it'd be only : 
- automations
- sound file
- piano roll

**Comment by jcelerier** [comment]
@aklevy if you fancy that one ?

**Comment by aklevy** [comment]
@jcelerier  I close this as the icon is ready to be integrated
