### ISSUE TITLE
Font handling on Linux is broken.

### ISSUE THREAD

**Issue by fhars** [ossia/score#1075]
If I start ossia.score-3.0.0-a13-2-linux-amd64.AppImage it says:
```
QFontDatabase: Cannot find font directory /opt/score-sdk/qt5-static/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
```
And then after that, most of the output is:
```
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
Warning: QFont::setPixelSize: Pixel size <= 0 (-1) (:0)
```

Looks like it is using a default font instead.

**Comment by jcelerier** [comment]
ah, saw that one - I believe the warnings are harmless, they have been introduced at some point between Qt 5.15 and Qt 5.15.2

Note that score uses the Ubuntu font on every platform so it should look "default" on Ubuntu.

**Comment by jcelerier** [comment]
yep that went away by updating the Qt version, won't be an issue in the next releases

**Comment by jcelerier** [comment]
(note that nothing can be done against the first warning - but it's a generic qt warning and we're specifying fonts explicitly in the software so it does not really matter)
