### ISSUE TITLE
score doesn't build on any Ubuntu version

### ISSUE THREAD

**Issue by fhars** [ossia/score#1076]
ossia score requires cmake 3.17, and even Ubuntu 20.10 does only have 3.16.2.

**Comment by fhars** [comment]
It builds if you change the requires cmake version in the CMakeLists.txt.

**Comment by jcelerier** [comment]
> It builds if you change the requires cmake version in the CMakeLists.txt.

huh, that is surprising - we use the CMake PCH feature which was introduced in 3.17.

**Comment by thibaudk** [comment]
Hi @fhars,
On Ubuntu, you can get CMake 3.18 from snap (instead of apt)

```
sudo apt purge cmake 
sudo snap install cmake --edge --classic 
```

**Comment by jcelerier** [comment]
that's a super useful information @thibaudk, could you add it to the wiki in the building page ? thanks !

**Comment by thibaudk** [comment]
@jcelerier done

**Comment by fhars** [comment]
A possible explanation might be that according to https://cmake.org/cmake/help/latest/release/3.16.html#commands `target_precompile_headers` was introduced one version earlier.

**Comment by jcelerier** [comment]
huh, indeed, wonder why it was bumped to 3.17 then. I tested on a ubuntu docker image and actually setting older versions looks like it works

**Comment by jcelerier** [comment]
was downgraded to cmake 3.13 and tested on both debian stable and ubuntu 20.04 (likely it will work on 18.04 too)
