### ISSUE TITLE
Package manager icon

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1077]
The latest release features a package manager in the settings. But for now its icon is not very pretty :p 

![pkg](https://user-images.githubusercontent.com/2772730/95050107-4cc51e00-06eb-11eb-9712-3105ca18958c.png)

@aklevy if you feel like it ?

**Comment by jcelerier** [comment]
(the code is in `PluginSettingsPresenter::settingsIcon`)

**Comment by aklevy** [comment]
Indeed, it is not very pretty ! 
I will look into it.

**Comment by jcelerier** [comment]
thanks, it's much better!

**Comment by jcelerier** [comment]
looking good in retina too
