### ISSUE TITLE
File dialog behaviour on linux is unfortunate

### ISSUE THREAD

**Issue by fhars** [ossia/score#1078]
The file dialogs for "Load" and "Save as..." default to the current working directory, which for the AppImage happens to be a hidden directory under /tmp, which will be deleted on the next reboot and changes every time you restart ossia score. This may not be the best default location to store a user's data.

In a related issue, debug builds (at least under Ubuntu 20.10) use the distribution standard file dialog (instead of the styled one the AppImage uses), but in a way that prevents the user from changing the directory.

**Comment by jcelerier** [comment]
Fixed both issues - now it'll look for a list of relevant directories first. The dialogs have also been forced to use Qt's ones in every Linux build as many users reported issues with the "native" color and file dialogs on Linux
