### ISSUE TITLE
It is hard to add things to short intervals

### ISSUE THREAD

**Issue by fhars** [ossia/score#1079]
The "+" is not visible if the display length of the interval is too short:
![image](https://user-images.githubusercontent.com/198941/95133388-88023400-0761-11eb-95b7-a68a62026775.png)

**Comment by jcelerier** [comment]
(paging the usual UI suspects @aklevy  @bltzr  @jln- )

Note that to add things you can drag'n'drop things instead from the library to the interval, or by right-clicking in the object menu on the top right (@jln- this may be useful to add to the docs).

And I'd be quite tempted to remove that "+" here in future versions as there are some upcoming features that would be better instead in the interval bar than adding a process for which drag'n'drop is superior imho (namely, preset snapshotting and enabling recording)

Another solution would be to go for touchdesigner-style UI and make the icons tinier and tinier when the interval becomes too short to display everything.
Opinions ?

**Comment by jcelerier** [comment]
the plus has been removed since then - now the official way is through drag'n'drop
