### ISSUE TITLE
"power" automatin dosen't do anything 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1083]

**Comment by jcelerier** [comment]
huh ? power is the "default" automation segment type used (but with a coefficient that makes it linear)

**Comment by thibaudk** [comment]
Interesting, both "power" and "linear" appear in the same drop-down menu with "easing".
So I guess I expected them to do different things.
Should one of them be removed ?

**Comment by jcelerier** [comment]
basically, linear is a *small* performance optimisation in the case where you know that you will never "curve" your curves

**Comment by thibaudk** [comment]
Cool ! didn't know that.
Do you think it can be stated on the info box on hovering ?

**Comment by jcelerier** [comment]
Maybe we can put it in the doc instead ?
<http://www.jcelerier.name>

**Comment by jln-** [comment]
This was kind of stated in old score 2.x.x but I'll make sure to update this bit of info as well.
