### ISSUE TITLE
crash when adding camera device

### ISSUE THREAD

**Issue by jln-** [ossia/score#1089]
Using score 3.0 a15, in the Device explorer, select add device,  camera, click 'add'.

-> score crashes.

https://gist.github.com/jln-/be99317de9919a23d27afd4c60756a46

**Comment by jcelerier** [comment]
interesting, is that a macbook camera ?

**Comment by jcelerier** [comment]
the crash itself should be fixed

**Comment by jln-** [comment]
Yes, it is on a Macbook Pro. Actually, when selecting 'Camera input' device column does not display anything (no built-in camera available). Sorry, should have mentioned that in first place.
