### ISSUE TITLE
Context menu for constraint of Loop Process

### ISSUE THREAD

**Issue by theod** [ossia/score#109]
I have created a loop and then added an automation on an address as the picture shows I can't see the automation : 

![capture d ecran 2015-12-17 a 15 44 25](https://cloud.githubusercontent.com/assets/118426/11872393/43228090-a4d5-11e5-91c7-80f295e9633d.png)

**Comment by theod** [comment]
then if I try to display the process in a new slot it crashes.

![capture d ecran 2015-12-17 a 15 46 24](https://cloud.githubusercontent.com/assets/118426/11872431/8078bffe-a4d5-11e5-9389-ac0c9830889d.png)

[crashlog.txt](https://github.com/OSSIA/i-score/files/65495/crashlog.txt)

**Comment by jcelerier** [comment]
For now and until I have time to write a proper one, I disabled the context menu (it was refering to the slot of the parent constraint anyway - but this particular crash has been fixed). To show a process you should press the little "~" in the inspector.

**Comment by theod** [comment]
this is fixed on dev ! thanks
