### ISSUE TITLE
ossia-score-vstpuppet crash

### ISSUE THREAD

**Issue by jln-** [ossia/score#1093]
When loading score v3.0.0-a16, I get a notification that vstpuppet crashes.

It may well be related to the fact that I have a plugin (Altiverb) that is not authorized and thus usually brings a pop up windows asking for authorization when launching audio apps.

crash log here: https://gist.github.com/jln-/86a2d1dca7c6967f593d4c074b7c8bfb

**Comment by jcelerier** [comment]
arf yes, now that score is notarized everything it loads must be notarized too it seems... gonna check if there's something to allow that

**Comment by jcelerier** [comment]
should be fixed by e4a40edb5fcc212bb413e4db06c419fa2152146b...
