### ISSUE TITLE
nodal view is glitchy

### ISSUE THREAD

**Issue by jln-** [ossia/score#1094]
Using v3.0.0-a16, switching to nodal view is glitchy when zooming or moving things around.

See attached screenshot (macOS 10.15.7 - non-retina screen if that matters)

![Capture d’écran 2020-10-20 à 15 48 46](https://user-images.githubusercontent.com/114325/96598418-227c7e80-12ef-11eb-8ffd-c4813b5eedb8.png)

**Comment by jcelerier** [comment]
seems like it has been fixed !
