### ISSUE TITLE
automation fullsize edit crash

### ISSUE THREAD

**Issue by jln-** [ossia/score#1095]
Yet another not reproducible (so far) crash.

I was basically going back and forth between main scenario view and the automation full size view with doing much edits in the automation itself.

I added a color process to the same interval, again going back and forth between full size view and main view, undo the creation of the color process (when in main view). And it crashed at some point.

Attached is the recovered scenario.

Crash log here: https://gist.github.com/jln-/1b40090aeca542e6c6a538da408212ea

Edit: actually, not attached is the recovered scenario... I did a Save as..., score looked ok but the apparently saved scenario is nowhere to be found on my computer...

**Comment by jcelerier** [comment]
arf, that one I really can't seem to be able to make it crash :( closing, please reopen if you see it again
