### ISSUE TITLE
crash when attempting to load scenario saved with old version (a15)

### ISSUE THREAD

**Issue by jln-** [ossia/score#1096]
As title states. Using v3.0.0-a16, when trying to load a scenario written using previous alpha, I get a message warning that the scenario is too old, then a second window stating "invalid something", then crash.

https://gist.github.com/jln-/0b5d8e8b8ca75c780c7397c1c0cbcd30

**Comment by jcelerier** [comment]
not getting any crash anymore with a17, on both macos and linux
