### ISSUE TITLE
scenario cannot be saved to disk

### ISSUE THREAD

**Issue by jln-** [ossia/score#1097]
Using v3.0.0-a16, scenario cannot be saved to disc.

In score, i can either save or use "save as", everything goes fine. If launching score again, saved files do appear in recent files in splash screen or in the recent men.

But when looking on my HD, no files exist.

I thus lost the scenario I've been working on for the full day for the documentation. :-( Luckily, it only had 2 states stored with a single parameter stored each and a default automation. :-)

But it may be more annoying for production times...

**Comment by jcelerier** [comment]
should be fixed by e4a40edb5fcc212bb413e4db06c419fa2152146b...
