### ISSUE TITLE
the second operand of trigger expression disappears

### ISSUE THREAD

**Issue by theod** [ossia/score#110]
if I setup a trigger expression like this : 

![capture d ecran 2015-12-17 a 15 49 14](https://cloud.githubusercontent.com/assets/118426/11872541/14c00fb4-a4d6-11e5-8c5b-85da1fd9e374.png)

then, if I focus on another element and then I go back on the trigger the second operand disappears : 

![capture d ecran 2015-12-17 a 15 49 59](https://cloud.githubusercontent.com/assets/118426/11872523/f730cb5a-a4d5-11e5-94ae-46b220bafd63.png)

**Comment by theod** [comment]
notice this bug also occurs for condition

**Comment by nvuaille** [comment]
Yep, it's fixed on dev, sorry for the noise

**Comment by theod** [comment]
sorry @nvuaille but on dev the bug is not fixed.
I'm on skype if you want to see how things goes on my machine.

**Comment by jcelerier** [comment]
I'm on it

**Comment by nvuaille** [comment]
I wrote to fast and remove the comment, sorry.

**Comment by theod** [comment]
fixed ! mega teuf excellent !
