### ISSUE TITLE
OSX step sequencer not showing sliders

### ISSUE THREAD

**Issue by MacroMachines** [ossia/score#1105]
https://www.dropbox.com/s/p2nkxrqu87hdbyx/Screen%20Shot%202020-10-24%20at%2012.29.58%20PM.png?dl=0
only "zoom in to edit steps" shows up on the step sequencer no matter what zoom level.  Mojave 10.14.6 and score 3.0.0-a19

**Comment by jcelerier** [comment]
fixed in master !
