### ISSUE TITLE
allow to unsplit a time node

### ISSUE THREAD

**Issue by theod** [ossia/score#111]
... or how to merge events of a same time node ?

I have splitted a time node in 2 events but I can't find the way to merge them afterward (I can't undo because I've added some stuff I don't want to loose of course !)

**Comment by nvuaille** [comment]
We were able to do that long time ago. Then it was disabled and never re-enable =P

**Comment by theod** [comment]
ok so I turn this ticket into a feature request

**Comment by nvuaille** [comment]
That's a particular case of what I mean in #122

**Comment by jcelerier** [comment]
I think that this works now ?

**Comment by jcelerier** [comment]
I tested a lot of times and couldn't make it crash, so I'm closing the issue for now.
