### ISSUE TITLE
unlocked move crash

### ISSUE THREAD

**Issue by jln-** [ossia/score#1110]
Not sure how to properly phrase this one. So see the attached gif 

(NB: it seems the frame got out of the GIF export. But basically, score crashes at the end of gif)

Using v3.0.0-a19

https://gist.github.com/jln-/963cd55950975ebeda00a3cc28406c89

![unlock-move-crash](https://user-images.githubusercontent.com/114325/97595210-c2c75700-1a03-11eb-94f9-34013b3df47f.gif)
[triggers.score.zip](https://github.com/ossia/score/files/5459485/triggers.score.zip)

**Comment by jln-** [comment]
By the way, it seems there is something wrong here regarding how point shared in processes is handled, doesn't it ? Like curvature in process #1 is ignored ?

**Comment by jcelerier** [comment]
should be fixed !
