### ISSUE TITLE
consecutive processes cant be scaled or move using event bar

### ISSUE THREAD

**Issue by jln-** [ossia/score#1111]
Using v3.0.0-a19, moving or scaling consecutive processes cant be done by grabbing the event bar (the one joining two consecutive intervals), although the mouse cursor changes and suggests it is possible.

It would be nice if it was possible, as mouse suggests. (moreover, it would be consistant since it can be done this way when trying to change the length of last process of a sequence for example)

**Comment by jcelerier** [comment]
looks like now it works !
