### ISSUE TITLE
right-click javascript process crash

### ISSUE THREAD

**Issue by jln-** [ossia/score#1112]
Using v3.0.0-a19, right-click on the JS process in the attached scenario crashes score. This is reproducible.

[javascript-crash.txt](https://github.com/ossia/score/files/5467854/javascript-crash.txt)
[javascript-crash.score.zip](https://github.com/ossia/score/files/5467855/javascript-crash.score.zip)

**Comment by jcelerier** [comment]
does not seem to crash in the latest versions, it seems that it was a bug that was fixed in Qt
