### ISSUE TITLE
"Add child" should propose to create a node without Address by default

### ISSUE THREAD

**Issue by theod** [ossia/score#112]
I would like to add a /mouse/click address to an OSC device.
unfortunatelly I can't add sub node  : 

![capture d ecran 2015-12-17 a 17 05 08](https://cloud.githubusercontent.com/assets/118426/11874503/63800c44-a4e0-11e5-87d4-43cf6abbd219.png)

do I miss something ?

**Comment by nvuaille** [comment]
You have to create 'mouse' as child of the device and then 'click' as child of 'mouse'

**Comment by theod** [comment]
but I don't want to declare "mouse" node with any typed Address under.
so by default we should have only a text field for tag then under an "add Address" button to start the setup of an address under this node.

does it make sens ?

**Comment by theod** [comment]
or another option would have two options into the menu : "add node" and "add address" ?
not sure about the utility of "add sibling" ...

@reno-, @bltzr, @avilleret and @jln- ?

**Comment by reno-** [comment]
I think that having nodes for each / in the address is a good convention.  It will be weird if we have some nodes that represents a / and some slash into other addresses. So I think I prefer to keep things as it is.

If it is a UI question, maybe we could ask to automatically expand nodes that are only nodes when using device explorer

**Comment by jcelerier** [comment]
I added a "None" value type to the address dialog box.

Should it be the first one proposed ? because I think that somebody wanted the types sorted alphabetically once.

**Comment by theod** [comment]
I would say to propose and focus on None option into the menu but to have them sorted alphabetically.
is it possible ?

this way it will increase the understanding of what we are doing IMHO.
