### ISSUE TITLE
Pattern sequencer bug

### ISSUE THREAD

**Issue by k164v** [ossia/score#1125]
Hi, 

I am currently running Ossis score 3.0.0-a21. I am trying to use the pattern sequencer add-on.

Currently, the pattern sequencer works well in the main session but every time I switch to the full-view, it will messed up the timing of pattern sequencer(make it runs super fast and cannot go back).

I tested both MacOS and Windows and I can confirm this issue occurs on both platform.

**Comment by jcelerier** [comment]
oh, very interesting issue, thanks

**Comment by jcelerier** [comment]
fixed (sorry, that needed some quite deep changes actually)
