### ISSUE TITLE
hidden adress slot

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1126]
The little white triangle is apparently the same color as the background for the inspector initialy as can be seen int this picture
![hiddenSlot](https://user-images.githubusercontent.com/26526517/102325990-1f66dd00-3f84-11eb-8cb2-27cda6cee09a.png)

It is there, just not visible, but it can be clcked-on and used
![hiddenSlotBack](https://user-images.githubusercontent.com/26526517/102327326-dc0d6e00-3f85-11eb-84e5-6ca96ede624f.png)

Once clicked it will also reaper in the correct color.
Probably just initialized with the wrong color

**Comment by jcelerier** [comment]
interesting, @aklevy  do you fancy looking at that one ?

**Comment by aklevy** [comment]
@jcelerier yep I will try to fix that

**Comment by aklevy** [comment]
Fixed, the bug was in the initialization of ArrowButton

**Comment by jcelerier** [comment]
ah, thanks !

**Comment by thibaudk** [comment]
Nice !
