### ISSUE TITLE
crash when zooming out

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1127]
This happens when a sound file wave form is visible and gets shrinked down by zooming out.
(probably a duplicate issue but I can not find the original)

**Comment by jcelerier** [comment]
can you provide the .wav file ?

**Comment by thibaudk** [comment]
This seems to be reproducible with anny soundfile in any scenario on Mac.
If a sondfile is visible, continue zooming back and shrinking it's size, it will crash

**Comment by thibaudk** [comment]
addendum:
after thorough tests, the issue doesn't seem that straight forward to reproduce.
Yet without hiding sound files, a few scores crash consistently.

**Comment by thibaudk** [comment]
addendum 2:
The crash only happens when a working sound driver is selected.
When 'dummy' is selected, zooming out is not an issue
