### ISSUE TITLE
Don't making a sequence using the current selection in device explorer

### ISSUE THREAD

**Issue by theod** [ossia/score#113]
Here are some pictures to illustrate the process.

1/ starting to make the sequence from an empty event: 

![capture d ecran 2015-12-17 a 17 30 06](https://cloud.githubusercontent.com/assets/118426/11875331/6e8e4958-a4e4-11e5-81a2-26f619b00a0a.png)

2/ looking into the end event state: there is a "/speed 0" message 

![capture d ecran 2015-12-17 a 17 31 04](https://cloud.githubusercontent.com/assets/118426/11875359/8926f878-a4e4-11e5-839d-c5dbd29edaad.png)

3/ looking into the first event to see if there is a reason why "/speed 0" message has been added:
no reason because the speed value is also 0...

![capture d ecran 2015-12-17 a 17 31 16](https://cloud.githubusercontent.com/assets/118426/11875398/b65fd300-a4e4-11e5-84d1-d7eb7c1c10b7.png)

I add @reno- and @bltzr to confirm this is a none desired behavior.

**Comment by nvuaille** [comment]
I'm not sure that I understand but : 
- sequence duplicate namespace (with current value) even if value are the same as in the start state (that's what it really does and not necessary what it should do)
- creating a state with a selection in device explorer add this address to the state (not sure it should do that for a sequence ...)

**Comment by theod** [comment]
I'll try to be more clear.
Before I make the sequence I have 2 events where the state for each of them are:

(1) 
- speed 0
- number 20

(2)
empty

then when I create a sequence from the second event, the state of the new third event is: 

(3)
- speed 0

for now I would expect to have nothing in the third state as I start from an empty state.

and in the future, if I remember well what @reno- asked for, if speed value is not the same, we would expect to have an automation for speed from (2) to (3) from 0 to the other value. Am I right @reno- ?

**Comment by jcelerier** [comment]
When creating an event, if there is a node selected in the explorer then it is added in the state. This was a feature request from @bltzr last time at Paris if I remember correctly

**Comment by theod** [comment]
ok ! fine.
so maybe this feature should be muted when making a sequence as in that case we want to work according to the namespace of the previous events.
what do you think @bltzr ?

**Comment by jcelerier** [comment]
This feature will be muted when making a sequence.
