### ISSUE TITLE
notes from ÉESI workshop

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1133]
- 10.13 version
- make Kinect app available

**Comment by jcelerier** [comment]
- ability to set a number of iteration in a trigger
- external editor

**Comment by bltzr** [comment]
- add default gain widget to all audio processes (in the process header ?)

**Comment by jcelerier** [comment]
* show video out in the background à la touchdesigner

**Comment by jcelerier** [comment]
kinect patch: depth ?

**Comment by jcelerier** [comment]
big sur: issue with fontconfig: must remove qt.conf 

=> done

**Comment by jcelerier** [comment]
* 10.13 version => done

* make Kinect app available => @thibaudk

**Comment by jcelerier** [comment]
except the kinect thing which is not really related to score I put everything in separate issues, closing that one
