### ISSUE TITLE
Full screen the Window device on startup

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1139]
The particular use case is from @escuta on the [forum](https://forum.ossia.io/t/questions-about-video/208).
It concerns a command line argument to run on a headless setup in conjunction with the "no-gui" & "autoplay" arguments.

related to https://github.com/ossia/score/issues/1138

Another way, I would imagine, would be an option in the right click menu of the window device, under "show", to toggle full screen.
This toggle state would be preserved on reload.

**Comment by jcelerier** [comment]
Actually what about putting the "full screen" as a node of the device ? this way you can control it from the score

**Comment by thibaudk** [comment]
this what I initially thought but this doesn't seem to be a parameter used for interaction, and more of an option you set once.
In situation, I could see that having the window set to full size during the execution or the initialization could bring some very "annoying" behavior. For example, vIf one needed to work on the scenario on a single screen, and the full screen of the window was set everytime they reinitialize...

**Comment by jcelerier** [comment]
> very "annoying" behavior. For example, vIf one needed to work on the scenario on a single screen, and the full screen of the window was set everytime they reinitialize...

yep that could be annoying for sure.

what I'm going to do for now is to put the window fullscreen if we play with --autoplay. 

then we'll discuss things next week

**Comment by thibaudk** [comment]
Perfect !
