### ISSUE TITLE
don't store messages when storing what is below a node

### ISSUE THREAD

**Issue by theod** [ossia/score#114]
When I store the state of the output model (cf Documentation/Examples/Max) the "record/file/path" message and some others (like "dspStatus") are stored but I don't want them so I need to go into the state to remove them manually (and at this point it is not easy to know which parameters and which are messages...).

I'm wondering if we really want messages to be part of a massive storage (I mean when I select the output node and then I drag it to the event).

actually I would like the following behavior : 
- if I select a node without selecting something precisely under, I want to store only parameters.
- if I select at least one thing below a node my self I want only what I have selected.

is it clear ?
and does it makes sense for other users ? @reno-, @bltzr , @avilleret and @jln- ?

**Comment by jcelerier** [comment]
I think that it was not there originally but @pchdev asked me to add them when dragging a state from the explorer. Maybe a user settings somewhere ?

**Comment by theod** [comment]
ok so we should wait for @pchdev to explain why he needed them.
I guess it is for a device like an OSC device where we usually deal with messages as there is not necessarily an echo from the device. so in that case it makes sense.

and finally I think in the case I describe I simply have to remove those nodes from the device explorer to not store them...

**Comment by pchdev** [comment]
yeah I see what you mean, and this has been a "problem" for me as well.. It just seemed logical to me to have the possibility to send messages like "bang" etc. directly from i-score, or, let's say choosing a waveform for an oscillator (like "sine", "sawtooth", "square" etc.). 
Yet, I didn't necessarily want to have them stored in a state when dragging a whole node-container, I just wanted to have the possibility to drag them individually into a start/end state, which was not the case before.

I don't know if I'm really clear here, let me know if I'm not :)

**Comment by theod** [comment]
yes you are ! thanks

**Comment by bltzr** [comment]
I was also confused by this behavior... and IMHO messages should not be retrieved when doing a snapshot
I agree that we need a way to send messages from i-score (hence to store them), but that shouldn't be done this way, I think...
I'm even surprised messages give any value at all when queried...

**Comment by bltzr** [comment]
So, I'll reopen the issue, if that's OK for you guys

**Comment by pchdev** [comment]
yep! good idea

**Comment by jcelerier** [comment]
consensus : hierarchy : only take the parameters

**Comment by theod** [comment]
we discussed this during the Bod and we realize that @pchdev said that it was agree with us : 

> I didn't necessarily want to have them stored in a state when dragging a whole node-container, I just wanted to have the possibility to drag them individually into a start/end state, which was not the case before.
