### ISSUE TITLE
score file crashes score

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/score#1148]
Open and play this score in v3.0.0-a22 on Mac Mojave freezes Score.

[crash_starwars.score.zip](https://github.com/ossia/score/files/5936745/crash_starwars.score.zip)

**Comment by thibaudk** [comment]
crashes for me too,
properly disabling the trigger or removing the transition doesn't seem to help.

**Comment by jcelerier** [comment]
fixed in new release (a22 did create corrupt save files, sorry for that)
