### ISSUE TITLE
device explorer filters are broken

### ISSUE THREAD

**Issue by theod** [ossia/score#115]
when I use the filters under the device explorer I don't what I expect : 

here is the namespace without filtering : 

![capture d ecran 2015-12-18 a 10 53 12](https://cloud.githubusercontent.com/assets/118426/11894169/be8e86e8-a575-11e5-9cd2-456dc98daef3.png)

and with a filtering for Set 1 : 

![capture d ecran 2015-12-18 a 10 53 24](https://cloud.githubusercontent.com/assets/118426/11894173/ca2b49e6-a575-11e5-91be-7385b1cda056.png)

**Comment by nvuaille** [comment]
I guess it's filtering upon name whatever you choose in the combobox ...
I'm looking for that !

**Comment by nvuaille** [comment]
@jcelerier it seems that the QVariant stored (for each cell) has something wrong with type other than string ...

**Comment by nvuaille** [comment]
Better ! but ...
You look if the requested entry is contained in the field. That's good for addresses name but for value it's a bit strange : if I ask for "5" in the "value" field, I saw all the "0.5" values or "-5" or any number with a 5 in it...

**Comment by theod** [comment]
thx @nvuaille it's working for "Set" and "1".
but as you mentioned there are a lot of trouble in value filtering.
I put them below

**Comment by theod** [comment]
here is the namespace without filtering : 
![capture d ecran 2016-02-03 a 17 08 49](https://cloud.githubusercontent.com/assets/118426/12788537/2726813a-ca9a-11e5-9aa1-96b65ebb3365.png)

**Comment by theod** [comment]
here are some troubles I've noticed on Value : 

for Int value
![capture d ecran 2016-02-03 a 17 07 50](https://cloud.githubusercontent.com/assets/118426/12788561/3c110bce-ca9a-11e5-923b-3ff35a2d4043.png)

**Comment by theod** [comment]
for float value : 
![capture d ecran 2016-02-03 a 17 08 04](https://cloud.githubusercontent.com/assets/118426/12788566/4291bdf4-ca9a-11e5-8024-cd7c1a442028.png)

**Comment by theod** [comment]
for tuple value : 

![capture d ecran 2016-02-03 a 17 07 32](https://cloud.githubusercontent.com/assets/118426/12788613/646d4196-ca9a-11e5-944c-6269f0864fc0.png)

**Comment by nvuaille** [comment]
One should use the dot '.' as decimal separator, even if the explorer display a coma ','. That's why 0,5 match to nothing.

**Comment by theod** [comment]
I've also have a trouble for "Get" "0" or "Set" "0" : 

![capture d ecran 2016-02-03 a 17 11 06](https://cloud.githubusercontent.com/assets/118426/12788655/a3be081c-ca9a-11e5-91d1-9baae45c6efd.png)

**Comment by theod** [comment]
same problem than value for min and max : 

![capture d ecran 2016-02-03 a 17 12 48](https://cloud.githubusercontent.com/assets/118426/12788673/c1018340-ca9a-11e5-9911-0cd6c756f34a.png)

![capture d ecran 2016-02-03 a 17 12 59](https://cloud.githubusercontent.com/assets/118426/12788676/c447bd62-ca9a-11e5-9570-35a4eaba3261.png)

**Comment by bltzr** [comment]
can you try again and see if this is still broken @theod ? 
(I couldn't figure out exactly what the problem was, from the comments...)

also, from my tests, filtering does work, but nodes are not expanded, which is a bit awkward but, if you trust the fact that it does work indeed, that can still be useful 
or, that could be useful if the recursive snapshotting took the filter into account - because then you could just select ancestor nodes instead of each and any filtered node.... just saying... (am I being clear enough ?)

**Comment by jcelerier** [comment]
@bltzr : don't worry, they are still broken :p 

however I'm questioning the relevancy of filtering by e.g. min / max. is this really necessary  ?

**Comment by bltzr** [comment]
OK glad to know we have some bugs left ;-)

Filtering by min max is useless IMHO. Do we have filtering by tags? (Cannot check right now... But that would be useful)

Also did you get what I meant about taking the filters into account for recursive snapshots? Ie only those nodes that would be visible if all the nodes was expanded would be included in a state when drag'n'dropping... Does that sound reasonable?
