### ISSUE TITLE
Widget to combine rate and time division

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1154]
this would alow to skip having to choose "none' in the time division chooser, for the rate to be used (in the LFO for exemple).
It would also help to visualize the relationship between musical division and rate in Hz.

**Comment by jcelerier** [comment]
@aklevy if you're interested in participating in the design for this too ?

**Comment by thibaudk** [comment]
I am not too sure about the final result anymore, or the final behavior.
A quaver doesn't represent the same value in Hz, according to a different tempo.
When changing the current tempo, should all these widgets update ?

Or should an Hz window only appear when "none" (in Quantification) is set ?

**Comment by jcelerier** [comment]
> Or should an Hz window only appear when "none" (in Quantification) is set ?

i think so yes

**Comment by jcelerier** [comment]
this is done: Process::TimeChooser (and the associated widget)
