### ISSUE TITLE
setting OSC rate disables both sending and receiving

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1156]
this is using the rate widget in the edition window of the device.

**Comment by jcelerier** [comment]
for all protocols ?

**Comment by thibaudk** [comment]
It is only available for osc and oscquerry.
for oscquerry, it works if the rate is set on initialization. If it is later edited, I have some weird behavior but that may be on my side

**Comment by jcelerier** [comment]
duplicate of #987
