### ISSUE TITLE
[Windows] Crash when switchin from half-screen to full-screen

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1157]
This happened twice while working with recording and playback of automatons and messages,
to and from an OSC Device.

When pressing full-screen, the score window is first duplicated for a second before crashing. 

Here is the scenario that crashed
[Mosca.zip](https://github.com/ossia/score/files/5990431/Mosca.zip)

tested with 9280e8f binary (from Azure)

**Comment by jcelerier** [comment]
@thibaudk  does that still happen ?

**Comment by jcelerier** [comment]
wait it's the score window itself which crashes, not a gfx thing ?

**Comment by jcelerier** [comment]
Seems to work fine with the above scenario on b4
