### ISSUE TITLE
destroying a node doesn't turn off all listening on it and its children

### ISSUE THREAD

**Issue by theod** [ossia/score#116]
here are some pictures that illustrates the issue : 

here the listening on /input/audio/gain is active as expected : 

![capture d ecran 2015-12-18 a 11 24 27](https://cloud.githubusercontent.com/assets/118426/11894819/0bf16a14-a57a-11e5-8b18-86998fd1621b.png)

then I remove the  /input/audio/gain from the device explorer and you can see the listening is still active : 

![capture d ecran 2015-12-18 a 11 24 44](https://cloud.githubusercontent.com/assets/118426/11894838/2d18f6d0-a57a-11e5-9322-00a523af0600.png)

**Comment by jcelerier** [comment]
I fixed it in i-score but maybe it would be nice for the API to double check for it when a OSSIA::Address is about to be destructed ?
