### ISSUE TITLE
Strange state behaviour

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1160]
In this scenario, the intervals under the "Chef d'orchestre JS" act strangely

[proto.zip](https://github.com/ossia/score/files/6041987/proto.zip)

After the "Conductor" interval ends, the following interval will only play until it's end state but never actually finish.
the following interval never starts.

**Comment by jcelerier** [comment]
is that still the case ?

**Comment by jcelerier** [comment]
hmm from the score it's just that there is something else in the score that launches the "retrig" message which restarts this whole sub-score
