### ISSUE TITLE
musical metrics preference is not saved

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1161]
when setting it off, it will go back to on at the next startup

**Comment by bltzr** [comment]
this is also not saved in the .score file : if I uncheck the notes icon, it’s back on when opening the file

**Comment by jcelerier** [comment]
that should be fixed as of 3.0.0-b2 (it's saved as part of the settings, then at some point in v3 I want to have proper per-project settings and then maybe it'll make sense to save it there)
