### ISSUE TITLE
Impossible interval

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1162]
![simplescreenrecorder](https://user-images.githubusercontent.com/26526517/110495946-4d783b00-80f5-11eb-8a91-4df663c37c0f.gif)

at the very bottom of this scenario, an invisible interval is connected to the previous state.

[TESTAGAIN.zip](https://github.com/ossia/score/files/6109641/TESTAGAIN.zip)

Navigating with the arrow keys, one can see that the interval actually loops back from right to left.
But it doesn't seem to be a transition since it is also influenced vertically

this may also be the reason why this score crashes every other time on play.

could be related to #1160

**Comment by jcelerier** [comment]
I can't fix that specific one but I should have fixed the thing that was causing those weird intervals to appear - please test edition, merging, etc... a lot to see if you see them cropping up again !
