### ISSUE TITLE
[mac os] score crash on load

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1163]
this score crashes on load, throwing the following error
LLVM ERROR: IO failure on output stream: Bad file descriptor

[Walking_02.4.zip](https://github.com/ossia/score/files/6124132/Walking_02.4.zip)

If llvm is involved, I should maybe mention that it uses a couple Faust effects

**Comment by thibaudk** [comment]
after recompiling without Faust or llvm the scenario oppens.
Another fatal audio error appears.
restarting with the dummy driver works.

After removing all Faust, it seems that it can be reloaded somewhat consistently on mac

**Comment by thibaudk** [comment]
After more tests, i seems that disconnecting from the network allows the scenario to be loaded.
An OSC and an OSCQquery device are used, and both show up as disconnected when opening the scenario.
Understandable for the OSCQuery one, but for plain OSC too ?

**Comment by thibaudk** [comment]
Same issue with midi.
This was tesrted on a24, where no audio output was possible, even on successful reload,
down to a21, where the scenario can be loaded when disconnected form both the network and the midi device.

**Comment by jcelerier** [comment]
should be fixed, can you retry on async_prtocools ?
