### ISSUE TITLE
logical error ?

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1164]
In the attached score, the rule of triggers only being available for validation when all previous intervals are playing is violated. 
Setting up the exact same example in v2 yields the expected results. 

see the final interval start playing immediately.

[logical.zip](https://github.com/ossia/score/files/6152741/logical.zip)

could be related to 
#1162
&
#1160

**Comment by thibaudk** [comment]
this just came back,

tested on b375e9b1f684fb9b37b4db716efe4fbeea2946fd

**Comment by thibaudk** [comment]
There seems to be some improvement on this front.

The remaining issue is that only the first "min duration" reached on converging intervals is taken into account.
All other min duration are ignored when a trigger is set to always

![logical_error](https://user-images.githubusercontent.com/26526517/116972734-c04bff80-acbb-11eb-89cd-bd5f50dbb057.png)

In this First case the trigger is validated as soon as we the second lower interval is played.

![logical_error2](https://user-images.githubusercontent.com/26526517/116977108-52570680-acc2-11eb-9bf5-28430940fbd8.png)

Here, the trigger is validated once the min duration of the top interval is reached.

**Comment by jcelerier** [comment]
can you try again with the latest commit (libossia must be updated) ?

**Comment by thibaudk** [comment]
Yes perfect ! 
This works now
