### ISSUE TITLE
cradh when openinng scenario with audio + midi + artnet

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1165]
here is the coredumpctl log
https://filesender.renater.fr/?s=download&token=7b7f5f59-0c98-4d9b-976e-20201de81331

this scenario in question can be found here 
https://github.com/scrime-u-bordeaux/marelle/blob/main/marelle_v2.score

seems related to devices

**Comment by jcelerier** [comment]
Can you also send the score binary ?

**Comment by thibaudk** [comment]
the .scorebin file or the actual score program ?

**Comment by jcelerier** [comment]
actual score program

**Comment by thibaudk** [comment]
here
[ossia-score.zip](https://github.com/ossia/score/files/6217110/ossia-score.zip)

**Comment by jcelerier** [comment]
Can you try with the latest feature/async_protocols ? It should be fixed

**Comment by thibaudk** [comment]
yes it now opens ! great !
I still need to test with the full setup.

Cheers !
