### ISSUE TITLE
Crash when JACK driver is selected without jack installed

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1169]
This also prevents score from reopening without erasing .config/OSSIA/score.conf

**Comment by jcelerier** [comment]
on which distro could I test that ?

**Comment by thibaudk** [comment]
ubunutu 20.04

**Comment by jcelerier** [comment]
hum, weird, I tested on a clean debian 10 (which should be equivalent) without any instance of JACK and in a33 it does not seem to crash. Can you still reproduce it on your side ?

**Comment by jcelerier** [comment]
bump @thibaudk, how can I reproduce that ?

**Comment by thibaudk** [comment]
sory I didn't see the previous answer. Witch would be the only way I can think of for reproducing.
Maybe it is fixed or something else was eluding me.
Closing for now then

**Comment by jcelerier** [comment]
okay thanks :) I'll try again on a clean machine to make sure, maybe some ubuntu 21.04
