### ISSUE TITLE
Play while focusing on a constraint in fullscreen should only play the constraint content

### ISSUE THREAD

**Issue by theod** [ossia/score#117]
a typical use case is when you want to improve a curve : 

![capture d ecran 2015-12-18 a 11 54 40](https://cloud.githubusercontent.com/assets/118426/11895341/41a2d7fc-a57e-11e5-83c7-2fd42e6aa007.png)

does it make sense for other users ? @reno-, @bltzr, @avilleret and @jln- ?

**Comment by jcelerier** [comment]
it's been the case for quite some time actually ! 
maybe it should be a settings however.

![hierarchy](https://cloud.githubusercontent.com/assets/2772730/20146510/70a35568-a6a4-11e6-9927-432f9a32962b.gif)
