### ISSUE TITLE
use a fixed faust library version to make sure that things work

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1179]
tested with release 3.0.0-a30

**Comment by thibaudk** [comment]
Tested with a33 Appimage too, seems to be a Faust math library mismatch

```
Debug: Faust error:  maths.lib : 124 : ERROR : syntax error, unexpected IDENT, expecting LPAR or DEF
 (:0)
```
Maybe the version used in score is not up to date ?

**Comment by jcelerier** [comment]
ah, it seems that there was an issue with the faust library - some things work, 
like e.g. Harmonic Oscillator, but some don't like marimbaMIDI.

**Comment by jcelerier** [comment]
done
