### ISSUE TITLE
crash after undoing a node removal that was listening for updates

### ISSUE THREAD

**Issue by theod** [ossia/score#118]
this is a reproductible crash.
1/ open "listening on return.maxpat"
2/ open "listening on return.scorejson"
3/ unfold Max node to see info node (at this point value update is ok)
4/ remove the info node
5/ undo the removal (at this point value update is not happening anymore)
6/ try to fold the Max node
=> crash !

here are all the needed files and the crashlog

[listening on return.zip](https://github.com/OSSIA/i-score/files/66512/listening.on.return.zip)

**Comment by jcelerier** [comment]
I tried and couldn't reproduce but it's because I think that I fixed #116 which was related
