### ISSUE TITLE
Icons for graphics settings

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1186]
A few new settings panel has appeared : Graphics (for settings related to the video API, rendering, etc)

Having an icon for it would be great !

**Comment by aklevy** [comment]
Does this look good ?
![settings](https://user-images.githubusercontent.com/9166925/117576944-0522cc80-b0e8-11eb-8300-29ff944cac26.png)

**Comment by jcelerier** [comment]
yes very nice !
