### ISSUE TITLE
i-score crashes when removing nodes from the explorer

### ISSUE THREAD

**Issue by bltzr** [ossia/score#119]
I just selected 3 (toplevel) nodes, hit -backspace, and boom !

Process:               i-score [43051]
Path:                  /Applications/i-score.app/Contents/MacOS/i-score
Identifier:            org.i-score
Version:               1.0.0-a34 (1.0.0-a34)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           i-score [43051]
User ID:               501

Date/Time:             2015-12-29 15:26:33.352 +0100
OS Version:            Mac OS X 10.11.2 (15C50)
Report Version:        11
Anonymous UUID:        9D4409BC-6C04-D9BC-6E6E-FC93AFD04755

Sleep/Wake UUID:       7880B48E-37B9-492F-9130-51D7B23F580B

Time Awake Since Boot: 600000 seconds
Time Since Wake:       1700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fcad6a00000
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x7fcad6a00000:
    MALLOC_TINY            00007fcad5800000-00007fcad6a00000 [ 18.0M] rw-/rwx SM=PRV  
--> 
    STACK GUARD            00007fff4e2e0000-00007fff51ae0000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.i-score                     0x000000010dbce080 OSSIA::Node::erase(std::__1::__wrap_iterstd::__1::shared_ptr<OSSIA::Node const_>) + 80
1   org.i-score                     0x000000010db595c2 OSSIADevice::removeNode(iscore::Address const&) + 386
2   org.i-score                     0x000000010d97231a NodeUpdateProxy::removeNode(TreePath<TreeNode<iscore::DeviceExplorerNode> > const&, iscore::AddressSettings const&) + 426
3   org.i-score                     0x000000010d963fc5 RemoveAddress::redo() const + 453
4   org.i-score                     0x000000010d92fcea iscore::AggregateCommand::redo() const + 42
5   org.i-score                     0x000000010d93f9f6 iscore::CommandStack::redoAndPush(iscore::SerializableCommand_) + 22
6   org.i-score                     0x000000010d988793 DeviceExplorerWidget::removeNodes() + 1251
7   org.qt-project.QtCore           0x000000010f7c85d0 QMetaObject::activate(QObject_, int, int, void__) + 2528
8   org.qt-project.QtWidgets        0x000000010e320a60 QAction::activate(QAction::ActionEvent) + 288
9   org.qt-project.QtWidgets        0x000000010e320935 QAction::event(QEvent_) + 245
10  org.qt-project.QtWidgets        0x000000010e32997b QApplicationPrivate::notify_helper(QObject_, QEvent_) + 251
11  org.qt-project.QtWidgets        0x000000010e32c2de QApplication::notify(QObject_, QEvent_) + 5630
12  org.i-score                     0x000000010d925265 SafeQApplication::notify(QObject_, QEvent_) + 21
13  org.qt-project.QtCore           0x000000010f7984f3 QCoreApplication::notifyInternal(QObject_, QEvent_) + 115
14  org.qt-project.QtGui            0x000000010ea1c92d QShortcutMap::dispatchEvent(QKeyEvent_) + 269
15  org.qt-project.QtGui            0x000000010ea1c621 QShortcutMap::tryShortcutEvent(QObject_, QKeyEvent*) + 257
16  libqcocoa.dylib                 0x000000010fe7f504 -[QNSView handleKeyEvent:eventType:] + 708
17  com.apple.AppKit                0x00007fff89885715 -[NSWindow _reallySendEvent:isDelayedEvent:] + 2108
18  com.apple.AppKit                0x00007fff891dd735 -[NSWindow sendEvent:] + 517
19  libqcocoa.dylib                 0x000000010fe716d7 -[QNSWindow superSendEvent:] + 39
20  libqcocoa.dylib                 0x000000010fe71080 -[QNSWindowHelper handleWindowEvent:] + 432
21  com.apple.AppKit                0x00007fff891da57b -[NSApplication sendEvent:] + 4382
22  libqcocoa.dylib                 0x000000010fe8881e -[QNSApplication sendEvent:] + 78
23  com.apple.AppKit                0x00007fff8910d03a -[NSApplication run] + 796
24  libqcocoa.dylib                 0x000000010fe852df QCocoaEventDispatcher::processEvents(QFlagsQEventLoop::ProcessEventsFlag) + 2191
25  org.qt-project.QtCore           0x000000010f795c1c QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) + 412
26  org.qt-project.QtCore           0x000000010f798a95 QCoreApplication::exec() + 341
27  org.i-score                     0x000000010d9279d4 main + 84
28  libdyld.dylib                   0x00007fff956d45ad start + 1

**Comment by jcelerier** [comment]
I tried fixing it in v1.0.0-a35 (should be online in about 1 hour)
