### ISSUE TITLE
Closing startup panel

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1215]
Using the "escape" key on the startup panel closes it and leaves score blank.

There is also no way to "abort launch" and close the startup panel with score, witch is useful for example when score was launched twice by mistake.

Maybe, if possible, do not show the main score screen before the splash screen is closed.

**Comment by jcelerier** [comment]
exit button added thanks to @RobinMontferme @aklevy ; I added the feature to create a new document when escape is pressed. :cat:
