### ISSUE TITLE
merging events and timenodes : workflow ?

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#122]
Case 1 : 
I have an existing event and I want to merge it with another existing event. 
Case 2 : 
I have an existing event and I want to put it on an existing timenode (without merging any events = merging timenodes)

Example : You have 2 parallel ways and you want to do a conjunction (= synchronise the end) without creating a new constraint. 

What should be the workflow ?

@theod @bltzr @jln- @reno- @avilleret @jcelerier @pchdev any proposition ?

**Comment by theod** [comment]
here is a screenshot : 

![capture d ecran 2016-01-27 a 11 25 48](https://cloud.githubusercontent.com/assets/118426/12610594/ed7d597e-c4e8-11e5-9405-1c3a352d3406.png)

so from what I understand is how to connect the two last events ?

**Comment by theod** [comment]
@bltzr proposes to display the timenode of a single event when we are moving a single event under another.

**Comment by theod** [comment]
I have another proposition to allow the synchronisation of to event (e.g. the merge of those two events into a time node). a we have a "sequence" creation mode I would like to have a "synchronize" creation mode. in this mode, when I click and drag from an event, I create another event under it (without creating the a next time constraint as it is now) : 

![capture d ecran 2016-03-16 a 12 10 53](https://cloud.githubusercontent.com/assets/118426/13810447/2eb6a3e8-eb70-11e5-8e54-b912ea69114c.png)

if there is an event near to the end of the synchronisation I'm creating, I would like to get : 

![capture d ecran 2016-03-16 a 12 12 56](https://cloud.githubusercontent.com/assets/118426/13810529/99c33f0c-eb70-11e5-9367-331e85f499f1.png)

still in "synchronize" mode, I would like to get the same result if  I'm creating a constraint from a previous event to another event in the future.

does it make sens for you @nvuaille ? I have the feeling that having a particular creation mode would help you to solve this issue don't you ?

**Comment by jcelerier** [comment]
seems to be ok, just have to add a button

**Comment by bltzr** [comment]
added to Lyon's topic list

**Comment by jcelerier** [comment]
merging has been reenabled for some time and seems to work correctly now
