### ISSUE TITLE
can't access to I/O type and other options when editing a Bool typed Address

### ISSUE THREAD

**Issue by theod** [ossia/score#123]
If I create an Address and I select Bool type I can see many options : 

![capture d ecran 2016-01-26 a 19 02 40](https://cloud.githubusercontent.com/assets/118426/12589782/bb001ef2-c45f-11e5-8a43-f922a0aae275.png)

but i I try to edit the Address afterward the options are not available anymore : 

![capture d ecran 2016-01-26 a 19 03 06](https://cloud.githubusercontent.com/assets/118426/12589816/e5668668-c45f-11e5-8b5c-bd352e5bd7d5.png)

**Comment by theod** [comment]
there is also a strange behavior with Tuple typed Address but in that case the type si None when I try to edit the Address. not sure it is related ?

**Comment by theod** [comment]
this appends on a36 release and on dev branch too

**Comment by jcelerier** [comment]
seems that the problem is because it is a message

**Comment by theod** [comment]
it works now !
bravo !
