### ISSUE TITLE
cmd+c on an event A then cmd+v on an event B doesn't copy the state of A into B

### ISSUE THREAD

**Issue by theod** [ossia/score#125]
is this a bug or lack of documentation ?

**Comment by theod** [comment]
and to be more precise the state of A should be merged into the state of B

**Comment by nvuaille** [comment]
I guess we should before answer this one : https://github.com/OSSIA/i-score/issues/55

**Comment by nvuaille** [comment]
(and maybe answer this one to : https://github.com/OSSIA/i-score/issues/122)

**Comment by nvuaille** [comment]
For now, cmd+v doesn't do anything I think.
The current way to add the state of event A to the state of event B is to use the "Paste Content" option (in object menu and in contextual menu)

**Comment by theod** [comment]
but how do I copy the content of A ?
if I do cmd+c on the eventA and then "Paste content" on B it doesn't work.

here A is the start pattern event : 
![capture d ecran 2016-01-27 a 16 04 03](https://cloud.githubusercontent.com/assets/118426/12617391/c2067920-c50f-11e5-868f-d8fba5a85eec.png)

and B the end pattern event : 
![capture d ecran 2016-01-27 a 16 06 07](https://cloud.githubusercontent.com/assets/118426/12617412/df2e4064-c50f-11e5-9f7d-b892d8412ef9.png)

B remains empty after selecting "Past content" from the menu.

**Comment by nvuaille** [comment]
hmmm ... 
Works for me on linux. Can you try to use the menu "Object/copy" instead of cmd+c ? I fear that OSX is kidding us ...

**Comment by theod** [comment]
same result :-s

**Comment by jcelerier** [comment]
Just checked, it's because it is not implemented for the loops (but it should be done generically - my fault)

**Comment by theod** [comment]
there is still a problem when trying to copy the start pattern event content of a loop
