### ISSUE TITLE
Ignore all quantisation when "Musical" time is off

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1251]
Waiting for the next bar or syncing to quarter notes does not make much sens when neither "exist"

**Comment by jcelerier** [comment]
what is supposed to happen with processes that depend on a synchronisation mechanism ?
for instance: pattern sequencer, metronome

**Comment by jcelerier** [comment]
up

**Comment by jcelerier** [comment]
(note that I changed the system to use the quantification setting on the interval, can you check again with how it works now ? e.g. setting "Free" quantization on the topmost interval should disable quantization)

**Comment by thibaudk** [comment]
sorry I didn't see the reply, i'll test.



> what is supposed to happen with processes that depend on a synchronisation mechanism ?
> for instance: pattern sequencer, metronome

I supose these would be the exceptions and would not be affected by turning "Musical" off

**Comment by thibaudk** [comment]
actually, thinking of it now, I wonder if the pattern sequencer, metronome and other processes depending on synchronization could be set in Hz instead of musical units when "Musical" is switched off.
like the LFO in "Free" mode.
and/or in samples like the step sequencer.

I think Hz would be more useful.

But triggers in particular should ignore all quantization when "Musical" is off.
I'll look into it see if I can propose a PR
