### ISSUE TITLE
display actual rather than generic name of process in nodal view 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1260]
![image](https://user-images.githubusercontent.com/113982/126813095-175771cb-a393-42f6-9f9d-b5593a6d8136.png)

in this case, e.g., it would be more informative to have "synth-pd" and "test-CS" in the headers of the processes, wouldn't it ?

**Comment by jcelerier** [comment]
huh, it works here ? 
![huh](https://user-images.githubusercontent.com/2772730/127388088-2c6cd6cd-21c9-435d-9674-bef089f4c319.png)

**Comment by jcelerier** [comment]
(minitest is a pd one)

**Comment by bltzr** [comment]
When loading the score? Or when dynamically, when renaming a process from the objects window?

**Comment by jcelerier** [comment]
When dropping in a new score (and renaming dynamically in the object inspector), I'll test reloading

**Comment by jcelerier** [comment]
ah indeed, it's the reloading which breaks.
