### ISSUE TITLE
how to move an event between its min and max bound without moving the bounds ?

### ISSUE THREAD

**Issue by theod** [ossia/score#127]
here is a screenshot of a typical case I just want to move the event for space convenience but not he max bound because I've put it at a precise duration : 

![capture d ecran 2016-01-27 a 18 29 11](https://cloud.githubusercontent.com/assets/118426/12622201/8178e3a6-c524-11e5-833c-bc7df549710c.png)

is it possible ?

**Comment by nvuaille** [comment]
It's a CSP's policy, but not the default one and there's no user interface to change that for now =) (it's one question for the next skype).

**Comment by theod** [comment]
this will be solved with the CSP.
