### ISSUE TITLE
score duration in bars at startup when "show musical metrics is off"

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1274]
![image](https://user-images.githubusercontent.com/113982/128498882-2c953a6d-f369-4e6e-ab30-8d2b2b1ee37a.png)

toggling "show musical metrics is off" on and off puts the score duration back to min-seconds

**Comment by bltzr** [comment]
> toggling "show musical metrics is off" on and off puts the score duration back to min-seconds

actually it’s toggling the "musical mode" button in the editor that fixes that

**Comment by jcelerier** [comment]
can you check if that still happens ?

**Comment by bltzr** [comment]
yes



>

**Comment by jcelerier** [comment]
fixed :)
