### ISSUE TITLE
use [] to access Tuple value index in Expression

### ISSUE THREAD

**Issue by theod** [ossia/score#128]
here is what happen in i-score when I click on Ok to store the Expression : 

![capture d ecran 2016-01-27 a 18 43 00](https://cloud.githubusercontent.com/assets/118426/12622502/f9ede72c-c525-11e5-882e-ce170322899a.png)

**Comment by nvuaille** [comment]
What does this expression mean for you ?
Comparators need definition for other than 1 dimension numbers. For now, i-score doesn't know how to compare tuple.

**Comment by theod** [comment]
yes you're right.
this typically relative to spatial interaction authoring so I add @jcelerier to explain how it thinks i-score will help us in the future for such a case.

should we postpone this to a release/2.0 ?

**Comment by reno-** [comment]
For thé Time being, we might use [index] to use condition for tuples. 

Flock/deviation[0] > 5 && Flock/deviation[0] > 5

Does it make sense?

**Comment by theod** [comment]
a lot !

**Comment by theod** [comment]
but this i-score feature maybe needs some new features in API ...

**Comment by jcelerier** [comment]
> but this i-score feature maybe needs some new features in API ...

I don't think so and it makes sense and also allows nesting easily.

Should Matlab syntax (tuple[1, 2]) or C syntax (tuple[1][2]) be prefered ? 
What should happen if there is an out of bound access ?

**Comment by theod** [comment]
> Should Matlab syntax (tuple[1, 2]) or C syntax (tuple[1][2]) be prefered ? 

:+1 for C syntax

> What should happen if there is an out of bound access ?

a crash :-)

**Comment by jcelerier** [comment]
>  but this i-score feature maybe needs some new features in API ...
> 
> I don't think so and it makes sense and also allows nesting easily.

sorry, using my brain for more than half a second told me that yes, indeed it's necessary to add this in the API.
Now, the big question : if you add arrays accessors, why not add instances ? and then why not call methods on these instances ? And then, why not directly use something like any of the tens of systems that already do the same thing and are mentioned
-  here  : http://www.z25.org/static/_rd_/zocp_init_plab/index.html 
-  or here : http://linuxfinances.info/info/corbaalternatives.html

?

**Comment by reno-** [comment]
Protocol buffers from Google sounds good !!

**Comment by jcelerier** [comment]
There is alos https://capnproto.org/ which is roughly the successor of ProtoBuf

**Comment by theod** [comment]
all what I read about capnproto looks really nice.
however I'm not sure to understand at which level this will be introduced into the API ?
I've opened a ticket to continue this discussion here : https://github.com/OSSIA/API/issues/20

**Comment by jcelerier** [comment]
Also added in the "textual" expression editor (not the graphical one)

**Comment by theod** [comment]
I need a demo for this because the parser does seems to like what I do : 
![capture d ecran 2016-03-16 a 12 39 12](https://cloud.githubusercontent.com/assets/118426/13811152/3543750c-eb74-11e5-987f-d38111932b0f.png)

**Comment by jcelerier** [comment]
Same that for Impulse, it has to be done in the "textual" editor on the menu at the right.

**Comment by theod** [comment]
could you provide me a screenshot because I can't see any menu !

**Comment by theod** [comment]
oups sorry I did'nt see the previous answer ! thanks

**Comment by theod** [comment]
I tried this expression in the expression editor : (newDevice:/pos[2] == 1)
but it returns an error. what I'm doing wrong ?

**Comment by jcelerier** [comment]
It may show as an error (red background) in the editor widget but if you re-enter the edit menu and it shows the correct expression it means that the parsing has been done correctly and the correct Expression should be created in the API (but there could still be bugs here :p)
