### ISSUE TITLE
creating an audio device with a space in the name breaks device explorer

### ISSUE THREAD

**Issue by Swiftb0y** [ossia/score#1289]
It results in a popup saying `Internal error: Error: it != m_devices.cend()`.
Adding more devices still works but the device explorer display breaks (spinny stays indefinitely). 
Happens on 3.0.0-b3.

**Comment by jcelerier** [comment]
thanks for the report!

**Comment by jcelerier** [comment]
okay, for now I'm disabling the editing of the name, then in a later version will allow to change it again but for now this has some non-obvious consequences that I do not want to tackle just before the release. thanks !

**Comment by Swiftb0y** [comment]
But wouldn't not being able to edit the name mean that there can only ever be a single device of each type since there can't be duplicate names?

**Comment by jcelerier** [comment]
no, it's only done for the audio device (for which there can only be a single one since it's to access your soundcard's I/O and score currently is only able to handle one soundcard at the time). Other devices, OSC, MIDI can change name without issue :)

**Comment by Swiftb0y** [comment]
Ah, right, I forgot. Sounds good to me then.
