### ISSUE TITLE
crash when trying to setup an Expression with a composition

### ISSUE THREAD

**Issue by theod** [ossia/score#129]
Here is what I was trying to do : 

![capture d ecran 2016-01-27 a 19 04 57](https://cloud.githubusercontent.com/assets/118426/12623110/e265c39c-c528-11e5-9664-05c99916e8a0.png)

the crash occurs when I click on Ok.

[crashlog.txt](https://github.com/OSSIA/i-score/files/107083/crashlog.txt)

**Comment by theod** [comment]
@jcelerier told me you're maybe more aware about this issue

**Comment by nvuaille** [comment]
@jcelerier : did you change something/ test it ? I had crash only on OSX, I can't reproduce it on any Linux.

**Comment by jcelerier** [comment]
yes, I worked on it monday.

**Comment by nvuaille** [comment]
Doesn't crash anymore !
But question : if there's no binary operator, the 2nd relation is not saved, without a word. Should we say something to the user ?

**Comment by jcelerier** [comment]
maybe put it in red if it is not the first and empty ?

**Comment by theod** [comment]
yes it works ! 

> if there's no binary operator, the 2nd relation is not saved, without a word. Should we say something to the user ?

+1 for red  and maybe we should block the ok button ?

**Comment by theod** [comment]
I close this one as I've opened a new one for the last point
