### ISSUE TITLE
No VST3 recognized on Windows 10

### ISSUE THREAD

**Issue by alfonso73** [ossia/score#1290]
Hi, VST2 are correctly scanned. VST3 are not.

**Comment by jcelerier** [comment]
Thanks for checking, looking into it

**Comment by alfonso73** [comment]
@jcelerier thanks!

**Comment by jcelerier** [comment]
hmm, I've tried with a few vst3, Dexed, Evaluator, Tyrell N6, FSA FourHead, Vastaus and they seem to be detected and run correctly on my windows machine.
Which one did you try that did not work ?

**Comment by jcelerier** [comment]
anyone else with a windows machine that could try ?

**Comment by jcelerier** [comment]
sorry, tried on multiple Windows systems and I cannot reproduce, please reopen if you have more details !
