### ISSUE TITLE
time progression is not displayed on flexible TimeConstraint

### ISSUE THREAD

**Issue by theod** [ossia/score#130]
here is a screenshot that illustrates this trouble : 

![capture d ecran 2016-01-28 a 09 23 59](https://cloud.githubusercontent.com/assets/118426/12638936/1cda8ca6-c5a1-11e5-9525-a8804988216d.png)

**Comment by nvuaille** [comment]
The problem was with infinity in maximum duration

**Comment by theod** [comment]
yes it's works now ! thanks !
