### ISSUE TITLE
Index mismatch between Audio device tree and audio device matrix

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#1306]
Indexes start at 0 in the Audio device tree, and at 1 in the matrix when editing a node.
Potentially only a graphical issue as index 1 in the tree and in the matrix seem to correspond

**Comment by jcelerier** [comment]
@thibaudk if you want to look at it it's pretty easy, by calling 

     m_mapping.setHorizontalHeaderLabels({ ... }) 

and 

     m_mapping.setVerticalHeaderLabels({ ... })

in AudioDevice.cpp, after `m_mapping.setColumnCount` and `m_mapping.setRowCount` are called

**Comment by jcelerier** [comment]
let's postpone this to 3.1
