### ISSUE TITLE
Sample&hold object

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1309]
A new process that would take an value and sample it at a given rate (or upon an input)

**Comment by jcelerier** [comment]
@RobinMontferme assigning to you as with was a request from Gaël.

The idea is to have a process with an input of type value, which would "sample" it at regular interval. e.g. if the interval is 3, given : 

    1 2 3 4 5 6 7 8 9 1 2 3 4 5

the output would be 

    1 1 1 4 4 4 7 7 7 1 1 1 4 4

(actual intervals in flicks but you get the idea)

**Comment by jcelerier** [comment]
although I wonder if it isn't just something that we can do with @thibaudk 's rate limiter ? https://github.com/ossia/score/blob/master/src/plugins/score-plugin-fx/Fx/RateLimiter.hpp

**Comment by jcelerier** [comment]
@thibaudk what do you think ? maybe it's just a matter of adding a "manual" sample input to the Rate Limiter ?

**Comment by thibaudk** [comment]
currently the rate limiter outputs the current incoming value if it falls on the given subdivision.
Would a sample and hold simply do the same, only outputting the value at the previous beat ?

**Comment by thibaudk** [comment]
so maybe just adding a "Hold" button to keep the current value ?

**Comment by thibaudk** [comment]
or should the "Hold For" control, with a rate widget, to indicate how long a value should be held ?

**Comment by jcelerier** [comment]
> Would a sample and hold simply do the same, only outputting the value at the previous beat ?

from what I could understand of Gaël's needs, the idea is to have two inputs: 

A: the signal
B: the "hold" message

Every time there is an impulse on the "hold" message, the process takes the current value of the signal and outputs it.

**Comment by jcelerier** [comment]
so maybe it is a really different object after all.

**Comment by thibaudk** [comment]
I'll circle back with @gaeljaton

**Comment by gaeljaton** [comment]
hi dudes!
yeah, I was looking for S&H object like module synth.
*bool/trigger input for "holding" last input
*data input (to be hold) 
*ouput for "holded" signal
(optionnaly : *bool/trigger input for release the holding => output is bypassed)
internal sample rate could be hard coded or adjustable, but, I guess it have to be around audio rate...
cheer's guys!
https://www.musicstore.com/fr_FR/EUR/Doepfer-A-148-Dual-Sample-Hold/art-SYN0003184-000

**Comment by jcelerier** [comment]
hey ! so I added a few expression presets which allow various cases:

- Time-based sample&hold: it will sample at a regular interval (adjustable with a) 
  * https://github.com/ossia/score-user-library/blob/master/Presets/Expression%20Value%20Filter/Sample%20and%20Hold.scp
- Hold A: it will let the signal go through if a == 1, and hold the last value otherwise
  * https://github.com/ossia/score-user-library/blob/master/Presets/Expression%20Value%20Filter/Hold%20A.scp
- sample and hold A: it will sample when the signal becomes >= 1 so if the input in "a" does 0 1 0 0 1 0 it samples 2 times
  * https://github.com/ossia/score-user-library/blob/master/Presets/Expression%20Value%20Filter/Sample%20and%20Hold%20A.scp

I think that this covers most cases so closing, please reopen if more is neede :-)
