### ISSUE TITLE
color the border of the event instead of filling it

### ISSUE THREAD

**Issue by theod** [ossia/score#131]
as the screenshot illustrates it : 

![capture d ecran 2016-01-28 a 09 23 59](https://cloud.githubusercontent.com/assets/118426/12638963/59aa6ea8-c5a1-11e5-8cff-4add72ad4fa8.png)

at execution time the events are filled with a color so it is unclear if they have a state or not.
I would prefer to color the border of the events.

**Comment by nvuaille** [comment]
Should the condition bracket have same color as event during execution ?

**Comment by theod** [comment]
as a logical element the condition widget should be yellow by default (like the trigger) then green or red depending if its event is HAPPENED or DISPOSED.

**Comment by theod** [comment]
very nice !
