### ISSUE TITLE
AppImage version: Install the desktop entry

### ISSUE THREAD

**Issue by Himura2la** [ossia/score#1311]
I see you have the `.desktop` file: https://github.com/ossia/score/blob/master/cmake/Deployment/Linux/AppImage/ossia-score.desktop

But it does not appear in my `~/.local/share/applications/` directory after first start.
Maybe it's not intended to, but anyway I'd like to have such ability.
Maybe it should not be done automatically, but there should be at least a button in settings to create a desktop entry.

CentOS Stream 8

**Comment by jcelerier** [comment]
hi ! interesting, I though that the AppImage was supposed to do that automatically

**Comment by Himura2la** [comment]
OK, I see that there are many AppImages without such integration. 
But some programs do care about desktop entry themselves. For instance, https://www.nuclino.com/download
![Screenshot from 2021-10-10 22-51-31](https://user-images.githubusercontent.com/7802808/136711104-c75b652e-3a4c-4757-9b64-fe09b685bee4.png)

**Comment by jcelerier** [comment]
hm, this looks like a standard thing. But I looked a bit in the appimage doc and repo and could not find that text anywhere. @probonopd do you know what I should do to use that feature ? is it a standard apprun script that can be found somewhere ?

**Comment by Himura2la** [comment]
Personally I think that's custom code just for Nuclino. I guess we could implement something similar for score.
But the blocking popup on launch is not the best idea, I think we'd better add a button to Settings and Splash Screen. 
I've seen this approach in JetBrains IDEs (Android Studio).

**Comment by probonopd** [comment]
The screenshot shows some old code I once wrote but that is no longer recommended.

We recommend not do do this kind of thing anymore and let a [dedicated daemon](https://github.com/AppImage/awesome-appimage/#desktop-integration) or the desktop environment handle this for all AppImages.

**Comment by jcelerier** [comment]
okay, I'll go with following the recommended best practices on this. I will add a link to that page to the ossia download page so that people can set up the integration in the recommended way. Thanks all !
