### ISSUE TITLE
crash on macos 11.6 / score 3.0.0-rc1

### ISSUE THREAD

**Issue by avilleret** [ossia/score#1313]
while playing with gfx, I got this attached crash log.
I made a scenario with an Output Window device.
Add a process with Shader.
Setup processes output to window.
Hit play -> badaboum

[scrore_crash_log.txt](https://github.com/ossia/score/files/7387120/scrore_crash_log.txt)

**Comment by avilleret** [comment]
note that the shader was empty

**Comment by jcelerier** [comment]
ah I can reproduce it that way, thanks
