### ISSUE TITLE
score is eating a lot of CPU while idle on macos 11.6

### ISSUE THREAD

**Issue by avilleret** [ossia/score#1314]
to reproduce : open score, create a new scenario and wait a bit
and then the CPU jump to 60% and even more while I was not doing anything.

![image](https://user-images.githubusercontent.com/504914/138654833-ae25bba0-7ac3-41da-8d19-73cb1a98fc26.png)

**Comment by jcelerier** [comment]
Arf, I can't seem to reproduce it here... waited for half an hour.
Do you think you could capture a trace in Instruments ?

**Comment by jcelerier** [comment]
Tried a fix (https://bugreports.qt.io/browse/QTBUG-50181), will be available on the next release

**Comment by jcelerier** [comment]
closing the issue as I don't see any particular cpu usage ... for current builds score sits at 1.6% CPU with an open document on my mac mini
