### ISSUE TITLE
Artnet Universe always defaults to 0 

### ISSUE THREAD

**Issue by A-Costa** [ossia/score#1315]
Hi everyone, first of all thank you so much for your work. Score is an amazing piece of software.

I believe the Artnet device has a bug related to the setup of the Artnet Universe.

When adding a new device, after selecting Artnet from the menu it is possible to specify a Universe. 
Unfortunately it seems that whatever Universe is specified in the menu, score will keep sending packets to Universe 0.

To make sure i have also checked the packets using Wireshark. The payload of the packets contains 0 where the Universe should be set, even though at creation of the Artnet device I specified a different Universe.

This is happening with version `3.0.0-rc1` on MacOs.

**Comment by jcelerier** [comment]
thanks for the report ! checking..

**Comment by jcelerier** [comment]
eh, indeed it was only handled in the E1.31 case...
 
I've tried something (but I don't have DMX hardware right now to check :/).

There will be a new version here soon if you can try (~40 minutes): https://github.com/ossia/score/releases/tag/continuous 

Alternatively, could you make me a small screenshot of a packet with wireshark and show me which bytes are for the universe so that I can check it that way ?

**Comment by A-Costa** [comment]
For sure, screenshot coming!

**Comment by A-Costa** [comment]
Ok so here in the first screenshot the main Wireshark screen of the captured frame. Keep in mind that this shows full details about the whole ethernet frame, so the position of the bytes is shifted:

<img width="1280" alt="Schermata 2021-11-18 alle 01 19 12" src="https://user-images.githubusercontent.com/17851789/142311429-692128cc-c018-43bd-9209-525d631bd25e.png">

I've also made a screenshot of the isolated Artnet packet:

<img width="1280" alt="Schermata 2021-11-18 alle 01 22 24" src="https://user-images.githubusercontent.com/17851789/142313796-09154a7d-d596-4402-a3a2-3c9881f9c008.png">

Which shows that the Universe should be specified in two bytes with offset 14 and 15. That can also be seen in the Packet Format section in [Wikipedia](https://en.wikipedia.org/wiki/Art-Net#Packet_format).

**Comment by jcelerier** [comment]
oh interesting, thanks for the link !

**Comment by jcelerier** [comment]
![ta](https://user-images.githubusercontent.com/2772730/142393220-81b8e70b-e9d8-4985-bc3d-798384c88b2b.png)

okay, got it working !  :)

**Comment by jcelerier** [comment]
didn't know that wireshark has a custom visualizer for it but of course it does aha

**Comment by A-Costa** [comment]
Of course, how would you hack concerts light show otherwise?? 😂
