### ISSUE TITLE
Select address in QLineEdit by right click instead of button

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#132]
Mabe it could be done like this ? 

http://www.qtcentre.org/threads/7099-QLineEdit-contextMenu

By adding the QMenuView inside the right click menu instead of having a button that must be pressed.
This would make the inspector more readable I think.

**Comment by nvuaille** [comment]
Seems funny !

**Comment by nvuaille** [comment]
I did it !

**Comment by jcelerier** [comment]
:cupid:
