### ISSUE TITLE
build fail on Ubuntu 15.10

### ISSUE THREAD

**Issue by avilleret** [ossia/score#133]
trying to build i-score myself on my Ubuntu 15.10 laptop leads to :

```
/home/antoine/lib-src/OSSIA/i-score/base/plugins/iscore-plugin-js/JS/JSAPIWrapper.cpp:11: erreur : use of undeclared identifier 'qjsEngine'
    auto engine = qjsEngine(this);
                  ^
```

this happens with Ninja/Clang++, make/g++ and QtCreator (with which I can force to build against Qt5.4 instead of 5.5);

**Comment by jcelerier** [comment]
From the looks of it, it needs `qtdeclarative5-dev` . I'll add it to the readme.

**Comment by avilleret** [comment]
I already have it
another idea ? :-D

**Comment by jcelerier** [comment]
lie down, try not to cry, cry a lot.

I'm installing a VM, I'll tell you asap

**Comment by jcelerier** [comment]
okay, this was due to the use of a Qt5.5 function.
I pushed the fix on master.

**Comment by avilleret** [comment]
indeed I was using Qt5.4 even on command line
thanks for the fix

**Comment by jcelerier** [comment]
normally it should work up to Qt 5.3 in order to keep it running on raspberries, but I don't have the time to test very often on old versions.
