### ISSUE TITLE
Use ExpressionPulse in expression editor

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#134]
I added the ExpressionPulse to the parser and the Expression data model.

On the parser, it will look like `impulse(device:/address)`. 
On the tree, it is part of the `ExprData` variant, so one has to check for it : 

```
        if(e.is<State::Pulse>())
        { ... }
```

It could be nice to add it as a capability to the ExpressionEditorWidget.

**Comment by jcelerier** [comment]
@theod I added next to the Trigger widget support for textual editing which allows for ExpressionPulse usage.

I encountered a small problem : since `(` and `)` are valid characters in addresses, I replaced the expression to look like : 

`(device:/an/address impulse)`

**Comment by theod** [comment]
could you make me a demo because I don't manage to get the support for textual editor next to the trigger.

**Comment by theod** [comment]
I also tried to put impulse word after an address but it seems that the parser return an error.

**Comment by theod** [comment]
here is a picture of the trouble : 
![capture d ecran 2016-03-16 a 12 41 18](https://cloud.githubusercontent.com/assets/118426/13811183/65bb7400-eb74-11e5-8291-64bf6342ad91.png)

**Comment by jcelerier** [comment]
Expression editor should look like this : 

![impulse](https://cloud.githubusercontent.com/assets/2772730/13811320/4cd94114-eb75-11e5-9e40-133021229a84.png)

One has to press the "#" symbol (while waiting for a proper "settings" icon :p ) and choose "edit"

**Comment by theod** [comment]
bravo !

**Comment by jcelerier** [comment]
I'm for keeping this issue open as long as it isn't implemented as a widget or something like this (the "edit text" is just a hack to be able to try things quickly.
