### ISSUE TITLE
Stretch / crop modes for videos & images

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1346]

**Comment by josephlarralde** [comment]
On a 1440 x 900 macbook screen, if I play a full HD video in full screen, the width / height ratios of the screen and video do not match and the video is stretched to fill the screen dimensions.

IMO the expected default behaviour should be the video filling the maximum space in the screen without being stretched : if it is more "horizontal" than the screen, there would be black (or whatever background color) lines above and below, and in the other case (video more "vertical" than the screen) there would be black lines at the left and the right of the video.

**Comment by jcelerier** [comment]
okay, I've implemented this (along with the other common stretch modes), will push soon ! thanks :)

**Comment by josephlarralde** [comment]
Cool, thanks !
By stretch modes, do you mean some score parameters that could be tweaked as a workaround ?
I tried to modify the size of the window device, but it didn't change the fullscreen result.

**Comment by jcelerier** [comment]
here's the prototype, the scaling mode can be changed on the video inspector when clicking on the video process:

https://github.com/ossia/score/releases/tag/continuous

**Comment by josephlarralde** [comment]
Nice, all the stretch modes make perfect sense together, working as expected on my machine !
I guess we can close the issue :)
