### ISSUE TITLE
Playback cursor lags/jitters if view is scrolled vertically

### ISSUE THREAD

**Issue by s-ol** [ossia/score#1357]
I'm using score 3.0.1 on NixOS with Wayland.
While things are playing, the playback cursor moves from left to right normally as long as I am scrolled all the way to the top.
If I am scrolled even a little bit down, the playback cursor only updates sporadically and otherwise stays in the same place. It seems as if it maybe reacts to mouse movement only, redrawing when that happens.

Here is my derivation (can be used to reproduce the build):

<details>

```nix
{ pkgs ? import <nixpkgs> {} }:
  let inner =
    {
      qt5,
      cmake,
      pkg-config,
      libllvm,
      boost175,
      git,

      SDL2,
      avahi,
      portaudio,
      portmidi,
      libjack2,
      alsaLib,
      ffmpeg,
      libsndfile,
      lame,
      flac,
      libopus,
      libvorbis,
      # faust,
      lilv,
      fftw,

      fetchFromGitHub,
      lib, stdenv,
      ...
    }:

    stdenv.mkDerivation rec {
      version = "3.0.2";
      pname = "ossia-score";

      src = fetchFromGitHub {
        owner = "ossia";
        repo = "score";
        rev = "v${version}";
        hash = "sha256-hZelxgmG4DjsPnvt0Q67l4OTNDQBl9gTtbn04weg6UY=";
        fetchSubmodules = true;
      };

      nativeBuildInputs = [ qt5.wrapQtAppsHook git ];

      buildInputs = with qt5; [
        cmake
        pkg-config
        SDL2.dev
        libllvm
        qtbase
        qtdeclarative
        qtquickcontrols2
        qtserialport
        qtsvg
        qtwebsockets
        boost175

        alsaLib
        portaudio
        avahi
        libjack2
        ffmpeg
        libsndfile
        lame
        flac
        libopus
        libvorbis
        # faust
        lilv
        fftw
      ];

      cmakeFlags = [
        "-Wno-dev"
        "-DCMAKE_BUILD_TYPE=Release"
        "-DCMAKE_UNITY_BUILD=1"
        "-DDEPLOYMENT_BUILD=1"
        "-DCMAKE_SCRIPT_RPATH=ON"
        "-DLilv_INCLUDE_DIR=${lilv}/include"
        "-DLilv_LIBRARY=${lilv}/lib/liblilv-0.so"
      ];

      meta = {
        description = "An interactive sequencer for the intermedia arts";
        homepage = "http://ossia.io/";
        license = lib.licenses.gpl3Plus;
        platforms = lib.platforms.linux;
      };
    };
  in inner pkgs
```

</details>

and nix-info:
```
nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.4, channels(s-ol): "nixos-unstable-22.05pre347947.689b76bcf36", channels(root): "home-manager-21.11, nixos-21.11.334587.e6377ff3554", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by jcelerier** [comment]
hi, thanks ! 

can you try running score with --no-opengl to see if that changes something ? 

also:

- what would be the easiest way for me to try with the same configuration ? 
- which DE are you using ? I know that there are unresolved issues between Qt and GNOME and wayland (at least with the version of Qt that score uses - we need to ship QGnomePlatform I think)

**Comment by s-ol** [comment]
I tried `--no-opengl` but that didn't help.

I looked a bit closer and I can now tell that the issue reliably happens exactly when the green/turquoise main timeline scrolls out of view: 

![image](https://user-images.githubusercontent.com/1731279/152659135-29618a1b-f377-4be3-ae06-8b19cab0275a.png)

As you can see I got rid of the default events/timelines (these might be the wrong terms, I'm very new to this tool) and put everything directly in the main timeline. Maybe the issue is related to that?

> which DE are you using?

I'm running sway right now.

> what would be the easiest way for me to try with the same configuration ?

On a NixOS system, you should be able to copy the derivation I posted above in a file `ossia-score.nix` and then build it using `nix build -f ossia-score.nix`. This will leave a symlink `result` in your working directory, at which point you can run `result/bin/ossia-score` to execute it.

I've also noticed that it happens in the appimage version as well. Since you probably don't have a NixOS installation, it would probably be a good idea to first see if you can reproduce it with the appimage on any other Linux distro that you have a quick way of running Wayland on.

**Comment by jcelerier** [comment]
oh okay, thanks ! I think I see where the issue is, it does not take the correct item length into account for updating the viewport... checking how to fix that.

**Comment by jcelerier** [comment]
so interesting, I can reproduce it under wayland compositors only
