### ISSUE TITLE
Tempo automation points don't have precise time and value controls in full size view in the same way Automation (float) does.

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1363]
(Appimage 3.0.2 - Arch Linux)

**Current Behaviour:**

When zooming into tempo automation envelopes in the full size view and selecting a point, the inspector does not show t(ms) and value input options, making it much harder to precisely edit tempo curves. The inspector just shows "Point" with no associated options. When selecting an Automation (float) envelope in the same full size view, the above options are present.

**Expected Behaviour:**

It should be possible to edit the precise value of tempo automation points using the inspector in the same way one can edit generic automation points.

**General Thoughts:**

I'd like to be able to perform precise repitching operations on audio files using tempo curves and it will be extremely fiddly without being able to input exact values for each point.

**Comment by jcelerier** [comment]
(thanks for your detailed reports by the way, it is very nice and useful!)
