### ISSUE TITLE
Copy and paste points within the same automation item?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1364]
It's possible to duplicate complete automation items on the timeline, but it doesn't look as though it's possible to copy and paste points within the same automation item. I feel like it would be quite useful to be able to do this, especially for precise edits where you want to be able to replicate similar patterns across the one envelope.

**Comment by jcelerier** [comment]
Yep. One of the next improvement will be a generalized copy-cut-paste interface, so far it had been done in a very ad-hoc way . Same for midi, etc.

**Comment by jcelerier** [comment]
https://user-images.githubusercontent.com/2772730/155427723-7700d5fa-aaff-4ffb-ac54-9c578d695bd7.mp4

getting there...  not a trivial problem

**Comment by jcelerier** [comment]
fixed in a811e5b4c :)
