### ISSUE TITLE
folding a node at execution time close address listening

### ISSUE THREAD

**Issue by theod** [ossia/score#137]
I though this was resolved but it is still possible to close/open address listening during execution by folding/unfolding node into the device explorer : 

![capture d ecran 2016-02-03 a 11 09 38](https://cloud.githubusercontent.com/assets/118426/12779241/33902850-ca67-11e5-9b02-160763f080cd.png)

this is a critical bug as it breaks all trigger interactions.

**Comment by theod** [comment]
@jcelerier I have added a post in API to see if an address is closing/opening the listening.
by the way it seems there are some strange behaviors also into the API relative to listening activation but I would like to be sure the interface is not doing anything at execution time.

**Comment by jcelerier** [comment]
okay, this will require a bit of time to do this properly.

**Comment by jcelerier** [comment]
Pushed in dev  to fix this, but please test many cases because it changed a lot of things.

**Comment by theod** [comment]
ok thx. I'll made some test later before to close this issue

**Comment by theod** [comment]
this is ok now !
