### ISSUE TITLE
Can't select nodal process wire

### ISSUE THREAD

**Issue by RobinMontferme** [ossia/score#1372]
An error window pops up when trying to select  nodal process wire.

This can be reproduce by adding at least 2 of process with nodal input/output, connect them and then trying to select the wire.
![image](https://user-images.githubusercontent.com/22815889/157058142-608753fb-09ad-4b6e-b987-e69bc86eb1c4.png)
Tested on latest commit (fc66fa2)

OS: Manjaro Linux x86_64 
Host: Precision 7560 
Kernel: 5.15.25-1-MANJARO 
DE: Xfce 4.16 
WM: Xfwm4 
CPU: 11th Gen Intel i7-11850H (16) @ 4.800GHz 
GPU: NVIDIA RTX A3000 Mobile 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
Memory:  31302MiB

**Comment by jcelerier** [comment]
should be fixed by 6900a1d07096e82a832fc312a294e3032a29b733
