### ISSUE TITLE
Small bugs with serial protocol

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1373]
-  [x] "Bool", "Char" and "VecNf" aren't implemented yet for Serial 
- [x] Parent nodes sow up as "Impluse" types
- [x] "min", "max", "Acces", "Description" & "Units" don't show up in the Device Explore
- [x] There is no way to avoid sending the '\n' at the end of each messages. 
- [x] Inversly, there is no way to receive messages if they don't end with '\n'

_Originally posted by @thibaudk in https://github.com/ossia/score/issues/756#issuecomment-449881108_

**Comment by jcelerier** [comment]
@thibaudk can you recheck those with current git master?

**Comment by jcelerier** [comment]
all of this looks fixed

**Comment by thibaudk** [comment]
> @thibaudk can you recheck those with current git master?

Very sorry, I missed that message
