### ISSUE TITLE
Add support for virtual MIDI ports

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1378]
As discussed in the chat with @smoothdeveloper (https://gitter.im/OSSIA/score?at=623df17f9a09ab24f3bfd394) - when adding a new midi device, if we're on macos or linux we could easily request the creation of a virtual MIDI port.

**Comment by RobinMontferme** [comment]
fixed by pr #1382

**Comment by jcelerier** [comment]
:+1: thanks again !
