### ISSUE TITLE
i-score doesn't save the scenario

### ISSUE THREAD

**Issue by himito** [ossia/score#138]
In OSX, when one has a new file i-score does not save the scenario by pressing ⌘ + S :astonished: . It is necessary to do "Save As"  in order to save the new scenario.

**Comment by nvuaille** [comment]
For explanation, it's because we used to detect a new file by an unset name. But now, it has one : "untitled". So on new document cmd+s doesn't ask for a name/location and you have certainly a score stored somewhere in your temporary files =) 

So. We have to fix that. -_-
