### ISSUE TITLE
Can't change time signature in 3.0.6 appimage?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1383]
Trying to change the time signature from 4/4 to anything else doesn't seem to do anything.

Current Behaviour:

Hit delete to delete 4/4, replace it with 6/8, 8/8, or anything else. Reverts back to 4/4 and the console gets spammed with

"Warning: Unsupported composition mode (:0)" many times.

Expected behaviour:

Changing the time signature works. 

Bonus Thoughts:

Backspace doesn't seem to delete the signature until I first press delete.

**Comment by featherfurl** [comment]
This seems to be a regression from 3.0.5. Seems to work there fine.

**Comment by jcelerier** [comment]
fixed, thanks for the report!
