### ISSUE TITLE
Rescaling midi piano roll doesn't update until midi notes are dragged

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1384]
There also doesn't seem to be a functional difference between "rescale midi" and "rescale all midi". Both rescale all midi notes in the piano roll.

**Comment by jcelerier** [comment]
ah, those were added for a specific art project. I think that they should be redone (and maybe it would be a good motivation to introduce a small LISP dialect to process these midi notes...).

Regarding the "rescale midi" / "rescale all midi", "rescale all" actually rescales all the piano rolls in the whole score. but it was only necessary for one project at some point and should be removed I believe, as it can be pretty unexpected behaviour (although it's undoable without issues)..
