### ISSUE TITLE
No LV2 in appimage, but no JSFX in ossia-score-git aur package?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1388]
I'd love to be able to use both. I'm not super fussed about where I get my packages from. I remember reading somewhere that there was some reason why lv2 support was being left out of the appimage, but I feel like the absence of JSFX support from the aur package may be an oversight?

**Comment by jcelerier** [comment]
hmm for support the AUR package we'd need to package ysfx for archlinux too so that ossia-score packages can link against it... @jpcima if you want I can look into it ?

**Comment by jcelerier** [comment]
made an ysfx package: https://aur.archlinux.org/packages/ysfx-git ; will update ossia-score-git and ossia-score shortly

**Comment by jcelerier** [comment]
fixed in ossia-score-git, and will be fixed in the next ossia-score AUR package too
