### ISSUE TITLE
device filtering resets fold status of nodes

### ISSUE THREAD

**Issue by theod** [ossia/score#139]
this is not critical but just annoying.
each time I change the filtering result is folded and so I have to unfold everything to see the result.
I would expect to unfold each element of the result.

![capture d ecran 2016-02-03 a 17 10 35](https://cloud.githubusercontent.com/assets/118426/12788769/43a49b20-ca9b-11e5-827f-3f5276f8a6af.png)

**Comment by jcelerier** [comment]
From what I see in `DeviceExplorerFilterProxyModel` I am not sure that this is possible (apart from saving the list of all the open nodes somewhere, which is not really cool)

**Comment by theod** [comment]
ok no problemo
I postpone it for a next release so

**Comment by jcelerier** [comment]
done !
