### ISSUE TITLE
Type precise values into the inspector?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1391]
It doesn't look like there's any straightforward way to input exact values for plugin sliders in the inspector. I can type a precise tempo by clicking on the tempo value slider at the bottom of the screen, but this behaviour doesn't seem to be replicated for sliders in the inspector. If I change, say, the output gain of a plugin from 1 to something other than one it's effectively impossible for me to set it precisely back to 1. Presumably I could send precise values to the relevant address from elsewhere, but this feels like a hacky and not intended solution.

**Comment by jcelerier** [comment]
ah indeed. If the slider is visible in the main score view, you can right-click on it to show up a small textual editor for precise input, we should definitely add this to the inspector too (or maybe look at how other software do it, I'm sure there  are intelligent UI design choices that can be made here... @aklevy @RobinMontferme @thibaudk if any of you have an idea...)

**Comment by jcelerier** [comment]
@RobinMontferme this one should be relatively straightforward: the widgets are here: https://github.com/ossia/score/blob/master/src/lib/score/widgets/ControlWidgets.hpp  ; the idea is to catch the right-click and show a QSpinBox or something like this to allow manual user input as a little popup .

**Comment by jcelerier** [comment]
yay thanks !
