### ISSUE TITLE
Native file chooser widget

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#1401]
For processes where choosing files is useful. e.g. it could be a button that when clicked opens a file dialog or something like this

**Comment by RobinMontferme** [comment]
which process should we first focusing on?
- Audio
- Midi
- Video

Anything else?

**Comment by jcelerier** [comment]
actually I think that it should be a bit more general: the API would tell "I want a file chooser for .wav files" and it'd work. Processes would just specify this.

e.g. in Qt this is just setting a filter such as the string: "*.wav, *.aiff, <etc...>" on the file chooser dialog

**Comment by jcelerier** [comment]
:) thanks!
