### ISSUE TITLE
External MIDI file referencing?

### ISSUE THREAD

**Issue by featherfurl** [ossia/score#1403]
I'm in the middle of writing a text based notation system that generates midi files and it would be really useful to be able to reference a midi file externally to a score which updates automatically within ossia score every time I change it.

In reaper there's an option to reference external midi files directly like this, but I haven't seen anything like this in score.

I'd love to be able to use score as the glue for semi-live & non linear composition work and I'm slowly edging towards this being possible.

If there's no mechanism for doing this already, I'd love to see this feature at some point in the future.

**Comment by jcelerier** [comment]
Hmmm, right now it copies the MIDI data indeed. But I think that this feature would also be interesting for @smoothdeveloper who is in the process of revamping the MIDI support, maybe that can fit in. At worst it's not very hard to implement : we have to save the media file name as part of the midi process, and add a QFilesystemWatcher to detect whenever the file changes on disk to reload it in score.

**Comment by jcelerier** [comment]
done in dev with the "Midi/Midi File Reader" process :)
