### ISSUE TITLE
Bug: Color automation/control surface does not respect rgba8 domain

### ISSUE THREAD

**Issue by capital-G** [ossia/score#1410]
If you want to perform a color automation via libossia and score you run into problems as the color domain does not get obeyed by ossia score color automations or surface control.

Say you have created a color target (rgba8) via libossia/oscquerry, adjusting it via a surface control will output the domain [0,1] instead of [0, 255], therefore the color is black all the time.
Increasing the range to [0,255] via a value mapper works but reveals that the order is not rgba but maybe argb? At least the colors are off.

Here is a screenshot of a control surface and on the left the value that got assigned by it
![grafik](https://user-images.githubusercontent.com/8267062/173187505-50222da0-76cb-4a2f-b182-0a5466947e67.png)

I would expect that color transformation happens automatically or can be adjusted manually.

**Comment by capital-G** [comment]
Current workaround for me is

* Adding a mapping curve behind the automation to transform it to the domain [0,255]
* Changing the line https://github.com/bltzr/ofxOscQuery/blob/1727b4b12c5bc0f1a8c8365fd6abe2ebbfcbc9d9/src/ofxOssiaTypes.h#L241 from
   ```cpp
   static ofx_type convertFromOssia(const opp::value& v)
    {
      return ofx_type(v.to_vec4f()[0], v.to_vec4f()[1], v.to_vec4f()[2], v.to_vec4f()[3]);
    }
   ```
   to
   ```cpp
   static ofx_type convertFromOssia(const opp::value& v)
    {
      return ofx_type(v.to_vec4f()[1], v.to_vec4f()[2], v.to_vec4f()[3], v.to_vec4f()[0]);
    }
   ```

**Comment by jcelerier** [comment]
Hmmm, I'm seeing the bug in the control surface, but for the automation it seems to output correctly to [0-255], can you confirm ? 

![Rgba](https://user-images.githubusercontent.com/2772730/173326583-d10d900b-016f-430a-8f6a-9334671b10eb.png)

**Comment by jcelerier** [comment]
fixed for control surface

**Comment by capital-G** [comment]
Oh, I figured out what my problem was when using the color automation, I drag&dropped the color onto the color automation, but what you actually want to do is to drop it on the green button - this fixed it for me what I did manually with the mapping curve and the order of the values.

**Comment by jcelerier** [comment]
ah I see ! i'll make it so that it works that way too, dropping on the gradient seems natural and there's no particular reason for it to behave differently..
