### ISSUE TITLE
2 LFO Noise output the same signal

### ISSUE THREAD

**Issue by capital-G** [ossia/score#1412]
When I took a look at #1411 I also found that two LFOs in noise mode with identical dialed parameters put out the identical wave - I think this is not what you want from multiple noise sources?

<img width="525" alt="grafik" src="https://user-images.githubusercontent.com/8267062/173197334-71871d68-5ca1-48f3-8f3b-9f1f4300f8b2.png">

**Comment by jcelerier** [comment]
hmm indeed - right now it uses the same seed everywhere to ensure reproducibility, I'll make the seed ~~per-instance~~ fully random
