### ISSUE TITLE
adding key points to color automations should be undoable 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1418]
Currenly they don't seem to be

**Comment by jcelerier** [comment]
it works here (right click on the key point), doesn't on mac ?

**Comment by jcelerier** [comment]
it's even in the docs :cat:

**Comment by bltzr** [comment]
I mean, adding or removing key points doesn't seem to be included in the Action History, and hence is not affected by doing Undo/Redo (in the Edit menu)

**Comment by jcelerier** [comment]
uh... can you make a video ? it works as expected here, both on linux and mac - every modification to the gradient goes through the undo history

**Comment by bltzr** [comment]
yep, it works on the latest version. I had the problem on a previous (the last one before it broke on MacOS 10.13/14)
well anyway, nevermind, it works!

**Comment by bltzr** [comment]
maybe I just got confused, though, who cares (and sorry for the noise if I did)
