### ISSUE TITLE
don't allow min bound and max bound to reach the end event position

### ISSUE THREAD

**Issue by theod** [ossia/score#143]
as discussed on the dev list it would increase readability and would avoid some ambiguity when https://github.com/OSSIA/API/issues/22 will be available.

the idea is to avoid this :  

![capture d ecran 2016-02-05 a 10 51 00](https://cloud.githubusercontent.com/assets/118426/12842934/6c5583c0-cbf6-11e5-9a96-500b389320ec.png)

by limiting bounds to this : 

![capture d ecran 2016-02-05 a 10 51 05](https://cloud.githubusercontent.com/assets/118426/12842948/7bb40d46-cbf6-11e5-8b1f-85f65a78b15a.png)

**Comment by bltzr** [comment]
I have mixed feelings about this, because that would mean that the time would be corresponding to the (non-traced) vertical diameter of the semi-circle
hence, if we set the min to 0 (or just above), that would mean that it would be displayed somehow *before* the start state of the constraint - I'm not sure that's any better

**Comment by jcelerier** [comment]
I remember long, long, debates about this and this has already been shifted *twice* in i-score. Both cases have problems. for instance if the min goes before zero, then it would not easily be selectable here : 

![min](https://cloud.githubusercontent.com/assets/2772730/26174974/62773cd8-3b51-11e7-8484-35ed922e6977.png)

**Comment by bltzr** [comment]
Yes that was me or less my point... I think it's OK as is

**Comment by bltzr** [comment]
Can anybody say this to 1.5? That's not possible on github mobile version

**Comment by bltzr** [comment]
*set not say

**Comment by jcelerier** [comment]
> I think it's OK as is

I agree, I haven't heard any complaint so far from users
