### ISSUE TITLE
use correct names of presets in dmx fixtures

### ISSUE THREAD

**Issue by yiids** [ossia/score#1441]
for example a moving head, will have a color wheel channel. Currently different colors just have the name WheelSlot Wheelslot.1 etc. In the fixture json file there is the names of the presets, would make sense to display them in the artnet device

**Comment by jcelerier** [comment]
@RobinMontferme would you feel like looking at this ? everything should be around ArtnertDevice.cpp

**Comment by RobinMontferme** [comment]
@yiids  I am currently looking into the issue you've open on dmx fixtures for presets names usage. 
Could you provide either an example or/and provide a fixture json file to help us ?

**Comment by yiids** [comment]
this fixture for example: https://open-fixture-library.org/shehds/led-spot-60w
has a color wheel. this is how it is shown when added as a artnet fixture:
https://imgur.com/4pVfrA3.png
Instead, there should be the names of the colors
