### ISSUE TITLE
tween automations should work on ports

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1445]
in the screenshot's example, the automation will start with the curve's first value (even though tween is enabled)
![Image 14-12-2022 à 10 59](https://user-images.githubusercontent.com/113982/207565424-2039abd8-fa71-4f5d-9af4-b9d0d1e3c4c1.jpg)

**Comment by jcelerier** [comment]
so the feature has been started a long time ago and is actually somewhat implemented at the engine level but I have bugs that I never managed to finish fixing...

**Comment by thibaudk** [comment]
initially opened here : https://github.com/ossia/score/issues/969
Should I close the old one ?

**Comment by jcelerier** [comment]
nope let's keep the old one
