### ISSUE TITLE
[UI] Clearer visual hints when patching cables

### ISSUE THREAD

**Issue by yiids** [ossia/score#1458]
In big scores sometimes  is a bit difficult to connect cables to the right ports. Some visual hints could be helpfull. For example ports that already have something connected to them could be filled in or have a different color. 
When dragging a cable over a port maybe some hint window could appear showing you the name and the number of the input port. 
I have this issue a lot with for example the video mixer,  when dragging a cable from the other side of the score, sometimes its difficult to see to which port you are connecting.

**Comment by jcelerier** [comment]
so, I tried some things in the last commits: 

- now drop "mangetism" will ignore ports of the wrong type which reduces a lot of errors (e.g. audio & midi cables)
- it will also ignore most "impossible" drag/drop of cables

likely there is more to do to improve this... maybe some magnet widget that zooms on what you are dropping on if it's small?

**Comment by yiids** [comment]
there seems to be some regression here, previously (tested in 3.0.5) the ports of a node would get slightly bigger when you would be hovering over them to connect something, now (3.1.11) they stay the same size

**Comment by jcelerier** [comment]
thanks for noticing, I had added some security but broke this case!

fixed in 5444a0431bb8997174f1eb5ffdd6a2d77cd15e4e
