### ISSUE TITLE
automation update rate is too high !!

### ISSUE THREAD

**Issue by bltzr** [ossia/score#146]
The current update rate for automations seems to be 1ms.
This creates a lot of traffic on the network... and a lot of processing on the client size (particularly when having many simultaneous automations running)
Mileages may vary on this... but I'd suggest having 10ms as default. 
This is equivalent to 100fps, which is more than enough for video... and anyway, no update rate can be enough for audio, so ramping on the client side (with a 10ms ramp) could be a way to handle this...

15 ms could  also work.. that's roughly 60 fps...

Opinions ?

**Comment by bltzr** [comment]
@theod said he could change this in the API, but that might break tests... @jcelerier @nvuaille ?

**Comment by jcelerier** [comment]
@theod told ya :p

**Comment by bltzr** [comment]
wot ya mean @jcelerier ?

**Comment by jcelerier** [comment]
https://github.com/OSSIA/i-score/commit/c9335db6b6f674a800e38da212e2197321b1ba17

**Comment by bltzr** [comment]
I don't understand... but Théo does... 
BTW, he has reduced the rate to 10 ms ... could you please make a release @jcelerier so I can try it ?
thx

**Comment by bltzr** [comment]
I guess this is fixed in the setting panel now, so closing the issue
