### ISSUE TITLE
[MIDI] Assigned knobs dont output their value untill you collapse the midi device in the device explorer

### ISSUE THREAD

**Issue by yiids** [ossia/score#1465]
There is a midi device with a bunch on knobs assigned to parameters in a score. Sometimes the knobs will not send their value to the parameter untill you go to the device explorer, collapse the midi device, and actually look at the value changing.
some pics to clarify:
I open the score and it looks like this, and cc values are not being sent to the parameters: 
![image](https://user-images.githubusercontent.com/62114515/227380975-3e43a7ef-3a0d-4bf6-b11d-7fd009e3d919.png)

then I check the midi controller and now the values do get sent:
![image](https://user-images.githubusercontent.com/62114515/227381100-143b5f52-dd59-4d9c-a90b-a328cc91d4b0.png)

**Comment by yiids** [comment]
i just accidentally pressed close

**Comment by jcelerier** [comment]
arf, I'm aware of this bug for quite some time but every time I try to reproduce it I don't manage... can you share your score ?

**Comment by jcelerier** [comment]
ahh i think i got a repro

**Comment by jcelerier** [comment]
fixed in 4a5008c5eba1e389d632b4e10ee1b921a3dc71e8 :)
