### ISSUE TITLE
Internal error: libsuil-0.so.0: not found for AppImage (v3.1.10)

### ISSUE THREAD

**Issue by edumeneses** [ossia/score#1471]
I found the following error when trying to run Ossia Score's latest AppImage ([
ossia.score-3.1.10-linux-amd64.AppImage](https://github.com/ossia/score/releases/download/v3.1.10/ossia.score-3.1.10-linux-amd64.AppImage)) on Pop!_OS 22.04 (≃Ubuntu 22.04).

`Internal error: libsuil-0.so.0: not found.`

[v3.1.9](https://github.com/ossia/score/releases/tag/v3.1.9) also presents the same behaviour.

**Comment by jcelerier** [comment]
Should be fixed by 3328682!

**Comment by jcelerier** [comment]
can confirm that current bleeding edge builds run fine on ubuntu 22.04 (https://github.com/ossia/score/releases/tag/continuous)

**Comment by edumeneses** [comment]
Thanks!
