### ISSUE TITLE
Add ossia-score to homebrew-casks (macOS applications distributed as binaries)

### ISSUE THREAD

**Issue by luzpaz** [ossia/score#1477]
Homebrew cask (https://github.com/Homebrew/homebrew-cask)

> Homebrew Cask extends [Homebrew](https://brew.sh/) and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Visual Studio Code and Google Chrome.

> We do this by providing a friendly CLI workflow for the administration of macOS applications distributed as binaries.

How to: https://docs.brew.sh/Adding-Software-to-Homebrew
Link to latest stable that can be used: 
https://github.com/ossia/score/releases/download/v3.1.11/ossia.score-3.1.11-macOS.dmg

Note: I'm not on macOS so I can't add a formula for it. They want submissions to be tested first before merge. So this task is for someone who has homebrew-casks installed and can engineer the formula (should be pretty straight-forward)

Related to #1476

**Comment by jcelerier** [comment]
I've made a formula for homebrew once, I guess it wouldn't be too hard for casks: https://github.com/jcelerier/homebrew-packages/blob/master/Formula/cninja.rb

**Comment by jcelerier** [comment]
https://github.com/Homebrew/homebrew-cask/pull/149989

**Comment by luzpaz** [comment]
Downstream merged!
Closing!

**Comment by luzpaz** [comment]
downstream cask package manager renamed the cask from ossia-score to score (https://github.com/Homebrew/homebrew-cask/pull/149989#issuecomment-1610598368)
