### ISSUE TITLE
min and max bounds are still displayed after removing a trigger

### ISSUE THREAD

**Issue by theod** [ossia/score#148]
here is the initial situation : 

![capture d ecran 2016-02-09 a 15 41 21](https://cloud.githubusercontent.com/assets/118426/12919366/03a10290-cf44-11e5-8662-52e5ba4bd069.png)

autre removing the first trigger I have this : 

![capture d ecran 2016-02-09 a 15 42 23](https://cloud.githubusercontent.com/assets/118426/12919378/13b0d638-cf44-11e5-8ea4-4dd2d9bc6a34.png)

and if I try to remove the bounds my self it is not possible because the toggles are not available in the inspector : 

![capture d ecran 2016-02-09 a 15 42 33](https://cloud.githubusercontent.com/assets/118426/12919415/3c227afe-cf44-11e5-86ac-c928d01a93b6.png)

**Comment by theod** [comment]
notice that if I move the node the max bound disappears : 

![capture d ecran 2016-02-09 a 15 47 31](https://cloud.githubusercontent.com/assets/118426/12919475/83f67790-cf44-11e5-9d1c-04d794510e9c.png)

**Comment by theod** [comment]
and at execution everything works like if there was still a trigger (the listening is opened when min bound is reached) : 

![capture d ecran 2016-02-09 a 16 08 21](https://cloud.githubusercontent.com/assets/118426/12920084/7ab5262e-cf47-11e5-9115-581204f3f8cb.png)

**Comment by nvuaille** [comment]
The min was not correctly set to the default duration ... Fixed !

**Comment by theod** [comment]
yes ! it is fixed ! thank you
