### ISSUE TITLE
can't move the first point of a curve

### ISSUE THREAD

**Issue by theod** [ossia/score#149]
as shown in the picture I can move the last point but not the first point : 

![capture d ecran 2016-02-09 a 21 53 47](https://cloud.githubusercontent.com/assets/118426/12930308/d4cce608-cf77-11e5-909f-ea37281401bb.png)

**Comment by theod** [comment]
as he plans to use mapper, I add @bltzr to warn him about this issue.

**Comment by theod** [comment]
@nvuaille are you aware of Mapper implementation or should we assign to @jcelerier ?

**Comment by theod** [comment]
but I've managed to drag the point in fullscreen mode however if I move the point to far on top the point I can't move it afterward.

![capture d ecran 2016-02-09 a 21 59 10](https://cloud.githubusercontent.com/assets/118426/12930467/c224e5e0-cf78-11e5-9397-ed168c6635f2.png)

**Comment by jcelerier** [comment]
mh, the GUI part is exactly the same as for automation so it's weird if it works for automation and not for this :(

**Comment by theod** [comment]
yes it is the same for Automation

**Comment by nvuaille** [comment]
It seems to work fine for me ...
Not really fine indeed but it moves. I think the grip zone is to small. 

PS : just notice that a timenode seems to hide the point

**Comment by theod** [comment]
yes I guess it is just a matter of making the grip zone larger.

**Comment by theod** [comment]
yes it is better now !
I will open another issue concerning the fact that if I move the point to far on top, the point I can't move it afterward.
