### ISSUE TITLE
score v3.1.12 tries to run on macOS Catalina, but can't, possibly because of Qt 6.6

### ISSUE THREAD

**Issue by Rhys-T** [ossia/score#1491]
I was working on reporting a Syphon-related issue in score v3.1.11, saw that 3.1.12 was available, and figured I'd test it first in case it had already been fixed. Unfortunately, the new version doesn't seem to run at all on my (macOS 10.15 Catalina) system. It thinks it can - the OS doesn't show the app as being too new or anything - but it immediately exits with a segmentation fault (specifically, a null pointer), displaying both the usual crash report dialog and a smaller dialog that just says "**The application “ossia score” can’t be opened.**"

It looks like Qt 6.6 doesn't support Catalina, but the app doesn't know that, tries to run, and crashes in the initializers/constructors before it even reaches `main`. The weird thing, though, is that Qt 6.**5** - which score 3.1.11 seems to use - supposedly doesn't support Catalina either (6.5 is the version that dropped it), yet that version of score _does_ (mostly) run on my system somehow.[^qtdev]

[^qtdev]: The other weird thing is that [this page](https://www.qt.io/product/qt6/technical-specifications) _does_ list 10.15 as supported - as a _development_ system, at least. It doesn't list specific versions of macOS at all under _target_ systems, though.

Does the score app just need to have its minimum macOS version increased to match reality, or is there something else going on here?

Also, should I still submit the Syphon problem I was originally having? I'm kind of stuck with Catalina at the moment for Reasons™, and I don't know when/if I'll be able to test 3.1.12 or later. (And it's possible that even the old version of score only had that problem on Catalina anyway.)

---

Just in case this _isn't_ supposed to be failing, here's what seem to be the most relevant parts of the crash log. I can give the complete log file if you need it, but I'll need time to make sure I've cleaned out any personal info.

<details>
<summary>Crash log excerpts</summary>

```
Process:               ossia score [17114]
Path:                  /Applications/ossia score.app/Contents/MacOS/ossia score
Identifier:            io.ossia.score
Version:               3.1.12 (3.1.12)
Code Type:             X86-64 (Native)

OS Version:            Mac OS X 10.15.7 (19H2026)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [17114]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	000000000000000000 0 + 0
1   io.ossia.score                	0x000000010b8953a0 qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*) + 208
2   io.ossia.score                	0x00000001038f7123 _GLOBAL__sub_I_qrc_qcocoaresources.cpp + 35
3   dyld                          	0x0000000122572353 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 535
4   dyld                          	0x000000012257275e ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
5   dyld                          	0x000000012256d17b ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 493
6   dyld                          	0x000000012256b234 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
7   dyld                          	0x000000012256b2d4 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
8   dyld                          	0x00000001225596a8 dyld::initializeMainExecutable() + 199
9   dyld                          	0x000000012255ebf7 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6728
10  dyld                          	0x0000000122558227 dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
11  dyld                          	0x0000000122558025 _dyld_start + 37
```

</details>

**Comment by jcelerier** [comment]
hello! I believe this is more an issue on our side than on Qt.. I'd be surprised if anything broke in the following stack trace between 6.5 and 6.6, Qt's resource system is very OS-independent..

and all the code is built with -mmacos-version-min=10.15 including Qt

> Also, should I still submit the Syphon problem I was originally having?

yes definitely! thanks for your very precise bug report, it's very helpful!
The syphon code hasn't been touched in a while and i know new versions of syphon have been pushed for metal support, so maybe i'll try to look into updating it as a first step

**Comment by jcelerier** [comment]
so, this should be fixed too with https://github.com/ossia/score/releases/v3.1.13 ?

**Comment by Rhys-T** [comment]
3.1.13 seems to run fine on Catalina. Thanks!

**Comment by jcelerier** [comment]
\o/
