### ISSUE TITLE
Score 3.1.12 doesn't open in Windows 10

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#1493]
After uninstalling Score 3.1.11 and installing 3.1.12, Score doesn't open. Tested on two Windows 10 machines.

**Comment by evanmtp** [comment]
(possibly related to https://github.com/ossia/score/issues/1491 ?)

**Comment by jcelerier** [comment]
yep, I saw it.. for some reason it works when I build on my machine but not when on the CI. I'm rebuilding it right now, sending you a build ASAP (along with libossia max, java, pd builds.. sorry this took me so long to get to it but i'm on it this morning)

**Comment by jcelerier** [comment]
I replaced the binary, can you try this one ? https://github.com/ossia/score/releases/tag/v3.1.12

**Comment by evanmtp** [comment]
Just tested the new binary and it's working. Thanks, @jcelerier !
