### ISSUE TITLE
Missing library on Raspbian; libicui18n.so.67

### ISSUE THREAD

**Issue by glenpike** [ossia/score#1498]
Using out of the box, latest Raspbian clean install, downloaded with the Raspberry Pi imager and downloaded the 64bit version of Ossia Score, but I get the error:

'Shared object "libicui18n.so.67" not found'.

I do have "libicui18n.so.72" on my system, so I guess the build is coded for a specific version of libicui18n rather than the generic one?

Thanks

**Comment by jcelerier** [comment]
sadly the ICU libs aren't compatible between them, an app that links against libicu 67 *needs* ICU 67 at runtime and won't even run with ICU 72 - looks like we have to ship it manually. Thanks for the heads-up !

**Comment by jcelerier** [comment]
Are you on raspbian bullseye or bookworm btw? bookworm i guess?

**Comment by glenpike** [comment]
> Are you on raspbian bullseye or bookworm btw? bookworm i guess?

Yes, sorry, I am on Bookworm.  I might see if there's an older version of Bullseye - I couldn't see at first glance yesterday, but will try again.

**Comment by jcelerier** [comment]
don't worry - stay on bookworm, it shuold work. I have a new release in progress, I'll add the libicu required file

**Comment by jcelerier** [comment]
on it...

**Comment by jcelerier** [comment]
https://github.com/ossia/score/actions/runs/7332752964/artifacts/1135590574 can you try this one?

**Comment by glenpike** [comment]
> https://github.com/ossia/score/actions/runs/7332752964/artifacts/1135590574 can you try this one?
Sorry for the delay.
That build runs / starts ok on a fresh and updated Bookworm.
The synths.effects example runs, but glitchy.
The video effects example runs, but jerky.
The 3d examples crash with a segfault.
I tried those on a Bullseye installation and they all ran ok and seemed smoother.  I am testing Bookworm on a TV with HDMI audio and video, Bullseye was on a monitor, together with a USB soundcard, so their could be differences there?
Bullseye seems more stable 🤷

**Comment by jcelerier** [comment]
should be fixed in 3.1.13 : https://github.com/ossia/score/releases/tag/v3.1.13

for the bullseye / bookworm difference: bookworm by default runs under Wayland. On the Pi 4 i found this actually works much less well and reverted mine to X11. But at some point ossia should get a native wayland backend to fix things... it's still some more packaging work.

The 3D example crash was a bug in a shader and should have been fixed.

**Comment by jcelerier** [comment]
fixed for some time
