### ISSUE TITLE
a point at the top left corner can't be moved

### ISSUE THREAD

**Issue by theod** [ossia/score#150]
if I move the point to far on the top left cornet, the point I can't move it afterward.
of course I can avoid to put the first point here but this means I can start an automation from the max bound value.

**Comment by nvuaille** [comment]
I can't reproduce this issue ...
Do you have a screenshot/ a scenario ?

**Comment by theod** [comment]
here is a screenshot where each point are in the corners.
![capture d ecran 2016-02-10 a 16 39 00](https://cloud.githubusercontent.com/assets/118426/12951941/003e022a-d015-11e5-9717-09964ecf9c54.png)

I can move the bottom right point but not the top left one.

**Comment by nvuaille** [comment]
mhh
I think it's because of the startTimeNode, which seems to be over your point.
If you move down your constraint I guess you will be able to move the point. So, I'm going to put that timenode back.
