### ISSUE TITLE
Build error on Fedora 38

### ISSUE THREAD

**Issue by ycollet** [ossia/score#1512]
I am trying to build score on Fedora 38 and I met a build error:
```
/builddir/build/BUILD/ossia-score-3.1.14/src/plugins/score-plugin-protocols/Protocols/DNSSDDeviceEnumerator.cpp: In member function 'void Protocols::DNSSDEnumerator::start()':
/builddir/build/BUILD/ossia-score-3.1.14/src/plugins/score-plugin-protocols/Protocols/DNSSDDeviceEnumerator.cpp:29:11: error: incomplete type 'QTimer' used in nested name specifier
   29 |   QTimer::singleShot(1, this, [this] {
      |           ^~~~~~~~~~
```

**Comment by jcelerier** [comment]
oops, likely just missing `<QTimer>`. I wonder why it builds in CI...

**Comment by jcelerier** [comment]
(btw if you aren't doing so I really recommend to set -DCMAKE_UNITY_BUILD=1 for package builds, it will make the build much faster with no drawbacks)

**Comment by ycollet** [comment]
Yes, probably :)

**Comment by ycollet** [comment]
I will check for UNITY_BUILD flag. Thanks for the hint.

**Comment by jcelerier** [comment]
pushed the missing header in any case

**Comment by ycollet** [comment]
Build went fine with -DCMAKE_UNITY_BUILD=1
I close the ticket :)
Thanks a lot !

**Comment by jcelerier** [comment]
fyi : I'm test-driving Fedora as a main OS (through Asahi Linux) so there may be less breakage in the future :)

**Comment by ycollet** [comment]
Perfect ! :) Thanks a lot for. your software !
