### ISSUE TITLE
Gaphical issue for Script device with lots of inlets

### ISSUE THREAD

**Issue by guillaumeriousat** [ossia/score#1520]
When a Script device has more than 4 inlets, the box is not automatically resized by Ossia and the additionnal inlets are not visible until the user clicks on the arrow.

Workaround : click on the little arrow on the left of the device and the device will update.

![image](https://github.com/ossia/score/assets/117857232/02b48137-7ffa-4c39-863a-3967cff3bceb)

**Comment by jcelerier** [comment]
done in 3.3
