### ISSUE TITLE
crash when removing a process

### ISSUE THREAD

**Issue by theod** [ossia/score#155]
when I remove a process from a constraint : 

![capture d ecran 2016-02-15 a 18 56 17](https://cloud.githubusercontent.com/assets/118426/13056510/13746276-d416-11e5-9b1f-af500efbf467.png)

I have the following crash : 

[crashlog.txt](https://github.com/OSSIA/i-score/files/131210/crashlog.txt)

**Comment by theod** [comment]
by the way is there another way to remove a process from a constraint ?
shouldn't we be able to remove it using backspace shortcut @bltzr ?

**Comment by jcelerier** [comment]
> by the way is there another way to remove a process from a constraint ?

When would that happen ? What would you put the focus on ? 
For instance imagine that you click on the background of the scenario, press backspace : everything gets removed because the scenario is a process. Seems fishy to me.
Of course something can be added in the context menu.

**Comment by theod** [comment]
I mean if I select a slot with some process inside I would like to remove them.
of course we should avoid this for the root scenario
