### ISSUE TITLE
Apple Silicon support dropped for 3.2.3

### ISSUE THREAD

**Issue by krehel** [ossia/score#1550]
Hi! 👋  Homebrew maintainer here.

Noticed when updating the Homebrew Cask for Score that the latest versions over the last couple days no longer have ARM builds available.  Noting this for your awareness, and to inquire if those builds (or a universal binary) will be made available?

Thanks! 😀

**Comment by jcelerier** [comment]
hello ! yes, I need to automate copying from github actions : https://github.com/ossia/score/actions/workflows/mac-builds.yaml into the release (right now I do this manually as some releases come from Azure Pipelines and others from GH actions and they overwrite each other).

**Comment by jcelerier** [comment]
sorry, there's a flurry of releases right now as I'm trying to get flatpak support and this requires a new release every time I do a small change

**Comment by krehel** [comment]
Please no apologies @jcelerier - just a notification from one project maintainer to another. 😄

When we notice build regression like this, we try to let upstream know in case there are issues in the build pipeline that the project isn't aware of, but it sounds like you are very aware. 

Best of luck in working through your releases! ❤️

**Comment by jcelerier** [comment]
Should be good again in 3.2.4

**Comment by jcelerier** [comment]
I see you updated, thanks !
