### ISSUE TITLE
[UI] 3.2.4 Left panel's resizing issue 

### ISSUE THREAD

**Issue by HugoGenillier** [ossia/score#1552]
The left pannel behaves differently since the latest version. It cannot be minimized to the left as before.

Current version 3.2.4 (Linux) :
![Last version](https://github.com/ossia/score/assets/118723648/7fa9a66b-3a4c-4c66-9d2d-82ed84ee1778)

Older version 3.2.0 (Linux) :
![2024-07-1111-40-54-ezgif com-video-to-gif-converter](https://github.com/ossia/score/assets/118723648/fce765b8-86ae-4689-acd5-57735787fe7b)

The default size, has also changed and appears to be almost twice as big as before. Leading the user to have a smaller workspace for creating scores. Also knowing that the resizing of this panel is less permitive this creates a new issue cluttering the UI. 

Default size now :
![image](https://github.com/ossia/score/assets/118723648/084ba4da-64e0-4187-af46-3860a5860ff3)
Default size before :
![image](https://github.com/ossia/score/assets/118723648/9cf835c2-0222-497f-a8ea-bf80c0802de2)

Solution : 
Fix this new bug to bring back the old left panel's management.

**Comment by jcelerier** [comment]
Fixed in 3.3
