### ISSUE TITLE
bleeding edge version crashes on macOS 14.2

### ISSUE THREAD

**Issue by samamou** [ossia/score#1573]
crash report: [score-crash.txt](https://github.com/user-attachments/files/17421937/score-crash.txt)

**Comment by jcelerier** [comment]
Issue A:   x86-64 build crashes in rosetta. We should have a warning message that prevents this to ever happening: for instance by launching a script that shows a pop-up and tells the user the app isn't compatible with rosetta. Or maybe check if there's a way to indicate to apple to not even try to run the app through rosetta.

Issue B: in continuous build ci script, it looks like the name of the released binary isn't ok. The binary generated by GH Actions is correct, it's just the "continuous" deploy step which isn't doing the right thing.

**Comment by jcelerier** [comment]
fixed a week ago

**Comment by jcelerier** [comment]
+ added thing to plist to prevent macOS to try running the macintel version on applesilicon macs: https://github.com/ossia/score/commit/a085530f96f4260927751b48c827e6c78e18f631
