### ISSUE TITLE
crash when removing the whole content of boids_choregraphy project

### ISSUE THREAD

**Issue by theod** [ossia/score#158]
here are the steps to reproduce the crash : 
- open /i-score/Documentation/Examples/Processing/boids_choregraphy/boids_choregraphy.scorejson
- select all the content of the scenario with cmd+a
- press backspace to delete everything

**Comment by nvuaille** [comment]
Can't reproduce here ...

**Comment by nvuaille** [comment]
That's may be fixed !

**Comment by jcelerier** [comment]
can't reproduce either, even undoing it works ^__^
