### ISSUE TITLE
Exposing OSC device to OSCQuery makes score crash

### ISSUE THREAD

**Issue by samamou** [ossia/score#1581]
### Steps to reproduce
1. Add an OSC Device
2. set OSCQuery port
2. re-open the device window to **edit** device 
3. click on **ok** makes score crash

[score_crash.log](https://github.com/user-attachments/files/17721416/score_crash.log)

**Comment by jcelerier** [comment]
not reproducible on linux so far..

**Comment by jcelerier** [comment]
fixed in 3.3.1
