### ISSUE TITLE
score crashed on quitting the app 

### ISSUE THREAD

**Issue by samamou** [ossia/score#1582]
Not entirely sure what let to this, but score crashed onExit

[score_crash.txt](https://github.com/user-attachments/files/17725450/score-crash.txt)

**Comment by samamou** [comment]
Another crash report onQuit
[score-crash.txt](https://github.com/user-attachments/files/17757216/score-crash.txt)

**Comment by jcelerier** [comment]
yep, I started investigating it at home on my mac earlier today... haven't had much success so far though

**Comment by jcelerier** [comment]
fixed in master! :)
