### ISSUE TITLE
Learn OSC mode

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#159]
@theod this may require something specific in the API ?

**Comment by theod** [comment]
I would say only a "learn" attribute into OSC protocol but this will not be only thing to do as we need to enable the listening into Jamoma.

as I will not be available today you can look at **bool Engine::setDeviceLearn(std::string deviceName, bool newLearn)** into https://github.com/i-score/i-score/blob/master/src/data/Engine.cpp

**Comment by jcelerier** [comment]
okay thanks !

**Comment by jcelerier** [comment]
fixed by 3be73583530eeb8240b42de53a1b0f8699542135
