### ISSUE TITLE
v3.3.1 macOS Intel build failure

### ISSUE THREAD

**Issue by daeho-ro** [ossia/score#1592]
I can see the `.dmg` build for Intel version is failed,
- https://github.com/ossia/score/actions/runs/11866841823

can it be retried? 
Thanks,

**Comment by jcelerier** [comment]
I'll tag 3.3.2 in a couple hours. Sadly GH action & azure macOS builds are very flaky, roughly 50% of the builds fail - https://github.com/actions/runner-images/issues/7522

**Comment by jcelerier** [comment]
done and 3.3.2 is there ! :)
