### ISSUE TITLE
CSV recorder offsets columns  by one to the left

### ISSUE THREAD

**Issue by bltzr** [ossia/score#1595]
in the attached example, the CSV recorder sends to /oh1/DD13252B/bpm (label of first column) the value of /oh1/DD159B28/bpm (label of second column) when playing the attached CSV

[CSVbug.zip](https://github.com/user-attachments/files/17851619/CSVbug.zip)

**Comment by jcelerier** [comment]
fixed in b7060ec0d5a03353331138bc498e495832a193ca
