### ISSUE TITLE
changing main constraint's speed is impossible

### ISSUE THREAD

**Issue by bltzr** [ossia/score#160]
while it is possible for any other constraint in the scenario
@jcelerier might add precisions...

**Comment by nvuaille** [comment]
Actually the constraint speed is not transmit to its children : in any subscenario the speed of the parent constraint has no effect on the constraints inside the subscenario.

**Comment by bltzr** [comment]
if the propagation to children constraints fixed as well (as reported @nvuaille ?) or should I create an issue for that ?
