### ISSUE TITLE
record automations for a node's children 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#161]
currently, one has to select individual nodes in order to record automations for them... it would be nice that this also works for its children (and actually grand-children and so on) when selecting a node - just like it does when doing a state snapshot

**Comment by jcelerier** [comment]
this has been implemented.

**Comment by bltzr** [comment]
but is apparently causing crashes.... can we keep open until we figure out the problem ?

**Comment by jcelerier** [comment]
I'm trying as hard as I can but I can't make anything crash when recording the whole nebula device :
![audio 1](https://cloud.githubusercontent.com/assets/2772730/15746647/bc607bf2-28d7-11e6-98c5-467a1cab1eb0.gif)

**Comment by bltzr** [comment]
do you actually have the Nebula patcher at hand ?
maybe that’s why ????

I’m changing values on the remote side...

**Comment by bltzr** [comment]
though, it requires a certain number of dependencies... but that's doable...

**Comment by jcelerier** [comment]
no, I change them from the device explorer window. If you can make me a zip I'll try

**Comment by bltzr** [comment]
when doing this by hand (like you do) I don't get any crash either
and I tried again with changing parameters remotely, and it didn't crash either, though I pulled and rebuild since the last time... so maybe this was fixed by some pixies in the meantime (are you one of them, @jcelerier ? ;-)  )
@avilleret could you please try as well ? you're usually better than me for finding nasty bugs :-p

**Comment by bltzr** [comment]
though I still get the funny looping phenomenon (restarting the scenario when hitting the initial event of the recorded automation)
but I guess that's a horse of a different color :-)

**Comment by bltzr** [comment]
so if @avilleret confirms that this works, I guess we could close the issue...

**Comment by bltzr** [comment]
I couldn't find an issue for the restarting bug, did you create one, @jcelerier ? I thought I saw it on the API repo, but couldn't find it... 
here's what I get in the terminal when that happens: https://gist.github.com/bltzr/4f17283f4593ad8c4d3dc7fea87449f7

**Comment by bltzr** [comment]
though I get a crash when recording from a parent node, but not the root node (vent.H for instance)

**Comment by jcelerier** [comment]
yep, there was a crash in there. Fixed in master.

**Comment by jcelerier** [comment]
> though I still get the funny looping phenomenon

I tried and tried but I don't have it :(

**Comment by bltzr** [comment]
here's what I do to record:
![recall](https://cloud.githubusercontent.com/assets/113982/15772065/46428dfa-296f-11e6-9564-896336f225fe.gif)
Then I just connect the "box" to the beginning of the scenario:
![playrecall](https://cloud.githubusercontent.com/assets/113982/15772082/57810114-296f-11e6-94e0-6a14cc4d2dc7.gif)
And if I save the file (attached), it crashes i-score when opening it.
I have tested with a fresh build from source (after pulling on master)
[BugRecAllLoop.scorejson.zip](https://github.com/OSSIA/i-score/files/297132/BugRecAllLoop.scorejson.zip)
If you don't manage to reproduce, we can look into installing my device (Nebula) on your machine

**Comment by avilleret** [comment]
[OT] wow ! very cool videos ! you should put them in an online tuto !

## 

do it yourself
http://antoine.villeret.free.fr

2016-06-03 9:47 GMT+02:00 Pascal Baltazar notifications@github.com:

**Comment by bltzr** [comment]
[OT] that's GIFs - @himito pointed me to https://itunes.apple.com/fr/app/giphy-capture.-the-gif-maker/id668208984?mt=12 but you don't use Macs, do you ? :-p

**Comment by bltzr** [comment]
GIF- based online tutorials, THAT IS  21st century !!! :-)

**Comment by jcelerier** [comment]
(@avilleret : there are already some up there : http://i-score.org/category/tutorials/ ; under linux I used SimpleScreenRecorder which can output gif, webm, h264...)

**Comment by bltzr** [comment]
So now we don't have an excuse anymore not to make tutorials ;-)

**Comment by bltzr** [comment]
I guess we can close this issue now that it works, so I can make a new one ;-)
