### ISSUE TITLE
score 3.3.2: webcam feed not showing in window (passthrough object)

### ISSUE THREAD

**Issue by bolducmanuel** [ossia/score#1611]
[webcam_passthrough.zip](https://github.com/user-attachments/files/18070244/webcam_passthrough.zip)
](url)

**Comment by jcelerier** [comment]
hm on which os is that ? just opened it and it worked here on linux. Just in case make sure that you don't have e.g. a firefox tab which has the camera open as on linux only one process can access the camera at a time

**Comment by jcelerier** [comment]
@samamou do you think you could try on your computer ?

**Comment by samamou** [comment]
Same, doesn't work for me. When i hit play, my camera turns on but the feed doesn't show in the window.

**Comment by jcelerier** [comment]
Is it on mac, linux, both ?

**Comment by samamou** [comment]
I tried on mac ! @bolducmanuel i assume you tried on linux?

**Comment by jcelerier** [comment]
ahhh and what if you try with a more recent nightly ? https://github.com/ossia/score/releases/tag/continuous

**Comment by jcelerier** [comment]
I think I remember breaking a shader used for the YUV decoding and fixing it afterwards

**Comment by bolducmanuel** [comment]
it works on the nightly! thanks

**Comment by jcelerier** [comment]
cool, I'll tag a release quickly
