### ISSUE TITLE
build fails on nixos 15.09

### ISSUE THREAD

**Issue by magnetophon** [ossia/score#162]
I'm working on a [package](https://gist.github.com/7f874e1e0b04f2e42e46) for [NixOS](http://nixos.org).

All versions that I've tried give me:

```
-- Boost version: 1.58.0
  CMake Error at build/CMakeFiles/git-data/grabRef.cmake:36 (file):
    file failed to open for reading (No such file or directory):
      /tmp/nix-build-i-score-v1.0.0-a31.drv-0/i-score-6037d70/build/CMakeFiles/git-data/head-ref
  Call Stack (most recent call first):
  CMake/modules/GetGitRevisionDescription.cmake:77 (include)
  CMake/IScoreConfiguration.cmake:198 (get_git_head_revision)
  CMakeLists.txt:14 (include)
-- cotire 1.7.5 loaded.
```

When I `sed -e '77d' -i CMake/modules/GetGitRevisionDescription.cmake` the error is gone.

From v1.0.0-a37 or v1.0.0-a38 on (haven't tried yet), I get:

```
 -- The CXX compiler identification is unknown
 CMake Error at CMakeLists.txt:14 (project):
   The CMAKE_CXX_COMPILER:
       /var/empty/bin/clang++
         is not a full path to an existing compiler tool.
```

Version v1.0.0-a36 and older don't do this, but give me other problems.

**Comment by jcelerier** [comment]
Hello, 

For the second error it's because by default i-score uses clang++ for the build because we (as developers) are always git clone'ing in other computers, and it's just easier that way.

There are multiple build configurations that are available in these two folders : 

https://github.com/OSSIA/i-score/tree/master/CMake/Configurations
and
https://github.com/OSSIA/i-score/tree/master/CMake/Configurations/travis

If no configuration is set, by default the "developer" conf is chosen.

A configuration can be set like this : 
`cmake -DISCORE_CONFIGURATION=developer [i-score folder]` (file name without the .cmake suffix)

For an inclusion in a package manager I'd personnally choose the "static-release.cmake"  : configuration : i-score is based on a plug-in approach for modularity of the development process but for now the plug-in api isn't standardised hence it's just better to build the app and its plugins in a single binary (it will still link dynamically to Qt, etc... plug-ins just for the internal organisation). 
The `static-qt` configuration instead really looks for `.a` of Qt.

Thanks !

**Comment by jcelerier** [comment]
Also about your package : don't worry about the addons in OSSIA, they are all in extremely experimental state and don't offer useful features yet (or features that are only relevant to the research process). e.g. iscore-addon-audio with faust, libaudiostream & al are just here as a playground.
At most, iscore-addon-image and iscore-addon-autom3d may be useful.

Finally, for the first bug, could you check that the ".git" folder is present in the source directory ? This module is used to get commit info to display in a dialog box, but I don't think that it was tested without - I'll be doing a patch for this ASAP.

**Comment by jcelerier** [comment]
Could you try with v1.0.0-a52 ? Thanks.

**Comment by magnetophon** [comment]
@jcelerier Thanks!
I've updated [the package](https://gist.github.com/magnetophon/3c9271e41947ea803932) according to your suggestions.
Unfortunately, the build still fails:

```
 [709/777] Building CXX object base/plugins/iscore-plugin-js/CMakeFiles/iscore_plugin_js.dir/JS/JSProcessModelSerialization.cpp.o
FAILED: /nix/store/9fbfiij3ajnd3fs1zyc2qy0ispbszrr7-gcc-wrapper-4.9.3/bin/g++   -DISCORE_LIB_BASE -DISCORE_LIB_DEVICE -DISCORE_LIB_DUMMYPROCESS -DISCORE_LIB_INSPECTOR -DISCORE_LIB_PROCESS -DISCORE_LIB_STATE -DISCORE_PLUGIN_AUTOMATION -DISCORE_PLUGIN_CURVE -DISCORE_PLUGIN_DEVICEEXPLORER -DISCORE_PLUGIN_LOOP -DISCORE_PLUGIN_OSSIA -DISCORE_PLUGIN_SCENARIO -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -Discore_plugin_space_EXPORTS -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Ibase/plugins/iscore-plugin-space -I../base/plugins/iscore-plugin-space -I/nix/store/lfj41wlg1m05rfip5jja4mpfp84yiyhm-boost-1.58.0-dev/include -I. -isystem ../3rdparty/variant/include -isystem ../3rdparty/nano-signal-slot -I../base/lib -I../ -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/include -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/include/QtCore -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/mkspecs/linux-g++ -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/include/QtWidgets -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/include/QtGui -isystem /nix/store/rj0iyafchrdppzyidn5xz8q5bvnk1iv1-mesa-noglu-10.6.9/include -Ibase/lib -isystem /nix/store/abm9qnv54s9s9sb6sl3mdqvliwkhqf0c-qtsvg-5.4.2/include -isystem /nix/store/abm9qnv54s9s9sb6sl3mdqvliwkhqf0c-qtsvg-5.4.2/include/QtSvg -I../3rdparty/QRecentFilesMenu -Ibase/plugins/iscore-plugin-deviceexplorer -I../base/plugins/iscore-plugin-deviceexplorer -Ibase/plugins/iscore-lib-state -I../base/plugins/iscore-lib-state -Ibase/plugins/iscore-lib-device -I../base/plugins/iscore-lib-device -isystem /nix/store/nc1fslq47z4qpizwdjx97fjj6x7bvnd4-qtbase-5.4.2/include/QtXml -I../3rdparty/QProgressIndicator -Ibase/plugins/iscore-lib-process -I../base/plugins/iscore-lib-process -Ibase/plugins/iscore-plugin-ossia -I../base/plugins/iscore-plugin-ossia -Ibase/plugins/iscore-plugin-scenario -I../base/plugins/iscore-plugin-scenario -Ibase/plugins/iscore-plugin-curve -I../base/plugins/iscore-plugin-curve -Ibase/plugins/iscore-plugin-inspector -I../base/plugins/iscore-plugin-inspector -Ibase/plugins/iscore-plugin-automation -I../base/plugins/iscore-plugin-automation -I../API/Headers -isystem /nix/store/f8a98daj1gnn1jf22grz3dvfa8dgjrcr-JamomaCore-v1.0-beta.1/jamoma/include/jamoma -Ibase/plugins/iscore-plugin-loop -I../base/plugins/iscore-plugin-loop -Ibase/plugins/iscore-plugin-scenario/DummyProcess -I../base/plugins/iscore-plugin-scenario/DummyProcess    -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wnon-virtual-dtor -pedantic -Woverloaded-virtual -pipe -Ofast -fPIC -std=gnu++14 -MMD -MT base/plugins/iscore-plugin-space/CMakeFiles/iscore_plugin_space.dir/src/SpaceProcessFactory.cpp.o -MF base/plugins/iscore-plugin-space/CMakeFiles/iscore_plugin_space.dir/src/SpaceProcessFactory.cpp.o.d -o base/plugins/iscore-plugin-space/CMakeFiles/iscore_plugin_space.dir/src/SpaceProcessFactory.cpp.o -c ../base/plugins/iscore-plugin-space/src/SpaceProcessFactory.cpp
In file included from ../base/plugins/iscore-plugin-space/Space/computation.hpp:4:0,
                 from ../base/plugins/iscore-plugin-space/src/Computation/ComputationModel.hpp:3,
                 from ../base/plugins/iscore-plugin-space/src/SpaceProcess.hpp:5,
                 from ../base/plugins/iscore-plugin-space/src/SpaceProcessFactory.cpp:2:
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp: In member function 'constexpr spacelib::square_approx<size, side>::iterator spacelib::square_approx<size, side>::iterator::operator++() const':
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp:27:28: error: increment of read-only location '((const spacelib::square_approx<size, side>::iterator*)this)->spacelib::square_approx<size, side>::iterator::pos'
                 { return ++pos, *this; }
                            ^
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp: In member function 'constexpr spacelib::square_approx<size, side>::iterator spacelib::square_approx<size, side>::iterator::operator++(int) const':
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp:29:28: error: increment of read-only location '((const spacelib::square_approx<size, side>::iterator*)this)->spacelib::square_approx<size, side>::iterator::pos'
                 { return ++pos, *this; }
                            ^
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp: In member function 'constexpr spacelib::dynamic_square_approx::iterator spacelib::dynamic_square_approx::iterator::operator++() const':
../base/plugins/iscore-plugin-space/Space/square_approximator.hpp:74:28: error: increment of member 'spacelib::dynamic_square_approx::iterator::m_pos' in read-only object
                 { return ++m_pos, *this; }
```

**Comment by jcelerier** [comment]
Which version is this ? 
`iscore-plugin-space` hasn't been in the `base/plugins/` folder for about three months due to its experimental (at best) state.

**Comment by magnetophon** [comment]
@jcelerier Oops, I was accidentally building v36 instead of v52, sorry.
It builds now, but I still have to sed out the commit info line, even though I'm sure the .git is there.

I do get a lot of crashes, but I'll open separate issues for that when I have more info.

**Comment by jcelerier** [comment]
Okay, what version of Qt are you building against by the way and with which gcc/g++ ? I can guarantee "normal" operation under Qt >= 5.4 and gcc > 5.1 / clang > 3.5, it's less tested with older libs.

Thanks a lot for your work !

**Comment by magnetophon** [comment]
This is with qt 5.4 and gcc 4.9.3.
I'm building again with gcc 5.2.0 

And thank YOU for your work!!!  :)

**Comment by magnetophon** [comment]
I finished building, and still get lot's of crashes.
For example creating a new device will always segfault.

**Comment by jcelerier** [comment]
Do you know if there's something like a docker image of NixOS that would
allow me to check the package ?

**Comment by magnetophon** [comment]
Does this help: https://nixos.org/wiki/Installing_NixOS_in_a_VirtualBox_guest  ?

**Comment by jcelerier** [comment]
Hi, 
I took some time in order to try to build an x86_64 AppImage (binaries that should work on any linux distro). Could you test it on yours ? 
Thanks.

The appimage is here and has to be marked executable : 
https://github.com/OSSIA/i-score/releases/tag/v1.0.0-a68

**Comment by magnetophon** [comment]
@jcelerier Thanks, but that cannot work on NixOS:
To get the many benefits that it has, NixOS pays the price of not putting packages in their normal location. so your binaries can't find anything they need.

For more info see www.nixos.org
