### ISSUE TITLE
Changing the duration of a constraint causes that the constraint is moved to the top of the scenario 

### ISSUE THREAD

**Issue by himito** [ossia/score#163]
Hi!

it's me again :dancer:  each time that I change the duration of a constraint, that constraint is moved to the top of the scenario :sob: 

![constraint_duration](https://cloud.githubusercontent.com/assets/181677/13647368/19de975a-e634-11e5-8f9c-bfe4f1bf233f.gif)

**Comment by nvuaille** [comment]
It was fixed with dcb317bd8a2788f2d132575ee144868afa5664cd  (on dev for now)

**Comment by bltzr** [comment]
oh... gifs for bug reports ! That's cute ! 
(what do you use to create them ?)

**Comment by himito** [comment]
http://www.gifgrabber.com/ :smiley:

**Comment by bltzr** [comment]
muchas gracias Jaime !
