### ISSUE TITLE
Problem with sending value in mode OSC

### ISSUE THREAD

**Issue by gagnere** [ossia/score#164]
I built an OSC device called Unreal to send integer value to the remote device with test, as adresse name.
I can't send a value greater than 1... I have only two choices : 0 and 1...
I use v1.0.0-a52 Ubuntu14.04 version of Iscore

**Comment by theod** [comment]
Hi George,
did try to change the adress Clip mode from « Clip » to « Free » ?
I’ve experienced some strange behavior with this attribute so maybe it could help ?

Best,
TO

**Comment by gagnere** [comment]
It is it! Thank you.
g.

**Comment by jcelerier** [comment]
@theod what should be the default when creating a new device ? 
But since a few days it seems that the clip is always between 0 and 1, ignoring the values in OSSIA::Domain.
It may be in i-score if the tests are ok in the API.

**Comment by reno-** [comment]
The clip refers to a domain, but when creating an OSC parameter/address, it have not any domain first. So it should not have any clip.
Am I right?

**Comment by theod** [comment]
yes ! it should be « Free » by default.

**Comment by jcelerier** [comment]
It should be fixed (and free will be the default) in master
