### ISSUE TITLE
No Menu in a Javascript process

### ISSUE THREAD

**Issue by himito** [ossia/score#165]
Yo de nuevo :dancer:  

Clicking on '#' of a javascript state does not show a menu.

![bug_menu_javascript_state](https://cloud.githubusercontent.com/assets/181677/13925172/a39394e4-ef87-11e5-82f9-9056fef3fb1f.gif)

**Comment by nvuaille** [comment]
Fixed in dev (38caeaaa7e9e5395fd207e2ac79db4bf8ff1f82f) , I forget to put issue reference in commit message ...
