### ISSUE TITLE
pb without scenario layout for a v1 beginner

### ISSUE THREAD

**Issue by gagnere** [ossia/score#168]
I'm really confused with thes sizes of the constraint lines and state nodes. Using a ubuntu version with a 15'' laptop, i almost need 2 or 3 seconds to catch each constraint line and state dot, and i'm planning to build a 200 hundred events scenario for the ParOral project...
I would be very happy to have the choice of the sizes of this fundamental tools instead of the colors... I'm getting old and tired to work with tiny scores... Help!

**Comment by gagnere** [comment]
well, i tested i-score on a 17'', it's better... but I won't use always a 17''...

**Comment by nvuaille** [comment]
I'm working on it, changing elements size will be available soon !
