### ISSUE TITLE
states values of addresses shared with automations cannot be modified

### ISSUE THREAD

**Issue by bltzr** [ossia/score#169]
this happens when trying to modify a value either by:
- changing it by hand in the state inspector
- dragging the current value from the device explorer
- updating the state

AFAIK, I think this was broken in a recent build... (but I don't know precisely which one...)
This is quite critical (at least for me - even if it's not extremely urgent, as I'm not going to need to modify my scenario for the next three presentation days )

**Comment by bltzr** [comment]
I assigned to @jcelerier but maybe this is for @theod ?

**Comment by jcelerier** [comment]
For reference, everything that happens before pressing the "play" button is
pressed is a problem in i-score and not the API.

**Comment by jcelerier** [comment]
It should be solved in the next release.

**Comment by bltzr** [comment]
yes, that seems OK now, thanks !
