### ISSUE TITLE
UX for process panel 

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#171]
It should not switch to processes that are currently displayed in full view but only to their children

**Comment by bltzr** [comment]
not sure what you mean, but if I get it right, I think it's important to have access to process from the constraints displayed in fullview (useful i.e. when editing several automations in a row)

**Comment by bltzr** [comment]
if I understand well (do I?), processes should be shown:
- for the main constraint when the main header or background is hitten
- for the chosen box/constraint when its header/slot is hitten/selected
this is related to #429

**Comment by jcelerier** [comment]
hmm, sorry, I did not quite understand your post. but the process panel is currently disabled so maybe we can close this issue and come back at it when it is re-enabled.

The problem was that for instance if you have the scenario in full view, clicking in the background of the scenario would also show it in the process panel (which does not really makes sense).
