### ISSUE TITLE
Scrollbar handles for zooming in and out

### ISSUE THREAD

**Issue by lossius** [ossia/score#173]
Would it be possible to extend the scrollbars in i-score with small handles at the end that could be used to click and drag zoom-in and zoom-out? Reaper behaves this way.

Additionally, when holding the cursor over the horisontal (time) scrollbar and pinching/zooming at the trackpad, or using the scroll wheel, it would be nice if this also would be zooming in and out in time rather than  scrolling up and down.

There's a screencast here that illustrates how this works in Reaper:

https://sourceforge.net/p/i-score/mailman/attachment/0945D7F2-6A2D-41AE-978C-4E3A457E2152%40bek.no/1/

**Comment by bltzr** [comment]
this has been discussed again in #437 so I'm closing it - see you there (and we'll try to avoid French, I promise)
