### ISSUE TITLE
OSX zip file not downloading correctly

### ISSUE THREAD

**Issue by PostArchitekt** [ossia/score#175]
I just downloaded the OS X.zip and it appears to be incomplete. It has the circle with a line through it. I tried the earlier versions as well.

**Comment by PostArchitekt** [comment]
It's saying it's only 63.8% saved once it's downloaded.

**Comment by bltzr** [comment]
cana you try again (maybe from another browser ?) - it works fine here...

**Comment by PostArchitekt** [comment]
I just tried from different location using Safari above and then now using chrome. Same results with the exact same percentage of download. It's definitely not a hard drive space problem either.

**Comment by bltzr** [comment]
well... I really have no idea... this is actually stored in the Amazon cloud... so I don't really how we can help. It apparently works for other users.... Have you tried with another computer ?

**Comment by himito** [comment]
Hello,
I tried to download i-score with chrome and safari and it worked good. Maybe it is a problem with your connection.
I shared a dropbox folder with the i-score app if you want to install it: [Dropbox](https://www.dropbox.com/s/tln9rgpnuw57n2s/i-score-v1.0.0-a66-OSX.zip?dl=0)

**Comment by jcelerier** [comment]
closing, I don't think that it's something we have control over...
