### ISSUE TITLE
Mapping in base constraint does not play

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#176]
Steps : 
- create new doc
- create a device
- add a mapping in the base constraint (parallel with base scenario) and set its addresses
- play

Crash log : 

0   JamomaState::launch() const State.cpp   37  0x10bc01772 
1   RecreateOnPlay::BaseScenarioElement::baseScenarioConstraintCallback(OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptrOSSIA::StateElement) BaseScenarioElement.cpp 122 0x109c6d480 
2   RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0::operator()(OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptrOSSIA::StateElement) const   BaseScenarioElement.cpp 61  0x109c6e9ac 
3   std::__invoke<RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0&, OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptr<OSSIA::State>>(decltype(std::forward<RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0&>(fp)(std::forward<OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptr<OSSIA::State>>(fp0))), RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0&&&, OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, std::shared_ptrOSSIA::State&&)   __functional_base   413 0x109c6e836 
4   std::__function::__func<RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0, std::allocator<RecreateOnPlay::BaseScenarioElement::BaseScenarioElement(Scenario::BaseScenario const&, RecreateOnPlay::Context const&, QObject *)::$_0>, void (OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptrOSSIA::State)>::operator()(OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptrOSSIA::State&&)    functional  1370    0x109c6e6f3 
5   std::function<void (OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptr<OSSIA::State>)>::operator()(OSSIA::TimeValue const&, OSSIA::TimeValue const&, std::shared_ptrOSSIA::State) const    functional  1756    0x10bbe45fb 
6   JamomaTimeConstraint::ClockCallback(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char)    TimeConstraint.cpp  286 0x10bc04d6b 
7   decltype( *(std::forward<JamomaTimeConstraint *&>(fp0)). *fp(std::forward<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char>(fp1))) std::__invoke<void (JamomaTimeConstraint:: *&)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *&, OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char, void>(void (JamomaTimeConstraint:: *&&&)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *&&&, OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, unsigned char&&)   __functional_base   380 0x10bc0f0c7 
8   std::__bind_return<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>, std::tuple<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char&&>, _is_valid_bind_return<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>, std::tuple<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char&&>>::value>::type std::__apply_functor<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>, 0ul, 1ul, 2ul, 3ul, std::tuple<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char&&>>(void (JamomaTimeConstraint:: *&)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>&, std::__tuple_indices<0ul, 1ul, 2ul, 3ul>, std::tuple<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char&&>&&)   functional  2023    0x10bc0eff3 
9   std::__bind_return<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>, std::tuple<OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, unsigned char&&>, _is_valid_bind_return<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), std::tuple<JamomaTimeConstraint *, std::placeholders::__ph<1>, std::placeholders::__ph<2>, std::placeholders::__ph<3>>, std::tuple<OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, unsigned char&&>>::value>::type std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>::operator()<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char>(OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, unsigned char&&)   functional  2086    0x10bc0ee8c 
10  decltype(std::forward<std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>&>(fp)(std::forward<OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char>(fp0))) std::__invoke<std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>&, OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char>(std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>&&&, OSSIA::TimeValue const&&&, OSSIA::TimeValue const&&&, unsigned char&&) __functional_base   413 0x10bc0ecff 
11  std::__function::__func<std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>, std::allocator<std::__bind<void (JamomaTimeConstraint:: *)(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char), JamomaTimeConstraint *, std::placeholders::__ph<1>&, std::placeholders::__ph<2>&, std::placeholders::__ph<3>&>>, void (OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char)>::operator()(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char&&)  functional  1370    0x10bc0ecad 
12  std::function<void (OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char)>::operator()(OSSIA::TimeValue const&, OSSIA::TimeValue const&, unsigned char) const    functional  1756    0x10bb6370c 
13  JamomaClock::do_start() Clock.cpp   271 0x10bb61e95 
14  JamomaTimeConstraint::start()   TimeConstraint.cpp  102 0x10bc0717a 
15  RecreateOnPlay::ConstraintElement::play(TimeValue_T<double>)    ConstraintElement.cpp   93  0x109c988aa 
16  OSSIAApplicationPlugin::on_play(bool, TimeValue_T<double>)  OSSIAApplicationPlugin.cpp  227 0x109c58516

**Comment by jcelerier** [comment]
I replaced this by a warning. However the states won't be sent, for some reason.

**Comment by jcelerier** [comment]
now it works !
