### ISSUE TITLE
Play from here crash when infinite max

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#177]
Steps : 
- create two constraints in sequence
- create a trigger between them
- set the max of the first constraint to inf

![crash_playhere](https://cloud.githubusercontent.com/assets/5503180/14490374/c5fa13c6-0172-11e6-9adf-8814457086e0.png)

'Play from here' asked after the the second constraint crashes

**Comment by jcelerier** [comment]
@theod it seems to crash because in JamomaScenario::start we are in the last "invalid" case : 
for some reason, startStatus == Pending and endStatus == Happened

```
void JamomaScenario::start()
{
  // start each TimeConstraint if possible
  for (const auto& timeConstraint : mTimeContraints)
  {
    TimeEvent::Status startStatus = timeConstraint->getStartEvent()->getStatus();
    TimeEvent::Status endStatus = timeConstraint->getEndEvent()->getStatus();

    // the constraint is in the past
    if (startStatus == TimeEvent::Status::HAPPENED &&
        endStatus == TimeEvent::Status::HAPPENED)
    {}
    // the start of the constraint is pending
    else if (startStatus == TimeEvent::Status::PENDING &&
             endStatus == TimeEvent::Status::NONE)
    {}
    // the constraint is supposed to be running
    else if (startStatus == TimeEvent::Status::HAPPENED &&
             endStatus == TimeEvent::Status::NONE)
    {
      timeConstraint->start();
    }
    // the end of the constraint is pending
    else if (startStatus == TimeEvent::Status::HAPPENED &&
             endStatus == TimeEvent::Status::PENDING)
    {}
    // the constraint is in the future
    else if (startStatus == TimeEvent::Status::NONE &&
             endStatus == TimeEvent::Status::NONE)
    {}
    // error
    else
      throw runtime_error("TimeEvent's status configuration of the TimeConstraint is not handled");
  }
}
```

**Comment by bltzr** [comment]
It doesn't crash... but it doesn't play either (at least until the trigger's expression has turn true - which seems perfectly normal to me)
does anybody else want to try, or should I close the issue ?

**Comment by jcelerier** [comment]
I don't think that this has been fixed at all :(

**Comment by bltzr** [comment]
well, unless I misunderstood the problem, it works for me:
![trig-playfh](https://cloud.githubusercontent.com/assets/113982/15983719/55ce05ea-2fb1-11e6-840f-8b5b0551b8df.gif)

**Comment by bltzr** [comment]
sorry, I misread - that was **after** the second constraint
well then, it doesn't work (the 3rd constraint doesn't play), but it doesn't crash either
![trig-playfh-2d](https://cloud.githubusercontent.com/assets/113982/15983740/bc1097e6-2fb1-11e6-95e7-d841160d0f21.gif)

**Comment by jcelerier** [comment]
Not sure what kind of eldritch magic happened in the code but it seems that now it works.
