### ISSUE TITLE
bug sous scénario

### ISSUE THREAD

**Issue by simonjamain** [ossia/score#18]
comment reproduire : 
mode "create" + "fork creation"
créer contrainte
placer sous scénario sur cette contrainte

bug -> lors de la création d'éléments dans le sous-scénario ainsi créer, le mode fork n'est pas pris en compte alors qu'affiché comme tel, il faut le reactiver

**Comment by nvuaille** [comment]
Solution implémentée : au changement de focus, on réinitialise sur l'outil 'select/move'
