### ISSUE TITLE
Building on Ubuntu 14.04

### ISSUE THREAD

**Issue by tedr56** [ossia/score#182]
Hi.
I've just found this software which looks promising but I can't get its purpose yet.
After a quick try with debs install and a lot of crashes, I decided to build it.

This a semi-issue since I finally succeeded, but I think some Readme or INSTALL needs updates.

For the record, I "checkouted" the last tag at date, v1.0.0-a67 ede2453

First, it took me some time to realise that the git repo had some submodules.
I'd add this little line somewhere in the doc.
`git clone --recursive git@github.com:OSSIA/i-score.git`

Since last Qt in packet manager is 5.2, I  used this for cmake
`cmake -DCMAKE_PREFIX_PATH="$ISCORE_CMAKE_QT_PATH/opt/Qt/5.5/gcc_64/lib/cmake/" ..`

Then, I had some errors with QJsonArray with Qt5.3 (along CMake warnings) in `i-score/base/lib/iscore/serialization/QtTypesJsonVisitors.cpp`

`i-score/base/lib/iscore/serialization/QtTypesJsonVisitors.cpp:19: error: no matching function for call to 'QJsonArray::QJsonArray(<brace-enclosed initializer list>)'
     val = QJsonArray{pt.x(), pt.y()};`

`i-score/base/lib/iscore/serialization/QtTypesJsonVisitors.cpp:37: error: no matching function for call to 'QJsonArray::QJsonArray(<brace-enclosed initializer list>)'
         pt.m31(), pt.m32(), pt.m33()};`

These errors dispear in Qt 5.4 & 5.5.

Then, I had this strange and annoying error
`/usr/include/boost/detail/allocator_utilities.hpp:178: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = iscore::DocumentPluginFactory; _Dp = std::default_delete<iscore::DocumentPluginFactory>]'
   new (p) Type(t);`
https://gist.github.com/tedr56/197d3ef2262848f919a26387ca6a1ed0

I randomly tried libboost1.55-dev, instead of the default 1.54, and build finnaly passed.

Here is my little adventure in the i-score build.
It can also be used as a guide for those who try it unde linux.

Thanks for any interest.

**Comment by jcelerier** [comment]
Hello, 

thanks for your report ! 
For reference there is a CI system which builds the packages under ubuntu 14.04 but uses more recent version of many packages (as you guessed it, boost, qt, and also cmake, because they allow a faster development, which is the main concern due to the small workforce:) ).

This script outlines the required dependencies : https://github.com/OSSIA/i-score/blob/master/tools/travis/deps.sh

The wiki build pages are certainly outdated, I'll try to update them.

**Comment by jcelerier** [comment]
Hi, 
I took some time in order to try to build an x86_64 AppImage (binaries that should work on any linux distro). Could you test it on yours ? 
Thanks.

The appimage is here and has to be marked executable : 
https://github.com/OSSIA/i-score/releases/tag/v1.0.0-a68

**Comment by tedr56** [comment]
Hi jcelerier.
I just tried the AppImage.
I-Score does open but crash on opening file or when adding child.

**Comment by tedr56** [comment]
Terminal outputs

Opening File: https://gist.github.com/tedr56/c54341e21576f167e8f6493a7a6cd76f
Adding Child : https://gist.github.com/tedr56/f0f9b7140e8a46f2e48be506512780d7

Seems pretty the same.

**Comment by jcelerier** [comment]
interesting, I'll investigate tomorrow ! thank you so much !

**Comment by tedr56** [comment]
You're welcome :)

**Comment by jcelerier** [comment]
closing; I updated the wiki with up-to-date informations for building on 14.04 and I hadn't crashes in the appimage for a long time...
