### ISSUE TITLE
crash when removing state 

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#192]

**Comment by bltzr** [comment]
I was about to report on that - though is this when removing a state or an event ?
(maybe that's a question of how we name things... I'm not entirely sure about this)

**Comment by bltzr** [comment]
also, this happens when attempting to delete several objects, including states/events
as a result, it is currently impossible to delete more than just constraints 
(which makes the end of scenario very packed with old junk :-p )

**Comment by jcelerier** [comment]
I made some attempts to fix this, please test

**Comment by bltzr** [comment]
it still crashes (on e5346ea95e5aa3564cdbb341ebfa9489f53813ad )
- when creating an event from the scenario (with its previous constraint), then selecting this event AND the previous constraint, then pressing backspace -> CRASH !
  ![del-evt1](https://cloud.githubusercontent.com/assets/113982/15965509/a3c37b38-2f1e-11e6-8343-c8ba7e470e58.gif)
- when creating an event by drag'n'dropping an address/value from the explorer, then selecting the event/state, pressing backspace -> CRASH !
  ![del-evt2](https://cloud.githubusercontent.com/assets/113982/15965522/be653b84-2f1e-11e6-8cad-5c33cf5085bc.gif)
- also creating an event and a constraint by selecting another event before drag'n'dropping, then only selecting the newly created event DOESN'T CRASH
  ![del-evt-ok1](https://cloud.githubusercontent.com/assets/113982/15965626/59b105b4-2f1f-11e6-9ae9-3001a7ee2128.gif)
- Same when the event has been created in the editor:
  ![del-evt-ok0](https://cloud.githubusercontent.com/assets/113982/15965631/6fc22356-2f1f-11e6-9ecd-c99531e1e136.gif)

Hope this helps...

**Comment by bltzr** [comment]
update for case 2: when the event/state is selected by clicking on it (instead of selecting it by dragging around as on the second GIF above), then pressing backspace DOES NOT CRASH
![del-evt-ok2](https://cloud.githubusercontent.com/assets/113982/15965751/1a63e862-2f20-11e6-892c-fcff5d7cd562.gif)

**Comment by bltzr** [comment]
also, when selecting (via multiple selection: click, then cmd-click on previous constraint), it also crashes
![del-evt4](https://cloud.githubusercontent.com/assets/113982/15965808/5adf8856-2f20-11e6-9577-a0a494a2ce3d.gif)

**Comment by jcelerier** [comment]
I think that I found where most were coming from. Please try 939539147aa3eb56507b83e5f2e9873370c86b3a

**Comment by bltzr** [comment]
I cannot, because there's something wrong with 5602d42dce225819d2c02eac6443b0b5054cef29
(you probably forgot to commit something, check gitter)

**Comment by bltzr** [comment]
seems OK - closing the issue... will reopen if some have been missed...
