### ISSUE TITLE
object-selection is persistent

### ISSUE THREAD

**Issue by bltzr** [ossia/score#197]
currently, when selecting a new object, the previous one(s) stay selected, as if one had kept the shift button pressed...

**Comment by jcelerier** [comment]
I sometimes have it but right now I cannot reproduce it :(

**Comment by bltzr** [comment]
I have this absolutely all the time ! 
what if you click on a constraint, then another one - don't they all add up to the summary panel in the inspector ?
of course, it first did the problem... but now it doesn't any more... I'll try to find what (reproducible) behavior causes it to happen.

**Comment by jcelerier** [comment]
> what if you click on a constraint, then another one - don't they all add up to the summary panel in the inspector ?

niet

**Comment by bltzr** [comment]
I have the same... used to do that, but I can't reproduce it...
will tell you if it happens again when using it IRL

**Comment by jcelerier** [comment]
do you still have it ? I still cannot reproduce...

**Comment by bltzr** [comment]
nope, that seems OK now
