### ISSUE TITLE
new objects should be selected after creation

### ISSUE THREAD

**Issue by bltzr** [ossia/score#198]
(and the previous selection should be reset,so only this object should be selected, see #197 )

**Comment by bltzr** [comment]
up

**Comment by jcelerier** [comment]
I just pushed an implementation, but it feels really weird to me.

**Comment by bltzr** [comment]
OK I’ll try that and let you know

**Comment by bltzr** [comment]
if other @OSSIA/users want to try that out too... some feedback would be helpful...

**Comment by bltzr** [comment]
I actually like it
though there's one weird thing: in the case below:
![mai-25-2017 20-14-52](https://cloud.githubusercontent.com/assets/113982/26464114/ebd50880-4186-11e7-87c6-a22d63662967.gif)
it feels very weird that both states (and the constraint) are selected - only the last state (and maybe the constraint) should be selected IMO (i.e. the first state should not be selected)
