### ISSUE TITLE
right-clicking on an object should select it first

### ISSUE THREAD

**Issue by bltzr** [ossia/score#201]
as demonstrated below, right-clicking on an object doesn't select it first
in this case, this leads to the wrong state being played

![2dclick](https://cloud.githubusercontent.com/assets/113982/15931915/ee619e88-2e59-11e6-8052-cb74c5e9937c.gif)

**Comment by jcelerier** [comment]
this would make it harder to have right click on multiple selection since it would deselect everything selected...

**Comment by bltzr** [comment]
I just tried that in a couple softwares:
- in Apple Mail, the selection stays as is, and there's a little blue border indicating the contextual menu applies to the chosen item:
  ![mail-select](https://cloud.githubusercontent.com/assets/113982/16044861/6ead97fa-3246-11e6-949a-ba302c1f288c.gif)
- in Max, if right-clicking on an item which was not part of the previous selection, it cancels the previous selection, and selects only the clicked item:
  ![max-deselect](https://cloud.githubusercontent.com/assets/113982/16044949/be609a40-3246-11e6-81ab-157ad8669ae4.gif)
  BUT when clicking on an item which was part of the selection, the selection remains the same, and the action is applied to the whole selection (not only to the item)
  ![max-multi-select](https://cloud.githubusercontent.com/assets/113982/16044977/da86ee86-3246-11e6-9745-264e66a4bfb4.gif)

This behavior makes a lot of sense to me...
- Numbers (Apple's Excel), my accounting program, github's text editor, notationnal velocity, Apple Notes do just the same... so I guess, from my small test, this can be considered the common behavior...

**Comment by bltzr** [comment]
I'd still consider the current behavior a bug, though...

**Comment by jln-** [comment]
agree the current behavior is kindof a problem

**Comment by bltzr** [comment]
up

**Comment by jcelerier** [comment]
seems like it has been fixed at some point
