### ISSUE TITLE
scenarios are not loaded displaying the same part of the scenario as they were saved

### ISSUE THREAD

**Issue by bltzr** [ossia/score#202]
see below, zooming with the center of the screen at about 17'50, then saving
![zoom save](https://cloud.githubusercontent.com/assets/113982/15932191/0e1fd216-2e5b-11e6-805f-2043fda83a76.gif)

then opening the file, the center is now at about 14'50 (and the vertical position has moved, too) - also I'm not certain about the zoom level, but it seems (roughly) OK
![load](https://cloud.githubusercontent.com/assets/113982/15932263/42886356-2e5b-11e6-8d56-35349703f113.gif)

**Comment by bltzr** [comment]
this is even worse than it was before the zoom was reworked - now it goes WAY WAY WAY later than the end state !!!! 
This is probably one of the most urgent bugs to fix (probably along fixing the flaky zoom, as reported in #454 )

**Comment by jcelerier** [comment]
for now as a stop gap I disabled the saving / reloading; it will fit the whole score to the window instead. will get back to it when I have more time
