### ISSUE TITLE
zooming a lot in long scenarios makes the position jump

### ISSUE THREAD

**Issue by bltzr** [ossia/score#203]
after a certain zoom level, the position of the center of the display jumps into the past
here, the scenario is initially centered around 12' - when zooming in, at some point, it suddenly jumps to 6' or so...
![zoom-jump](https://cloud.githubusercontent.com/assets/113982/15932424/ee2e4932-2e5b-11e6-8b73-81c08e6719b2.gif)

**Comment by jcelerier** [comment]
it's because you are reaching the zoom level where quantum fluctuations start to matter

**Comment by bltzr** [comment]
ah... I see, so it creates anti-particles.... makes sense !

**Comment by jcelerier** [comment]
I don't think that it will be perfectly solvable... this is due to this : 
http://doc.qt.io/qt-5/qgraphicsview.html#centerOn

> Because pos is a floating point coordinate, and the scroll bars operate on integer coordinates, the centering is only an approximation.

Basically, at high zoom levels, this approximation becomes more and more apparent...
I tried to mitigate it a bit by reducing the max zoom ratio by a tiny fraction.

**Comment by jcelerier** [comment]
I mark as fixed (we spoke about it on gitter)
