### ISSUE TITLE
"creating curves" crashes i-score

### ISSUE THREAD

**Issue by bltzr** [ossia/score#206]
BTW, what is this supposed to do ?

**Comment by nvuaille** [comment]
It's supposing creating curves =P

Select an address (or more) and a constraint, and "creating curves" will create automation(s) in the constraint upon the selected address (linear from min to max)

**Comment by bltzr** [comment]
makes sense ! 
though, I didn't think of selecting addresses before pushing the button...
knowing that, this makes perfect sense!

**Comment by bltzr** [comment]
also, I tried that on a constraint with another automation, so the crash is indeed #199 - closing the issue, then
