### ISSUE TITLE
document scenario's end state behavior on stop 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#207]
leaving that there, because @theod told me, and I guess we're the two only ones to know:
when stopping the scenario, the content of its end state (on the main constraint) is sent/played

**Comment by bltzr** [comment]
This makes probably the "reinitialize" function useless (or even undesirable) now
anybody else than me using it ? 
@jcelerier @blueyeti @jln- @theod @reno- @avilleret @himito ?
If not, I'd recommend removing it (and the button in the toolbar) - this adds confusion, and looks like a "loop" symbol anyway

**Comment by jcelerier** [comment]
shouldn't this be a setting somewhere ? What if you have some actual state that you want to play on the final 'tick' but not when you press stop ?

**Comment by bltzr** [comment]
maybe you put it at the end of the scenario, _inside_ the scenario
for me, this is something like a "de-init", as @reno- has been using it in tapemovie
but, yes, this might be possible to disable it in some setting, why not..

**Comment by bltzr** [comment]
or maybe we can keep this (it could also be interesting, somehow....) but then change the logo, because this one is confusing... what about a kind of "rewind" logo ? Wouldn't that be more... "conventional" ?
![rewind-4_318-11036](https://cloud.githubusercontent.com/assets/113982/15966272/d65e86f6-2f22-11e6-8045-08b9656178b3.jpg)

**Comment by bltzr** [comment]
I have tried to change the icon locally, and I personally find it much clearer this way
this is how it looks:
![transport](https://cloud.githubusercontent.com/assets/113982/15991528/b55024c6-30b5-11e6-9e3d-2246cdfc03ed.png)
does anybody (particularly @blueyeti) object to this change ?
If not, I'll commit it...

**Comment by jln-** [comment]
FWIW, I like these

Best,
J

**Comment by jcelerier** [comment]
Due to the lack of objections, if you still have it I think that you can commit it.

**Comment by bltzr** [comment]
Just committed - couldn't test as the build fails on my machine - but I don't see what I could possibly have done wrong while changing 4 files's names...
