### ISSUE TITLE
does "loop content" do anything ?

### ISSUE THREAD

**Issue by bltzr** [ossia/score#208]
apparently it doesn't, see below:
(or did I get it wrong ?)

if It doesn't do anything, either we fix it or we remove it...

![loop-content](https://cloud.githubusercontent.com/assets/113982/15933140/caaa7d98-2e5e-11e6-984d-f57e70f23c56.gif)

**Comment by nvuaille** [comment]
Once again, time is the master =P When your rigid constraint ends, the following starts so there's no bug in your example.

If I remember, "loop content" allows to duplicate contents when you increase constraint duration.

**Comment by jcelerier** [comment]
this caused deep bugs in the engine so it is currently disabled; I'll also disable the graphical shortcut until it is sorted out.

**Comment by bltzr** [comment]
good idea!
