### ISSUE TITLE
Web site documentation - larger screenshot images 

### ISSUE THREAD

**Issue by lossius** [ossia/score#21]
IMHO the screenshot in e.g. these pages could be larger:

http://doc.i-score.org/introduction/index.html
http://doc.i-score.org/meeting-i-score-interface/index.html

Currently its difficult to get information at all from these images at all except that they are screenshots of a program that appears to be mostly really dark. Something along the line of lightbox.js would probably be useful.

**Comment by theod** [comment]
notice this issue refers to i-score 0.2 documentation

**Comment by jcelerier** [comment]
I'm closing since this documentation is not accessible anymore. 
Now there are tutorials here : http://i-score.org/category/tutorials/

hopefully it's better...
