### ISSUE TITLE
use plain keys (no modifiers) for interpolation/snapshots/etc...

### ISSUE THREAD

**Issue by bltzr** [ossia/score#210]
I'm wondering if this "family" of functions (with interpolating and creating curves) should use plain keys, without modifiers (like the selection/creation... etc.) tools...
not sure about this... 

When using i-score, this is something I often do, and (particularly when using it in the dark) I find having to press the command key superfluous 
but that's also a security... (though, we always have the possibility to undo)

others having opinions ? 
@jcelerier @blueyeti @jln- @theod @reno- @avilleret @himito ?

**Comment by jcelerier** [comment]
if the keyboard shortcuts are modifiable, would it be enough ?

**Comment by himito** [comment]
It would be nice to have our own kb shortcuts 💃

**Comment by bltzr** [comment]
I think having a way to define shortcuts, as suggested by @himito is a good idea, but a different topic.... so I'm creating a new issue for that and closing this one
