### ISSUE TITLE
add icon/button for "Refresh states"

### ISSUE THREAD

**Issue by bltzr** [ossia/score#211]
This is a **very** useful function.
So I guess it would be good to have it as a tool...

Not sure about which logo could be best for that, though.... a camera with a "recycling" double-arrow maybe ? - just the recycling arrow ?

**Comment by bltzr** [comment]
Thanks !
BTW, I think this would be clearer if the recycling arrow was around the (then smaller) camera.
I can do this if you give me the source of the icon

**Comment by jcelerier** [comment]
https://github.com/OSSIA/i-score/tree/master/base/plugins/iscore-plugin-scenario/Scenario/resources/icons_svg

**Comment by bltzr** [comment]
done and committed !
though, I didn't have the source for the camera in the svgs so I tweaked from the pngs.... I guess that's not best practice, but I had no way to do it otherwise....
