### ISSUE TITLE
FR: start offset

### ISSUE THREAD

**Issue by bltzr** [ossia/score#213]
it would be nice to have a start offset
i.e. it would start from a certain point, as in "play from here", but when pressing play
this would be particularly useful:
- when rehearsing a section of a scenario (when you repeatedly want to start from the same time)
- when starting the execution remotely through the network (at some other place than the beginning of the scenario, which is not possible for now, to the best of my knowledge)

another option (but is it really different) would be to send a "startfrom" (or whatever message) with the start time (in ms ?), and it would start from there (e.g. like the "seek" message to [sfplay~] in Max)

would that make sense ?
@jcelerier @blueyeti @jln- @theod @reno- @avilleret @himito ?

**Comment by jcelerier** [comment]
Isn't it just a "time bar" ?

**Comment by avilleret** [comment]
not really a time bar I think, something more like an 'in point' or 'start point'
and yes this feature makes sense to my eyes

**Comment by bltzr** [comment]
related to #241

**Comment by bltzr** [comment]
one part of it has been done with the ```transport``` parameter
the other one really isn't different from #241 so I'm closing this one
