### ISSUE TITLE
speed values shouldn't be stored

### ISSUE THREAD

**Issue by bltzr** [ossia/score#214]
for now, the speed value is permanent (stays at its value once changed, across successive executions), I don't think that's a good idea
IMHO speed is something you want to change at execution only, it shouldn't be permanent
(though I think it's nice that it's accessible as an address (i.e. it could be mapped from within i-score, e.g.), but then it should behave like Jamoma's messages
if one wants to have a constraint read more quickly, the easiest/most consistent way to do that is to change its duration

opinions ? 
@jcelerier @blueyeti @jln- @theod @reno- @avilleret @himito ?

**Comment by jcelerier** [comment]
so for instance when "stop" is pressed, the values should revert to the default ?

**Comment by bltzr** [comment]
I'd say yes
for me, speed is something you change on the fly when you have some ad hoc reason for... 
leaving it permanent is confusing (because then the X-size/duration proportionality is locally broken)
