### ISSUE TITLE
blank scenario should be discarded when loading another one

### ISSUE THREAD

**Issue by bltzr** [ossia/score#216]
leaving it in place is useless....
and once using i-score for a production, this is what happens 99% of the time (there is a useless tab on top)
no big deal, but mentioning it...

**Comment by jcelerier** [comment]
Should work in the latest commit, can you test ?

**Comment by bltzr** [comment]
No I can't :-p
(can't build, see gitter)

**Comment by bltzr** [comment]
works, thanks !
