### ISSUE TITLE
Remove play time indicators after playthrough.

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#219]

**Comment by jcelerier** [comment]
Fixed by 8bcdd07c96bc6f1e5d781d151f82d409be2ae4f5

**Comment by bltzr** [comment]
nope, they sometimes still show up

**Comment by jcelerier** [comment]
damn, do you have a save file where they show up ?

**Comment by bltzr** [comment]
yes, for example this one - it doesn't always stay, but often does (I'm using space bar and enter)
[times.scorejson.zip](https://github.com/OSSIA/i-score/files/310135/times.scorejson.zip)

**Comment by jcelerier** [comment]
I played it about twenty times and didn't get an indicator staying :(
Maybe it's OS X only... I'll try later.

**Comment by jcelerier** [comment]
I also don't get them staying in OS X ...

**Comment by bltzr** [comment]
maybe I'm damned

**Comment by jcelerier** [comment]
I disabled them temporarily they were eating a lot of resource... I'll have to find a better way to do it.
