### ISSUE TITLE
Crash at quit

### ISSUE THREAD

**Issue by lossius** [ossia/score#22]
With 0.3a12 I get the following crash when I quit i-score:

https://gist.github.com/lossius/d8dab9355c8940d11fa0

The steps here are simple and reproducible:
1. open i-score
2. Attempt to connect to Max (still doesn't work with Max at my laptop)
3. Quit i-score, and I say no when asked if I want to save.

**Comment by jcelerier** [comment]
this should have been fixed in 0.3a13
