### ISSUE TITLE
i-score's icon is gone on OSX

### ISSUE THREAD

**Issue by bltzr** [ossia/score#222]
this is how it shows up in the finder/dock, etc...
![noicon](https://cloud.githubusercontent.com/assets/113982/15971624/5ffea5a0-2f3a-11e6-8b7a-a48cf13f38af.png)

**Comment by jcelerier** [comment]
this should be fixed.

**Comment by bltzr** [comment]
well... sorry, but apparently it isn't... I pulled and rebuilt... should I do anything else ? Like cleaning the folder or so... ???
Astonishingly, the icon file is in the .app bundle:
<img width="636" alt="package_content" src="https://cloud.githubusercontent.com/assets/113982/15999589/07cc2c36-3147-11e6-8bde-39f0e6f2800e.png">

**Comment by bltzr** [comment]
I rm'd the build-release folder, and still no icon...
as long as it doesn't happen on the public build, this is not so much of a problem, though...

**Comment by jcelerier** [comment]
indeed, I had forgotten to push :p

**Comment by bltzr** [comment]
maybe that's why :-p

**Comment by bltzr** [comment]
seems it works now
