### ISSUE TITLE
min and max bounds should be off by default

### ISSUE THREAD

**Issue by bltzr** [ossia/score#223]
there really isn't much sense for the current default durations

**Comment by jcelerier** [comment]
I think that this needs discussion with @OSSIA/core

**Comment by bltzr** [comment]
oh yeah, sure ! let's discuss it:

my arguments for them being set off by default: 
- IMHO adding a trigger means that one doesn't know in advance when the event will be triggered - adding bounds to this indefinite duration is a further precision, and not always (or even most frequently)  needed
- I don't see any reason for having arbitrary durations by default

arguments I see for them being on:
- this is two clicks less to do when one wants to add bounds
- this prevents parts of the scenario to stall forever if someone forgot to trigger the trigger, or it something went wrong

though, I think that, in a convention over configuration perspective, they should be left off

**Comment by cbossut** [comment]
Agreed

Le samedi 11 juin 2016, Pascal Baltazar notifications@github.com a écrit :

> oh yeah, sure ! let's discuss it:
> 
> my arguments for them being set off by default:
> - IMHO adding a trigger means that one doesn't know in advance when
>   the event will be triggered - adding bounds to this indefinite duration is
>   a further precision, and not always (or even most frequently) needed
> - I don't see any reason for having arbitrary durations by default
> 
> arguments I see for them being on:
> - this is two clicks less to do when one wants to add bounds
> - this prevents parts of the scenario to stall forever if someone
>   forgot to trigger the trigger, or it something went wrong
> 
> though, I think that, in a convention over configuration perspective, they
> should be left off
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/OSSIA/i-score/issues/223#issuecomment-225361211, or mute
> the thread
> https://github.com/notifications/unsubscribe/ADiyF0_oUHWcHEniA_2lwTfOmtusQAt0ks5qKrYSgaJpZM4IzH0k
> .

## 

Clément Bossut
