### ISSUE TITLE
Allow to play only a sub-scenario

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#227]

**Comment by bltzr** [comment]
👍 +1

**Comment by bltzr** [comment]
How is this supposed to work ?
I tried different ways, but it always played the whole (parent scenario)...

**Comment by jcelerier** [comment]
it's not really possible to play just a sub-scenario. What happens is that you select its parent constraint and press "Play Constraint" on the right click menu. It will only play the constraint and its processes.
Do you think that it would be desirable to automatically do this when in full-view on another constraint ?

**Comment by bltzr** [comment]
yes, that would make sense to do so in full view - at least that's what I've been intuitively expected to happen...
though, I guess in most cases it would be necessary to compile the previous states of parameters, as when "playing from here"

**Comment by bltzr** [comment]
Let's not do that! (About the compilation)
After giving it some  thought I think it would be best to keep it simple stupid, and just play the sub scenario 
Though I guess it should play the start and end states of the parent constraint, in order to stay consistent with the way it works when the main scenario is in full view - is that a problem?

**Comment by jcelerier** [comment]
no, this makes the most sense. I would have found it very weird and unintuitive to also compile the previous (not visible) states. It should just behave like it would for the "global" scenario.

**Comment by bltzr** [comment]
does this still really need testing ? I guess there's some further work to do before it only plays the sub-scenario, right ?

**Comment by jcelerier** [comment]
it should already be commited

**Comment by bltzr** [comment]
it works, but there's a bug: the sub-states and sub-processes are not executed - compare both cases (look at the slider in Max on the left):
![works](https://cloud.githubusercontent.com/assets/113982/16055918/78a910fe-3273-11e6-9e40-50a79bd48cb2.gif)
![worksnot](https://cloud.githubusercontent.com/assets/113982/16055921/7c31e99e-3273-11e6-923f-b626aa276a88.gif)
on the second one, only the start state from the parent constraint is executed

**Comment by jcelerier** [comment]
howdy :)

**Comment by bltzr** [comment]
http://i.imgur.com/4brc1t7.jpg

**Comment by jcelerier** [comment]
@bltzr could you retry ? I am unable to reproduce :( for me it sends correctly whatever the hierarchy level I'm in (even if I'm zoomed in the automation)

**Comment by bltzr** [comment]
I am unable too... maybe i-score was in a bad mood... or I was tired... or there was a bad astral alignment... closing the issue
