### ISSUE TITLE
change function of sequence button 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#230]
Since a recent commit, and on @blueyeti 's suggestion, creating sequences now works with horizontal magnetism - this is **very cool** !

Though, now, the previous way it was working doesn't make much sense anymore... and is even sometimes a little bit of a nuisance...

So, what if we changed the function of this button to enabling/disabling the horizontal magnetism for creating sequences ?
When disabled, then there would be no way to create sequences (which allows to keep various events aligned without having interpolations), and when enabled, this would do just as it does currently.

If we do so, I guess we should then also change the behavior into being a kind of toggle.

Also, currently the shortcurt for this function is shown as being:
- Space in the Edit menu
- some random character on the tooltip (hint) of the button
  I guess that's because it's triggered by the shift modifier, and I guess causes some problems...
  Though, if we go as I propose, we won't need it anymore to be triggered by a modifier. It could be any other (normal) key. What about 'q' ? (As in seQuence)

Opinions ?

**Comment by jcelerier** [comment]
Ok

**Comment by jcelerier** [comment]
since there is no sequence button anymore, do you think this should stay open ?

**Comment by jcelerier** [comment]
(considering that there is a user setting to handle "So, what if we changed the function of this button to enabling/disabling the horizontal magnetism for creating sequences ?")

**Comment by bltzr** [comment]
well I don't think this is worth having a button for (the user setting to handle), that can stay in the preferences...
