### ISSUE TITLE
Try to find a way to merge "Create Curves" and "Interpolate States" 

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#232]

**Comment by bltzr** [comment]
if there are already values in the end and/or start states, they are used as extrema for the curve
if one or two of them is not present, range/min is used for the start value and range/max for the end value (maybe we could also use the alt modifier to invert this behavior ? just thinking out loud....)
would that make sense ?

I was also wondering that maybe curves could be created by drag'n'dropping addresses from the explorer to a constraint... what do you think ? Then the current value would be used at the end (or, if alt pressed, as the start, the end being then set to the range/min value ???) 
even, maybe, ideally, doing so would create a "ramp", i.e. at execution time, the start value would be queried when starting the ramp.

What do you think ?

**Comment by jcelerier** [comment]
> I was also wondering that maybe curves could be created by drag'n'dropping addresses from the explorer to a constraint... what do you think ? Then the current value would be used at the end (or, if alt pressed, as the start, the end being then set to the range/min value ???) 

yes, that would certainly be the best way to do this.

Need to discuss it more for the "use the start / end state according to alt" thing.

**Comment by bltzr** [comment]
> Need to discuss it more for the "use the start / end state according to alt" thing.

Sure, that was just a passing idea I grabbed on the fly

**Comment by bltzr** [comment]
maybe that could be just one button for both ? 
if there is content in the states, automations/interpolations are created for differing values ?
if it's on a constraint with empty states, then automations/interpolations (and corresponding states) are created for the chosen addresses in the device explorer.
What if some addresses are chosen in the device explorer, that are not in the states ? I'd say they are added the same way. Would that make sense ?

Maybe we could merge the snapshot and update state buttons in the same way ?

Opinions @OSSIA/users ?

**Comment by jcelerier** [comment]
> I was also wondering that maybe curves could be created by drag'n'dropping addresses from the explorer to a constraint...

since that's now possible, I propose instead removing the "create curves" button entirely (nobody seems to ever use it anyways).

**Comment by bltzr** [comment]
I agree

**Comment by jcelerier** [comment]
removed for quite some time
