### ISSUE TITLE
allow to remove points in curves

### ISSUE THREAD

**Issue by bltzr** [ossia/score#239]
currently when removing a point, it removes both adjacent segments
IMHO, it should just work reversely to how it does when adding points: it should just remove the point and merge both segments in one
if there was coefficients in segments, only the previous one is kept, the later segment's coef is discarded (that's a proposal... we could also makes a mean of both, I don't know.... ?)

opinions ?

**Comment by jcelerier** [comment]
question: what is the expected behaviour when removing the first / last point ?

**Comment by jcelerier** [comment]
I did something, not sure I'll have time to go much further.

**Comment by bltzr** [comment]
this works, except when trying to remove the first point after the start state, or the last before the end state (in which case the segment is removed)
