### ISSUE TITLE
Add "Add Trigger" / "Add condition" button

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#240]

**Comment by bltzr** [comment]
👍

**Comment by jcelerier** [comment]
This could be done by adding actions metadata in ScenarioActions.hpp and then creating the actions to ObjectMenuActions.cpp.
There could be two ways to implement the feature : Select an object, click, and a popup appears with the trigger / condition to add, or drag from the button to an object. Maybe both ways could be possible.

**Comment by jcelerier** [comment]
done
