### ISSUE TITLE
i-score crashes when a lot of elements are pasted

### ISSUE THREAD

**Issue by bltzr** [ossia/score#243]
In my case, I'm trying to encapsulate the whole content of a 9.5MB scenario (weight in JSON format) into a scenario inside of a loop pattern - when pasting elements from the contextual menu, i-score freezes for a while, and then crashes...
crash log: https://gist.github.com/bltzr/06cfe08ba34d2bc8f3515a7aaf40048c

**Comment by bltzr** [comment]
maybe though a simpler way to do this would be to give a way to actually encapsulate elements ?
i.e. changing their place in the scenario hierarchy without deleting/recreating them... ??

**Comment by jcelerier** [comment]
> maybe though a simpler way to do this would be to give a way to actually encapsulate elements ?

from a code point of view, this would absolutely not be simpler :package: 
Could you share the scenario that you are trying to copy - paste ? It shouldn't crash in any case.

**Comment by bltzr** [comment]
that's the one I shared with you (Nebula.scorejson):
- select all elements in the scenario
- create a bigger constraint than the size of the selected elements (e.g. 30')
- create a scenario process to this constraint
- fullView into it
- paste elements
- die !

**Comment by bltzr** [comment]
That might be a feature request for a future version of i-score (for when we have a team of 20 developers and as many test-writers :-p ) but this (and also de-encapsulating) would make a lot of sense.... just saying... should I create an issue ? (or is this really too complicated for any foreseeable future ?)

**Comment by jcelerier** [comment]
could you test again with a big scenario ? I fixed some things underneath that might have fixed this indirectly. I tried to make it crash by copying a few dozen of elements and it did not crash.

**Comment by bltzr** [comment]
problem is that my big scenario is in the old format, so it's difficult to test it (unless I'm doing another big one... but it was quite big, and thus not so easy to redo...)

**Comment by bltzr** [comment]
I've been copying a lot of stuff from @pach 's score the other day, and had no problem. So closing this issue until it (hopefully doens't) happen again
