### ISSUE TITLE
crash when loading

### ISSUE THREAD

**Issue by pach** [ossia/score#245]
crash when loading a file which has been made on a version compiled by Pascal (0.69) and load on a version I did just compile (with no jamoma installed on my mac).

https://gist.github.com/pach/08abeedf682c781dae23b1a7441b5f0b

**Comment by jcelerier** [comment]
does this still happen ?

**Comment by jcelerier** [comment]
> Debug: Warning: could not load device "Max" (DeviceSettingsSerialization:97, void Visitor<Writer<JSONObject> >::writeTo(Device::DeviceSettings &))

Yep, that's because of the absence of Jamoma.
