### ISSUE TITLE
crash on play (after a tiny few)

### ISSUE THREAD

**Issue by pach** [ossia/score#246]
https://gist.github.com/pach/53daa3b6ee18c01e46e9b44a392899f7

**Comment by pach** [comment]
Ok, compris.
Le premier node contenait encore un tuple que j'ai passé en 3 valeurs en sous-branches pour faire une interpolation.
Donc semble crasher quand envoi des données qui ne sont pas dans l'arbre de device.

**Comment by jcelerier** [comment]
J'ai essayé de lire le scénario sur plusieurs machines mais ça ne crash pas chez moi :-(

**Comment by jcelerier** [comment]
Je ferme car je n'arrive toujours pas à reproduire.
