### ISSUE TITLE
allow to create a sub-scenario by dragging a scenario file into the scenario editor

### ISSUE THREAD

**Issue by bltzr** [ossia/score#247]
according to @jcelerier 
https://github.com/OSSIA/i-score/commit/37f3fcc99d7aa6744ba7bf08a7ea1e823f3a9c5f#commitcomment-17984537
makes it relatively easy to do.

**Comment by bltzr** [comment]
is this  it "relatively easy" easy enough that it can be considered doable in a 1.1. scope ? (adding the milestone to force it just a little bit - feel free to remove it :-p )

**Comment by jcelerier** [comment]
yes, that one is easy, except one point that has to be decided : how are handled devices that are in the dragged score ? are they added, merged, to the existing devices ? ignored ? ignored if they exist ?

**Comment by bltzr** [comment]
I'd say merged if they are already here, or added if they aren't

**Comment by jcelerier** [comment]
this has worked for some time with .scenario / .layer files (see the library)
