### ISSUE TITLE
bug with string and OSC device

### ISSUE THREAD

**Issue by pach** [ossia/score#248]
http://im.ezgif.com/tmp/ezgif-2313108959.gif
http://im.ezgif.com/tmp/ezgif-630672048.gif

les chaines de caracteres se fixent à none des qu'un osc device envoi une chaine de caractere sur un noeud string. En parrallele elle n'envoi que des none des que l'on sauve un projet.

**Comment by bltzr** [comment]
en fait, on dirait qu'il y a un problème dans le plugin OSC (de Jamoma, I guess) parce que la même chose marche en Minuit...
@theod tu saurais nous dire en gros où ça pourrait coincer ?
(bon, j'imagine que c'est un pb d'API, mais c'est ptêt plus simple de reporter le bug ici..)

**Comment by bltzr** [comment]
une précision qui me fait me dire que c'est peut-être pas finalement du côté de l'API que ça se passe : en fait, le problème n'apparaît que pour un noeud qui a été chargé depuis un fichier.
Lorsque l'on crée un noeud dans i-score, il marche jusqu'à ce qu'on ferme le scénario. À la prochaine ouverture, il ne marche plus.

**Comment by bltzr** [comment]
et, lorsque j'ouvre le scénario avec ce param (qui ne marche plus), si j'en crée un nouveau (toujours string), il marche bien...

**Comment by bltzr** [comment]
works now
