### ISSUE TITLE
Navigation keyboard shortcuts

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#249]
To allow navigating in the elements of a sequence / timenode by keyboard.

e.g. : 
Left - Right : navigate between constraint - state (end state, start state)
Up - Down : navigate between the states of a timenode

**Comment by bltzr** [comment]
cmd/ctrl-up/down : go up/down one level of hierarchy (i.e. change which constraint is in fullView)

**Comment by jcelerier** [comment]
This can be done by using the actions defined in ScenarioActions.hpp:197 to trigger something in ObjectMenuActions.cpp.
The actions should certainly be added to a sub-menu, such as Object > Selection (see ObjectMenuActions::makeGUIElements). Inspiration can be taken from the existing actions such as Cut, Copy... 

For the hierarchy up-down feature, the current logic is in AddressBarItem and ClickableLabelItem.

**Comment by bltzr** [comment]
still a good idea IMO (not ultra-high priority though)

**Comment by jcelerier** [comment]
done
