### ISSUE TITLE
[BUG] state don't send data on trigger

### ISSUE THREAD

**Issue by pach** [ossia/score#250]
A manual trigg doesn't update and send the node attach to the state which is trigged. 
Need a second state a short while after to trig.
http://www.giphy.com/gifs/l46CgIgFFlyofoJFK

**Comment by pach** [comment]
donc pour clarifier. Un trig sur un nodetime n'envoi pas l'état de ce meme nodetime.

**Comment by jcelerier** [comment]
Ça devrait être réglé, voilà le nouveau comportement : 

http://webmshare.com/JAZGJ

**Comment by bltzr** [comment]
hé @jcelerier c'est fini, ce prosélytisme pour Firefox, tu veux pas mettre des GIFs comme tout le monde ?
