### ISSUE TITLE
[BUG] play from here doesn't work with trigger 

### ISSUE THREAD

**Issue by pach** [ossia/score#253]
Lorsqu'on tente de jouer un scenario depuis le milieu (play from here ou raccourci p) il ne rejoue que le timenode sur lequel on clic.
Visiblement du au fait que j'ai des triggers dans mon scénario.

**Comment by bltzr** [comment]
NB : ça ne le fait pas si les triggers ont une max bound - donc je suppose qu'il se dit que le trgger n'ayant pas été déclenché, ça ne doit pas être joué...

**Comment by jcelerier** [comment]
@bltzr tu peux me dire (sans oublier `git submodule update --init`) si ça casse rien ailleurs et si ça fait un comportement "cohérent" ? en gros j'ai fait un patch qui fait "comme si" toutes les contraintes souples jusqu'à l'endroit ou on fait play from here étaient en fait rigides.
