### ISSUE TITLE
Play / stop via network

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#263]
Try to have them go through the Qt event loop to prevent @bltzr  problems

**Comment by jcelerier** [comment]
@bltzr could you test with the latest commit on master ? fcd49df8ab9614f3acd9ba4bfdf69bdc079de739

**Comment by bltzr** [comment]
I just tried, and now, sending /play 0 or /play 1 via network does just the same: it toggles between play and pause - this is embarrassing...

**Comment by bltzr** [comment]
BTW, what was the initial problem again ? I remember there was an error message when stopping via network... was there anything wrong with play ? I don't remember...
anyhow, now, there IS a problem with play :-)

**Comment by jcelerier** [comment]
Should be ok now :

![output](https://cloud.githubusercontent.com/assets/2772730/17293340/0927ed5c-57f0-11e6-8fb2-f152b3eab35e.gif)

**Comment by bltzr** [comment]
I confirm it is indeed OK, thanks !
