### ISSUE TITLE
[crash] when playing mapping process

### ISSUE THREAD

**Issue by pchdev** [ossia/score#268]
A71 version
see enclosed files for report & test files :-)

pchd

[mapping_crash.zip](https://github.com/OSSIA/i-score/files/439638/mapping_crash.zip)

**Comment by jcelerier** [comment]
Ah, this was fixed in the current dev branch (https://github.com/OSSIA/i-score/tree/refactor/network). I still have some bugs to fix on it but I'll try to get a release going with it by mid-september.

**Comment by jcelerier** [comment]
@pchdev I made a release, if you have time please try :)

**Comment by pchdev** [comment]
cool! thanks, i'll try it out!

edit: it's working!

**Comment by pchdev** [comment]
dunno if you saw my edit, the bug is fixed as far as I'm concerned
