### ISSUE TITLE
i-score can't co-exist with Jamoma 0.5.7

### ISSUE THREAD

**Issue by lossius** [ossia/score#27]
It seems that if Jamoma 0.5.7 is installed on the computer, i-score starts looking for jamoma-related lib files in the wrong place, and crash.

Jamoma 0.5.7 installs header files, libraries and extensions into /usr/local/jamoma

**Comment by jcelerier** [comment]
Relevant Jamoma feature branch : https://github.com/jamoma/JamomaCore/pull/383

**Comment by theod** [comment]
I close it as the jamoma/JamomaCore#383 is fixed

**Comment by jcelerier** [comment]
the fix hasn't been merged so it still won't work :(

**Comment by jcelerier** [comment]
i-score won't look for jamoma libs anymore
