### ISSUE TITLE
Some problem with play from here

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#279]
@pchdev

**Comment by bltzr** [comment]
I think we should discuss it… what’s wrong on your side ?

**Comment by pchdev** [comment]
yes, it worked fine on my score few days ago, but now it seems the only way to make it work is inside a sub-scenario, starting from certain states, otherwise it gets stuck. I'll try to test some more to get a more precise feel of the error pattern. I'll send you the score as well

**Comment by bltzr** [comment]
that sucks !

**Comment by jcelerier** [comment]
ugh, I think that at some point there was the same problem with Georges Gagneré's work.

If you try to do "play from here" multiple times from always the same spot, does it always work (or not work) ?

**Comment by pchdev** [comment]
yeah, multiple times does not seem to change anything 
so here's the thing : I have 3 main sub-scenarios, it works fine on the first one, not at all on the second, and a little on the third :) (just before all conditions)

[quarre_main_backup.scorejson.zip](https://github.com/OSSIA/i-score/files/491148/quarre_main_backup.scorejson.zip)

**Comment by pchdev** [comment]
.. and it also makes sense about Georges, because we had the same scene/sub-scenario structure actually!

**Comment by jcelerier** [comment]
okay, it seems that "play from here" is broken as soon as there is a condition.

**Comment by jcelerier** [comment]
a quick fix could be to assume that conditions "before" play-from-here are true, but this means that two parallel branches would both execute... would you be okay with this ?

**Comment by bltzr** [comment]
I think that dealing with conditions with play from here are a pain in the ass anyway…
the only solution I can imagine would be to be able to set default behaviors for each condition when « played from here », but that’s maybe stretching things a little bit too far…
I think we discussed that previously with @theod, but I don’t remember the conclusions … (if there were any…)

**Comment by jcelerier** [comment]
>  set default behaviors for each condition

yeah, that's the other option. it's a bigger change but allows more flexibility...

**Comment by jcelerier** [comment]
okay, that's not that hard to do.
There will be three options : "always true, always false, evaluate the condition"/

**Comment by reno-** [comment]
Adding a default behavior for condition seems to be a nice addon, as it might be use for different cases :

Play from here
Trigger a condition after a timeout

**Comment by jcelerier** [comment]
done, it will be in the next release :)
