### ISSUE TITLE
Drawing issue when i-score window is large

### ISSUE THREAD

**Issue by lossius** [ossia/score#28]
<img width="2560" alt="screen shot 2015-09-11 at 18 29 14 2" src="https://cloud.githubusercontent.com/assets/38478/9820287/2b9e27ee-58b3-11e5-9789-d1aa06dfe46e.png">

I get a vertical coloured line in the right section of the scene section.

**Comment by jcelerier** [comment]
Yep, this is the last timenode / event of the scenario.

But there were talks of removing it. @nvuaille @bltzr @lossius @blueyeti @theod ?

**Comment by theod** [comment]
this is fixed
