### ISSUE TITLE
Values in a limited set should be shown in combo boxes in the device explorer

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#289]
instead of allowing to type anything

**Comment by bltzr** [comment]
we can use the range attribute for this (with a list of values instead of a range)

**Comment by jcelerier** [comment]
yes, that's already the case, but the problem is to only allow the user to select what's in the range. e.g. if the range is ["foo", "bar", "baz"] instead of a text input there should be a combo box where you can only choose the correct values.

**Comment by jcelerier** [comment]
(in case this was not clear, I'm referring to the input here in `value`: ![range](https://cloud.githubusercontent.com/assets/2772730/26162849/27df4f62-3b28-11e7-8d98-07ef98e8a737.png)  )

**Comment by jcelerier** [comment]
## To do : 

In the DeviceExplorer{Model,View} (and certainly also the StateInspectorWidget), delegates that match the various data types should be created, following this tutorial : http://doc.qt.io/qt-5/model-view-programming.html#a-simple-delegate

This could also be used to make a specific delegate for the boolean type that would fix #89 and special delegates for the range that would fix #87.

**Comment by jcelerier** [comment]
Adding this one to you @RobinMontferme as it touches some fun Qt stuff and the device explorer to change you of the central view woes ;p

**Comment by jcelerier** [comment]
done in addressitemmodel - leaving the device explorer free for any input as sometimes it may make sense to control the values outside of the set
