### ISSUE TITLE
handling of generic values from minuit

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#298]
they are represented as a tuple with 1 value, this kind of values should be useable wherever we need a normal value (int, float, etc).

**Comment by bltzr** [comment]
I'm not sure I get it... generic values are supposed to be absolutely anything,  including symbols, spaces, etc...

**Comment by jcelerier** [comment]
there are two different things : 

* generic values : a value for which the type does not matter. so it can be an int, a float, a string, etc. & change type over time.
* byte arrays : a value for which the type is not known. basically, it's unuseable unless you know how the bytes are arranged in memory (so this would only make sense in a javascript script for instance since a curve would be unable to determine if the value is an int or a float or something entirely different).

Currently, generic values (i.e. values without a given type) received from minuit (that is, with the minuit type `generic`) are assigned to the first element of a tuple since that's the only way to have an element with a varying type. But they are not byte arrays, which are real "anything" values corresponding to OSC blobs.

**Comment by bltzr** [comment]
OK, thanks for the explanation

**Comment by jcelerier** [comment]
let's say that we'll reopen this if somebody wants to use minuit again
