### ISSUE TITLE
Problem with colors of events during execution

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#299]
When there are multiple events on a timenode without trigger, the first one is grayed and the others are yellow

**Comment by bltzr** [comment]
that doesn't seem to be the case anymore, 
![zocizn](https://cloud.githubusercontent.com/assets/113982/26163087/dbac2aa6-3b28-11e7-99d0-37ee09a26aef.png)

though, when there is a trigger, only the first one (and the vertical bar) is yellow 
![aoc](https://cloud.githubusercontent.com/assets/113982/26163073/c8aa22b4-3b28-11e7-94e8-62d48e6bdcb5.png)

**Comment by bltzr** [comment]
sorry, false alarm, my scenario was wrong

**Comment by jcelerier** [comment]
?? this is still a bug.

**Comment by bltzr** [comment]
yes it's still a bug, I just got confused when creating my scenario: created a very small constraint instead of a timeNode - please ignore

**Comment by jcelerier** [comment]
seems like it's fine now
