### ISSUE TITLE
Minuit device is not released properly

### ISSUE THREAD

**Issue by lossius** [ossia/score#30]
Steps to reproduce:
1. Start Max and open j.minuit_device.maxhelp
2. Start i-score
3. Create a new device with default settings, connecting to Max
4. Make a second i-score (from File > New). leave it empty for the time being.
5. Close the first document, saving or not doesn't matter
6. Try to set up a new device in the second (and still open) document with default settings.

Result: you get a warning that this device exists already.

**Comment by jcelerier** [comment]
Fixed in dev
