### ISSUE TITLE
Alt for duplicate ?

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#302]
With the "Plus" cursor

**Comment by bltzr** [comment]
yes, please !

**Comment by jcelerier** [comment]
From another issue, alt is used to create a new event instead of a new state, so we have to find another key...

**Comment by pach** [comment]
alt-maj?
but alt is traditionnaly (on mac, I don't know on windows) the duplicate function. So make sense.

**Comment by bltzr** [comment]
I agree that, on Mac, alt is used for duplicating (what is it on Win and Nux ?), so IMHO if we want to change something, maybe that would rather be for creating a new event (shift ?)

**Comment by bltzr** [comment]
another option would be to have another + button on the bottom, that would allow to create a new event (and a visible condition ?)

**Comment by jln-** [comment]
mm… I’d rather test and see how it works with another shortcut than adding another + button.

**Comment by bltzr** [comment]
okay

**Comment by pach** [comment]
do agree on alt for duplicate and shift for new event. That's the one which makes more sense for me.

**Comment by bltzr** [comment]
shift is used for other things, as mentioned in #449 
I think we should solve this one way or the other before the release, hence 1.1
(I'm also adding this for Lyon)

**Comment by jcelerier** [comment]
I think that it's enough to have ctrl-c / ctrl-v to duplicate things, don't think it's such a common operation to warrant two different shortcuts

**Comment by bltzr** [comment]
Alt for duplicating Is pretty common, though, at least on MacOS

**Comment by bltzr** [comment]
OK I just saw it's used for scale mode, please disregard my previous comment
