### ISSUE TITLE
WebSocket protocol does not work in release builds

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#303]
Relevant message

    ":1 module \"QtQuick\" is not installed\n"

- [x] Fix it on OS X
- [x] Fix it on Linux
- [x] Fix it on Windows

**Comment by pchdev** [comment]
thanks for the release!

**Comment by jcelerier** [comment]
two issues with this on linux : 

- incompatible openssl version
- module qtquick is not installed (this also breaks js !)
