### ISSUE TITLE
[bug] gigantic lag with a76 (osx)

### ISSUE THREAD

**Issue by pchdev** [ossia/score#306]
heï !

almost unable to draw constraints and actually do anything, it's all freezy :-)
rest of the menus looks fine, its just the timeline window it'd seem

pierre

**Comment by bltzr** [comment]
seems to be OK on my side… what OS version are you on ?

**Comment by jcelerier** [comment]
same, I can't reproduce :( if you want we can see tomorrow ?

**Comment by pchdev** [comment]
@bltzr the captain
@jcelerier yes, i'll try to come by and show you tomorrow

**Comment by bltzr** [comment]
too bad I didn’t try before updating just right now

**Comment by bltzr** [comment]
though I just noticed (in Sierra) that a76 drains very high on the CPU (activity monitor says more than 100%), while doing nothing at all (just created a few events and states in it, and execution has not been started)
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/113982/20286607/d3c2a848-aac7-11e6-9e69-d33dfa64ea21.png)
in the meantime a75 (audio-version) sits nicely at 15%

**Comment by bltzr** [comment]
sorry that was the energy monitor... still a76 is much much higher than a75-audio, both doing nothing at all 
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/113982/20286691/74bd7c1e-aac8-11e6-9fe2-08c14dd5e844.png)
a76 actually fluctuates between 30 and 96

**Comment by jcelerier** [comment]
I wonder if it's related to this : https://bugreports.qt.io/browse/QTBUG-44228 because I have the same results on OS X while i-score gently sits at 1-2% CPU on linux & windows...

**Comment by pchdev** [comment]
ok! thxthxthxthxhthx

**Comment by jcelerier** [comment]
Cool ! 
Note: now it's opengl that does the rendering on OS X so there _may_ be some graphical glitches sometimes (but it should be smoother on older computers / retina resolution), so please make bug reports if there are weird things.

**Comment by jcelerier** [comment]
@bltzr I'd be interested to see the processor usage on your computer with a77 if you have a minute.

**Comment by bltzr** [comment]
it sits rather consistently at about 10% for a while after startup
then goes down to between 1.5 and 4.5 after a while
then up to 8% or so after I add a couple objects
then back down to 2%

I think we can say this is fixed

thanks

**Comment by jcelerier** [comment]
cool !

**Comment by jcelerier** [comment]
(other very intimate question : do you have a retina screen ?)

**Comment by bltzr** [comment]
I usually don't answer publicly to such intimate questions... but yes
