### ISSUE TITLE
build error on Ubuntu 16.10 : fmt/format.h not found

### ISSUE THREAD

**Issue by avilleret** [ossia/score#307]
On Ubuntu 16.10 with : 

~~~~
$ git describe --always 
6b453a8
~~~~

I have :
~~~~ 
../API/3rdparty/spdlog/include/spdlog/fmt/fmt.h:25:24: fatal error: fmt/format.h: Aucun fichier ou dossier de ce type
~~~~

while there is a `format.h` here : `./API/3rdparty/spdlog/include/spdlog/fmt/bundled/format.h`

any hint ?

**Comment by avilleret** [comment]
This helps :

```
git clone https://github.com/fmtlib/fmt.git
mkdir build-fmt
cd build-fmt
cmake ../fmt -GNinja 
ninja 
sudo ninja install
```

But I'm not sure you want to deal with dependency in this way.

**Comment by jcelerier** [comment]
did you do `git submodule update --init --recursive` after `git pull` ? fmt should be here : `i-score/API/3rdparty/fmt/fmt/format.h`

Besides, this seems to be fairly common, do you have an idea of where it could make sense to put ? in the readme ? the wiki ?

**Comment by avilleret** [comment]
shame on me, I forgot the `--recursive` flag....
thanks @jcelerier to take time to explain life to newbie :-)

**Comment by jcelerier** [comment]
haha honestly I wish that git did that by default...

**Comment by avilleret** [comment]
let's do it with alias : 
`git config alias.update "!(git pull && git submodule update --init --recursive)"`
then `git update` will do everything in one shot
