### ISSUE TITLE
build error on Ubuntu 16.10 with Boost 1.62

### ISSUE THREAD

**Issue by avilleret** [ossia/score#308]
Following https://github.com/OSSIA/i-score/wiki/Build-and-install#ubuntu-1610 ends up with https://gist.github.com/avilleret/d9e3fac4272f26dd7f0c7abb510be1b7

Still on Ubuntu 16.10 and at 6b453a8

**Comment by jcelerier** [comment]
I think that it's the same problem, the oscpack submodule does not seem up-to-date
