### ISSUE TITLE
can't create bifurcations from newly created sequence

### ISSUE THREAD

**Issue by bltzr** [ossia/score#309]
as demonstrated on the gif below, it is not possible to create bifurcations from a newly created sequence - one must first create another (bifurcating) constraint 
![bugsequences](https://cloud.githubusercontent.com/assets/113982/20286465/24c36a12-aac7-11e6-8378-a412ab055e9e.gif)

I believe this comes from the sequence toolbutton ( [...] next to the play toolbbutton) staying on once a sequence segment has been created...
![bugsequences2](https://cloud.githubusercontent.com/assets/113982/20286468/2990c670-aac7-11e6-9602-6caab66c19ec.gif)

though, now that sequences are created automatically when aligning constraints upon creation, maybe we don't need this button anymore ?

**Comment by jcelerier** [comment]
> I believe this comes from the sequence toolbutton ( [...] next to the play toolbbutton) staying on once a sequence segment has been created...

yep, seems to be it. It works if you focus another window and re-focus i-score so it's certainly something that is not reset correctly ; checking asap.

**Comment by pchdev** [comment]
tested, and its ok for me

**Comment by bltzr** [comment]
OK for me too, this can be closed
