### ISSUE TITLE
State at time = 0 is not triggered

### ISSUE THREAD

**Issue by lossius** [ossia/score#31]
Steps to reproduce:
1. Start Max and j.minuit_device.maxhelp
2. Tweek bitdepth and sample_ration settings in the mydegrade model.
3. Start i-score and make a new constraint.
4. From the inspector at the left side, choose the bitdepth and sample_ration parameters and drag them over start of the constraint, so that we get an initial state that is displayed as a larger white circle.
5. In max, tweek bitdepth and sample_ration to some other settings, and back in i-score drag this over the end of the constraint, so that we get a second state there.
6. Extend the constraint with yet another point, tweek settings i Max yet again, and drag in. Make sure that the settings of this third state differs from the first (and the second)

i-score should now look like this:

<img width="1344" alt="screen shot 2015-09-11 at 18 45 10" src="https://cloud.githubusercontent.com/assets/38478/9820601/3b2a3278-58b5-11e5-9b72-366da11e527b.png">
1. Start playback in i-score and observe Max.

Result: The 2nd and 3rd states gets triggered as expected, but with the first one nothing happens.

**Comment by jcelerier** [comment]
@theod I tried by adding a State like this in the scenario.cpp example:  

```
auto state = State::create();
auto mess = OSSIA::Message::create(local_test_address, new OSSIA::Tuple{new OSSIA::Float(1), new OSSIA::Float(2), new OSSIA::Float(3)});
state->stateElements().push_back(mess);
first_start_event->addState(state);
```

And it seems to not be triggered either.

**Comment by theod** [comment]
ok it is fixed on OSSIA API master branch
