### ISSUE TITLE
[feature request] audio from start or "here" in play from here

### ISSUE THREAD

**Issue by pach** [ossia/score#313]
When starting a scenario from the middle (with play from here), it could be good if the audio could start from the place where we start the scenario and not from the beginning of the track. So the sync between audio and nodes stay the same.
That might be an option on the audio process, depending on how the scenario is construct might be usefull or not.
I see two reason why it would necessary : 
- when in writing state of a scenario, you don't have to replay everything to check an effect
- in production, in case of crash or anything, you can restart from the right spot.

**Comment by bltzr** [comment]
👍 well... +💯 indeed !
I think that's very very convenient to have this, too...

**Comment by bltzr** [comment]
is that achievable for the end of the year (aka 1.1) ? 
is the audio plugin supposed to be included in the release, or everything related should be inlcuded in 1.5 ?

**Comment by jcelerier** [comment]
> is that achievable for the end of the year (aka 1.1) ?

not sure, for my phd I'm working on another approach for audio.

> is the audio plugin supposed to be included in the release, or everything related should be inlcuded in 1.5 ?

depends if it's stable enough. But it's mostly a packaging work : making faust, etc.. work fine everywhere.

**Comment by bltzr** [comment]
Anyway, that seems out of the scope of the SNI project so I'm setting this to 1.5.

>  for my phd I'm working on another approach for audio

can you tell us about it (concerning this issue) in a few words ?

**Comment by jcelerier** [comment]
> can you tell us about it (concerning this issue) in a few words ?

instead of using libaudiostream and having a duplication of structures I'm working on an alternative method that uses an audio / data / midi graph (with some novelties wrt the patterns found in max, pd, etc).

**Comment by bltzr** [comment]
OK that sounds promising...

though, is there a relation between this and the place in the sound file from where the playing starts ? (the original issue)

**Comment by jcelerier** [comment]
yes, because it's not just "the sound file", but the whole audio graph : effects, sends, returns, etc.. which have to be at the right "position" too.

**Comment by bltzr** [comment]
right, I didn't think about this.... thx

**Comment by jcelerier** [comment]
it's starting to work for simple cases... I'll try to make an "audio" release with the next release.

**Comment by jcelerier** [comment]
it now works :)
