### ISSUE TITLE
issue with multiple "pulse" trigger sequence

### ISSUE THREAD

**Issue by pchdev** [ossia/score#314]
I have a button on my phone that sends triggers to an impulse parameter on i-score. The problem is, I have two trigger events that are directly connected (in sequence) with the same trigger condition (phone:/phonebutton impulse). When I hit the button once, it actually triggers both of them. The thing is, I want them to be triggered individually, with both one hit of the button.

![iscore-triggers](https://cloud.githubusercontent.com/assets/9993105/20647289/ce897faa-b490-11e6-9c39-fee7d853245f.png)

any clues ?
cheers!

**Comment by pchdev** [comment]
**update** : if I put a Max duration on the second trigger, it works the first time. But if I replay, it triggers both events again.

**update**: ok, it works if I put the second trigger in a sub-scenario

**update**: and now it doesn't...

**Comment by bltzr** [comment]
and if you pout a min duration ?

**Comment by pchdev** [comment]
nope, doesn't work either. Also tried to add a normal constraint of 1 or more seconds in between the two triggers, but it still triggers both

**Comment by pchdev** [comment]
ok, my phone now sends phone:/phonebutton 1, and I put 0 on each trigger state.. this is the best workaround I got for now.

**Comment by bltzr** [comment]
BTW what to you use on your phone ? websocket ? Would you share ?

**Comment by pchdev** [comment]
yes it is web-socket based, github is here : https://github.com/pchdev/quarre_phone, but the .apk not really ready to be "released" so to speak...!

**Comment by bltzr** [comment]
thx!

**Comment by pchdev** [comment]
@jcelerier tested, it works!
thanks!
