### ISSUE TITLE
Javascript scripting

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#318]
There should be more thorough Javascript capabilities in i-score.

Ideally : it should be as powerful as the python console of blender (i.e. possibility to create elements, etc... through the console).

- [ ] Expose core elements of the i-score API to QML : factories, paths, etc.
- [x] Find a way to construct commands from Javascript. This could also serve to enable edition of a score through OSC.
- [x] Add a JS console.
- [x] Logging of JS messages / errors in the message panel.
- [ ] Elements of interface  in QML
- [x] Make Scenario::Command::Macro available
- [x] Make a class that allows to apply commands to the device tree

**Comment by bltzr** [comment]
I guess that's related to #376 right ?

**Comment by jcelerier** [comment]
yes; this is a specific issue about having a "script" panel, a bit like Blender where you can do UI operations through Python directly.

**Comment by jcelerier** [comment]
UI elements in QML won't happen and for the rest it's done
