### ISSUE TITLE
Ability to turn to linked states into an automation event.

### ISSUE THREAD

**Issue by lossius** [ossia/score#32]
_This is a feature request_

If I have made two states next to each others within the same constraint, like this:

<img width="1344" alt="transform" src="https://cloud.githubusercontent.com/assets/38478/9820733/0a5b7868-58b6-11e5-9671-5bdede23714a.png">

it would be nice to be able to right-click the line between them, and turn it into an automation, with interpolation.

**Comment by theod** [comment]
@jcelerier is this done ? it is possible to add an Automation but it seems it is not automatically making an interpolation on the addresses that are into the start and and event isn't it ?

however there is a new sequence operation that maybe make this feature request not relevant ?
@reno-, @bltzr and @avilleret ?

**Comment by nvuaille** [comment]
There is the "interpolate state" action that actually creates an automation per address present in start and end state (if values are differents)
