### ISSUE TITLE
Navigation panel

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#329]
Deport the navigation elements in the inspector

**Comment by jcelerier** [comment]
@OSSIA/core Thinking more of it, I'm starting to wonder if there shouldn't be two inspectors : 

* One for the object properties, e.g. the constraint's durations, the messages in a state, the trigger, etc.
* One for the object hierarchies, e.g. if one clicks on a constraint, then this inspector shows the child processes (that can be clicked), a bit like Unity3D's two inspectors : http://effectronica.com/fx_blog/wp-content/uploads/2011/07/unity_flamebroil_editor.jpg (hierarchy and inspector) or Blender : https://i.ytimg.com/vi/dQKsXmlDf78/maxresdefault.jpg

The navigation elements would also be in the "hierarchy inspector". Maybe it could be a tab in the device explorer ?

**Comment by jcelerier** [comment]
One of the reasons for this is that I'd like to allow plug-ins to add arbitrary properties for objects. 
For instance I'm currently working on the distribution of execution, and I'd like this plug-in to add the "computer where this will be executing" attribute to various elements (constraints, etc.) ; but this would bloat the current inspector even more.

**Comment by bltzr** [comment]
I guess @jln- should be interested by that

**Comment by theod** [comment]
+1
this is quite usual to separate object hierarchy and attributes and it helps a lot to understand how things are organized.

**Comment by bltzr** [comment]
I think it's good to get this out of the current inspector
I'm not sure it's that important to have a dedicated panel/inspector for that, but I might be overlooking some aspects

**Comment by bltzr** [comment]
I've created a specific issue for distribution management #457

**Comment by jcelerier** [comment]
done by @avilleret if I'm not mistaken, it's on top of the object panel
