### ISSUE TITLE
warning color is not updated correctly after moving constraint vertically

### ISSUE THREAD

**Issue by lossius** [ossia/score#33]
According to @jcelerier there's a graphical bug here. I don't think the (• was meant to be able to position itself to the left of the start of the constraint:

<img width="1372" alt="screen shot 2015-09-11 at 18 58 00" src="https://cloud.githubusercontent.com/assets/38478/9820871/17986bd4-58b7-11e5-80a4-a7e1a0f519c7.png">

**Comment by nvuaille** [comment]
That's not really a bug : until we have a working CSP, we allow all positions of min/default/max, even if those who wouldn't work. Now there's a color code (in dev, commit 98d18becf017e9306c41da186bb900062cb264ea) to show warning and error.

**Comment by theod** [comment]
I renamed the issue as I found a little bug.
if you have a constraint (with correct min and max) if you move it vertically and then you move its end event to place min before the start event then only the left part of the constraint is colored in orange.

![capture d ecran 2015-12-08 a 17 44 48](https://cloud.githubusercontent.com/assets/118426/11661675/6c97e86a-9dd3-11e5-80e0-1f04f3e6816f.png)

**Comment by nvuaille** [comment]
Should be fixed in dev (6ebc1e68309ad02b96b575bda87d1588ea6e9aba)

**Comment by theod** [comment]
yes ! thanks
