### ISSUE TITLE
There is no easy way to merge events/conditions

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#337]
- Possibility : 

* By default put all the new states in new events
* When multiple states are selected, add a button to put them in a single event / condition

**Comment by bltzr** [comment]
• By default put all the new states in new events 
-> I'm not sure about that: that's somehow contradictory with the current 'alt-drag while creating a state' behavior
actually, by default (unless alt is presssed while creating), states belong to the same event

 When multiple conditions are selected, maybe we could have an option in the right-click menu ?
And/or maybe the Condition button could turn to a "Merge conditions" button ??? (don't know if that's possible at all ?)

**Comment by bltzr** [comment]
I just maked #352 as a duplicate of this one, but the title is somehow ambiguous - it could also mean that we want to merge several states into a single state
I've disambiguated the title, so if we want to add the feature to  merge several states into a single state, we should create a specific issue for that

**Comment by bltzr** [comment]
isn't that what "Merge events" do ? if so,I guess we could close the issue

**Comment by jcelerier** [comment]
it has been disabled due to crashes AFAIK

**Comment by bltzr** [comment]
well, it actually works (I just tried)

**Comment by jcelerier** [comment]
can confirm that it works
