### ISSUE TITLE
Play from a given point in a constraint

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#341]
Do not play the other branches of a scenario.

**Comment by jcelerier** [comment]
@pchdev do you want to start from the exact point that was clicked in the constraint (like "play from here"), or from the beginning of the constraint that was clicked ?

**Comment by bltzr** [comment]
IMO it should play from the chosen point

**Comment by pchdev** [comment]
yes, from the chosen point would be nice indeed

**Comment by jcelerier** [comment]
It works with the play tool, when pressing "Alt".

**Comment by bltzr** [comment]
why with alt (and not just by clicking on the constraint/slot) ?

**Comment by jcelerier** [comment]
just clicking will only play the clicked constraint (like just clicking on a state will only play this state). Of course this can be reversed if it makes more sense...)

**Comment by bltzr** [comment]
it makes more sense to me to play from where it was clicked - just like we do in the scenario background (which is the slot of the main constraint) - but I might be missing something

**Comment by jcelerier** [comment]
I just did not want to change the actual behavior to not cause surprise to users

**Comment by bltzr** [comment]
I don't think so many users are aware of this behavior, so I guess you could just go ahead and change it - we're not in beta since so long, so I guess that's OK - any objection, someone from @OSSIA/users ?

**Comment by jcelerier** [comment]
ok, done in 7f4c2b154
