### ISSUE TITLE
i-score appImage doesn't have icon

### ISSUE THREAD

**Issue by avilleret** [ossia/score#342]
Here is how v1.0.0-b1 appears on Ubuntu 16.04 :
![image](https://cloud.githubusercontent.com/assets/504914/21220065/878eb900-c2b7-11e6-851d-11fc89b88f67.png)

**Comment by jcelerier** [comment]
huh. interesting ! did it work with the previous ones ? I updated the AppImage version so it is certainly due to that.

**Comment by avilleret** [comment]
no : 
![image](https://cloud.githubusercontent.com/assets/504914/21221871/686b7a06-c2bf-11e6-939c-6906974711d0.png)
But this only affect app icon shown in file browser.
The icon shown in Gnome 3 dock looks fine : 
![image](https://cloud.githubusercontent.com/assets/504914/21221924/acefd546-c2bf-11e6-923a-9587c5fa6b37.png)

**Comment by jcelerier** [comment]
apparently it's the file browser which has to implement it : https://pointieststick.wordpress.com/2018/08/26/this-week-in-usability-productivity-part-33/
