### ISSUE TITLE
issues with timenode/constraint selection

### ISSUE THREAD

**Issue by pchdev** [ossia/score#361]
with b3, i'm having real trouble making a selection of an individual constraint or timenode. 

Most of the times, when clicking, it selects only the timenode part in the inspector, leaving the “events“ part behind. Furthermore, the mouse release action seems to be ignored in that case, and the constraint is continously growing or shrinking as I move the mouse left or right. I have to click again in a “blank“ space in order to make it stop. 

EDIT : ok, it seems to be a problem of context, when clicking in a “blank space“ that, in terms of hierarchy, directly contains the timenode (the main scenario or a sub scenario), and cliking then on the timenode, it works fine.

**Comment by bltzr** [comment]
can you try the fix, @pchdev ?

**Comment by pchdev** [comment]
looks good to me
