### ISSUE TITLE
Encoding issue: Some Boolean operators appear as ? (Win8)

### ISSUE THREAD

**Issue by yousifalyousifi** [ossia/score#362]
OS: Windows 8, AMD Quad-Core A8-6410, Acer Aspire E 15

The Condition Boolean operator symbols show as:
**\=
?
\>
<
?
?
Pulse
True
False**

I'm guess the missing ones are "Not Equal", "Greater Than Or Equal To", "Less Than Or Equal To".

**Comment by jcelerier** [comment]
thanks for the report ! indeed these should be the unicode symbols you said. I'll look into it.
