### ISSUE TITLE
Recording not working (Windows 8, Videos inside)

### ISSUE THREAD

**Issue by yousifalyousifi** [ossia/score#363]
OS: Windows 8, AMD Quad-Core A8-6410, Acer Aspire E 15
Hello, so I am working with Processing, using the OscP5 library.
The connectivity works fine as you can see from the first link, but the recording doesn't seem to work like you have in your tutorial.
[Demonstrating 2 way connection](http://i.imgur.com/c3M3Ngn.gifv)
[Attempting to Record](http://i.imgur.com/8yEulHc.gifv)

Also, not sure if this is related but the time scroller at the top of the main score does not update in real time, it only updates when the mouse leaves or enters the main score area. (It might be normal behavior)
[Time scrolling not updated constantly.](http://i.imgur.com/kREfvjC.gifv)

**Comment by jcelerier** [comment]
> Also, not sure if this is related but the time scroller at the top of the main score does not update in real time, it only updates when the mouse leaves or enters the main score area.

This has been fixed in master, I will be doing a release of it tomorrow if everything goes well. 

The recording bug is not normal however. Could you send your .pde if it's not too big / private ?

**Comment by yousifalyousifi** [comment]
Here you go
```
import java.util.HashMap;
import java.util.Map;

import netP5.NetAddress;
import oscP5.OscMessage;
import oscP5.OscP5;

NetAddress addr;
OscP5 oscP5;
NetAddress iscoreAddr;
Map<String, Object> vars;

public void settings() {
  size(300, 300, P3D);
}

public void keyEvent(KeyEvent event) {
  if (event.getAction() == KeyEvent.PRESS) {
  }
}

public void setup() {
  vars = new HashMap<String, Object>();
  registerMethod("keyEvent", this);
  registerMethod("mouseEvent", this);
  oscP5 = new OscP5(this, 9001);
  iscoreAddr = new NetAddress("127.0.0.1", 9997);
  oscP5.plug(this, "aValue", "/aValue");
}

public void aValue(int value) {
  System.out.println("Incoming value: " + value);
}


int bgColor = 255;
boolean isDragging;

public void mouseEvent(MouseEvent event) {
  if (event.getAction() == MouseEvent.PRESS) {
    isDragging = true;
  }
  if (event.getAction() == MouseEvent.RELEASE) {
    isDragging = false;
  }
  if (isDragging) {
    int i = (int)(map(mouseY, height, 0, 0, 100));
    text("Sending", mouseX, mouseY);
    text(i + "", mouseX - 50, mouseY);
    line(0, mouseY, width, mouseY);
    OscMessage m = new OscMessage("/aValue");
    m.add(i);
    oscP5.send(m, iscoreAddr);
  }
}

public void draw() {
  background(bgColor);
  ortho();
  fill(0);
  textSize(30);
  text("100", 0, 25);
  text("0", 0, height);
}

public void oscEvent(OscMessage message) {
  System.out.println(message.get(0).intValue());
}

```
