### ISSUE TITLE
loading xml namespace with comment line in sublevel hides nodes

### ISSUE THREAD

**Issue by theod** [ossia/score#365]
only the first child is added under a node when loading the given xml namespace file.
the children seem to be hidden by the comment lines but this is only happening for the sub levels (comments at the first level don't make any trouble !).

[vv_namespace.xml.txt](https://github.com/OSSIA/i-score/files/789706/vv_namespace.xml.txt)

**Comment by jcelerier** [comment]
fixed by ce910afe1cba577394749b68227b5056dae10a41
