### ISSUE TITLE
Menu for accessing tuple elements in address fields

### ISSUE THREAD

**Issue by bltzr** [ossia/score#369]
it would be nice to have a menu for accessing tuple elements in the address fields (e.g. for automations, condition/trigger expressions, etc...

when no dataspace/unit is set, we would have, for a n-uplet:
- \*
- 1
..
- n 

when a dataspace is set (e.g. xyz position):
then we have a first menu, which offers the different "units":
- xyz
- aed
- etc....
and then another menu that proposes the possible options (e.g. for xyz) for this one automation/expression:
- \*
- x
- y
- z

**Comment by jcelerier** [comment]
where would this menu be ?

**Comment by bltzr** [comment]
probably to the right of the two other dataspace menus, I'd say (which would make them smaller, but I guess that's OK)
<img width="356" alt="capture d ecran 2017-02-23 a 11 43 00" src="https://cloud.githubusercontent.com/assets/365923/23255855/617b83fa-f9bd-11e6-8292-eff3a61b8da5.png">

**Comment by jcelerier** [comment]
okay, let's close this issue and continue in #379 because it's exactly the same

**Comment by bltzr** [comment]
on the "Unit" line

**Comment by bltzr** [comment]
okay
