### ISSUE TITLE
scenario "pause" after using condition

### ISSUE THREAD

**Issue by pach** [ossia/score#377]
![sous_scenario_pause](https://cloud.githubusercontent.com/assets/365923/23223328/17ab095e-f92b-11e6-9b22-4ac083f9256c.gif)

**Comment by pach** [comment]
https://gist.github.com/pach/8953fab499e5a00cb85449cad25bab5b

**Comment by bltzr** [comment]
still happening ?

**Comment by jcelerier** [comment]
this should have been fixed in the latest release ; at the very least I ran the scenario and could not notice anything blocking.
