### ISSUE TITLE
scenario hors temps

### ISSUE THREAD

**Issue by pach** [ossia/score#384]
Possibilité de trigger des scenario hors temps.
Si un node / constraint n'est pas connecté au temps et commence par un trigger, il peut alors etre triggé n'importe quand et toujours (on peut le retrigger meme s'il vient d'etre triggé).
voir scenario : https://gist.github.com/pach/2639ca06819e7c7229f953af6cddc17f

**Comment by reno-** [comment]
+10000
I really need to have scenario that could be triggered from another scenario.
I often do an action ( ramp of multiple parameters) several times in a show. What I need is to do a "template scenario) I,will trigger from another events.
This is like the "play" cue in Qlab that will play a cue that is not in the sequential list

**Comment by bltzr** [comment]
I also second this strongly - I guess we need to figure out how to represent this clearly (we discussed placing this on a kind of layer or sheet... so that it looks detached from the timeline....) 
it's also probably important to prevent users from connecting the end of such an "offtime" scenario to other objects in the main scenario (because this would certainly cause problems)
any idea, @jln- ?

**Comment by bltzr** [comment]
I guess this is one thing @matcham would be interested in...

**Comment by pach** [comment]
I do not completely agree about putting them completely out of time. 
There is some of this scenario that I want to be able to call at any time but during a certain amount of time (means inside a scenario). 
I do think the first proposal we discussed at montbeliard is still for me the best way to make them. 
Other possibilities would be to have in each scenario a detach layer which might be quite more constraining.

**Comment by bltzr** [comment]
What I remember from the discussions in Montbéliard would be that these "offtime" actions would be triggerable only when its parent scenario is active 
hence when one wants them to be available during a certain interval if time only, they have to be placed inside a sub-scenario
are we saying the same thing ?

**Comment by pach** [comment]
Yep!

**Comment by nvuaille** [comment]
And what about the "logical view" ? 
We could imagine a "Max-like" view where each box is an i-score process (like a scenario), and a way to link,  (des)activate them, having some atemporal trigger, ...
Maybe something like a statemachine (no more than a hierarchical logical representation) ?

I have no concrete ideas but may be we can think about it ...

**Comment by jcelerier** [comment]
@nvuaille : working on it :p

**Comment by pach** [comment]
link to #641

**Comment by pach** [comment]
Dans l'implémentation actuel, il faudrait que l'on puisse en mon sens recliquer à tout moment sur le trigger de départ s'il est sorti du temps. En gros qu'un trigger sur un scénario hors temps est toujours actif est en attente.
 Si le temps derriere est en cours de lecture, il repart du début. s'il a fini de lire ou est en attente, on lit du debut.

**Comment by bltzr** [comment]
we've been managing to determine graphically what Mr @pach actually wants:

let's say we have this:
<img width="630" alt="capture d ecran 2017-10-13 a 15 38 11" src="https://user-images.githubusercontent.com/113982/31548855-98f39234-b02c-11e7-939a-7b2b30109147.png">

what @pach wants, is that this does the same than this:
<img width="635" alt="capture d ecran 2017-10-13 a 15 40 57" src="https://user-images.githubusercontent.com/113982/31548978-f4d4115a-b02c-11e7-9e31-ffec7e57778a.png">
with both of those triggers responding to the same thing:
<img width="310" alt="capture d ecran 2017-10-13 a 15 41 28" src="https://user-images.githubusercontent.com/113982/31549048-3765d684-b02d-11e7-8149-be3a363455b7.png">
i.e. the first time the trigger is clicked it triggers the first one (at the beginning of the parent interval), and after that, it triggers the second one (at the end of the pattern)

also, there's a potential case to take into account:
what if we connect the "construct" to some point later in time, such as this:
<img width="620" alt="capture d ecran 2017-10-13 a 15 46 59" src="https://user-images.githubusercontent.com/113982/31549211-c83ee6c8-b02d-11e7-9750-9afd08dbafbe.png">
according to @pach this would remove the whole loop thing and just revert back to the way it currently works (i.e. the end trigger will wait that both branches are finished before becoming available)

**Comment by jcelerier** [comment]
what happens in this case ? 
![yuck](https://user-images.githubusercontent.com/2772730/33559021-cb52a05a-d90b-11e7-89bd-a2769646a52f.png)

**Comment by bltzr** [comment]
I'd say that it waits that both branches are finished before playing the last event
optionnally it could do what's specified in https://github.com/OSSIA/score/issues/680 ;-p

**Comment by jcelerier** [comment]
yes but for instance if you click multiple times on the trigger on the bottom without clicking on the trigger on top, should it still restart the whole sub-score ?

**Comment by bltzr** [comment]
let's say it should - and then we'll have to wait until it is done before the event can be triggered - is that OK with you, or is it the kind of case that would cause you headaches ?

**Comment by bltzr** [comment]
this works in the dataflow branch, aka V2 (or V3, @jcelerier), did you have the opportunity to test it @pach ? if you did, could you close the issue if that satisfies you ?

**Comment by pach** [comment]
Yep!
Tested with a lots of trigger.
Doesn't tested to attach them back to a scenario, but working perfectly
well for my case. :)

----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

**Comment by jcelerier** [comment]
it has now been merged in master
