### ISSUE TITLE
[feature request] variable in javascript

### ISSUE THREAD

**Issue by pach** [ossia/score#388]
possibility to have tree accessible in javascript threw a drag&drop

**Comment by pach** [comment]
exemple of utilisation in Unity :
- interface
<img width="713" alt="capture d ecran 2017-02-24 a 12 24 05" src="https://cloud.githubusercontent.com/assets/365923/23301857/4a6e060e-fa8c-11e6-8dcb-a1028028db98.png">

- corresponding script 
all variable declared public are accessible in the UI, threw drag and drop or interface.

```
public class followTarget : MonoBehaviour {
	public GameObject target;
```


```
public class PanTiltControl : MonoBehaviour {

	[Range (-270.0f, 270.0f)]
	public float pan;

	[Range (-135.0f, 135.0f)]
	public float tilt;

	GameObject bras;
	GameObject corps;
```

**Comment by jcelerier** [comment]
```
Object {
        property real pan;
        Range on pan { min: -270, max 270 }

       onTick: function(t) {
       }
}
```

**Comment by bltzr** [comment]
@jcelerier does that mean that this already exists (then the issue could be closed once this is documented) or are you specifying how this should work ?

**Comment by jcelerier** [comment]
this was a proposition of implementation so no, this does not exist yet

**Comment by jcelerier** [comment]
javascript now works like this ; see https://github.com/OSSIA/score/tree/master/Library/JS for examples
