### ISSUE TITLE
UI + (add device) button blue colour suggests that it is always active

### ISSUE THREAD

**Issue by lossius** [ossia/score#39]
<img width="1372" alt="screen shot 2015-09-16 at 16 08 23" src="https://cloud.githubusercontent.com/assets/38478/9906975/3adf8490-5c8d-11e5-9fdb-9730eacdb836.png">

This is just a minor feedback on one aspect of the user interface: The fact that the "+" button in the lower left edge of the interface is blue, is to me slightly misleading. It seems to suggest that it is already active, much in the same way that one of the two documents in the attached screen shot is active. For me it would make more sense if this icon was grey, and eventually turned blue when clicked.

**Comment by jcelerier** [comment]
@blueyeti so, this would require non-blue buttons for the device explorer.

**Comment by theod** [comment]
fixed as the color skin are completely different now
