### ISSUE TITLE
record parameter of type array lead to Internal error: 

### ISSUE THREAD

**Issue by jln-** [ossia/score#391]
I got the following error message when trying to play back a hand-recorded automation. The recorded parameter is of type array (position/cart3D).

Automation seems to be properly recorded. But playing back lead to 

Internal error: state_flatten_visitor_merger: impossible case (message <- const piecewise_vec_message&

![capture d ecran 2017-02-24 a 17 31 15](https://cloud.githubusercontent.com/assets/114325/23311838/c4089fee-fab7-11e6-9ce5-36c3b3dc8e81.png)

**Comment by jcelerier** [comment]
I think I fixed this one in a previous commit, I cannot reproduce it.

**Comment by jcelerier** [comment]
still can't reproduce so I close. please reopen if it happens
