### ISSUE TITLE
cant set processes on addresses containing an instance

### ISSUE THREAD

**Issue by jln-** [ossia/score#393]
When setting an address containing an instance (ie. /spat/source.1/position) in the 'Source' or 'Target' text field of the Mapping process, address get stripped off at the dot (ie. /spat/source)

This is with v1.0.0-b5-1

**Comment by jln-** [comment]
Renamed since it is also true for other processes (ie. interpolations) as experienced by Thomas

**Comment by jcelerier** [comment]
fixed
