### ISSUE TITLE
zoom problem with new scenario

### ISSUE THREAD

**Issue by bltzr** [ossia/score#412]
as illustrated in the attached screenshot, there is something wrong in the zoom display (or something) when creating a new scenario - maybe this comes from my preference settings
![zoooom](https://cloud.githubusercontent.com/assets/113982/23578195/7874fae4-00d1-11e7-9176-6ac09abca985.png)

**Comment by bltzr** [comment]
I just need to zoom a little and things jump back to normal...
![mars-04-2017 11-57-17](https://cloud.githubusercontent.com/assets/113982/23578210/bf9a0a9a-00d1-11e7-99f2-77abf49726ed.gif)

**Comment by pach** [comment]
Haha got quite a few version that I have this issue on load but I got use of the workaround an completely forgot to make the report.  ^^


Thomas Pachoud 
www.creapach.fr
