### ISSUE TITLE
MoveNotes::update does not update note data

### ISSUE THREAD

**Issue by SephDB** [ossia/score#415]
https://github.com/OSSIA/i-score/blob/master/base/plugins/iscore-plugin-midi/Midi/Commands/MoveNotes.cpp#L56
Currently, this loop looks like this:

     for (auto& elt : m_before)
     {
       NoteData data = elt.second;
       data.setPitch(qBound(0, data.pitch() + note_delta, 127));
       data.setStart(std::max(data.start() + t_delta, 0.));
       m_after.push_back(elt);
     }

Instead of pushing a new note with the new data in it, it pushes elt unchanged.

**Comment by jcelerier** [comment]
indeed ! thanks for noticing

**Comment by jcelerier** [comment]
fixed by 153a61b1b
