### ISSUE TITLE
Icon for mute button (was: Mute option on process)

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#419]
What about an option to mute a process ?

In order to play a constraint and following without sending some information (e.g do not play an automation)

**Comment by jcelerier** [comment]
it's already in the API, just have to make it visible in the gui :p

**Comment by bltzr** [comment]
We could have that on the constraint (with a header's UI widget), muting all its processes
and one for each process (e.g. in a kind of header for each slot)
we've been starting some sketches for these kind of things with @jln-

**Comment by bltzr** [comment]
of course, the first step would be to add a toggle to the process's inspector (and maybe grey-out a little the process's slot)

**Comment by jcelerier** [comment]
it's now available (but lacks a pretty icon)

**Comment by bltzr** [comment]
> it's now available (but lacks a pretty icon)

now, that's something for @jln- !!

**Comment by bltzr** [comment]
if you agree, @jln- we can reopen the issue (or create a new one) and assign it to you...

**Comment by jcelerier** [comment]
seems like it's done
