### ISSUE TITLE
Inspector number widgets should not respond to mouse scroll wheel

### ISSUE THREAD

**Issue by lossius** [ossia/score#42]
If you make e.g. an automation, and use a mouse with a scroll wheel, I believe there are some major user interaction problems with the number widgets of e.g. the min and max values:
- IMHO these widgets should not respond to scroll wheel at all. It's much to easy to pass by them with a mouse after a recent scroll, where the scroll wheel is still moving, and suddenly I have made an undesired changed to the value without being aware of it. I tested what the behaviour is in several other applications, such as Omni applications, Pixelmator, Max 7 and several others, and none of them have numbers in inspectors etc. responding to mouse wheel.
- Secondly, if this feature is going to be there, it is scrolling the wrong way compared to default modern OSX scroll wheel behaviour. This becomes particularly clear when using a trackpad: Double drag upwards diminish rather than increase the value.

**Comment by nvuaille** [comment]
It was closed in dev today (d68d327a7353c9a1bc9423e630311b70ff86689c). Just wait for the release =)
