### ISSUE TITLE
Qt5QuickControls2.dll is missing (1.0.0-b8 on Win8)

### ISSUE THREAD

**Issue by yousifalyousifi** [ossia/score#423]
Hi. When I launch i-score 1.0.0-b8 I am presented with this error:
[http://i.imgur.com/Biwrc87.png](http://i.imgur.com/Biwrc87.png)

I just installed 1.0.0-b7, and it launches fine.

OS: Windows 8, AMD Quad-Core A8-6410, Acer Aspire E 15

Thank you.

**Comment by jcelerier** [comment]
indeed, forgot to add it to the release package. thanks for the report! (1.0.0-b8 was a bit botched anyway, I have Linux and OS X build to fix too).
