### ISSUE TITLE
OSX click'n drag with 3 fingers doesnt work to create element

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#43]
To be honnest, element is created but the command is not send to the undo/redo stack.

To see the problem (on OSX yosemite) : 
- create a state
-  try to create a constraint from this state. 
  The constraint and is end state is visible but the command doesn't appear in the stack (and the undo/redo bug)

**Comment by bltzr** [comment]
https://www.youtube.com/watch?v=xphfUfydyaE

**Comment by nvuaille** [comment]
Tu nous l'as déjà sortit celle là !

**Comment by bltzr** [comment]
Certes, mais là elle est particulièrement approprié, non ?

Pascal Baltazar

**Comment by jcelerier** [comment]
Seems that it's not clear on the Qt side : https://bugreports.qt.io/browse/QTBUG-8312
