### ISSUE TITLE
use get/set fields instead of i/O type in node inspector (in device explorer)

### ISSUE THREAD

**Issue by bltzr** [ossia/score#430]

**Comment by bltzr** [comment]
I guess this should be done as part of the device explorer refactoring (when the subpanel/inspector for attributes is created)

**Comment by jcelerier** [comment]
indeed, and it's quite simple to do

**Comment by jcelerier** [comment]
before I implement it, we are definitely sure we want this ?

**Comment by bltzr** [comment]
Do you remember the context of his FR ?
Was it a discussion on gitter ?

**Comment by jcelerier** [comment]
I think it was just because it seemed more familiar to people to have get/set. But I have not heard anyone complaining since then so I'm wondering if it really matters, and if it wouldn't be worse to change for the people who got used to the current -> <- arrows.

**Comment by bltzr** [comment]
how about both?
-> (set)
<-> (get/set)

https://media.giphy.com/media/3ohfFhG5VDtDTzQv2o
