### ISSUE TITLE
 Qt5QuickControls2.dll error on windows

### ISSUE THREAD

**Issue by MatiasDelera** [ossia/score#432]
Hi. Im getting Qt5QuickControls2.dll error on windows 7 64. How I can fixit?.

**Comment by jcelerier** [comment]
hi, sorry this has been fixed in git but is not in a release currently. To solve, you should get a Qt installation (msvc2015 32 bit) and copy the dll from Qt/msvc2015/lib/ to the application folder

**Comment by jcelerier** [comment]
this is fixed in b10
