### ISSUE TITLE
enlever des paramètres des states suivis d'une interp avec tween

### ISSUE THREAD

**Issue by pach** [ossia/score#439]
on ne peux visiblement pas enlever d'un state des parametres utilisé dans une interp posé sur la contrainte de temps qui suit ce noeud, meme quand tween est activé. Toutefois pour avoir eu de nouveau ce cas hier, il semblerait que ça marche si on supprime (ça reste visible) qu'on sauve et qu'on relance le score.

**Comment by jcelerier** [comment]
en fait (c'est un choix qui avait été fait il y a un moment) dès qu'on a une courbe entre deux points, les state de part et d'autre de la courbe affichent la valeur qui correspond
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/2772730/25693369/332425ca-30a9-11e7-91c5-73994566e48d.gif)

**Comment by bltzr** [comment]
en fait, ça me paraît logique (et sain) que la valeur soit dans le state - par contre ça serait bien de pouvoir l'enlever sur le state de début quand il y a un tween... @pach ?

**Comment by jcelerier** [comment]
oui, il ne devrait pas être affiché dans ce cas là

**Comment by bltzr** [comment]
aaaabsolument !

**Comment by bltzr** [comment]
j'allais demander ce qu'il se passait si après avoir coché tween, on le décochait : sur quelle base il remettait la valeur... 
mais d'après ce que tu dis, @jcelerier , les valeurs ne sont pas enlevées de l'état, mais ne sont "pas affichées", donc elles sont gardées pour si on re-décoche tween, right ?

**Comment by jcelerier** [comment]
oui tout à fait. elles ne sont juste pas utilisées au moment de créer les structures d'exécution de libossia.

**Comment by bltzr** [comment]
du coup, @pach est-ce que c'est gênant pour toi, ou bien c'est juste cosmétique (pour savoir si on essaie de résoudre ça de façon prioritaire)

**Comment by pach** [comment]
Bah si elle apparaissent (visible) dans le state ça veux pour moi dire qu'elle est envoyé au début de mon intérim et que le tween n'as donc aucun interet. Une question de logique, non?

Thomas Pachoud 
www.creapach.fr

**Comment by bltzr** [comment]
oui, absolument logique, mais donc ça ne t’as pas posé d’autre problème que de logique ou de représentation (pas de comportement bizarre, quoi, right ?)
merci pour la réponse !

**Comment by pach** [comment]
Bah je redémarre i-score après chaque suppression de node pour la rendre
effective...
Du coup ça marche. Pas essayé sans redemarrer i-score.

----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

**Comment by pach** [comment]
Et en mon sens en terme de comprehension, c'est un truc à résoudre pour les
gens qui découvre i-score.
Parce que leurs dire, à oui c'est toujours la mais sauf que comme après ya
un tween, bah du coup c'est pas actif, mais c'est quand meme la, mais en
fait non...
Moi, je fuis! ;p

----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

2017-05-16 10:54 GMT+02:00 Thomas Pachoud <thomas.pachoud@gmail.com>:

> Bah je redémarre i-score après chaque suppression de node pour la rendre
> effective...
> Du coup ça marche. Pas essayé sans redemarrer i-score.
>
> ----- ----- -----
> Thomas Pachoud
> creapach.blogspot.fr
> assoikari.wordpress.com
> ----- ----- -----
> la campagne pour le FabLAboriGène de l’Amer
> <https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer> est
> engagée!
> -----
>
> On Tue, May 16, 2017 at 10:13 AM, Pascal Baltazar <

**Comment by bltzr** [comment]
oui oui, il faut le régler, on est d'accord (c'est pourquoi je l'ai mis sur la prochaine milestone) mais je voulais savoir si ça posait des problèmes à l'exécution.

**Comment by jcelerier** [comment]
hmm.. en essayant de voir comment faire je suis pas sûr que cacher soit la bonne solution, surtout pour les interpolations : notamment, si par exemple on réalise la séquence d'actions suivantes: 

* mettre des choses dans deux states (`/a 0` et `/a 1` ainsi que `/b 0` et `/b 1`  par ex.)
* interpoler avec l'addresse `/a`
* activer le tween 
* sélectionner tout dans le state de début et supprimer

ben si à un moment on enlève l'interpolation, un peu plus tard par ex., même si on avait eu l'impression de tout supprimer il restera maintenant le `/a 0` qui était là au début, ce qui me semble un peu contre-intuitif. Donc est-ce qu'il ne faudrait pas plutôt les afficher mais d'une couleur différente qui indique la désactivation ?

**Comment by bltzr** [comment]
pour moi l’idéal serait qu’il y ait un ? quand il y a un tween (et quand on enlève le tween ça remette la valeur) - c’est envisageable, ça ?
sinon italique (très) grisé
opinions ?

**Comment by pach** [comment]
Je dirai plutot italique grisé, qui est pas mal dans les codes de la plupart des logiciels quand des valeurs sont inactives.

Thomas Pachoud 
www.creapach.fr

**Comment by bltzr** [comment]
en même temps, ça donne l’impression qu’il y a une valeur, alors que le ? ça dit clairement (enfin, j’ai l’impression) que cette valeur est préelvée en direct… non ?

**Comment by bltzr** [comment]
mais si vous êtes d’accord et que c’est plus simple le grisé, ça me va, hein...

**Comment by jcelerier** [comment]
disabling the interpolation process, it will have to be remade at some point but as such it's very broken
