### ISSUE TITLE
automatically add a condition when a new event is created from an existing TimeNode

### ISSUE THREAD

**Issue by bltzr** [ossia/score#447]
e.g. when creating it with alt-drag from an existing state

**Comment by jcelerier** [comment]
should the condition be on the old event, new event, or both ?

**Comment by bltzr** [comment]
new one only IMO

**Comment by jcelerier** [comment]
## To do

I think the simplest way to do this is is to set a false expression (with `State::defaultFalseExpression()`) in `Scenario::Command::CreateEvent_State::redo()`.
