### ISSUE TITLE
Don't refresh namespace when loading a project

### ISSUE THREAD

**Issue by reno-** [ossia/score#45]
When you have a big namespace, it's so long to redo minuit discovery each time a project is loaded.

**Comment by reno-** [comment]
Version:
1.0.0-a9

Commit: 
820fb151f641167daed4ee339bfaa07151f57004

**Comment by jcelerier** [comment]
@theod it's related to the problems with the minuit refresh being called.

**Comment by theod** [comment]
this should be fixed now. you have also to update JamomaCore.

**Comment by theod** [comment]
this is fixed even if there are still some messages sent to i-score but this issue is handled here : https://github.com/OSSIA/i-score/issues/69
