### ISSUE TITLE
Slot vertical resize

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#450]
If a slot S is moved down so its bottom is outside its parent slot, and if this parent slot has a sibling slot below,  S is no more vertically resizable. 
In attachment: slot of "dice78..." is not resizable.

![slot_resize](https://cloud.githubusercontent.com/assets/5503180/25999551/e4861dfa-3725-11e7-92b6-39239112dfd0.PNG)

Tested on b14 on windows 10.

**Comment by jcelerier** [comment]
mhhh since they are different slots, the scenario should not go beyond the slot. I disabled it in  37edfb8

**Comment by bltzr** [comment]
this seems OK right now, so I'm closing the issue
