### ISSUE TITLE
max bound style in full view

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#452]

**Comment by jcelerier** [comment]
it's honestly a bit ugly : 

![screen](https://cloud.githubusercontent.com/assets/2772730/26037634/6eabb26a-38f7-11e7-90fa-6fee565cdce4.png)

I will be putting it from the default bound in both cases instead : 
![better](https://cloud.githubusercontent.com/assets/2772730/26037647/b956208e-38f7-11e7-8704-d28bf4639cf4.png)

**Comment by bltzr** [comment]
ok
