### ISSUE TITLE
tween on interpolations is buggy

### ISSUE THREAD

**Issue by bltzr** [ossia/score#456]
it interpolates from the current values to some mix of values from the start and end state (e.g. members 1, 2, 3 and 6 are from the end state, 4 and 5 from the start state)

**Comment by jcelerier** [comment]
hmm.. I am not able to reproduce it on a simple example. Could you tweak it in order to reproduce ? 
[bug-tween.scorejson.txt](https://github.com/OSSIA/i-score/files/1023707/bug-tween.scorejson.txt)

**Comment by bltzr** [comment]
as of today, this is still happening
![mai-28-2017 12-48-24](https://cloud.githubusercontent.com/assets/113982/26528131/0cbe989e-43a4-11e7-9326-e186ca396866.gif)

**Comment by bltzr** [comment]
the bug seems to happen when the interpolation is placed inside a sub-scenario

**Comment by bltzr** [comment]
You can try with the attached examples - as demonstrated on the gif, there is a kind of leap at the end of the second interpolation when the value is changed by hand between the first and the second interpolation 
I had other, similar-behaving bugs, that I cannot reproduce right but, hopefully, fixing this one will also fix the others...

![mai-28-2017 18-52-06](https://cloud.githubusercontent.com/assets/113982/26530552/3888ec26-43d7-11e7-86b9-134c02e28842.gif)

[Archive.zip](https://github.com/OSSIA/i-score/files/1034339/Archive.zip)

**Comment by jcelerier** [comment]
disabling the interpolation process, it will have to be remade at some point but as such it's very broken
