### ISSUE TITLE
process delegation

### ISSUE THREAD

**Issue by bltzr** [ossia/score#462]
as discussed in the #147 looooong thread of comments, it could be nice to devise some ways to delegate automations/interpolations (maybe also mappings and other processes) to remote devices (implementing libossia, such as ossia-pd and friends...)

maybe a simpler way to do this would be to include i-score players in the remote devices, though (just thinking out loud...)

**Comment by jcelerier** [comment]
> as discussed in the #147 looooong thread of comments, it could be nice to devise some ways to delegate automations/interpolations (maybe also mappings and other processes) to remote devices (implementing libossia, such as ossia-pd and friends...)

That's more or less what the network player and distribution extension does

**Comment by bltzr** [comment]
maybe also we shoud include the specs we have discussed for the pd version of the player, i.e. being able to create ramps or tweened interpolations on the fly, which would complete the ossia-pd feature parity with Jamoma4pd

**Comment by bltzr** [comment]
after looking into the implementation of such things, we kind of concluded that @jcelerier was (as often) very right:
> That's more or less what the network player and distribution extension does

so I'm closing this issue
