### ISSUE TITLE
change aspect of loop slot

### ISSUE THREAD

**Issue by bltzr** [ossia/score#463]
- [x] pattern/loop color switch
currently the color of the pattern is changed, as discussed in Montbéliard, it should instead be the loop's slot

- [x] pattern's slot size
also, there is no sense to keeping some free space *below* the pattern's slot, so it should scale vertically in order to match with the bottom side of the loop's slot (or just a little bit above so we can see the color of the loop's slot)

- [x] the + widget for the end state shouldn't be there 
as it can't be used, as in #422  

- [x] the trigger button doesn't work with the end state/TN of the pattern

**Comment by jcelerier** [comment]
for point 1 which color would you like ? I put this red-ish thing but I find it to be quite ugly...

**Comment by jcelerier** [comment]
> the trigger button doesn't work with the end state/TN of the pattern

are you sure ? it works fine here.

**Comment by bltzr** [comment]
yellow-ish maybe ?

**Comment by jcelerier** [comment]
> also, there is no sense to keeping some free space below the pattern's slot, so it should scale vertically in order to match with the bottom side of the loop's slot (or just a little bit above so we can see the color of the loop's slot)

what happen,s if there are multiple slots ? how are they resized ?

**Comment by bltzr** [comment]
you mean in the pattern ? I'd say yes.. Is that a problem ?

**Comment by bltzr** [comment]
>> the trigger button doesn't work with the end state/TN of the pattern

> are you sure ? it works fine here.
![mai-26-2017 09-37-36](https://cloud.githubusercontent.com/assets/113982/26485405/41785b28-41f7-11e7-8a6d-e72602655747.gif)

it doesn't work with the trigger button, just from the inspector...

**Comment by jcelerier** [comment]
ah sorry I thought the problem was when pressing the actual trigger

**Comment by jcelerier** [comment]
@bltzr I don't understand "yes" about "what happens if there are multiple slots ? how are they resized ?"

Also what happens if someone manually resizes a slot ?  
![zoom](https://cloud.githubusercontent.com/assets/2772730/26521028/ff6dc2e8-42de-11e7-83ba-da3ad9028d00.gif)

**Comment by bltzr** [comment]
OK now I understand the problem
I have no solution (yet)

**Comment by jcelerier** [comment]
fixed the trigger button problem

**Comment by bltzr** [comment]
everything's done, now, right ?
