### ISSUE TITLE
Device explorer: one tab per device ?

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#467]
I'm wondering more and more if the device explorer shouldn't have multiple tabs where a single device is shown per tab, instead of a big tree. Or maybe different tabs to categorize different kinds of devices : 

* A tab for all the "network" devices such as OSC, etc..
* A tab for the local device
* A tab for the midi devices

because then it would allow more easily to, for instance, display all the midi devices plugged in automatically in the midi tab, without bothering the users of other protocols. Likewise, it would make more sense to always have the "local" device available, but not force it if you look for something in some OSC device.

It could also be useful to manage more easily the various "networked" i-score players and their custom device.

Ideas ?

**Comment by pchdev** [comment]
but maybe still have an overview of all devices (without details)?

**Comment by bltzr** [comment]
that's certainly a good idea

though, I think it would be useful to have an "all" tab, so we can handle all devices at the same time when needed

**Comment by jln-** [comment]
mm... Isn't that something we should let up to the users, using some filtering options we discussed in the past ? Assuming one can pin filtering resultats as a new tab (just thinking out loud)

**Comment by bltzr** [comment]
Yes, that sounds like a very interesting idea!

**Comment by aklevy** [comment]
Not relevant anymore
