### ISSUE TITLE
Port Color gradient process to v2

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#468]
It would be nice to have a process that allows pretty gradient automations, à la [duration](http://www.trondlossius.no/system/photos/519/original/duration_screen.png). If someone feels like specifying it...

**Comment by pach** [comment]
👍

**Comment by jcelerier** [comment]
made a first test in git if someone wants to try (process is called gradient)

**Comment by jcelerier** [comment]
## To do

- [ ] Handle tweening
- [ ] Handle rescaling w/ grow-shrink
- [ ] Handle a gradient past default duration.

**Comment by bltzr** [comment]
TODO, continued:
- [x] port to v2

**Comment by bltzr** [comment]
port to v2 aka add a way to set an address to output the values

if it's possible to include some of the suggestions of #482 in the process, that would be great, but they can also wait, I guess

**Comment by jcelerier** [comment]
uh ? 
![color](https://user-images.githubusercontent.com/2772730/41673300-d7bf3806-74bc-11e8-9757-5e31e39cab37.gif)

**Comment by bltzr** [comment]
could you show the gradient process's inspector ? 

here, I don't have any way to set the address:
![grad](https://user-images.githubusercontent.com/113982/41675661-93b8cb98-74c3-11e8-862a-85af55f826b4.png)
that's v2a4

**Comment by jcelerier** [comment]
yes, you have to click on the port to show its inspector (or drop an address on it from the device explorer)

**Comment by bltzr** [comment]
so that's basically https://github.com/OSSIA/score/issues/774 that we need here

**Comment by bltzr** [comment]
> drop an address on it from the device explorer

I didn't know about this: that's an interesting feature to document, I guess - @jln-

**Comment by bltzr** [comment]
just tried with a rgba8 color param from this [ofApp](https://www.dropbox.com/s/ckxlwmwhc46vayn/example-singleServerDebug.zip), and the values were not scaled to the 255 range
so I'm reopening

**Comment by jcelerier** [comment]
> just tried with a rgba8 color param from this [ofApp](https://www.dropbox.com/s/ckxlwmwhc46vayn/example-singleServerDebug.zip), and the values were not scaled to the 255 range

now fixed
