### ISSUE TITLE
crash when creating an interpolation (automation)

### ISSUE THREAD

**Issue by reno-** [ossia/score#47]
Select a contraint
Create an automation by clicking  on 'interpolate state'

Crashlog here : 
https://gist.github.com/reno-/4a6b3e1fbbec0b258d33

**Comment by jcelerier** [comment]
seems to be a Qt bug that has been fixed in the latest version : https://bugreports.qt.io/browse/QTBUG-46264

**Comment by theod** [comment]
@reno- I assign it to you as it seems to be fixed

**Comment by reno-** [comment]
yes, I cannot reproduce now… Tx !
