### ISSUE TITLE
dependancy for Ubuntu 16.04

### ISSUE THREAD

**Issue by sensestage** [ossia/score#470]
Additional dependency on:
libavahi-compat-libdnssd-dev

And the qt install needs to be 571 instead of 57:

sudo add-apt-repository ppa:beineri/opt-qt571-xenial -y

**Comment by jcelerier** [comment]
thanks! looking on it. I think that they can be updated to use qt 5.8

**Comment by sensestage** [comment]
with 5.8 the -dev packages were missing for Qt, when installing qt-latest, and not found by cmake.

**Comment by jcelerier** [comment]
hm, the package should be `qt-latest` in all cases.

**Comment by jcelerier** [comment]
I checked and updated the build instructions here: https://github.com/OSSIA/i-score/wiki/Build-and-install#ubuntu-1604

I could complete a build by copy-pasting them in a virtual machine.

**Comment by sensestage** [comment]
ok, also newer versions of cmake and libboost...
building now

**Comment by sensestage** [comment]
Ok - it builds!
Thanks for the fast reactions!
