### ISSUE TITLE
default drag'n'drop behaviors on constraints

### ISSUE THREAD

**Issue by bltzr** [ossia/score#472]
currently, when drag'n'dropping one (or several) addresses on an event, it creates a state with the values of those adresses - good, let's keep that!

when adding an automation or an interpolation to a constraint, we can drag'n'drop an address onto it, and that assigns this address to this automation/interpolation - also good!
also, it sets the start state (and first point of the automation) to the address's minimum and the end state (and last point of the automation) to its maximum 
what if, instead, it set the end state (and last point of the automation) with the current (queried) value and put the tween mode on ?

IMHO that would be more useful.... because maybe we want to create once a ramp from the min to the max, but probably not very more often...
while using tweens directly can create something actually working (one could actually create a fully-working scenario this way... )

any opinions @OSSIA/users ?

If that's OK with this, we could also automatically create automations and constraints when addresses are drag'n'dropped on a constraint:
- an automation for float/int (and maybe dataspace tuples, e.g. colors...)
- an interpolation for plain tuples
IMO that would be very helpful to improve the authoring process...

**Comment by bltzr** [comment]
full list of processes created by type: https://github.com/OSSIA/i-score/issues/480

**Comment by pchdev** [comment]
I realize I don't think I answered that one,
you've got my vote, I'm ok with all of this

**Comment by jcelerier** [comment]
superseded by #659
