### ISSUE TITLE
General considerations for the device explorer refactor

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#473]
## To do

- [x] Remove the "additional" columns of the device explorer: min, max, etc.
- [x] Create a new panel (c.f. [doxygen](https://github.com/OSSIA/i-score/tree/master/Documentation/Doxygen) & [tutorials](https://github.com/OSSIA/iscore-addon-tutorial/tree/master/Tutorial/Panel)); let's call it AddressPanel since it will show an address.
- [x] This panel should contain a class inheriting from QAbstractItemModel and another from QListView.

The QAbstractItemModel class, (let's say AddressModel) should have as model a Device::DeviceExplorerNode instance and its path in the device explorer.

Every attribute of the object should then be displayed; to do this just reimplement rows(), columns(), data(), etc as mentioned here: http://doc.qt.io/qt-5/modelview.html.

The panel should in some way be connected to the DeviceExplorerView of the DeviceExplorerPanel. We can then connect to the `selectionChanged()` method to reload the AddressModel whenever the user selects a new node.

**Comment by bltzr** [comment]
@jln- did some mockups for that:
![ecouzab](https://cloud.githubusercontent.com/assets/113982/26643671/5d42e212-4632-11e7-991f-3d24e111444a.png)
(yes, it's a little dark)

**Comment by bltzr** [comment]
we also discussed adding a value-dependant widget (such as a colorbox for colors, a slider for values, etc...) just below the value row

Also, there are more mockups by Julien in https://www.dropbox.com/sh/94w1d8dnp7pagbg/AAD6xfL9hE1A8085w_q6dHL1a?dl=0

**Comment by jcelerier** [comment]
the base for this is done, remaining work is adding more widgets for specific types, let's make other issues for this
