### ISSUE TITLE
oscquery device 'disconnected' state should be more visible

### ISSUE THREAD

**Issue by pchdev** [ossia/score#477]
currently, the device's name is in italic when disconnected, which is not really visible in the device explorer. Maybe put it in red? or with some sort of highlight?

**Comment by LouisHLAV** [comment]
Hey!
I'm interested in tackling this issue.
Would appending  "(disconnected)" to the device's italicized name help? E.g., _`Device X (disconnected)`_

![Example of connected vs. disconnected devices](https://user-images.githubusercontent.com/43889220/197309446-9963429f-5712-4fdf-99df-6f4ad2fff948.png)

**Comment by jcelerier** [comment]
hello !
yes, that would be a pretty good way to do it I think :)

it should be relatively straightforward in the code: simply check for "disconnected" in the "name" case here and return the modifed version.

 https://github.com/ossia/score/blob/master/src/plugins/score-lib-device/Device/ItemModels/NodeDisplayMethods.cpp#L118 (function `deviceNameColumnData`)

please ping me directly here or on discord if you have issues with the build, I recommend using this script to set-up a proper development environment & build: https://github.com/ossia/score/blob/master/tools/developer.sh !

**Comment by jcelerier** [comment]
closing, thanks again @LouisHLAV !
