### ISSUE TITLE
b22 crash when refreshing namespace while playing

### ISSUE THREAD

**Issue by avilleret** [ossia/score#485]
with b22, I got a crash when refreshing a device namespace while playing (yes I'm crazy)
no bt for now, but should be easy to reproduce
the device was an openFrameworks application with ofxOSSIA

**Comment by jcelerier** [comment]
yeah, when refreshing all the nodes are deleted / recreated so if any was being used in an automation it would crash. I'd rather prevent refreshing during execution because else it would mean introducing mutexes everywhere which would give a non-negligible performance hit...

**Comment by avilleret** [comment]
disable refreshing while playing is fine for me

**Comment by avilleret** [comment]
or what about a quick and automatic stop, refresh, play-from-where-I-stop sequence ?

**Comment by jcelerier** [comment]
> or what about a quick and automatic stop, refresh, play-from-where-I-stop sequence ?

I don't think that it could be quick if it's a big device, so it would make the show lag a bit at least. Did you try automatic update of oscquery ? Normally it should work.

**Comment by avilleret** [comment]
lag is OK for me and would be always shorter than clic stop, update and then clic play from here

btw, what is automatic update of oscquery ?

**Comment by jcelerier** [comment]
> btw, what is automatic update of oscquery ?

normally if a node is added in the remote device it should appear in real time in i-score.

**Comment by jcelerier** [comment]
should work now too
