### ISSUE TITLE
UI: can't drag&drop a read only param in mapping source

### ISSUE THREAD

**Issue by avilleret** [ossia/score#486]

**Comment by jcelerier** [comment]
ah yes, this is because dragging "get" addresses has been explicitely disabled (so that they don't end up in states IIRC... @bltzr you requested this I think ?).

**Comment by jcelerier** [comment]
something that I could do is put the address anyway in the "drag" if there is only one address selected. This way it won't break the "copy all addresses recursively" behaviour of states, and when somebody wants to drag an address explicitely, it will be here.

**Comment by bltzr** [comment]
> something that I could do is put the address anyway in the "drag" if there is only one address selected. 

actually, this is precisely what @pchdev and myself requested, and I'm pretty certain this was already the case when drag'n'dropping addresses into states..

**Comment by jcelerier** [comment]
> and I'm pretty certain this was already the case when drag'n'dropping addresses into states..

nope, a "get "address was never put in the "drag" no matter what.

**Comment by bltzr** [comment]
ah OK, so we just discussed it then

**Comment by bltzr** [comment]
or maybe I dreamt it
