### ISSUE TITLE
b22 : fail to load a second scenario

### ISSUE THREAD

**Issue by avilleret** [ossia/score#487]
when a scenario is already open, I try to open a second one, but a popup appears and say that it is already open, which is indeed wrong

**Comment by jcelerier** [comment]
can you send your scenarios ?

**Comment by pach** [comment]
Le second serait il un copier/coller/renommer du premier? Auquel ca il faut si je ne m'abuse ouvrir le xml pour changer le nom du scénario principal.

Thomas Pachoud 
www.creapach.fr

**Comment by avilleret** [comment]
here they are :
[example.zip](https://github.com/OSSIA/i-score/files/1084187/example.zip)
And yes they share the same base.score_json parent file, then I used "Save As..." to make different versions.

**Comment by jcelerier** [comment]
ah, yes, that won't work (but it should of course).

**Comment by pach** [comment]
Maybe SaveAs should also rename the base scenario? But won't change
anything if we do copy/paste?
Or the main scenario should check that he got the same name as the file?


----- ----- -----
Thomas Pachoud
creapach.blogspot.fr
assoikari.wordpress.com
----- ----- -----
la campagne pour le FabLAboriGène de l’Amer
<https://www.helloasso.com/associations/dans-le-meme-bateau/collectes/le-fablaborigene-de-l-amer>
est
engagée!
-----

**Comment by jcelerier** [comment]
when doing "Save As", should the "current" scenario be the one that was saved to ? 
e.g. if I do : 

* New scenario
* edit stuff
* Save > foo.scorejson
* edit stuf
* Save As > bar.scorejson
* edit stuff
* Save

does the last save replace foo.scorejson or bar.scorejson ? 

If it's bar.scorejson I will have to clear the command stack when doing "save as...". Is this a problem ?

**Comment by jcelerier** [comment]
> But won't change anything if we do copy/paste?

I'm currently checking all the code to look for problems such as this. Hopefully this should be ok

**Comment by avilleret** [comment]
After I do `Save as foo` I want to edit foo
Instead I'll do a `Save a copy as` or something else
