### ISSUE TITLE
Auto-scroll of execution

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#493]
Maybe it could be tracking the position of the execution on the top constraint ? It will be weird if the scenario is for instance entirely contained in a loop though...

**Comment by bltzr** [comment]
we've discussed that in the past and, ideally, it should push whatever hasn't been executed (e.g. stuff after untriggered triggers) to the right along the way
I guess that's not for tomorrow, tho

**Comment by jcelerier** [comment]
Idea: keep zoom so that all the intervals currently playing are being shown

**Comment by jcelerier** [comment]
auto-scroll implemented since 3.0.2

**Comment by bltzr** [comment]
Oh
My 
Goddess!!!!

I need to try this!!!!

**Comment by bltzr** [comment]
Is there anything special to do in order for this to work?
Because I didn’t manage to have it scrolling in 3.0.3

**Comment by jcelerier** [comment]
View > Auto-scroll

**Comment by bltzr** [comment]
Oh thanks!
Shouldn’t that be a preference instead ? (real question)
IS it only based on the main interval?

**Comment by bltzr** [comment]
> Is it only based on the main interval?

Because I don’t find the current behaviour super efficient when there are triggers and/or interval speeds are changed

**Comment by jcelerier** [comment]
It will follow the currently selected interval and the main interval if
there are none. No idea of how to of it better without changing the whole
thing at execution time..

**Comment by bltzr** [comment]
If I remember well, we discussed having the possibility to change the Zoom level at runtime, in order to always have the latest and the first "cursors" (ie position of currently running intrvals) visible, but maybe that’s overkill?
