### ISSUE TITLE
[feature request] ui : display point value next to mouse when editing automation/interpolation curve

### ISSUE THREAD

**Issue by avilleret** [ossia/score#495]
when I select a curve point, its value appear in the inspector
but when I'm moving it the value is not updated while moving
thus it is hard to put it at an accurate position
would be great to display the updated value of the point (and maybe its time position) while dragging it next to the point/mouse

**Comment by jcelerier** [comment]
sounds like a good idea! would a tooltip be ok ? 

also, maybe this could be useful for states ? e.g. you hover a state and you have a tooltip that shows you its content... but this could be complicated for long lists of states

**Comment by bltzr** [comment]
yes, maybe that'd be heavy for states (not sure I'm for it)
but, definitely, that would be *very* useful for breakpoints as a tooltip
👍 💯 🥇
