### ISSUE TITLE
"Enter" on device context menu does not work

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#497]

**Comment by eirikblekesaune** [comment]
An explanation of how to reproduce (running 17ec7c76115f9e43ac4fe0b2976691171ee42f3b) on OS X.

Control clicking on a child (/my_float) shows a drop down menu. The drop down menu indicates that pressing enter should open the edit menu. Pressing the menu item in the menu opens the edit window correctly.
But, pressing the enter button while the chidl being selected only starts (textual) edit mode in the name or value widgets.

Maybe shift+enter would be a better keycombo for opening the edit window for this functionality? Then you could keep the name and value editing functionality which is good to have, and presumably i already used by other users?
