### ISSUE TITLE
Hovering tips for widgets items

### ISSUE THREAD

**Issue by eirikblekesaune** [ossia/score#498]
The user would be able to optionally turn on hovering tips for widgets. In general the UI for i-score has a lot of button, which is good. Buttons are nice.

But it would be good to have some short descriptions of the functionality for the widgets, and possibly a link to a helpfile.

These two images are examples of interfaces that I can't intuitively understand. This coming from the perspective of a first time user.
 
![lotsohbuttons1](https://user-images.githubusercontent.com/2708566/27378156-46d68f60-5677-11e7-8a2b-221773a1d9f1.jpeg)
![unknownbuttons](https://user-images.githubusercontent.com/2708566/27378160-49a909f2-5677-11e7-811a-0866a05a51fb.jpeg)

**Comment by jcelerier** [comment]
newer versions now have an info panel which displays infos on hover :-)
