### ISSUE TITLE
The trigger should be glowing in green too 

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#512]

**Comment by pchdev** [comment]
in reference to the dearly departed #522 issue, maybe draw an animated explicit circle around the T symbol or something like that too? 
...
jcelerier added [ergonomy **harder**] labels : )))

**Comment by bltzr** [comment]
we've ben discussing adding animated gifs in i-score, maybe that would be a good place to start ?
(just kidding)
apart from the stupid joke, I'm not so sure about the circle...

**Comment by pchdev** [comment]
I'd say, problem raised here is that the T symbol **points** to the state, so we'd have to somehow redirect intuitively the click, not on the state itself but on the T symbol. So, I don't know if the glowing will help, we ought to try it first I guess

**Comment by jcelerier** [comment]
done, thanks to @aklevy
