### ISSUE TITLE
"encapsulate" command to group a set of objects in a scenario.

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#514]

**Comment by bltzr** [comment]
there should also be a "encapsulate into a loop", or even "loop this" ?
this would:
- cut the selected content
- create a constraint of the same size than the "encapsulated" content (or a tiny little bit more)
- create a loop process
- create a scenario process on the pattern
- paste the  selected content inside this sub-scenario
- (maybe add a trigger at the end of the loop... not sure about this... what do you think @jln- and @lossius ?)

**Comment by jcelerier** [comment]
that's been done for a long time, let's open other issues for specific problems with the current implementation (I think there's already one)
