### ISSUE TITLE
Reflexion about "play tool"  icon

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#516]
* stethoscope
* mouse cursor should change
* drop-down menu ? 
* triangle with 1 inside
* triangle with circle inside

**Comment by lossius** [comment]
I suggest the following:

<img width="73" alt="screen shot 2017-06-21 at 14 12 09" src="https://user-images.githubusercontent.com/38478/27383549-c8ceada4-568b-11e7-8b6e-77df2768652b.png">
