### ISSUE TITLE
allow trigger triggering by clicking on the state

### ISSUE THREAD

**Issue by bltzr** [ossia/score#522]
not only on the trigger object
(that's a requestion from @lossius )

**Comment by pchdev** [comment]
hmm that might be dangerous in case you only want to read the info of the state in the inspector, no ?

**Comment by jcelerier** [comment]
I'm in favor of not doing this.

**Comment by bltzr** [comment]
Actually I'm not so much in favor of doing it either, but maybe that means that we need to improve the trigger's affordance at execution time (like making it blinking, as proposed in #512 )
should I close the issue ? I'm doing it, please feel free to reopen it if necessary
