### ISSUE TITLE
add automation/mapping/etc... parameters to the local tree

### ISSUE THREAD

**Issue by bltzr** [ossia/score#523]
especially min and max

**Comment by jcelerier** [comment]
hmm.. I remember why it isn't done : how should it interact with undo-redo ?

**Comment by bltzr** [comment]
hmmm.... my first thought is that this shouldn't be included in the undo/redo stack
i.e. if the user wants to change this from some mapping or automation, then they accept the consequences
this said, I think that's a very interesting and powerful feature, so I wouldn't forbid it (if it's not hard to implement as such, without undo/redo support)

**Comment by bltzr** [comment]
duplicated in #671
