### ISSUE TITLE
Display file path for scenarios

### ISSUE THREAD

**Issue by eirikblekesaune** [ossia/score#529]
It would be nice to see the file path of the scenario that I'm working on.

In some applcations the filepath is displayed in the OS top line, so in i-score it could be:
`i-score - 1.0.0-b23 - "/Users/i_am_a_boy/i-scoreStuff/MyComposition.jsonscore"`

**Comment by jln-** [comment]
In some others it is when right-clicking in the window name (ie. Max)

**Comment by jcelerier** [comment]
done
