### ISSUE TITLE
macOS "recover document" menu ends up behind the splash screen

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#535]

**Comment by eirikblekesaune** [comment]
Enter keyboard event is caught by the recover window so for now we can get the application up and running despite this bug.

**Comment by jcelerier** [comment]
reported here: https://bugreports.qt.io/browse/QTBUG-61592?filter=-2

**Comment by DocSunset** [comment]
I noticed a situation in which score appeared to be frozen on startup, but in fact there was a dialog box saying "the desired audio preferences could not be applied." which was behind the splash screen. Perhaps another form of this same issue?
![screen shot 2018-11-28 at 3 21 28 pm](https://user-images.githubusercontent.com/17572588/49180136-d5b9e400-f321-11e8-82bc-638f3df2c399.png)
![screen shot 2018-11-28 at 3 21 31 pm](https://user-images.githubusercontent.com/17572588/49180141-da7e9800-f321-11e8-9e70-5a9ecfe0d9f1.png)

**Comment by jcelerier** [comment]
thanks for the report, it's not the same issue but this one can be handled more easily I'd say

**Comment by jcelerier** [comment]
fixed, the new start screen should be implemented as to not have this problem
