### ISSUE TITLE
color scheme issues

### ISSUE THREAD

**Issue by bltzr** [ossia/score#540]
this is to be discussed with @stirem

we have to address: 
- [ ] progress "bar" (which is green on cyan, hence not so visible...) @blacksound was proposing using strong color contrasts

- [ ] color-blindness

please feel free to add, @jln- @lossius  and others

**Comment by eirikblekesaune** [comment]
The cyan blue is 0x22C3DB. The complementary is orange 0xE37C2A.
Here how the proposed colors look:

![coloeurs](https://user-images.githubusercontent.com/2708566/27425387-890f3d48-5738-11e7-9ad5-a67e4c22d024.jpeg)

**Comment by lossius** [comment]
This discussion came up when talking about accessibility with respect to colour blindness. We should confer with @stirem on this.

The following is a useful tool to see how the program looks for users with various kinds of colour blindness:

https://michelf.ca/projects/sim-daltonism/

**Comment by jln-** [comment]
Colorwise, maybe constraints could be just grey, so the focus is on processes racks.

Line thickness may also be reduced, while keeping the current progression bar thickness ?

**Comment by jcelerier** [comment]
@blueyeti will certainly be interested by this issue
