### ISSUE TITLE
Contextual menu for javascript editor slots

### ISSUE THREAD

**Issue by eirikblekesaune** [ossia/score#545]
When trying to open a contextual menu for a javascript code editor slot, the contextual menu for a code editor opens instead and then colors are transparent. See image:
<img width="284" alt="codeeditorcontextmenubug" src="https://user-images.githubusercontent.com/2708566/27428886-a975826c-5743-11e7-8631-9dc072f3b4eb.png">

Shouldn't it be possible to open a contextual menu for the slots instead?

**Comment by jcelerier** [comment]
fixed
