### ISSUE TITLE
Confusion between Control-C and Control-V for copy-paste

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#55]
Do we copy the contents or the elements by default ? 
How to paste elements from the top menu ?

**Comment by theod** [comment]
@jcelerier : do you need user inputs here ? if yes, could you give some problematic examples ?

**Comment by bltzr** [comment]
> Do we copy the contents or the elements by default ? 
> I'd say yes
> How to paste elements from the top menu ?
> You mean, where are they put on the timeline ?
> Maybe roughly on the topleft corner of the editing window ?

**Comment by nvuaille** [comment]
> > Do we copy the contents or the elements by default ? 
> 
> I'd say yes

@bltzr , what did you mean ?

**Comment by bltzr** [comment]
I mean that, yes, we copy the contents or the elements by default
(that was JM's question)
i.e. messages are copied with a state, or processes with a constraint

**Comment by nvuaille** [comment]
hmmm ...
I thought (and think) that 
contents = states/processes
elements = event/constraint (= temporal structure)

So I understood the question like that : "On copy action, do we copy states/processes to put it in another event/constraint or do we copy event and constraint to put in another place of the scenario ?

**Comment by bltzr** [comment]
> Le 29 janv. 2016 à 17:56, nvuaille notifications@github.com a écrit :
> 
> hmmm ...
> I thought (and think) that 
> contents = states/processes
> elements = event/constraint (= temporal structure)
 
 I think so, too
> So I understood the question like that : "On copy action, do we copy states/processes to put it in another event/constraint or do we copy event and constraint to put in another place of the scenario ?

 I’d say it depends if an element of the same kind is selected (then merge) or not (then create new element with content)

agree ?

**Comment by nvuaille** [comment]
Ohhhh yep, I was so far away ... -_- but finally I've got it !

So yes, I agree : no choice on copy but on paste. We paste as new element by default but, if selection allow it we paste the content in the selected thing.

**Comment by bltzr** [comment]
is that OK for you @jcelerier ? should that be postponed to 1.1 or is this something quick ?

**Comment by jcelerier** [comment]
hmm in hindisght it honestly seems a bit weird to merge. I fixed ctrl-v so that it would just paste new elements on click; merging can be another action accessible from the menus.

**Comment by bltzr** [comment]
agreed
