### ISSUE TITLE
Spline control points are lost off widget bound

### ISSUE THREAD

**Issue by eirikblekesaune** [ossia/score#559]
When moving spline points outside the widget bound, I can't seem to reach them if a point is placed outside the bounds of the spline process view bounds.

Attached is a score withone spline process with control points off view bounds.

[SplinePointsOffScreen.scorejson.zip](https://github.com/OSSIA/i-score/files/1095313/SplinePointsOffScreen.scorejson.zip)

**Comment by eirikblekesaune** [comment]
Here is an image of the result:

![splinepointoffviewbounds](https://user-images.githubusercontent.com/2708566/27442559-de599720-5770-11e7-958f-751078075d84.jpeg)

**Comment by jln-** [comment]
This is discussed in a general spline discussion (https://github.com/OSSIA/i-score/issues/459) so closing this for now.
