### ISSUE TITLE
Focus issues when recording with a selection

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#58]
On the first right-click everything will be deselected.

On the second right click, "Record from here" appears in the context menu.

What is the expected behaviour ?

**Comment by theod** [comment]
is it normal to have to do 2 right-click to access to something ?
it seems not a very common way to do.
anyway the menu start to be to messy and we are going far away from the initial idea to work with tools (Play tool, Record tool, Selector tool, ...).

I add @reno-, @bltzr, it seems to me that is not a relevant issue and we have to think out of the box here.

**Comment by jcelerier** [comment]
this seems to be no longer relevant

**Comment by reno** [comment]
Hey all,

I think you missed a character at the end of this username. This is not the
reno you're looking for.
