### ISSUE TITLE
interpolation process UI design

### ISSUE THREAD

**Issue by bltzr** [ossia/score#580]

**Comment by bltzr** [comment]
we've discussed with @lossius the design of the interpolation process UI
we thought it should stand a little more apart than the plain automation process
maybe something like this ?
<img width="449" alt="oziez" src="https://user-images.githubusercontent.com/113982/27494454-40e34cdc-584e-11e7-9263-37dc9d7ec98c.png">

**Comment by jcelerier** [comment]
disabling the interpolation process, it will have to be remade at some point but as such it's very broken
