### ISSUE TITLE
crash when removing empty device

### ISSUE THREAD

**Issue by bltzr** [ossia/score#592]
this happened because I closed ossia-pd first

https://gist.github.com/bltzr/ebb22ad745e4c4b82990da6eb51ca466

**Comment by bltzr** [comment]
I had another similar case, after killing pd (because it wouldn't close), so the device didn't look empty, but it obviously wasn't there (even if still appearing in the zeroconf list of the Add Device panel)
So I guess this is related to some bug in pd... even though it's always better if i-score is able to cater with this kind of mayhem (and not crash)

**Comment by jcelerier** [comment]
yes, the crash is a bug in i-score

**Comment by jcelerier** [comment]
this one should be ok now
