### ISSUE TITLE
little selection glitch after selecting triggers and conditions

### ISSUE THREAD

**Issue by bltzr** [ossia/score#593]
as demonstrated below:
![glitch-selection-cond](https://user-images.githubusercontent.com/113982/28370891-c5330980-6c9b-11e7-9c93-5ecab18b4dd4.gif)
![glitch-selection-trig](https://user-images.githubusercontent.com/113982/28370890-c530cd32-6c9b-11e7-9988-cdd745eb70d3.gif)

**Comment by jcelerier** [comment]
finally fixed that one !

**Comment by bltzr** [comment]
Oh yeah, GG! That was a nasty one !
