### ISSUE TITLE
Code signing for the release

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#594]
https://msdn.microsoft.com/en-us/library/ms537361(v=vs.85).aspx

https://developer.apple.com/support/code-signing/

**Comment by bltzr** [comment]
yes, I guess not having to workaround the "can't open this app because it's not verified" (or so) would help adoption ;-)

**Comment by jcelerier** [comment]
we now have an EV code signing cert and an Apple dev account :-)

**Comment by jcelerier** [comment]
everything has been code signed for quite some time noew
