### ISSUE TITLE
Usability or Help section/introduction movie

### ISSUE THREAD

**Issue by willosof** [ossia/score#596]
You need help people out a bit here. I'm certain that this application is perfect for what I want to do, but to understand how this works, you need to be psychic.

Usability or at least some self-evident stuff would be preferred over help section.

**Comment by jcelerier** [comment]
thanks for the issue! Stuff to help learning the software are lacking right now but we are working on it.

**Comment by jcelerier** [comment]
documentation has been greatly improved: https://ossia.io/score-docs/ - please reopen if it's still not understandable enough :)
