### ISSUE TITLE
Listening bug if node is expanded while playing / recording

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#60]
It will start to be listened, and then will not be listened anymore, when stop is pressed.

Also there might be problems if a node that was recorded was folded during recording.

Finally we have to take care of the interactions that might happen with the API, for instance if a trigger is waiting for a message.

**Comment by theod** [comment]
I close this issue as there is a more generic issue opened recently : https://github.com/OSSIA/i-score/issues/85
