### ISSUE TITLE
alternate edition mode: scale both processes around the moved timenode

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#601]

**Comment by jcelerier** [comment]
Implemented it like this: 
![col](https://user-images.githubusercontent.com/2772730/28715582-f1224886-7398-11e7-9b40-54037e629bfd.gif)

Is it ok @blueyeti  ?
also what should be the keyboard shortcut to modify processes like this ? All the cmd, alt, shift, etc... are already taken it seems...

**Comment by bltzr** [comment]
this is great ! thanks @jcelerier & @blueyeti for doing this!

I guess we should think this along with the several questions around the "lock" mode (i.e. #585  and #491 ) - I'll add a section for that in the specs google doc

for now, maybe we could use one of the available keys (m ?)

**Comment by bltzr** [comment]
that's happening with alt, now, right @jcelerier ?

**Comment by jcelerier** [comment]
yes
