### ISSUE TITLE
bug in loop if pattern as 2 inside scenario

### ISSUE THREAD

**Issue by pach** [ossia/score#606]
The loop process seems to have quite a bug when the pattern as two embbed scenario.
![bug_loop2scenar](https://user-images.githubusercontent.com/365923/28992562-4104eb26-79a0-11e7-8159-56868b2d71a4.gif)
The second scenario is read only on first loop.

Here is a simple example scenario : 
https://gist.github.com/pach/1275981c33d28a997536fc9c395343b8

**Comment by jcelerier** [comment]
quite interesting, thanks!

**Comment by jcelerier** [comment]
it was just some variables not being reinitialized. do you want me to make a release for this ?

**Comment by pach** [comment]
I guess they will be a future release up to the 21 of august?
I'm in vacations up to there. :)

**Comment by jcelerier** [comment]
ok, yeah there will be ! good vacations :)



-------
Jean-Michaël Celerier
http://www.jcelerier.name
