### ISSUE TITLE
crash when opening a file with a device existing in the former project

### ISSUE THREAD

**Issue by theod** [ossia/score#62]
to reproduce it you can save a project with a newDevice Minuit device for example.
then you can restart i-score, create a new Minuit device and then try to open the project you saved before. at this point you should have a warning window and then a crash

[crash log.txt](https://github.com/OSSIA/i-score/files/28097/crash.log.txt)

**Comment by jcelerier** [comment]
I think that the problem, more generally, is of multiple documents binding on the same device, since everything seems to be located in a global table. What should be done ?

**Comment by theod** [comment]
I would say the document notion is for scenario only. if we open several projects with their own network setup each but with a same device (with the same name I mean), I would warn the user and then keep only one device. so the network explorer will display a kind of merge of all network setups.

but this need to be discussed with @bltzr, @reno- and @jln-.

one potentiel problem I see with this approach is what have to be saved once all devices are in the same tree. each document have to remember which device belong to him to save only those ones.

**Comment by jcelerier** [comment]
I think that this may cause further problems with the local devices of the scenarios that would be loaded :/

**Comment by jcelerier** [comment]
okay, to solve this for now I added the ability to disconnect / reconnect devices; the devices of the current document will be automatically disconnected  and reconnected when switching between multiple documents and a disconnected device will be shown in italic in the device explorer (it can be re-enabled by hand with a right-click, but this should not be necessary unless for instance you want to run multiple instances of i-score, or if you have a program running on the same port and you don't want to quit i-score).

**Comment by jcelerier** [comment]
It would be nice if this would be a service of the OSSIA API instead, because for now I have to re-check everywhere in the scenario to recreate the nodes that I am removing when disconnecting.

**Comment by jcelerier** [comment]
This is in master and can be tested from now.

**Comment by theod** [comment]
this not crashing anymore.
thanks !
