### ISSUE TITLE
preferences' zoom level doesn't affect interval's thickness on startup

### ISSUE THREAD

**Issue by bltzr** [ossia/score#629]
I'm pretty sure it did a while ago...

**Comment by bltzr** [comment]
(it works in b28)

**Comment by bltzr** [comment]
actually when the zoom level has been set to some value, this value is not recalled at startup (e.g. with a zoom level of 50%, when creating a new scenario, it will appear as a 100% thickness, and will get updated only when changing the zoom level value again)
![zooom](https://user-images.githubusercontent.com/113982/33025762-1d647358-ce0f-11e7-91f3-e03cd9ec9449.gif)

**Comment by jcelerier** [comment]
zoom is handled differently now which fixes that
