### ISSUE TITLE
Address setValueType is never called when loading a project

### ISSUE THREAD

**Issue by theod** [ossia/score#63]
int the explorer the displayed value is always 1025 !

![capture d ecran 2015-11-05 a 16 37 32](https://cloud.githubusercontent.com/assets/118426/10972956/ce8b1e6e-83db-11e5-9b48-260b2c6f6efa.png)

**Comment by theod** [comment]
when I store the value it is also the same bad value 

![capture d ecran 2015-11-05 a 16 40 35](https://cloud.githubusercontent.com/assets/118426/10973015/01623ee4-83dc-11e5-816c-afbb46fdf989.png)

**Comment by theod** [comment]
it happens systematically for a the [j.parameter controller @type none] as it is an Impulse value.

**Comment by theod** [comment]
@jcelerier in case you have an idea if it is more related to the core than to the gui ?

**Comment by theod** [comment]
I found a case where the problem happens. I've renamed the issue to focus on this case.

**Comment by theod** [comment]
now there is no more request when loading a project the Address are not well loaded from a saved project. I mean if I put a break point into JamomaAddress::setValueType and I load the joined project we never pass into it (remove the .txt extension at the end of the file name !).

[bug - address not typed.scorejson.txt](https://github.com/OSSIA/i-score/files/28547/bug.-.address.not.typed.scorejson.txt)

this is resulting in none typed Address so the value is never correctly initialized (even if a value come from a Max patcher thru listening answer as without type the conversion failed) and so it reminds NULL.
then it appears that i-score displayed NULL values as 1025.

**Comment by jcelerier** [comment]
@theod  could you test with what's in master ? thanks!

**Comment by theod** [comment]
it works ! thanks
