### ISSUE TITLE
score doesn't like spaces in OSC addresses when learning

### ISSUE THREAD

**Issue by bltzr** [ossia/score#635]
for instance, Millumin sends messages in this format:
/millumin/layer:layerName/opacity 0.53

when learning, those get duplicated at every incoming message to:
millumin:/millumin/layerName.1/opacity
millumin:/millumin/layerName.2/opacity
and so on...

**Comment by bltzr** [comment]
in the case of Millumin, this is the equivalent of our ```.``` 
Though I don't know if we should generalize upon that... 
but, if ```:``` is a problem in libossia, maybe we could replace it with ```.```  and see how it turns out for other softwares...

**Comment by bltzr** [comment]
FYI just tried [ossia.parameter source:2] in ossia-max and that didn't pose any problem

**Comment by bltzr** [comment]
now I noticed that score doesn't like spaces in addresses (Millumin does that, too...) so I'm reopening, and renaming the issue

**Comment by bltzr** [comment]
the behavior is the same (adding instances)

**Comment by jcelerier** [comment]
![oh no](http://avatar.amuniversal.com/feature_avatars/recommendation_images/features/wn/large_wn_rec_201706020930.jpg)

**Comment by jcelerier** [comment]
now it works
