### ISSUE TITLE
graphically indicate in the editor the selection of several elements 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#637]
those include (TBCompleted):

- [x] process view (also make them selectable from the process background)
 
- [x] triggers 

- [x] conditions (actually we can select the white bar of an event, but it could be useful to also be able to select the yellow bar+C of the condition itself, and that this be visible somehow)

**Comment by jcelerier** [comment]
> but it could be useful to also be able to select the yellow bar+C of the condition itself, and that this be visible somehow)

sleecting it like this is already possible. how would it look when selected ?

**Comment by bltzr** [comment]
maybe by becoming blue, like the others ? or with a blue outline ?
also for triggers, I guess...

**Comment by jcelerier** [comment]
done in 2.2.1
