### ISSUE TITLE
interpolation process should be changed to interpolating between states

### ISSUE THREAD

**Issue by bltzr** [ossia/score#640]
as discussed in Bergen and actually advertised in the online documentation, interpolation should happen between states, and not between parameters \@type tuple
(yes, I know, I'm the culprit for that, but people change, Steven)

**Comment by bltzr** [comment]
well actually, http://i-score.org/process-overview-interpolation/ kind of mixes between address and state, but I can commit to updating once this process is also updated

**Comment by jcelerier** [comment]
hmmm... what happens : 

* for "special" types, eg string, impulse, list("hello", list(1, 2, 'c')) ?
* when a message is only at the start or end state ?

**Comment by bltzr** [comment]
> hmmm... what happens :
> for "special" types, eg string, impulse, list("hello", list(1, 2, 'c')) ?
when a message is only at the start or end state ?

I'd say: nothing

**Comment by bltzr** [comment]
if this cannot be done before the 1.0 release, we should remove this process

**Comment by bltzr** [comment]
I've been thinking about this for a while, and here's a workflow proposal that will hopefully:
- make it easy to quickly create interpolations,
- allow to split interpolations into separate automations when possible
- allow to be able to still use interpolations for parameters where automations would be complicated (aka lists with many items)
- allow to unify this with the "interpolate between states“ function

So, that would somehow extend the workflow proposed in #659 and creating interpolations or automations depending on the dropped parameters :
- if there is just one uni-dimensionnal parameter, then an automation is created as described in #659 (this could be extended to do the same with a set of uni-dimensionnal parameters... to be discussed, I can see pros and cons to that)
- if there are some other parameters, then we create an interpolation. 

As announced in the issue title, this refactoring of the interpolation process would deal with __*states*__ instead of just multi-dimensionnal parameters (which was confusing, as @lossius argued).
Here, we consider a __*state*__ as a general set of parameter-value pairs, not just as a State object in score (while the latter is a sub-item of the former category). Sorry for using the same word, I hope discriminating with the Capital and italic+bold will help make it clear enough.
That's probably an implementation detail, but I guess this hypothesis would imply that the Interpolation process deals with two internal __*states*__, which could be fused with the adjacent States (more on this later).

So, basically, an Interpolation process would hold two internal __*states*__ (i.e. sets of parameter-value pairs), say A and B, and would, for each parameter, allow to interpolate the value between this parameter's value in A (when the curve is at the bottom) and its value in B (when the curve is at the top). Of course, this would only happen for numerical values (including vecnfs and numerical elements of lists).

On the UI side of things:
- for the curve edition, I would still stick to what was proposed in #580 , ie. something like this (of course implemented in the current score's design style):
<img width="449" src="https://user-images.githubusercontent.com/113982/27494454-40e34cdc-584e-11e7-9263-37dc9d7ec98c.png">
in this example, state A could be dropped in the light blue section, and state B in the darker part, in order to define or update it (namespace and/or values)

- for the inspector, what about something like this:
<img width="449" src="https://user-images.githubusercontent.com/113982/39767703-a83573e4-52e7-11e8-9316-c152c3351d44.png">


explanations:
  - in this case, that would be a tweened interpolation, which implies that, for each parameter, the value would be fetched at the beginning of the process, and then interpolated according to the designed curve. That's why the first value column is empty here.
  - for each parameter, there would be a "turn into automation" button (or maybe just "-> automation") that would remove the chosen parameter from the interpolation, and create an automation process with the interpolation values for the beginning and end (and also tween enabled if it was for the interpolation). If one of those is a vecnf or a list, then we create as many elements as the parameter contains (and if some of those, for a list, are not automatable, aka symbols, then we don't create any automation for it - anyway, it wouldn't have been interpolated)
  - I added a checkbox, so we can turn off interpolations for certain parameters. Also, non-eligible parameters would not be interpolated (of course), and displayed as such. Both of those are arguable, and could be left off.
  - If some values or parameters are missing from the start or end state, then they are not interpolated (and the line is greyed out, as is the string parameter in the example), as demonstrated below:
<img width="449" src="https://user-images.githubusercontent.com/113982/39768631-3398788a-52ea-11e8-873d-d4373a37aca1.png">



Well, basically, that's it.

Now, the relationship with the States: 
Just like it was defined in #659, if the interpolation was created by dropping a set of parameters on an interval:
- if no State was present at any side of the interval, then the set of parameter-value pairs (aka __*state*__) will be assigned to __*state*__ B of the Interpolation process, and the tweening will be enabled
- if there is a State at the beginning of the interval, then we use this one for __*state*__ A (left column, top part of the curve editor) and use the dropped __*state*__ for __*state*__ B. 
- if there was only an end State, then we use the set of parameters from the dropped __*state*__ for __*state*__ B, with the values of those parameters from the end State (and leave the end State as is, more on this later), and we enable the tweening
- if there were States both at the beginning and the end, then we use the start State as __*state*__ A and the dropped __*state*__ as __*state*__ B.

If the Interpolation process was created by adding a process (plus button on the interval, right-click in the Objects window, whatever....):
- if no State was present at any side of the interval or if there is a State at the beginning of the interval, then the Interpolation is empty and awaits information.
- if there is only an end State, then we use the end State as __*state*__ B and tween.
- if there were States both at the beginning and the end, then we use the start State as __*state*__ A and the end State as __*state*__ B.

Also, when using the "Interpolate between States" button from the menu, that would do just the same as this last case (use both States to create an Interpolation), instead of creating a bunch of automations. 

We could also add a "turn all into automations" button (as demonstrated in the second mockup) which would... well... create an automation for each of the parameters.

Now once the Interpolation is already created, the content of __*states*__ A and B can be changed (values can be updated or parameter/values can be added) by dropping a set of parameters from the Device Explorer (DE) onto each of the zones from the interpolation (e.g. top/dark zone for A, bottom/light zone for B, see below).
What seems interesting in this is that, it allows to realize what was signaled in https://github.com/OSSIA/score/issues/530#issuecomment-310732380 : we can stop the interpolation before it comes to its end. 
We can also do a kind of "bell" shape, as proposed @lossius : 
![interpolationbell](https://user-images.githubusercontent.com/113982/39767165-5cc72868-52e6-11e8-89ce-bdd71c7d225b.png)
 
And, if we use the start or end States for creating the Interpolation __*states*__, they can be deleted at a later time without losing the Interpolation contents.

So, basically: if there are start or end States, we use their __*states*__ for the Interpolation, and if we manually add __*states*__ (e.g. by drag'n'dropping sets of parameters from the DE), they take over.

What do you guys think ? @jcelerier @jln- @avilleret @pach @reno-  (well @OSSIA/users  basically)

I probably forgot things, but then I'll add them in further comments.

**Comment by bltzr** [comment]
Update: for those reading this in their email client, I'd advise going online as I've been editing the comment a bit, and some images also didn't show up in the first version

**Comment by bltzr** [comment]
also @thibaudk @pchdev

**Comment by bltzr** [comment]
I don't think I mentionned #480 but that be could helpful to review it in order to know how to create automations for single parameters

**Comment by bltzr** [comment]
big question: AFAIK interpolations are not used anywhere anymore currently
should we keep them ? and if we do, how should they be used ?
ping @jln-

**Comment by jcelerier** [comment]
disabling the interpolation process, it will have to be remade at some point but as such it's very broken
