### ISSUE TITLE
local tree: send play / stop messages ?

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#647]

**Comment by bltzr** [comment]
can you elaborate a little ?
send to or from score ?

**Comment by jcelerier** [comment]
from score to the stuff connected to the local tree

**Comment by bltzr** [comment]
yep, that would be good - can't it just "listen" to the existing parameters ?

**Comment by jcelerier** [comment]
sure, but currently the "parameters" aren't triggered from the UI (there is no explicit notion of "parameter" in C++).

**Comment by bltzr** [comment]
ah OK, then +1
