### ISSUE TITLE
unexpected offset on graphical blue bounds of a time constraint

### ISSUE THREAD

**Issue by theod** [ossia/score#65]
here is a picture of what seems strange to me when I saw the green time vert progressing more than expected.

![capture d ecran 2015-11-06 a 01 32 56](https://cloud.githubusercontent.com/assets/118426/10986128/8eb5c0c2-8427-11e5-9fdb-eae9fd471230.png)

the trigger condition is always true so I would expected the time bar to stop at the beginning of the round blue bound instead of the end of the transparent blue zone.

but maybe it is just me and others (@bltzr, @reno- , @jln- , @avilleret ) have another point of view ?

**Comment by reno-** [comment]
I agree…

**Comment by nvuaille** [comment]
It's not really a bug. If you set min = max, the bounds will form a circle : that's mean that the exact date is in the center of the arc ( = end of transparent zone). But I agree, that's surprising !
