### ISSUE TITLE
[feature-request] drag & drop parameter on trigger 

### ISSUE THREAD

**Issue by pchdev** [ossia/score#654]
taking parameter address as target for expression evaluation (default to pulse ?)

**Comment by bltzr** [comment]
shouldn't we do the same for conditions ? (not sure because we don't have a default behavior, aka pulse, for conditions... but that might help anyway, might it not ?)

**Comment by jcelerier** [comment]
example of drag'n'drop:  

for events : 

1. reimplement dropEvent on TriggerView like this: https://github.com/OSSIA/score/blob/master/base/plugins/score-plugin-scenario/Scenario/Document/Event/EventView.cpp#L174

2. redirect like this in TimeSyncPresenter for instance https://github.com/OSSIA/score/blob/master/base/plugins/score-plugin-scenario/Scenario/Document/Event/EventPresenter.cpp#L96

3. another example for instance in the automations, with more mimetypes handled: https://github.com/OSSIA/score/blob/master/base/plugins/score-plugin-automation/Automation/AutomationPresenter.hpp#L63

**Comment by bltzr** [comment]
@pach !

**Comment by avilleret** [comment]
this should have been fixed with 7c2107c5f47c0d7ecd24c4db9c8d82619823e4b3

please try and feedback

**Comment by bltzr** [comment]
does work indeed
