### ISSUE TITLE
drag'n'drop of processes

### ISSUE THREAD

**Issue by bltzr** [ossia/score#655]
- [x] On peut “jeter” le process en-dessous pour créer un nouveau ‘slot’ - du coup, on montre celui qui était en-dessous de la pile de layers (s’il n’y en a qu’un, on ne peut rien faire)

- [x] Si on jette un process (placé en-dessous (below) ou au-dessus (above) sur un slot existant, il se met sur la layer supérieure.

- [ ] Si on enlève tous les processes sur une pile, le slot disparaît, comme une pile de cartes, en fait

**Comment by bltzr** [comment]
- [x] on peut insérer un process entre deux autres

**Comment by jcelerier** [comment]
>  on peut insérer un process entre deux autres

comment qu'on fait ça ?

**Comment by bltzr** [comment]
comme ça:
![insert](https://user-images.githubusercontent.com/113982/40584223-9d62619c-619d-11e8-8e1e-5fbf8d576c0f.gif)

**Comment by bltzr** [comment]
that could be also a way to reorder processes (in addition to the objects view, as requested by @evanmtp in #761

**Comment by jcelerier** [comment]
sooo... a bit like this ?
![rec-2018-05-27_13 49 06 1](https://user-images.githubusercontent.com/2772730/40584633-9954f0cc-61a4-11e8-85bf-43c1f7b0111a.gif)

**Comment by bltzr** [comment]
well, **exactly** like this !

thanks a lot !

**Comment by jcelerier** [comment]
well, it's done then :p please test
