### ISSUE TITLE
move the tool panel on top of the score panel

### ISSUE THREAD

**Issue by theod** [ossia/score#661]
as all tools / modes are related to time operations on the score.
as it is now it is also on top of the explorer panel while nothing is related to it

**Comment by bltzr** [comment]
is that a hard one, @jcelerier  ?

**Comment by jcelerier** [comment]
hmmm... I don't really know to be fair. Currently it just uses Qt's default thing which works like this :
http://doc.qt.io/qt-5/qmainwindow.html#details

to do it by hand means not using QMainWindow's toolbar stuff (here: https://github.com/OSSIA/score/blob/master/base/lib/core/presenter/Presenter.cpp#L117 ) but instead make this class: https://github.com/OSSIA/score/blob/master/base/lib/core/document/DocumentView.hpp 
a QWidget, show it and reparent its child "DocumentViewDelegate" to it while also adding the toolbars to it (with an explicit [QToolbar](http://doc.qt.io/qt-5/qtoolbar.html), for instance in a QHboxLayout with the toolbar on top and the document at the bottom.).

**Comment by bltzr** [comment]
I'd say: let's forget about this, that's not very critical (and this is an euphemism)

**Comment by jcelerier** [comment]
clsoing, there's no easy way to do this right now
