### ISSUE TITLE
X translation threshold

### ISSUE THREAD

**Issue by bltzr** [ossia/score#662]
from #585 (now closed), this comment might be worth reviewing and acting upon 

> @blueyeti said when we met last week that, in his opinion, the problem came from a bad interaction design, and that there should be a kind of motion threshold in order to avoid moving things by mistake when grabbing them
he said he would also review other softwares in order to see what's the best way to do all of this
so I'm assigning to him

**Comment by jcelerier** [comment]
done for states in 08ca014de ; please test the new movement behaviour. I tried on intervals also but there it feels more natural if they can always move.
