### ISSUE TITLE
change logo for #601

### ISSUE THREAD

**Issue by bltzr** [ossia/score#663]
the current one is probably suboptimal

**Comment by bltzr** [comment]
see #601

**Comment by bltzr** [comment]
did you forget this one, @jln- ? or is it on the workbench ?

**Comment by jln-** [comment]
I did not forget. Just wasn't totally convinced by my idea. Still am not but pushed for test. See https://github.com/OSSIA/score/commit/2c82df7dd2fac70c2af3148af9b9d479882003ce

**Comment by bltzr** [comment]
well... this mode allows to move an event between two intervals... and the logo shows only one interval, to the left... maybe adding another one to the right would be more relevant (and IMHO acceptable)

**Comment by jln-** [comment]
Oh! Something apparently went wrong with the SVG exports (png were ok). Fixed now in https://github.com/OSSIA/score/commit/e5eebdc844a690e702c1818da78054f7930e8815
