### ISSUE TITLE
remove edit window for parameters

### ISSUE THREAD

**Issue by bltzr** [ossia/score#668]
since all of its attributes can now be changed from the device explorer's inspector

**Comment by jcelerier** [comment]
That's  `DeviceExplorerWidget::edit()` in DeviceExplorerWidget.cpp

Also the code in AddressItemModel.cpp should be continued to provide: 

* Custom value editors according to the dataspace & min / max; eg color choosers, 2d pads, angle choosers, etc ; a lot of types aren't handled either
* Handle properly all the "optional" attributes, eg description, etc. Currently it's a mess.

**Comment by bltzr** [comment]
I'm not sure it's so important to remove it, actually... it doesn't really bother anybody since it's not invoked
