### ISSUE TITLE
Javascript process needs testing

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#67]
As the result of some experiments this week-end, i-score inherited a new process, which allows to write javascript code at run-time that will be executed on each tick of the process.

Here is some example code  to put in the text box in the inspector when such a process is added to the constraint : 

```
(function(t) {
  var obj = new Object;
  obj["address"] = 'OSCdevice:/millumin/layer/x/instance';
  obj["value"] = t + iscore.value('OSCdevice:/millumin/layer/y/instance');
  return [ obj ];
});
```

Some informations : 
- `t` is the relative time in the process, between 0 and 1 if I am not mistaken.
- The function shall return an array of messages which will form a state together. A message is simply an object with an `address` and a `value` field.
- One can fetch values from the tree tree with the `iscore.value(address)` function which is for now the only "i-score Javascript API" function.
- There will be nothing displayed if the code is invalid - patches welcome!

Please test.

**Comment by theod** [comment]
waouh !
I've managed to create an edit the code of a javascript process but I cannot test it at execution time due to the issue #71.

**Comment by theod** [comment]
about the syntax : 
is Object could be rename in Message and have two initialization arguments for address and value ? 
in order to allow for example : 

var msg = new Message('OSCdevice:/millumin/layer/x/instance', t);

this would allow quick Message management.

**Comment by jcelerier** [comment]
paging @cbossut for this

**Comment by theod** [comment]
it works perfectly at execution time !

**Comment by reno-** [comment]
Whaoou !! Exciting !!
