### ISSUE TITLE
waveform range management is a little bit weird

### ISSUE THREAD

**Issue by bltzr** [ossia/score#670]
from my tests, it seems that one needs to change the min/max values before they are actually taken into account
![nonsinse](https://user-images.githubusercontent.com/113982/31508882-c5c167e4-af7f-11e7-8b78-dff00b954696.gif)
![sinology](https://user-images.githubusercontent.com/113982/31508881-c5a19342-af7f-11e7-8e27-9bb0d85efc10.gif)

also, this Min/max kind of duplicates the shift-vertical drag way of setting the range of the waveform

last but not least, there is no relation from the start and end points of the waveform and the values at which the waveform starts and ends (so that causes leaps....)

would it be possible that the waveform modulates over the segment (i.e. applying a sine on a segment like this:
<img width="388" alt="capture d ecran 2017-10-12 a 19 06 45" src="https://user-images.githubusercontent.com/113982/31509097-8bed1094-af80-11e7-9e73-426e4a73d4c7.png">
would do something like this:
<img width="377" alt="capture d ecran 2017-10-12 a 19 10 45" src="https://user-images.githubusercontent.com/113982/31509260-31c48164-af81-11e7-9661-09347aee3cb6.png">
of course, not exactly this (because in this case some Xs have several Ys)
what do you think @jcelerier ?

**Comment by jcelerier** [comment]
> would it be possible that the waveform modulates over the segment (i.e. applying a sine on a segment like this:

this wouldn't change the discontinuities... if you can change frequency, start, and end there's no way around it. Maybe this should be a separate LFO process instead ?

**Comment by jcelerier** [comment]
another possibility to get continuity is to do something like this: 
<img width="756" alt="capture d ecran 2017-10-12 a 19 56 01" src="https://user-images.githubusercontent.com/2772730/31511344-ba412df2-af87-11e7-945a-20959bc0e255.png">

(sin(x) * exp(-x^2))

**Comment by bltzr** [comment]
yes, I guess a LFO process would be the right way to handle this: it's convenient as is (or is it ?) but not really manageable for all usages

**Comment by jcelerier** [comment]
since there is now a LFO process, I would propose a removal of the waveforms in automation since it's a bit buggy. @OSSIA/core  ?

**Comment by bltzr** [comment]
👍

**Comment by jcelerier** [comment]
I'll let this for a week and if no one manifests... off they go

**Comment by bltzr** [comment]
it's been a month and no one manifested, so they should go - RIP and amen little waveforms !
