### ISSUE TITLE
control attribute of process

### ISSUE THREAD

**Issue by pach** [ossia/score#671]
If you do want to control in real time the range of a mapping (or automation or anything), you need to be able to control min and max range (through the local tree for example)

**Comment by bltzr** [comment]
oh yes, please please please !!!

**Comment by jln-** [comment]
:thumbsup:

**Comment by bltzr** [comment]
I guess this one needs your contribution @jcelerier ?

**Comment by bltzr** [comment]
(if that's not too hard, in which case, it'll have to wait)

**Comment by jcelerier** [comment]
that's relatively easy to do ; here's an example for instance for min / max of automation ; currently doing it for addresses is not possible easily though.

```c++
#pragma once
#include <Engine/LocalTree/Scenario/ProcessComponent.hpp>
#include <Automation/AutomationModel.hpp>

namespace Engine
{
namespace LocalTree
{
class AutomationComponent : public ProcessComponent_T<Automation::ProcessModel>
{
  COMPONENT_METADATA("49d55f75-1ee7-47c9-9a77-450e4da7083c")

public:
  AutomationComponent(
      const Id<score::Component>& id,
      ossia::net::node_base& parent,
      Automation::ProcessModel& proc,
      DocumentPlugin& ctx,
      QObject* parent_obj)
      : ProcessComponent_T<Automation::ProcessModel>{
          parent, proc, ctx, id, "AutomationComponent", parent_obj}
  {
    m_properties.push_back(add_property<double>(
        node(), "min", &proc,
        &Automation::ProcessModel::min,
        &Automation::ProcessModel::setMin,
        &Automation::ProcessModel::minChanged, this));
    m_properties.push_back(add_property<double>(
        node(), "max", &proc,
        &Automation::ProcessModel::max,
        &Automation::ProcessModel::setMax,
        &Automation::ProcessModel::maxChanged, this));
  }

private:
  std::vector<std::unique_ptr<BaseProperty>> m_properties;
};

using AutomationComponentFactory = ProcessComponentFactory_T<AutomationComponent>;
}
}
```

and then add it to the list in score_plugin_engine.cpp after Engine::LocalTree::LoopComponentFactory

**Comment by bltzr** [comment]
isn't that the same thing than #523 ?

**Comment by bltzr** [comment]
min and max is already very very cool, and actually what most of us would dream of!

**Comment by bltzr** [comment]
could you please also add min and max for in and out of the mapping process @avilleret ?

**Comment by avilleret** [comment]
> could you please also add min and max for in and out of the mapping process @avilleret ?

this is almost done

**Comment by avilleret** [comment]
anything else @bltzr  ?

I mean for this issue... I still have a long list to address

**Comment by bltzr** [comment]
nope, thanks, that’s enough for this issue - I’ll fix it once it’s tested (soon)
