### ISSUE TITLE
crash on load on OSX 10.9

### ISSUE THREAD

**Issue by avilleret** [ossia/score#672]
a fresh build made with build.sh on 10.12 with the option -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 added to the configuration step crashes on load on 10.9.2

here is the log : 
https://gist.github.com/anonymous/ec6a87134cf8e344ab54a52d3a3fb847

**Comment by jcelerier** [comment]
I think that recent versions of Qt stopped supporting 10.9 anyways. :(
