### ISSUE TITLE
Transport buttons dont reflect Score status (paused/stopped)

### ISSUE THREAD

**Issue by jln-** [ossia/score#674]

**Comment by bltzr** [comment]
what should they show ?

**Comment by jln-** [comment]
Maybe stop button could stay yellow once it has been pressed and until play is clicked again ?

This way we could identify when Score is playing/paused or when stop (hence at the beginning)

**Comment by bltzr** [comment]
yes, makes sense

**Comment by jcelerier** [comment]
I implemented the same behaviour than in other sequencers: no more "pause" icon, the play icon just becomes lighted when it's playing
