### ISSUE TITLE
domains don't seem to work for parameters @type list / vecnf

### ISSUE THREAD

**Issue by bltzr** [ossia/score#679]
there even isn't a domain field in the edit window: that's when adding a parameter in a hand-made OSC device

**Comment by bltzr** [comment]
domains are also not displayed for remote vecnf and list params, as demonstrated below:
![vecrange](https://user-images.githubusercontent.com/113982/39759850-10db7db2-52d4-11e8-99f8-f710e1df4329.png)
maybe that's related to https://github.com/OSSIA/libossia/issues/386 ?
anyway, we should maybe do a little checkup on the whole range/domain stuff in libossia...

**Comment by bltzr** [comment]
this now works for remote parameters - thanks @jcelerier ! 

though, there still isn't any support for domains for hand-made created list parameters in OSC devices (the initial topic of this issue). Is that worth keeping this issue open ? Do we really need this ?

**Comment by jcelerier** [comment]
> though, there still isn't any support for domains for hand-made created list parameters in OSC devices (the initial topic of this issue). Is that worth keeping this issue open ? Do we really need this ?

yes, it's a bit harder to implement but I think that it should be available at some point

**Comment by bltzr** [comment]
I guess we should do that as part of #356 
for other, undetermined tuples (aka ```@type generic``` in Jamoma), I don't think it's necessary to self-inflict headaches on that
