### ISSUE TITLE
removing triggers doesn't set the previous constraints to "non-flexible" again

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#681]

**Comment by nvuaille** [comment]
unit test ? =P

**Comment by avilleret** [comment]
@nvuaille PR are welcome :-)

**Comment by bltzr** [comment]
this is only when pressing backspace after selecting a trigger - if we disable the trigger from the inspector, the previous interval is set to rigid as usual - so I guess we just forgot to include this in the specifications when @avilleret implemented the new deletion policy

**Comment by avilleret** [comment]
haha ! this will be my joker : "sorry, this was not in the specs !" ;-)
