### ISSUE TITLE
use logo for the play tool

### ISSUE THREAD

**Issue by bltzr** [ossia/score#683]
knowing that this tool allows to:
- send the content of a state when clicking on a state
- play an interval (from its beginning) and everything that follows when clicking on an interval
- play the whole (sub-)scenario from a certain date when clicking somewhere (at this date) in the background

**Comment by jln-** [comment]
I sketched this at some point. How does that sound (just a quick and dirty test, here) ?
![capture d ecran 2017-11-20 a 16 28 47](https://user-images.githubusercontent.com/114325/33026173-1ea8e7c0-ce10-11e7-8f0e-e4a3ebf4458f.png)

**Comment by bltzr** [comment]
why not... this implies the idea of inspecting something when it's actually triggering it, but unless someone has a better idea, let's use this

**Comment by bltzr** [comment]
done in 66bfdec4

**Comment by bltzr** [comment]
two things:
- what if we used a kind of eyedropper (aka color picker) instead of the magninfier ? it conveys the idea of probing rather that  just inspecting, which is maybe more appropriate ?
- this didn't make it to v2, so I'm reopening the issue (@jln- actually made the logo, but it was never used, is called playfromhere_*.*)

**Comment by bltzr** [comment]
i'm also changing the issue name to reflect the fact that it needs to be added to the implementation

**Comment by jln-** [comment]
> what if we used a kind of eyedropper (aka color picker) instead of the magninfier ? it conveys the idea of probing rather that just inspecting, which is maybe more appropriate ?

Nice idea ! +1

**Comment by jcelerier** [comment]
new logo implemented (thanks @aklevy)
