### ISSUE TITLE
little + for object creation shouldn't be influenced by zoom level

### ISSUE THREAD

**Issue by bltzr** [ossia/score#686]
or it gets very small when the zoom level goes down
e.g. for a zoom level of 50% we get this:
![capture d ecran 2017-11-25 a 10 47 55](https://user-images.githubusercontent.com/113982/33229397-2476129c-d1ce-11e7-96f1-b7872f602cb8.png)

could you point me to where this can be changed @jcelerier ?

**Comment by jcelerier** [comment]
i don't think we'll be able to change that easily: the zoom now uses Qt's feature which zooms / unzooms the whole UI
