### ISSUE TITLE
Object window: don't display parent if child count < 2

### ISSUE THREAD

**Issue by avilleret** [ossia/score#687]
- N’afficher les syncs que si il y a un trigger || il y a >= 2 events
- N’afficher les events que si il y a une condition || il y a >= 2 states

**Comment by bltzr** [comment]
ça paraît logique
ouisque c'est là qu'on voit  les syncs/events

**Comment by bltzr** [comment]
in the case below, the trigger should be shown, if that's not too much of a headache to fix this (if it is, I guess we can live with this behavior)
![capture d ecran 2017-12-04 a 12 54 54](https://user-images.githubusercontent.com/113982/33551723-8f1144ca-d8f2-11e7-995a-71d2d4d299d2.png)

 (as is the case when selecting a lonely state with a condition)
![capture d ecran 2017-12-04 a 12 56 57](https://user-images.githubusercontent.com/113982/33551746-a325094c-d8f2-11e7-953c-a00396a99118.png)

**Comment by bltzr** [comment]
I'm putting this back into "in progress", if it's a headache, please feel free to put it into Done, and we'll look into it some day in the future when we'll be rich and have a zillion developers
