### ISSUE TITLE
there are gaps in the object window

### ISSUE THREAD

**Issue by bltzr** [ossia/score#689]

**Comment by bltzr** [comment]
<img width="785" alt="capture d ecran 2017-11-27 a 12 55 35" src="https://user-images.githubusercontent.com/113982/33271786-7c9a6f52-d388-11e7-8aa4-5d424e6eb20a.png">

**Comment by jcelerier** [comment]
does this still happen ? I tried to reproduce this configuration but I don't have gaps

**Comment by jcelerier** [comment]
closing due to lack of reproducibility
