### ISSUE TITLE
don't push value when loading a project

### ISSUE THREAD

**Issue by theod** [ossia/score#69]
when I load a project I can see that some stored values are pushed to Max.
it happens in iscore2OSSIA::setValue(OSSIA::Address& addr, const iscore::Value& val).

as I'm not sure the use of this function I prefer to assign it to you @jcelerier .

by the way I'm wondering why values are stored into the network tree ?
I would expect that all Address attributes to be stored except the value itself as it is supposed to be handled by States and Messages of the Scenario.

**Comment by jcelerier** [comment]
> I would expect that all Address attributes to be stored except the value itself as it is supposed to be handled by States and Messages of the Scenario.

How could we display the value in the device explorer if it's not stored anywhere ? I'm not sure I understand.

I'm looking into the setValue issue asap

**Comment by theod** [comment]
I add @bltzr, @reno, @jln- and @avilleret here because it is an interesting question but I think you should simply query the values which are unfold and visible in the tree.

I don't know if the fold/unfold state of the network tree is saved in the project, but if not it will should have no query at the loading and then when the user will explore the tree it will query values.

and if the fold/unfold state is saved this not a problem anymore as some values will be queried but not all the tree some it shouldn't take too much time.

**Comment by jcelerier** [comment]
Sure but I still have to store them somewhere (due to the Qt tree API). Besides it would mean that nothing would be displayed as values when loading if there isn't an external device ?

**Comment by theod** [comment]
IHMO it makes no sens to display the state of something that doesn't exist.
by the way maybe the interface should explicit the fact the Address has no value (e.g. nullptr) using a grey color of a - into the value column ... not sure what is the easiest to code for you ?

**Comment by theod** [comment]
but please wait for more points of view before to change this as maybe others are not agree with me

**Comment by theod** [comment]
here is a gist with what Max received and which generates errors and open Audio Status window
https://gist.github.com/theod/f85877ca00192d7139d0

**Comment by bltzr** [comment]
that doesn't seem to be the case anymore, could you please test, @theod ?

**Comment by jcelerier** [comment]
I also think that this has been fixed a long time ago. Please reopen if it's not the case of course !
