### ISSUE TITLE
configuring with CMake 3.10 fails

### ISSUE THREAD

**Issue by avilleret** [ossia/score#690]
here is a full output : 

https://gist.github.com/avilleret/d1a73ab0b3e02bc2bf763f37b8092d9d

switching back to 3.9.6 works

on Archlinux 4.11.12-1-rt16-MANJARO

**Comment by bltzr** [comment]
same on MacOS

**Comment by jcelerier** [comment]
seems to work on cmake 3.10 and 3.11
