### ISSUE TITLE
objects created (or encapsulated) offtime should have a trigger by default

### ISSUE THREAD

**Issue by bltzr** [ossia/score#694]
![loop-it-cond](https://user-images.githubusercontent.com/113982/33560951-7a33d9cc-d911-11e7-828f-5dd8fe8a0728.gif)

**Comment by bltzr** [comment]
![floating-cond](https://user-images.githubusercontent.com/113982/33561054-d9c25184-d911-11e7-946d-d40f65eeb3da.gif)

**Comment by bltzr** [comment]
I guess this is caused by the (uncommon) situation when the start state has been deleted, so when creating the state, it doesn't find any predecessor to connect to

**Comment by bltzr** [comment]
so maybe we should just prevent the start state from being deleted, because that also breaks the automatic connection stuff a lot - would that be sensible/doable ?

**Comment by bltzr** [comment]
after some tests, this is unrelated to the start state being deleted, which is another problem, and will be addressed in another issue

**Comment by bltzr** [comment]
this also simply happens when double-clicking in the scenario's background

**Comment by bltzr** [comment]
@jcelerier says they should have a trigger by default - I second his proposal!

**Comment by bltzr** [comment]
they don't have a condition anymore in v2, but I think they should definitely have a trigger, so I'm keeping the issue and changing its title

**Comment by jcelerier** [comment]
by default things won't be offtime anymore when dropped so I think that this can be closed

**Comment by bltzr** [comment]
could be nice to have a way to create things offtime with a shortcut or something, though (like holding alt while drag'n'dropping).... what do you think @OSSIA/users ?

**Comment by jcelerier** [comment]
you can just double-click in the background to start an "offline scenario"

**Comment by bltzr** [comment]
OK, and then you drag from there, right ?

could be nice to include this in the doc, in https://ossia.github.io/score/first_steps/time_approach/index.html#out-of-time-events don't you think so, @jln- ?
