### ISSUE TITLE
sometimes min and max bounds are shown when encapsulating a scenario fragment

### ISSUE THREAD

**Issue by bltzr** [ossia/score#697]

**Comment by bltzr** [comment]
![capture d ecran 2017-12-05 a 09 44 09](https://user-images.githubusercontent.com/113982/33599116-698240de-d9a5-11e7-8d16-87661a70f42d.png)

**Comment by jcelerier** [comment]
I also had this happen just when creating an interval sometimes

**Comment by jcelerier** [comment]
Fixed
