### ISSUE TITLE
crash when trying to create a sequence

### ISSUE THREAD

**Issue by theod** [ossia/score#70]
steps to reproduce : 
- create an event
- change the value of /mydegrade/audio/gain to -96 in Max
- drag the value of /mydegrade/audio/gain to the event
- change the value of /mydegrade/audio/gain 0 in Max
- pomme+shift from the event to create sequence
  => crash

![capture d ecran 2015-11-09 a 14 57 15](https://cloud.githubusercontent.com/assets/118426/11035369/52a724b8-86f2-11e5-857e-5e8242ca2b44.png)

**Comment by jcelerier** [comment]
Should be fixed by 8c82d6c

**Comment by theod** [comment]
fixed ! thanks
