### ISSUE TITLE
add a way to create processes on the main constraint

### ISSUE THREAD

**Issue by bltzr** [ossia/score#702]
that could be a little + widget, like on any other interval

or is there a reason why this is impossible, @jcelerier ?

**Comment by jcelerier** [comment]
well for now there is a workaround: right click on the object inspector and you can add process from here

**Comment by jcelerier** [comment]
I think that the little + was there before but I removed it because you couldn't really click on it

**Comment by bltzr** [comment]
what if we added this little + somewhere in the main header ? 
like, on the left, where the collapse arrow lays for non-main headers ?

**Comment by jcelerier** [comment]
with all the drag'n'drop possible nowadays, is this still necessary ?

**Comment by jcelerier** [comment]
I'm of the opinion that the little "+" has to go to be replaced by drag'n'drop of processes from thel library anyways, what do you think ? (what is currently in the space used for the little + could instead be speed control / pause)

**Comment by jcelerier** [comment]
closing - drag'n'drop works fine for this

**Comment by bltzr** [comment]
how do you create a mapping process with drag'n'drop ? from the library ?

**Comment by jcelerier** [comment]
yep
