### ISSUE TITLE
OSCquery on windows wont find devices

### ISSUE THREAD

**Issue by ofersmi** [ossia/score#704]
It's  a bit of a shot in the dark since there is not yet a manual for this, but I have tried with the OSSIA max external and with the OSSIA in vcvRack, and find devices doesn't work, my list is empty.
Also when I manually type in the ip and port I don't get any parameters list in the device that I created.  
I know its not the clearest bug report,,,,
version v1.0.0-b40 
OS windows10

Ofer

**Comment by jcelerier** [comment]
So, to do this we should use the built-in bonjour support in windows 10 : ideally there should be a new implementation done here: 

    https://github.com/jcelerier/Servus/tree/master/servus

which uses the functions here: 

    https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd

since Microsoft hates us, we have to use the WinRT binding for zeroconf, a bit like I did here for the UWP MIDI API : 

    https://github.com/jcelerier/RtMidi17/blob/master/rtmidi17/detail/winuwp.hpp

**Comment by jcelerier** [comment]
maybe we should investigate https://github.com/rampantpixels/mdns to see if it solves this

**Comment by jcelerier** [comment]
will finally be fixed in v3 :)
