### ISSUE TITLE
automation / gradient send weird values

### ISSUE THREAD

**Issue by pach** [ossia/score#705]
In last score (last version from jmc with dataflow and out of time trigger)
Gradient automation seems to send same anything but the color value.

<img width="450" alt="screen shot 2018-01-17 at 23 49 13" src="https://user-images.githubusercontent.com/365923/35072025-42949336-fbe3-11e7-802c-f9b2d454899f.png">

**Comment by pach** [comment]
or 
<img width="325" alt="screen shot 2018-01-18 at 00 05 47" src="https://user-images.githubusercontent.com/365923/35072072-5e5ea20a-fbe3-11e7-9aa1-706d8c837c17.png">
which is still wrong

**Comment by jcelerier** [comment]
hmmm... weird: I just did a small test and here's what I've got: 
![weird](https://user-images.githubusercontent.com/2772730/35148063-2101aef0-fd11-11e7-9078-4569fd72cbd9.png)

this seems correct to me: first I have mostly red an green, then mostly green, then red and blue which makes pink

**Comment by jcelerier** [comment]
this should be fixed, there was a problem when the units weren't argb
