### ISSUE TITLE
can't play a scenario 

### ISSUE THREAD

**Issue by theod** [ossia/score#71]
when I click on play nothing happen !

here is the scenario I made to test it (please remove the .txt)
[bug - play.scorejsont.txt](https://github.com/OSSIA/i-score/files/30009/bug.-.play.scorejsont.txt)

**Comment by theod** [comment]
I assgin to you jcelerier because there were more changes into i-score than into the API but maybe I'm wrong (I didn't look further to see what happens here).

**Comment by jcelerier** [comment]
I sent you messages on skype about this, it looks like a problem in the recent API commits.

It works for API at 016777f but not 61a7101 after some bisect

**Comment by theod** [comment]
fixed !
