### ISSUE TITLE
problem with installation in linux

### ISSUE THREAD

**Issue by nick87720z** [ossia/score#715]
I tried to get it working under gentoo, as well as writing live ebuild. It seems, that not all files are installed, and some installed libs are in wrong location.

Cmake configuration:
https://gist.github.com/nick87720z/aeeb8c47a6f5894ef9ade1e19a533dc1

For what is installed, following commands are executed from build dir:
```
$ find ./destdir | sort | less
./destdir
./destdir/usr
./destdir/usr/bin
./destdir/usr/bin/score
./destdir/usr/libscore_lib_base.so
./destdir/usr/libscore_lib_device.so
./destdir/usr/libscore_lib_inspector.so
./destdir/usr/libscore_lib_process.so
./destdir/usr/libscore_lib_state.so
./destdir/usr/plugins
./destdir/usr/plugins/libscore_plugin_automation.so
./destdir/usr/plugins/libscore_plugin_curve.so
./destdir/usr/plugins/libscore_plugin_deviceexplorer.so
./destdir/usr/plugins/libscore_plugin_engine.so
./destdir/usr/plugins/libscore_plugin_inspector.so
./destdir/usr/plugins/libscore_plugin_js.so
./destdir/usr/plugins/libscore_plugin_library.so
./destdir/usr/plugins/libscore_plugin_loop.so
./destdir/usr/plugins/libscore_plugin_mapping.so
./destdir/usr/plugins/libscore_plugin_midi.so
./destdir/usr/plugins/libscore_plugin_pluginsettings.so
./destdir/usr/plugins/libscore_plugin_recording.so
./destdir/usr/plugins/libscore_plugin_scenario.so
```
Libs in /usr are more like to be in /usr/lib, /usr/lib64, /usr/lib32 (usually cmake handles this).

And for full list of compiled libs and exes - (content of destdir is cut):
```
$ find . -executable -type f | sort
./API/OSSIA/libossia.so
./base/player/libscore_player_plugin.so
./base/player/libscore_player.so
./base/plugins/score-plugin-deviceexplorer/Explorer/DeviceExplorer.qrc.depends
./CMakeFiles/3.9.6/CMakeDetermineCompilerABI_C.bin
./CMakeFiles/3.9.6/CMakeDetermineCompilerABI_CXX.bin
./CMakeFiles/3.9.6/CompilerIdC/a.out
./CMakeFiles/3.9.6/CompilerIdCXX/a.out
./CMakeFiles/CheckTypeSize/OFF64_T.bin
./CMakeFiles/feature_tests.bin
./CMakeFiles/git-data/grabRef.cmake
./NodeTest
./player
./player_device
./player_network
./plugins/libscore_lib_base.so
./plugins/libscore_lib_device.so
./plugins/libscore_lib_inspector.so
./plugins/libscore_lib_process.so
./plugins/libscore_lib_state.so
./plugins/libscore_plugin_automation.so
./plugins/libscore_plugin_curve.so
./plugins/libscore_plugin_deviceexplorer.so
./plugins/libscore_plugin_engine.so
./plugins/libscore_plugin_inspector.so
./plugins/libscore_plugin_js.so
./plugins/libscore_plugin_library.so
./plugins/libscore_plugin_loop.so
./plugins/libscore_plugin_mapping.so
./plugins/libscore_plugin_midi.so
./plugins/libscore_plugin_pluginsettings.so
./plugins/libscore_plugin_recording.so
./plugins/libscore_plugin_scenario.so
./score
./State_EqualityTest
./State_ExpressionTest
./State_SerializationTest
./State_UnitTest
```

Update:
by ldd - all libs in /usr depend on libossia.so, in some libossia.so appears 2 or 3 times:
```
$ ldd ./destdir/usr/libscore_lib_base.so | grep libossia
	libossia.so => not found
$ ldd ./destdir/usr/libscore_lib_device.so | grep libossia
	libossia.so => not found
	libossia.so => not found
	libossia.so => not found
$ ldd ./destdir/usr/libscore_lib_inspector.so | grep libossia
	libossia.so => not found
	libossia.so => not found
$ ldd ./destdir/usr/libscore_lib_process.so | grep libossia
	libossia.so => not found
	libossia.so => not found
	libossia.so => not found
$ ldd ./destdir/usr/libscore_lib_state.so | grep libossia
	libossia.so => not found
	libossia.so => not found
```

**Comment by nick87720z** [comment]
I made mistake with shared libs in /usr, they are in /usr/lib.
But another problem here, is that cmake options, which should configure libdir, do nothing here.
Even with -DINSTALL_LIB_DIR=/usr/lib64 it still installs to /usr/lib.

Issue with libossia.so is correct - after i install it manually to /usr/bin, "score" begins to work.

**Comment by jcelerier** [comment]
hmm... IIRC there is a setting to enable to respect the FHS. I don't have much time this week but starting from next week I'll try to overhaul the whole build stuff to fit better with linux distros - currently it's centerd about building AppImages that can work everywhere

**Comment by nick87720z** [comment]
SCORE_BUILD_FOR_PACKAGE_MANAGER: Set FHS-friendly install paths
this?

update: it is already set in ebuild (i just forgot about it)

**Comment by jcelerier** [comment]
ah yes, that's the one ! well, if it's not working I should debug it :p

**Comment by jcelerier** [comment]
the build has changed a lot since then, I'd recommend to use the same steps than the AUR package (which builds all of score's lib together statically, they are only useful as separate libraries during development to reduce compile time but it makes no sense to have them as separate libs for the releases): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ossia-score
