### ISSUE TITLE
Mapping and interpolation failure on Feature/Dataflow 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#716]
Attempting to map one of the values from an Array ignores the "@[...]" selection. Values are mapped sequentially and always starting from the first one.

The Interpolation process dosen't output anything, either withe single values or arrays.
The "Interpolate states" command still works perfectly tho (tested with 2048 FFT bins without a hiccup) 

![scoreprocesses](https://user-images.githubusercontent.com/26526517/37026812-d482069a-212f-11e8-8cb8-6ea607ed89df.gif)

Tested on Ubuntu Studio 17.10 commit: 
870359a2910637816e7b067a12ce3df283d33f92
09b12525860f0b1951fdb628a6fec0b932a0cf65

Works fine on Master branch

**Comment by jcelerier** [comment]
> The Interpolation process dosen't output anything, either withe single values or arrays.

yes, on the dataflow branch it has to be reimplemented. Same for the spline and metronome processes.

**Comment by thibaudk** [comment]
Actually, i relalised that th problem of addressing values at specific "@[]" indexes causes this issue only for mappings.

this day, on commit b83019e9bcbb2bd465aae8739f217d6c2b26fef0

automation can address indexes of an array perfectly.

VecNf or list Indexes set as source of mappings are ignored and only the first value of the array gets mapped.

VecNf or list Indexes set as target of mappings are ignored and the mapped value is copied at every indexes of the array.

**Comment by jcelerier** [comment]
thanks, that will be a great help to find the cause of the bug !

**Comment by thibaudk** [comment]
Awsome!!
This now works in the above example
on comit f2d45e56907cd004dc5950606131fee46b17e968

Will do further testing if needed but that seems to be fixed.
(is there a particular reason why this was reopened?)

**Comment by jcelerier** [comment]
yes, interpolation process still does not work

**Comment by thibaudk** [comment]
Oo yes that's true, the issue referenced both.
Mapping is all good then anyway!

Well done!

**Comment by thibaudk** [comment]
Should the interpolation process simply be removed ?

**Comment by jcelerier** [comment]
well it has been removed for a long time
