### ISSUE TITLE
Linking executable failed because of JACK support on Linux

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#719]
Could it be because I am using JACKD-2 or is it a libasound problem?

tested with Ubuntu Studio 17.10 on commit 406a1977afe242197d054797d02994e8c3275a4a

log:

[1641/1641] Linking CXX executable score
FAILED: score 
: && /usr/bin/c++  -O3 -march=native -std=c++1z -O3 -DNDEBUG  -rdynamic base/app/CMakeFiles/score.dir/Application.cpp.o base/app/CMakeFiles/score.dir/main.cpp.o base/app/CMakeFiles/score.dir/moc_Application.cpp.o  -o score  base/lib/libscore_lib_base.a base/lib/libscore_lib_base.a /usr/lib/x86_64-linux-gnu/libQt5QuickControls2.so.5.9.1 base/plugins/score-plugin-pluginsettings/libscore_plugin_pluginsettings.a base/plugins/score-plugin-inspector/libscore_plugin_inspector.a base/plugins/score-plugin-deviceexplorer/libscore_plugin_deviceexplorer.a base/plugins/score-plugin-curve/libscore_plugin_curve.a base/plugins/score-plugin-automation/libscore_plugin_automation.a base/plugins/score-plugin-scenario/libscore_plugin_scenario.a base/plugins/score-plugin-loop/libscore_plugin_loop.a base/plugins/score-plugin-mapping/libscore_plugin_mapping.a base/plugins/score-plugin-engine/libscore_plugin_engine.a base/plugins/score-plugin-media/libscore_plugin_media.a base/plugins/score-plugin-fx/libscore_plugin_fx.a base/plugins/score-plugin-js/libscore_plugin_js.a base/plugins/score-plugin-midi/libscore_plugin_midi.a base/plugins/score-plugin-recording/libscore_plugin_recording.a base/addons/iscore-addon-shaders/libscore_addon_shader.a base/addons/iscore-addon-staticanalysis/libscore_addon_staticanalysis.a -lX11 -Ofast -fno-finite-math-only -ffunction-sections -fdata-sections -Wl,--gc-sections -fuse-ld=gold -Wl,-z,defs -Wl,--threads -Wl,--thread-count,4 base/plugins/score-plugin-media/libscore_plugin_media.a -lavcodec -lavformat -lavutil -lswresample /usr/lib/liblilv-0.so -ldl /usr/local/lib/libfaust.a -ldl /usr/local/lib/libfaust.a -lssl -lcrypto -lcurses -lz -L/usr/lib/llvm-4.0/lib -lLLVM-4.0 base/plugins/score-plugin-js/libscore_plugin_js.a base/plugins/score-plugin-engine/libscore_plugin_engine.a base/plugins/score-plugin-loop/libscore_plugin_loop.a base/plugins/score-plugin-scenario/libscore_plugin_scenario.a base/plugins/score-plugin-automation/libscore_plugin_automation.a 3rdparty/Qt-Color-Widgets/libColorWidgets-qt5.a base/plugins/score-plugin-mapping/libscore_plugin_mapping.a base/plugins/score-plugin-deviceexplorer/libscore_plugin_deviceexplorer.a 3rdparty/QProgressIndicator/libQProgressIndicator.a API/3rdparty/Servus/servus/libServusQt.a base/plugins/score-plugin-curve/libscore_plugin_curve.a base/plugins/score-lib-device/libscore_lib_device.a /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.9.1 base/plugins/score-lib-process/libscore_lib_process.a base/plugins/score-lib-inspector/libscore_lib_inspector.a base/plugins/score-lib-state/libscore_lib_state.a base/lib/libscore_lib_base.a API/OSSIA/libossia.a /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5.9.1 API/3rdparty/ModernMIDI/libModernMIDI.a -lasound -lpthread /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.1 API/3rdparty/Servus/servus/libServus.a -lavahi-common -lavahi-client -ldns_sd /usr/lib/x86_64-linux-gnu/libportaudio.a -lpthread -fvar-tracking-assignments -gdwarf-4 -Wl,--dynamic-list-cpp-new -Wl,--dynamic-list-cpp-typeinfo /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.9.1 3rdparty/QRecentFilesMenu/libQRecentFilesMenu.a -Ofast -fno-finite-math-only -ffunction-sections -fdata-sections -Wl,--gc-sections -fuse-ld=gold -Wl,-z,defs -Wl,--threads -Wl,--thread-count,4 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.9.1 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.1 && :
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction GetStreamTime : erreur : référence à « jack_frame_time » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction GetStreamTime : erreur : référence à « jack_get_sample_rate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_get_sample_rate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_port_get_buffer » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_get_sample_rate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_frame_time » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_port_get_latency » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_port_get_latency » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_port_get_buffer » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction JackCallback : erreur : référence à « jack_port_get_buffer » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction RealStop : erreur : référence à « jack_port_connected » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction RealStop : erreur : référence à « jack_port_disconnect » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction RealStop : erreur : référence à « jack_port_connected » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction RealStop : erreur : référence à « jack_port_disconnect » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_port_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_port_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_connect » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_port_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_port_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction StartStream : erreur : référence à « jack_connect » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction CleanUpStream : erreur : référence à « jack_port_unregister » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction CleanUpStream : erreur : référence à « jack_port_unregister » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_client_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_get_sample_rate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_register » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_register » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_get_ports » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_by_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_get_ports » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_by_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_get_latency » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_get_buffer_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_port_get_latency » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_get_buffer_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction OpenStream : erreur : référence à « jack_frame_time » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction Terminate : erreur : référence à « jack_deactivate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction Terminate : erreur : référence à « jack_client_close » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_client_open » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_client_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_client_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_get_ports » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_client_name_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_get_ports » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_port_by_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_port_by_name » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_on_shutdown » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_set_error_function » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_get_buffer_size » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_set_sample_rate_callback » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_set_xrun_callback » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_client_close » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_set_process_callback » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_Initialize : erreur : référence à « jack_activate » non définie
/usr/lib/x86_64-linux-gnu/libportaudio.a(pa_jack.o):fonction PaJack_GetClientName : erreur : référence à « jack_get_client_name » non définie

**Comment by thibaudk** [comment]
Fixed with commit 5ad94e0f2f3b8e5314fc3b63db7753f785934489

Perfect!!

**Comment by thibaudk** [comment]
The same problem reacures with the latest commit
41e003d487dcf74739577a8d4eb2a1134d33dc30
And can be fixed in a similar way adding

    find_library(Jack_LIBRARY NAMES jack)
     if(Jack_LIBRARY)
      target_link_libraries(ossia PUBLIC ${Jack_LIBRARY})
     endif()

at 
https://github.com/OSSIA/libossia/blob/master/OSSIA/CMakeLists.txt#L286

Should this be added to this CmakeList.txt?

**Comment by jcelerier** [comment]
hmm, the fix should be in the file FindPortaudio.cmake at line 106 : it's detecting whether portaudio has been compiled with JACK support : if that's the case, then score should be linked against JACK.

Could you try to add some debug messages in the FindPortaudio.cmake: for instance at line 105, add 

    message("portaudio libs are : ${PORTAUDIO_LIBRARIES}") 

and then add a check after the condition (`if("${PORTAUDIO_LIBRARIES}" MATCHES ".*\.a")`) to check if it is entered correctly ?

**Comment by thibaudk** [comment]
This returns something a bit weird:

portaudio libs are : /usr/lib/x86_64-linux-gnu/libportaudio.a
-- Looking for PaJack_GetClientName in /usr/lib/x86_64-linux-gnu/libportaudio.a
-- Looking for PaJack_GetClientName in /usr/lib/x86_64-linux-gnu/libportaudio.a - not found
portaudio libs are : /usr/lib/x86_64-linux-gnu/libportaudio.a

and fails to build again,

Tested on Ubuntu Studio 18.04

**Comment by jcelerier** [comment]
why doth thy gods hateth me 

could you try replacing PaJack_GetClientName with PaJack_Initialize in the CMake ?

**Comment by thibaudk** [comment]
same result on the cmake:

portaudio libs are : /usr/lib/x86_64-linux-gnu/libportaudio.a
-- Looking for PaJack_Initialize in /usr/lib/x86_64-linux-gnu/libportaudio.a
-- Looking for PaJack_Initialize in /usr/lib/x86_64-linux-gnu/libportaudio.a - not found
portaudio libs are : /usr/lib/x86_64-linux-gnu/libportaudio.a
 
trying to build again ...

**Comment by thibaudk** [comment]
Yhea same problem

**Comment by jcelerier** [comment]
wait my code is wrong

could you replace the line with : 

      check_library_exists(${PORTAUDIO_LIBRARIES} PaJack_GetClientName "" PORTAUDIO_NEEDS_JACK)

by

      check_library_exists(portaudio PaJack_GetClientName "${PORTAUDIO_LIBRARIES}" PORTAUDIO_NEEDS_JACK)

**Comment by thibaudk** [comment]
Yes this worked! Thanks!

Sorry for the late reply.
Should I push this change?

**Comment by jcelerier** [comment]
yes please !

**Comment by thibaudk** [comment]
done
