### ISSUE TITLE
mapping: target range is wrong

### ISSUE THREAD

**Issue by theod** [ossia/score#72]
I've joined a simple scenario where I have created : 
- an automation on newDevice:/myinput/audio/gain from -96 to 12
- a mapping between newDevice:/myinput/audio/gain and newDevice:/myoutput/audio/gain (without touching the curve and the range bounds)

when I play the scenario the output gain is stuck on -96 until the input gain cross 0 and then it grows to ~7 dB.

is something wrong into i-score or is it an API problem ?

[bug - mapping bounds.scorejson.txt](https://github.com/OSSIA/i-score/files/30132/bug.-.mapping.bounds.scorejson.txt)

**Comment by jcelerier** [comment]
Mhh.. I just checked and for the curves function, I do (with values replaced according to what I see in the debugger): 

For the automation : 

```
    curve->setInitialValue(-96);
    curve->addPoint(
        OSSIA::CurveSegmentLinear<float>::create(curve), 1, 12);
```

For the mapping : 

```
    curve->setInitialValue(-96);
    curve->addPoint(
        OSSIA::CurveSegmentLinear<float>::create(curve), 12, 12);
```

**Comment by theod** [comment]
ok I'll do a test for this in OSSIA API

**Comment by theod** [comment]
ok I found !
it is simply because the Curve API is still oriented for temporal curve => starting from 0. !
in the Mapper case we must be able to fix the starting coordinate too.
I work on a branch to not break the compatibility with i-score.

**Comment by theod** [comment]
but this is raising a lot of questions ...
for example the code of valueAt() suppose that the curve is bijective which is not necessary the case for Mapper case. 

Maybe "Curve" should be renamed in "Bijection" ?

**Comment by theod** [comment]
and so maybe we should define something more generic on top of "Bijection" ? something like a "Function" or "Transformation" class that simply provide a method which takes a template X in argument and returns a Y ?

**Comment by theod** [comment]
and so a Mapper can work with any king of "Transformations" (including "Bijections") while Automation only work with "Bijections" ... thinking out loud ...

**Comment by theod** [comment]
so while the API don't provide such feature I would hide the Mapper plugin in i-score.

**Comment by bltzr** [comment]
What's the problem exactly? Not sure I get it from your previous comments 

Pascal Baltazar

**Comment by theod** [comment]
the problem is that for now you can only map between 0. to Y1 and X2 to Y2.
the API doesn't provide a way to change the 0. as the Curve class was designed to handle time progression from 0. ! and when I was thinking about allowing the access to the 0. a lot of questions raised.

**Comment by bltzr** [comment]
OK, thanks for the explanation, now I understand !

**Comment by bltzr** [comment]
it seems that this is now fixed
