### ISSUE TITLE
Operator error in IntervalHeader.cpp:49:21

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#720]
since commit 4faba241159aa6f8da2712b206f0a1e1850caab7
mak returns 
no match for ‘operator!=’ (operand types are ‘QCursor’ and ‘const QCursor’)
   if(this->cursor() != openCursor())
      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
It is the only error in the build. Tested on Ubuntu Studio 17.10.
Builds perfectly with full feature up until then.

full error output:
score/base/plugins/score-plugin-scenario/Scenario/Document/Interval/IntervalHeader.cpp:49:21: error: no match for ‘operator!=’ (operand types are ‘QCursor’ and ‘const QCursor’)
   if(this->cursor() != openCursor())
      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/QVector4D:1:0,
                 from /home/scrime/Documents/dev/score/base/lib/score/serialization/DataStreamVisitor.hpp:18,
                 from /home/scrime/Documents/dev/score/base/lib/score/prefix.hpp:68,
                 from /home/scrime/Documents/dev/score/build/base/lib/cotire/score_lib_base_CXX_prefix.cxx:4,
                 from /home/scrime/Documents/dev/score/build/base/lib/cotire/score_lib_base_CXX_prefix.hxx:4,
                 from /home/scrime/Documents/dev/score/build/base/plugins/score-plugin-scenario/cotire/score_plugin_scenario_CXX_prefix.cxx:4,
                 from /home/scrime/Documents/dev/score/build/base/plugins/score-plugin-scenario/cotire/score_plugin_scenario_CXX_prefix.hxx:4:

**Comment by jcelerier** [comment]
should be fixed now

**Comment by thibaudk** [comment]
Yes it is.
Chears!

**Comment by thibaudk** [comment]
For some reason this build perfect with Ninja but licking fails with make

here is the make log:

[100%] Linking CXX executable ../../score
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getTimeSyncs() const : erreur : référence à « std::allocator<Scenario::TimeSyncModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getTimeSyncs() const : erreur : référence à « std::allocator<Scenario::TimeSyncModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getTimeSyncs() const : erreur : référence à « std::allocator<Scenario::TimeSyncModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getTimeSyncs() const : erreur : référence à « std::allocator<Scenario::TimeSyncModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getEvents() const : erreur : référence à « std::allocator<Scenario::EventModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getEvents() const : erreur : référence à « std::allocator<Scenario::EventModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getEvents() const : erreur : référence à « std::allocator<Scenario::EventModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getEvents() const : erreur : référence à « std::allocator<Scenario::EventModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getStates() const : erreur : référence à « std::allocator<Scenario::StateModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getStates() const : erreur : référence à « std::allocator<Scenario::StateModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getStates() const : erreur : référence à « std::allocator<Scenario::StateModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getStates() const : erreur : référence à « std::allocator<Scenario::StateModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getIntervals() const : erreur : référence à « std::allocator<Scenario::IntervalModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction Scenario::ProcessModel::getIntervals() const : erreur : référence à « std::allocator<Scenario::IntervalModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getIntervals() const : erreur : référence à « std::allocator<Scenario::IntervalModel*>::allocator() » non définie
../plugins/score-plugin-scenario/libscore_plugin_scenario.a(moc_ScenarioModel.cpp.o):moc_ScenarioModel.cpp:fonction non-virtual thunk to Scenario::ProcessModel::getIntervals() const : erreur : référence à « std::allocator<Scenario::IntervalModel*>::allocator() » non définie
collect2: error: ld returned 1 exit status
base/app/CMakeFiles/score.dir/build.make:232 : la recette pour la cible « score » a échouée
make[2]: *** [score] Erreur 1
CMakeFiles/Makefile2:4111 : la recette pour la cible « base/app/CMakeFiles/score.dir/all » a échouée
make[1]: *** [base/app/CMakeFiles/score.dir/all] Erreur 2
Makefile:162 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
