### ISSUE TITLE
Faust support fails since last commit

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#721]
tested with faust commit 92ab4456842b963c4d018ed7bc1b899d49bf4c1a
score commit 89aa62f6b4c9830948ea1f8a833f434eb3212d8a
On Ubuntu 17.10

**Comment by thibaudk** [comment]
Changing back "if (0)" to "if (NOT MSVC)" in 
https://github.com/OSSIA/score/blob/feature/dataflow/CMake/modules/FindFaust.cmake#L50
fixes the support.

**Comment by jcelerier** [comment]
hmmm... the more complete fix would be to detect if the faust build is static or dynamic but if you want you can commit the fix (granting you the rights asap).

**Comment by thibaudk** [comment]
Cool, I'll try to look into that too.

**Comment by jcelerier** [comment]
this now works, right ?

**Comment by thibaudk** [comment]
Yes but I didn't make it detect if the faust build is static or dynamic yet. The issue can be closed tho.
