### ISSUE TITLE
[dataflow]

### ISSUE THREAD

**Issue by bltzr** [ossia/score#723]
Interpolations don't work anymore with parameters ```@type Vec2f``` on branch dataflow

see attached score
[interpolationBugPositions.score.zip](https://github.com/OSSIA/score/files/1880672/interpolationBugPositions.score.zip)

**Comment by jcelerier** [comment]
yes, interpolations have to be reimplemented (it's the last process that requires this :D)

**Comment by bltzr** [comment]
so, I guess we should do that well, as specified in #640 then... 
and take care of the multi-dimensionnal parameters in a consistent way, also (this is not completely satisfactory, yet, IMHO...)

also just noticed this was duplicating #716 , sorry for not checking before...

> it's the last process that requires this 

the last time I tried the color process, there was no way to set an address. Has that been fixed ?
if not, should I open an issue ?

**Comment by jcelerier** [comment]
> the last time I tried the color process, there was no way to set an address. Has that been fixed ?

yup

**Comment by bltzr** [comment]
:clap:
