### ISSUE TITLE
minor bugs with "Sound_file" process 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#724]
It's mostly a GUI issue, appart from the the crash when encapsulating a Sound file.
Encapsulation works no problem when the sound file is empty (no file path provided).

"Put in a loop" works in both cases perfectly.

The Gui problem is illustrated here: the representation of the file is desynchronized with the audio output, lagging behind the sound.

![vokoscreen-2018-04-06_21-13-14](https://user-images.githubusercontent.com/26526517/38439829-6dc56de8-39df-11e8-8354-779ef25cd9e0.gif)

It gets more and more obvious as time goes by.

Also, loading a sound_file of 4 tracks and above shows weird slashes and parasite in the image (only a cosmetic problem). The 4 tracks plays fine tho.

I apparently cross the limit attempting to play a 20 track file. No output is generated. I'll make Further test to spot the cut off.

Tested on Ubuntu 17.10
commit d32a42439fa1a3c09a3ea52b42c5000ee5647b49

**Comment by thibaudk** [comment]
At this point, both the crash when encapsulating and the apparent limit of the number of channels for the sound file have been completely fixed, Congrats!
Only remains the desynchronized audio and visual representation of the sound file as well as the graphical artefact's when loading a track with more than two channels.

Another bug occurred, regarding sound in general, as well as the "local" Device.
Manipulating the speed of the parent interval creates a lot of sound artefact's for a sound file aswell as for the "Audio Generator" process. 

This seems to be weirdly correlated to the fact that the "Playtime" parameter in the local device is only refreshed when "speed" is manipulated. (i might be well off there)

![vokoscreen-2018-04-10_19-16-03](https://user-images.githubusercontent.com/26526517/38572595-cdcb2f54-3cf3-11e8-81e6-87742355ae09.gif)
 
Settings : 
_Audio : Driver "JACK"
              Rate "48000"
              Buffersize "512"
_Execution : all default except Clock Source "Dataflow"
Using the "default" Clock Source dosen't cause the problem showed above (but no sound).
(this probably belongs to an issue of it's own)

Is there a Setting i am missing?
is there a way to differentiate between "true" time-stretch of a sound file, with "natural" pitch shift, 
and a time-stretch that attempts to preserve the pitch?   

Tested on Ubuntu 17.10
commit 84d9adc6947f59b95b996d83dea4765056a4fc08

**Comment by jcelerier** [comment]
> Another bug occurred, regarding sound in general, as well as the "local" Device.
Manipulating the speed of the parent interval creates a lot of sound artefact's for a sound file aswell as for the "Audio Generator" process.

it's normal, time stretching / pitch shift is not implemented yet for audio. Basically don't use speed on boxes with audio for now (it'll come in some months, I promise!).

**Comment by thibaudk** [comment]
ok ok, sorry, no rush!

I'll keep an eye on the 'playtime' of the 'local' device but will reference it in another issue if it is relevant.

**Comment by jcelerier** [comment]
> The Gui problem is illustrated here: the representation of the file is desynchronized with the audio output, lagging behind the sound.

could you try this again on the latest commit ? I think that I found and fixed the cause. There are still weird flashes when there are many waveforms though, I don't know why that is...

**Comment by jcelerier** [comment]
![hidpi](https://user-images.githubusercontent.com/2772730/52967174-87a8ff80-33a9-11e9-97da-d40d082fb39e.png)

e.g. here's a render of the same waveform at 1'10" mark - seems pretty similar for both Audacity and score

**Comment by thibaudk** [comment]
It seems to work perfectly now when score is running at 44100 Hz.
And with both 44100 and 48kHz files (pitched up).

I Used Jack as a driver.
Neither soundfile rates produces good images when score is running at 48kHz.

The fix only works at 44100Hz

**Comment by jcelerier** [comment]
should be done as of 2.3

**Comment by thibaudk** [comment]
Sound files appears to be stretched by a factor of 2.
They  play fine but look displaced.

here is the original in ocean audio with a peak at 7... 

 <img width="1440" alt="Capture d'écran 2019-07-04 16 47 40" src="https://user-images.githubusercontent.com/26526517/60675924-d26d7480-9e7d-11e9-80ed-1bc0190ef90f.png">

and here is the same file in score, with the same peak showing at 14...

![imageSon](https://user-images.githubusercontent.com/26526517/60675473-c46b2400-9e7c-11e9-9e14-624f6fd27801.png)

switching from 48000 to 44100 pushes the peack to appear at 15 ...

THIS IS ONLY A PROBLEM FOR STEREO FILES 
MONO FILES ARE SHOWING UP CORRECTLY.

**Comment by jcelerier** [comment]
what does it give now ?

**Comment by thibaudk** [comment]
Seems to be working now
