### ISSUE TITLE
crash on load on Archlinux with fresh feature/data_flow build

### ISSUE THREAD

**Issue by avilleret** [ossia/score#725]
here is the crash log : https://gist.github.com/avilleret/ed3b574525c1d71e1436d1e8fc66a305

Score was on 80a62240a49cddda98f6dbf7cc9fb8f6268801e3
API on 69a9ff268db82f29e1b66b90f431ed7be6cb767c

Jack is working (tested with Pd)

**Comment by jcelerier** [comment]
does this still happen ? I tried on multiple machines but never had this...

**Comment by jcelerier** [comment]
I'm closing for now, please reopen at some point if you still cannot run it on arch

**Comment by avilleret** [comment]
yes it works now, on master branch, thanks

**Comment by jcelerier** [comment]
nice! I wonder what it was..
