### ISSUE TITLE
Crash when adding a child to an OSC device if child name begin with a "slash" 

### ISSUE THREAD

**Issue by reno-** [ossia/score#73]
Create an OSC device
add a child '/test'
i-score crash.
it would be nice to remove the first slash if there is one
https://gist.github.com/reno-/338ff78e4bec560225a3

**Comment by jcelerier** [comment]
The commit 70464256e516dc15ca3192d215fcbd2384d02bda restricts which characters can be entered in various text edits. Please tell me if I forgot some.

**Comment by theod** [comment]
I assign to @reno- for testing

**Comment by reno-** [comment]
yes it works now
