### ISSUE TITLE
problems with attributes display

### ISSUE THREAD

**Issue by bltzr** [ossia/score#732]

**Comment by bltzr** [comment]
I noticed some field duplicates when trying to set some attributes:
notably description and tags are duplicated (the second one of each starting lowercase)
also, the tags field always remains empty, whatever the content of the TAGS attribute is
I've tested with ofxOscQuery and ossia-max and had the same behaviour in both
<img width="537" alt="screen shot 2018-04-27 at 16 14 56" src="https://user-images.githubusercontent.com/113982/39367127-3610c070-4a36-11e8-9873-6b6fd7c0f23e.png">

**Comment by jcelerier** [comment]
just checked and I don't see the duplicated things anymore
