### ISSUE TITLE
2.0.0-a3 doesn't output realtime OSC

### ISSUE THREAD

**Issue by ofersmi** [ossia/score#743]
Sending from a time interval interpolation between 2 osc values to udp (i tried both in max and vvvv) and while score is playing nothing comes out. only when pausing all the values get spit out. I have tried exactly the same thing in 1.0.0 b38 and it worked perfectly. 
Ofer

**Comment by ofersmi** [comment]
even more, for now v2 doesnt outpu any osc while playing, if I type the value in the device explorer I can see max receiving data, but when trying to animate values nothing arrives until I stop the timeline.

**Comment by thibaudk** [comment]
In Settintgs/Execution, make sure you select the "Dataflow" ClockSource. This will also require you to set the proper Rate and BufferSize in Settings/Audio according to your driver, as with this option score is sample accurate.

The interpolation Process is on it's way, so for now, I would recommend using simple Automation(Float).   Make sure to uncheck "Tween" in the Inspector window for your first test. 
If you are looking for interpolations, you can use the "interpolate state" feature.

**Comment by ofersmi** [comment]
@thibaudk ok so selecting dataflow as clock source completely stops score, now when pressing play nothing happens.
About the audio for now I can not get audio to run at all... (http://forum.ossia.io/t/can-i-play-a-music-or-video-file/29/12)

**Comment by thibaudk** [comment]
@ofersmi  Ok sory dindn't folow that on he forum.
I can't do anything for windows but i reproduced the issue on Linux with the "Default" ClockSource.

**Comment by ofersmi** [comment]
@thibaudk I now got a new version from Jean-Michaël Celerier and ASIO works there, now when I select dataflow I get OSC output! so I think problem solved?

**Comment by thibaudk** [comment]
@ofersmi cool! It would be good to have a functional default clock as well in the future tho. Or do away with it all together. Glad it now works for you anyway.
