### ISSUE TITLE
logo for "reinitialize"

### ISSUE THREAD

**Issue by bltzr** [ossia/score#745]
I thought we discussed this before, but I can see no trace here:

I think the current logo for "reinitialize" is quite misleading: it looks like a kind of loop.

I've just added two attemps at this on the repo, here are the pngs
I'm interested in feedback on this if some of you have any @jln- @aklevy @jcelerier ?

![logo_reinit_off](https://user-images.githubusercontent.com/113982/39707194-f7a882f6-5213-11e8-8511-487a5ac4f4ca.png)
![logo_reinit_on](https://user-images.githubusercontent.com/113982/39707195-f7cef904-5213-11e8-9e36-8a18baed9c54.png)

**Comment by jln-** [comment]
Yes, I agree the loop-like one is misleading.

One may argue the this proposal do imply that it gets back to start but not so much that it resets. But still, it is much better that current state.

**Comment by bltzr** [comment]
what about something going this way ?

![logo_reinit-test](https://user-images.githubusercontent.com/113982/39744588-1afc3086-52a5-11e8-9e77-d600802e5f71.png)

not so sure, just drawing out loud...
