### ISSUE TITLE
menu bar icons order

### ISSUE THREAD

**Issue by bltzr** [ossia/score#746]
currently, the order seems random, IMHO, it shouldn't

my ordering proposal:
![menubarproposal](https://user-images.githubusercontent.com/113982/39722477-30ca4518-5243-11e8-8c90-54bb72b47ae1.png)

opinions about this @jln- @aklevy @jcelerier @blueyeti ?

some comments (from left to right) :
- we have two buttons for grow/shrink and scale, when basically it's a toggle between two modes, so I guess he'd be better if we used a toggle - I placed it next to the "lock" button (for which we could find a better name, I guess)
- I've changed the reinit button, as proposed in #745 next to the stop button
- I've also added a next trigger button (as discussed in #733) , at its right (the same, reversed to the right), I don't know if the similarity between both (while the functions are very different) is misleading... I guess it might be
- then, I guess a big speed slider should be useful, and a very good advertisement of this great (and quite singular) feature of score
- the next two buttons are "go back to previous trigger", and "skip to next trigger", as discussed in #733 (there would be missing a "go to next trigger" as discussed here) - we'll see when (and if) this is implemented
- a timecode - why not, now that we have a timebar
- finally, it felt better to have the audio on/off button to the right, and the volume (a "volume" label could help, BTW) to its left

what do you guys think ?

**Comment by bltzr** [comment]
in order to manage the placement when the menu expands, I'd say there are 3 blocks:
- tools (undo to scalemode) are left-aligned
- play buttons and execution-related widgets (from play to the timecode) are center-aligned
- audio widgets (colume and on/off) are right-aligned 

also, we should define a policy about what happens when the menu bar is squeezed and there's not enough space to fit all buttons
maybe, we "truncate" from the right when on edition, and from the left when in execution ?

**Comment by bltzr** [comment]
we could also add numerical values to speed and volume (in dB I'd say)
I've updated the image above accordingly

**Comment by jcelerier** [comment]
not really relevant anymore I think given how everything has changed :p
