### ISSUE TITLE
play from here is broken !

### ISSUE THREAD

**Issue by bltzr** [ossia/score#753]
I don't know when this got broken, but values from previous states are not recalled anymore when "playing from here" - this is a critical problem (for me, but also for @ofersmi who initially reported the issue this morning  in a private chat)

![playfromhere](https://user-images.githubusercontent.com/113982/40231058-eeb65b08-5a99-11e8-9256-667501e1225a.gif)

[playfromhere.score.zip](https://github.com/OSSIA/score/files/2016521/playfromhere.score.zip)

**Comment by ofersmi** [comment]
Hey all, so its closed? is there a new build?

**Comment by jcelerier** [comment]
I can make you one in a few hours
