### ISSUE TITLE
New value but no output 

### ISSUE THREAD

**Issue by ofersmi** [ossia/score#754]
I dont like declaring a bug like this, but I can not find a pattern, sometimes it happens, sometimes it wont. 
I add a new value to the timeline (in this gif int 3 for Trig) but playing wont output anything! 

![new_value_no_output](https://user-images.githubusercontent.com/3447083/40231865-f0993654-5a9c-11e8-9dd9-043270e5d8d2.gif)

**Comment by jcelerier** [comment]
> I dont like declaring a bug like this, 

no problem that's fine ! could you share you .score file if possible ?

**Comment by ofersmi** [comment]
not really, 
thats the problem. I can not recreate this bug... and sometimes if I open and close the project it will be magically fixed.... I thought I would report it only because it happened and I could gif it happening. 
sorry

**Comment by jcelerier** [comment]
should be fixed
