### ISSUE TITLE
Add support for JACK transport

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#755]
as per http://forum.ossia.io/t/jack-transport-as-clock-source/51

**Comment by jcelerier** [comment]
getting there :)
![transport](https://user-images.githubusercontent.com/2772730/114737703-913f0f80-9d47-11eb-9665-233388b8b438.gif)

**Comment by thibaudk** [comment]
Very nice !

**Comment by jcelerier** [comment]
almost there :-)

![transport2](https://user-images.githubusercontent.com/2772730/114911423-4690c680-9e1f-11eb-96d0-e83e4eee6054.gif)

**Comment by jcelerier** [comment]
closing as the feature is pretty much there, if there are bugs please open new issues !
