### ISSUE TITLE
Vertical scroll/zoom bar

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#769]
A vertical scroll and zoom bar for the timeline, as well as keyboard shortcuts to zoom in and out vertically, would be useful.

**Comment by jcelerier** [comment]
just to note, there is a vertical zoom - it is done by doing shift+scroll wheel (or the equivalent gesture on a touchpad, likely two-finger scroll)

**Comment by jcelerier** [comment]
Added some documentation on the feature
