### ISSUE TITLE
"Settings" and "Recent files" aren't saved anymore

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#770]
The "Recent Files" sub menu doesn't update since the latest release.

Same goes for any of the "Settings".
Should all the settings appear in the next start-up as the new default ?

**Comment by jcelerier** [comment]
are you sure about this ? It seems to work fine here, on both mac and linux

**Comment by thibaudk** [comment]
Yes, since a few builds ago, both "audio" and "theme" settings default back to an older configuration at every start-up of score.
"execution" settings don't seem to be that much more updated at next start-up.
the "Recent files" submenu is stuck.

is there a config file that might be laying around from previous build and is not updated?

**Comment by thibaudk** [comment]
I couldn't actually recreate it with a fresh build in a new linux install.
Must have been a conflict in my machine.

Sorry for the false alert
