### ISSUE TITLE
VST window always on top

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#771]
When showing the VST's GUI, most sequencers would always display this new window on top.
This feature has been requested by composers taking part in the OSSIA/score workshop.

**Comment by jcelerier** [comment]
this one is fairly easy to do yourself if you want.

See  http://www.qtcentre.org/threads/7384-Force-a-QDialog-to-be-the-top-level-Window-and-to-stay-at-this-level

and the class VSTWindow in VSTWidgets.hpp (in the "media" plug-in).

**Comment by thibaudk** [comment]
Cool! 
Yes I will try it my self soon.
Thanks for the pointers! Keep them coming.

**Comment by thibaudk** [comment]
Woks great on both vst's and the "working lv2's"
tested on Ubuntu 18.04
