### ISSUE TITLE
allow to move a whole slot to a new interval when drag'n'dropping with alt pressed

### ISSUE THREAD

**Issue by bltzr** [ossia/score#779]
currently, we can:
- move a whole slot (several layers) to a new position in the same interval (with alt)
- move a single slot to a new interval, by drag'n'dropping it somewhere else in the scenario

though, it would be very cool if we could combine both and move a whole slot (several processes) to another interval (by pressing al), currently, that only moves the topmost one

**Comment by bltzr** [comment]
is that clear enough or do you want a gif @jcelerier ?

**Comment by bltzr** [comment]
this was implemented, isn't it @jcelerier ?

**Comment by jcelerier** [comment]
yes but test it for a bit, I may have forgotten some cases

**Comment by bltzr** [comment]
yes, there's are a few bugs: 
- [ ] it's possible to move a slot from an interval to another one *only* by dropping the slot *between* the other slots. When trying to drop it above another slot, it doesn't work
- [ ] when dropping a slot to another interval, it's placed at the bottom, not where it's dropped
- [ ] also the visual (violet) cue doesn't happen when dropping to another interval
- [x] when undoing the racks are hidden

this is all demonstrated on the gif below

![slots](https://user-images.githubusercontent.com/113982/42098859-5be6c2ce-7bbc-11e8-85aa-ede05c84c3ce.gif)

**Comment by bltzr** [comment]
there are still 3 sub-items from the last comment - should we move this back into the TODO ? Or are those hard to implement and I should tag this for a future version ?

**Comment by jcelerier** [comment]
no, all of this is doable with a bit of time
