### ISSUE TITLE
Mapping to one element of vec3f doesn't work

### ISSUE THREAD

**Issue by avilleret** [ossia/score#784]
An LFO plugged to a mapping with output address : `voxelstrack:/blob.1@[0]`
`voxelstrack:/blob.1` is a vec3f.
all coordinates moves together with the same value.
This sounds like a bug :-)

**Comment by thibaudk** [comment]
It has been reported in

#716 
and 
#723

**Comment by bltzr** [comment]
OK, so we can close this one, thanks @thibaudk

**Comment by avilleret** [comment]
oups sorry for noise
