### ISSUE TITLE
Using strings in trigger conditionals

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#785]
Currently, the conditional operators for triggers only accept numerical values. Would you consider allowing strings to control the trigger conditionals? I’m working on a project with a bunch of intervals that are not connected to the root time node, and are meant to be triggered from Max. It’d be nice to be able to trigger those intervals by sending their names to a parameter. It’d be especially nice if it was possible to use the == conditional to trigger an interval with a matching string and pause/stop the interval when a non-matching string is sent.

**Comment by bltzr** [comment]
It works with strings actually but you have to put them in “quotes”
