### ISSUE TITLE
process header layout

### ISSUE THREAD

**Issue by bltzr** [ossia/score#787]
out port should be right-justified
currently it goes out of view from the right as demonstrated below

![portout](https://user-images.githubusercontent.com/113982/41672303-db9b0052-74b9-11e8-8102-73516fa45785.gif)

**Comment by bltzr** [comment]
also, in ports should be left-justified

when scaling down, a policy proposal could be to first remove text labels, in the following order:
- O (for out port)
- I (for in port
- all other text labels (if any) than the process name
- the process name 

here's a little GIF to illustrate the situation:
![image](https://files.gitter.im/OSSIA/K0wK/ports.gif)

**Comment by jcelerier** [comment]
has been entirely remade nowadays, let's open new issues for things to change to the current v.
