### ISSUE TITLE
bug when trying to encapsulate a detached state with other objects 

### ISSUE THREAD

**Issue by bltzr** [ossia/score#788]
as demonstrated below 

this is a quite marginal case, I guess, but it can be a little  painful because that kind of "escapes" the undo process, so if there was some content in the desired encapsulation, it's lost forever

![encapsulate](https://user-images.githubusercontent.com/113982/41674966-a812aa5c-74c1-11e8-81e3-151effd1c8ef.gif)

**Comment by jcelerier** [comment]
just in case, when you see "internal error", could you label them as crashes ? (even if score keeps running, when this happens the safest thing to do is to save the document as another one that the working one and close score - it means that something got corrupted pretty bad)

**Comment by bltzr** [comment]
OK that was relted to some previous bug, then I guess
