### ISSUE TITLE
Dotted line

### ISSUE THREAD

**Issue by ofersmi** [ossia/score#791]
Why does an automation become dotted (and stops spitting out values)? and how to undo that?
![image](https://user-images.githubusercontent.com/3447083/41766550-a3f5ef6e-7607-11e8-8d06-d78a051a1357.png)

**Comment by jln-** [comment]
The automation is dotted when it is in 'easing mode' (that is when the previous state does not contain the parameter used in the automation).

This can be undone from the automation Inspector. Uncheck 'easing' checkbox

**Comment by bltzr** [comment]
that’s it, except it’s called “tween"

**Comment by ofersmi** [comment]
ho. ok . and tween doesnt work for now right?

**Comment by bltzr** [comment]
it *should* work

at least, if your device can be queried for values, it should

at least, here on my machine, it does work with v2a4

![tween](https://user-images.githubusercontent.com/113982/41768959-08ca9380-760e-11e8-9961-299f44316474.gif)

**Comment by bltzr** [comment]
this was with ossia-max (ie OSC-query) 
I just tried with a plain OSC device and it also works

**Comment by ofersmi** [comment]
Ok now I get it, tween is a sort of pickup mode, where ever your current value is it wil pickup from there and go to the value you animated!

**Comment by bltzr** [comment]
ex.act.ly !

isn't it useful ?

**Comment by ofersmi** [comment]
ho so very! love it!

**Comment by jln-** [comment]
> I just tried with a plain OSC device and it also works

I just tried with a osc device and it actually does not work as in your screencap. Max Tween value is set to the maximum parameter value and not to the one stored in state

**Comment by bltzr** [comment]
how did you create the automation/tween ? 

because if you dropped the parameter from the DE, it doesn't add the current value to the end of the automation, that's a known issue: https://github.com/OSSIA/score/issues/659#issuecomment-348979042

**Comment by jln-** [comment]
OK, that's how I did it. Sorry for noise

**Comment by bltzr** [comment]
well, we should be sorry that it doesn't work the way it should, instead

can we close the issue, now ?

no problem anymore @ofersmi ?

**Comment by bltzr** [comment]
> Sorry for noise

How come you don't know every issue's comment by heart @jln- ?

**Comment by ofersmi** [comment]
@bltzr  Yes we can

**Comment by ofersmi** [comment]
and @jln- you should really work on memorizing every issue and comment... its not ok.

**Comment by jln-** [comment]
I started doing so from the oldest one. Funnily, oldest open issue is: https://github.com/OSSIA/score/issues/41
