### ISSUE TITLE
[doc] add a disclaimer on the interpolation doc that it's currently broken in v2

### ISSUE THREAD

**Issue by bltzr** [ossia/score#794]
on https://ossia.github.io/score/in_depth/interpolation_process/index.html

see #640

**Comment by bltzr** [comment]
hmmm... that's not very visible (I had to look for it)

could it be BIG ? and maybe RED ?

**Comment by bltzr** [comment]
blinking would be the best, but you know...

**Comment by jcelerier** [comment]
also [with some rainbows](http://www.dpgraph.com/) please @jln-
