### ISSUE TITLE
Crash When Choosing Jack Audio Backend

### ISSUE THREAD

**Issue by aliefhooghe** [ossia/score#798]
Score keep crashing when I choose Jack Audio Backend when (and only when) jack is started. I have this problem both with a homemade build on archlinux and with the AppImage release (a7) on Linux Mint.

**Comment by jcelerier** [comment]
is it still the case with the latest release ?

**Comment by aliefhooghe** [comment]
Not at all !!

**Comment by jcelerier** [comment]
alrighty then !
