### ISSUE TITLE
Sound File Processes Missing

### ISSUE THREAD

**Issue by petervanhaaften** [ossia/score#799]
**Observed behavior:**
It is impossible to drag and drop an audio file into a scenario. Also, the 'sound file' process is missing from the process menu.

**Steps to reproduce**
1) Create a new score file.
2) Create a new scenario.
3) Drag an audio file into created scenario.

**Expected behavior**
When an audio file is dragged into a scenario, the scenario should show a visualized waveform.

**Version/Specs**
Tested on v2a7, although according to discussions on Gitter, it has existed since v2a6.
2017 MBP, High Sierra.

![soundfilebug](https://user-images.githubusercontent.com/5347358/43039895-eb91c5dc-8d04-11e8-92d8-bdba113fecf5.gif)

**Comment by bltzr** [comment]
should be fixed with v2a8
