### ISSUE TITLE
OSCQuerry Comunicatiion is broken

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#823]
A couple issue of that sort arose since 2.0.0.a9 but I didn't get a chance to properly test.

With 2.0.0.a10, values sent to the device are not refreshed in the Device Explorer.
They only appear correctly after refreshing name spaces.

Setting values from the Device Explorer dosen't seem to have any effect.

Everry few seconds, the line "[error] HTTP: Connexion ré-initialisée par le corepondant" is printed many times to the "Message" window.

![vokoscreen-2018-08-19_09-10-15](https://user-images.githubusercontent.com/26526517/44306474-e0162a80-a38f-11e8-899a-3145ceb7150e.gif)

tested with ossia-supercollider, ossia-pd and ofxOscQuerry
on Ubuntu 18.04
with commit 99d10ac34d5e2a08b3e4723a0420c284702fe9ba

**Comment by bltzr** [comment]
Is that with the latest version of libossia? (See latest score releases notes) Because some oscquery specs changed lately, and that looks like those recent changes didn't make it to both sides in your setup 

I also had the http error, though, but IIRC that didn't prevent communication from working

**Comment by thibaudk** [comment]
thanks, indeed, I didn't read the release notes.

With the latest version of ossia-pd, the device was found but score couldn't connect to it.
I'll upgrade the libossia dependencie for the other environments and continue testing.

**Comment by bltzr** [comment]
We're a  in the middle of changes related to oscquery updates, so things will probably be slightly unstable for a little while (one month?), so, unless you want to help on that (which would be very welcome) I'd recommend using a9 and previous versions (and also previous libossia versions)

**Comment by jcelerier** [comment]
should be ok now ?

**Comment by thibaudk** [comment]
Cheers! 
I am sure it' works great.
just having trouble building supercollider with boost 1.67 and lincking it to libossia.
@pchdev  proposed to rethink ossia-supercollider's implementation for more stability in the long run.
will get to it soon as.
for now this can be closed, tests will reveal their need for more specific issues, if any.

Well done!
Keep up the good work
