### ISSUE TITLE
osc messages to score

### ISSUE THREAD

**Issue by nicolight** [ossia/score#824]
In order to control ossia score from osc I didn't find any instruction about how to proceed.
Pascal Baltazar answered that messages have to be sent on localhost 6666 (where do we setup this port?)
/play1 => play
/play0 => pause
/stop => stops and rewinds

He also said "You couldn't have guessed because we didn't document it " !!
so please it could be good to add a section in the documentation.
thanks a lot.
nicolight

**Comment by bltzr** [comment]
Hi @nicolight thanks for reporting this.

> localhost 6666 (where do we setup this port?)

This can be done by adding a Local device (ctrl/cmd-B), and setting the OSC port to the desired value as demonstrated below
![image](https://user-images.githubusercontent.com/113982/44457452-87e75e80-a603-11e8-95fd-0fcb2000484a.png)

Also, the messages are not `/play0`and `/play1`but `/play`with value `1`(for start/resume) and `0` (for pause). `/stop` is correct (it's just a message, without argument/value, ie. similar to a bang).

As you will notice, when adding a Local device, score will declare all its elements with OSC adresses for each and every one. Then you can have access to further parameters, like transport (which will make you "jump" to some point in the timeline), or to `speed` which allows to change the clock speed of each interval, and so on...

And, yeah, we should document this - @jln-, feel like it ?

**Comment by jln-** [comment]
Yes. Assigning this to myself to make an "How to" section in the doc

**Comment by jcelerier** [comment]
Note: the place for the doc for that one should be

https://github.com/ossia/ossia.github.io/blob/master/_score_features/localtree-feature.markdown

**Comment by jcelerier** [comment]
documented in https://ossia.io/score-docs/devices/local-device.html
