### ISSUE TITLE
min and max params for automation XY

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#825]
At the moment, X and Y can only range fro 0 to 1.

This is probably a duplicate but i couldn't find where.

**Comment by jcelerier** [comment]
> This is probably a duplicate but i couldn't find where.

no I don't think it's a duplicate, but maybe we should make a single issue for features of this process ? (I made it very quickly as a test so it's fairly lacking)

**Comment by jcelerier** [comment]
actually yes, it was a duplicate of https://github.com/OSSIA/score/issues/459
