### ISSUE TITLE
Error when using 'play from here'

### ISSUE THREAD

**Issue by reno-** [ossia/score#83]
I have this error when using first 'play state' and then 'play from here'.
Not 100% reproductible, but I have the error a lot of time.

'Internal error: TimeEvent's status configuration of the TimeConstraint is not handled'

![capture d ecran 2015-12-06 a 14 48 07](https://cloud.githubusercontent.com/assets/127730/11613640/7ab253d8-9c28-11e5-8689-e5df5eb33dc7.png)

**Comment by reno-** [comment]
Version 1.0.0-a31 'Oh, je suis désolée'

**Comment by theod** [comment]
this was a bug into the API so it would be fixed into the next release
