### ISSUE TITLE
automation is broken in 1.0.0-a31 'Oh, je suis désolée'

### ISSUE THREAD

**Issue by reno-** [ossia/score#84]
Make 2 state with an automation process between
The first value is sent evrey frame during the automation length, and the end value is sent only when reaching the end event.

**Comment by nvuaille** [comment]
@theod : 

Dans le commit "Removing TimeConstraint::setDuration and exception ..." (ab43f1f4951b30a8999f28e3b712311b48b47a83) tu as modifié l'implémentation de TimeConstraint::start (TimeConstraint.cpp, ligne 87) en enlevant l'appel à la méthode do_setDuration.

Et, a priori, sans cette ligne les automations ne sont plus lues ...
Est ce qu'on peut la remettre ou est ce que ça avait d'autres impacts ?

**Comment by theod** [comment]
ouch ! je la remets pour voir

**Comment by theod** [comment]
j'ai résolu le problème mais je crois qu'il devrait y avoir d'autres problèmes potentiels notamment dans le cas d'automation lié à une contrainte dont la durée est souple sans durée maximum. car dans ce cas la position est toujours 0 puisque la durée est infini... à tester de votre côté mais je fais des tests du mien.

**Comment by theod** [comment]
bon apparement fausse alerte pour le bug potentiel sus-mentionné ...
