### ISSUE TITLE
unit.orientation.euler is a Vec4f but only pitch, roll & yaw are accesible parameters

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#841]
This can be seen when creating the ossia parameter externaly and exposing it through OSCQuery or
by creating an OSC parameter direcly in the device explorer and setting it's unit as euler in the edit window.

**Comment by bltzr** [comment]
it should be a vec3f (and pitch, roll & yaw are the only parameters)

http://ossia.github.io/libossia/html/classopp_1_1node.html#abe8954fca7c67f310b91ac91e8986295
