### ISSUE TITLE
new linker error on Ubuntu 18.04

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#842]
This has been tested both before and after recent binutils and g++ update with a fresh clone

```
[100%] Linking CXX executable ../../ossia-score
/usr/bin/ld.lld: error: undefined symbol: main
>>> referenced by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o:(_start)
collect2: error: ld returned 1 exit status
base/app/CMakeFiles/score.dir/build.make:190: recipe for target 'ossia-score' failed
make[2]: *** [ossia-score] Error 1
CMakeFiles/Makefile2:4924: recipe for target 'base/app/CMakeFiles/score.dir/all' failed
make[1]: *** [base/app/CMakeFiles/score.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
``` 

the Scrt1.o does exist in /usr/lib/x86_64-linux-gnu

**Comment by jcelerier** [comment]
is it still the case ?

**Comment by thibaudk** [comment]
Yes, just tested again with a fresh clone

**Comment by thibaudk** [comment]
Just tryed again with commit 740ec8f63530414a92b77e1afa994ef21fb166b4
and libossia on the master branch commit af7eebd093a0eeddee9da3a8c82ec278ee20df33

And it WOKS!!

Cheers!

**Comment by jcelerier** [comment]
that's... really weird, I didn't change anything related to this so I think that there might be a problem somewhere else on your machine
