### ISSUE TITLE
segmentation fault related to the local tree 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#846]
* crash when editing (simply creating a new interval) 
with the local device deployed in the Device  Explorer.

![vokoscreen-2018-10-06_02-02-39](https://user-images.githubusercontent.com/26526517/46565062-0413d800-c90c-11e8-9b18-6166e806f0a2.gif)

Also, neither processes nor states can affect parameters of the local tree any more.

**Comment by jcelerier** [comment]
investigating, but that's beyond weird : I was changing stuff yesterday exactly because I noticed that sending messages to the local tree wasn't working (e.g. having a state changin a LT value).

**Comment by thibaudk** [comment]
since last commit, the crash now only happens upon deleting groups of intervals, states and syncs

with an error message that I don't realy know hwo to translate:
"Trappe pour point d'arrêt et de trace (core dumped)"

![vokoscreen-2018-10-06_19-21-47](https://user-images.githubusercontent.com/26526517/46574003-34f01d80-c99d-11e8-8dc3-e8908124929d.gif)

**Comment by jcelerier** [comment]
actually in this case it's not the local tree which causes problem, opening another issue to track it
