### ISSUE TITLE
Crash related to Address listening management

### ISSUE THREAD

**Issue by reno-** [ossia/score#85]
Not 100% reproductible, but happened twice
First, create a minuit device and explore
Second, refresh namespace
Third, navigate in the device explorer => crash
crashlog : 
https://gist.github.com/reno-/dc4051e129c3540809f3

**Comment by theod** [comment]
it is relative to address listening. I know @jcelerier made some fix into JamomaAddress::removeCallback to avoid this kind of troubles.

by the way I've noticed some strange behaviors into the opening and the closing of the listening so I rename this issue to be more precise.

**Comment by theod** [comment]
however we should find a way to reproduce this issue as I don't manage to get a crash.

**Comment by theod** [comment]
I just had a crash related to address listening : 

[crashlog.txt](https://github.com/OSSIA/i-score/files/65619/crashlog.txt)
