### ISSUE TITLE
[ conditions ] issues with 'equal-like' operators

### ISSUE THREAD

**Issue by pchdev** [ossia/score#855]
score 2.0.0 a23, macOS

I can't set conditions with the  '=', '!=', '>=', '<=' operators, expression is not accepted
'>' and '<' operators work fine though

tested with both a float and and int parameter

![score-equality-issue](https://user-images.githubusercontent.com/9993105/46729171-e08ebb80-cc84-11e8-9fb9-f2ff1d1a7a52.png)

**Comment by jcelerier** [comment]
#854 ;p

**Comment by jcelerier** [comment]
I'll be pushing a release today as soon as everything builds

**Comment by pchdev** [comment]
ow, okay, sorry, forgot to pull today.. :>
