### ISSUE TITLE
Turning a process off only works when playing 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#857]
If a process is turned-off before playing,
it is working regardless, 

![vokoscreen-2018-10-11_16-45-21](https://user-images.githubusercontent.com/26526517/46810272-95ea6d80-cd70-11e8-88b6-f87e3547b65e.gif)

A process can only be properly turned-off when score is currently playing.

also, when turning off a scenario while playing, all encapsulated processes are muted but states are still evaluated. should everything be muted inside a turned-off scenario?

**Comment by jcelerier** [comment]
hmm that's weird, I don't have the same behaviour on my machine

**Comment by jcelerier** [comment]
> also, when turning off a scenario while playing, all encapsulated processes are muted but states are still evaluated. should everything be muted inside a turned-off scenario?

yep, I would say so

**Comment by thibaudk** [comment]
Just tested with commit d2cd6db
The problem persists on Ubuntu 18.04

**Comment by jcelerier** [comment]
you also need 19997acb9785bdaa43e7a9264506fe2397db847c on score

**Comment by thibaudk** [comment]
Perfect! that fixed it.
Cheers!
