### ISSUE TITLE
error when recovering work from i-score after i-score crash

### ISSUE THREAD

**Issue by reno-** [ossia/score#86]
It happend each time i-score crash and the project has never been saved

ObjectPath::find  Error! Child not found

**Comment by reno-** [comment]
![capture d ecran 2015-12-06 a 16 59 49](https://cloud.githubusercontent.com/assets/127730/11614187/c810cfd0-9c3a-11e5-8b4b-1d978887030c.png)

**Comment by reno-** [comment]
and the minuit device cannot be explored . I have to quit i-score and re-create the device manually

**Comment by jcelerier** [comment]
Sorry, I don't have enough information and cannot reproduce :(

Please not that this might be happening if you're trying to open a save file from a previous commit - I try to guarantee that there will be no changes in the save format but cannot make any promises before 1.0.0 final. (actually, I can promise that there will be some breaking changes before).
