### ISSUE TITLE
Minuit not working in v2.0.0-a23 and v2.0.0-a24

### ISSUE THREAD

**Issue by blueyeti** [ossia/score#861]
test with jamoma - Max/MSP, mac and windows

to reproduce open j.minuit_device.maxhelp of the max/MSP jamoma package, and create minuit device in score with default settings. the device is created empty, as il max was not opened.

**Comment by bltzr** [comment]
you just need to change `@remote/name` to "score"
this should be updated in Jamoma's package (maybe create an issue for that, and assign it to @jln- ?) 
definitely not a score bug
