### ISSUE TITLE
faust sliders aren't updated when paramter values are passed through inlets

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#876]
Comparing other audio processes

![vokoscreen-2018-12-01_17-01-31](https://user-images.githubusercontent.com/26526517/49330131-ca1d2600-f58a-11e8-83e5-1c0e9bbd9915.gif)

Faust Process do respond to values passed through inlets but the slider dosen't move and the values aren't printed on it. 

![vokoscreen-2018-12-01_17-03-13](https://user-images.githubusercontent.com/26526517/49330197-b6be8a80-f58b-11e8-853b-f962f846c351.gif)

**Comment by jcelerier** [comment]
done
