### ISSUE TITLE
crash with "put in a loop"

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#878]
Any "event" or "sync" containing more that 3 states causes crashes when attempting to "put in a loop"

these sort of selections:
![put_in_a_loop_crash](https://user-images.githubusercontent.com/26526517/49676469-1d571300-fa7a-11e8-9235-942dba0d8064.png)
 
produces this crash every time when calling "put in a loop" from either the "object" menu or with "ctrl + shift + L"

tested with the feature/simple_states branch on commit:
36d4e2e1f0c99780f830acbce5ac1eefbdd284fb

**Comment by thibaudk** [comment]
This has indeed been fixed for "empty" conditions but keeps on happening with "actual" conditions (configurations different from all branches set to "always")

Crashes now only occurs when playing the conditions, not anymore when creating the loop.
even a Looped condition created without the "put in a loop" shortcut may crash the same way.  

tested on master branch with commit 134f2e2da

**Comment by jcelerier** [comment]
> This has indeed been fixed for "empty" conditions but keeps on happening with "actual" conditions (configurations different from all branches set to "always")

hmm do you have a case that crashes ? 
here this works for me (both while doing put in loop and playing, with all three conditions set to random stuff) : 

![qssqd](https://user-images.githubusercontent.com/2772730/49791617-258ca800-fd31-11e8-8086-2732ec925acd.png)

**Comment by thibaudk** [comment]
![condition_crash](https://user-images.githubusercontent.com/26526517/49795646-d3e91b00-fd3a-11e8-8ec0-2729192b9057.png)

This plays fine whene the condition is set to "always" and offset behavior is "true"
but crashes with everything else i've tested (condition "never" + ofset "false", 
specific conditions + offset "true"...)

I Imagine I may have entered some incoherent ones like condition "never" and offset "true",
but they definitely weren't the only crashes
