### ISSUE TITLE
i-score doesn't allow to create two Minuit devices with the same UDP port for i-score

### ISSUE THREAD

**Issue by reno-** [ossia/score#88]
With minuit protocole, we should be able to have several devices talking to i-score on the same udp port (default 13579).
And maybe the udp port could be hardcoded… as it is for art-net for exemple (6454).

**Comment by theod** [comment]
totally agree ! this feature is part of the major rewrite of the device management part of the API.

**Comment by jcelerier** [comment]
I think that the better way would to be make it so that the device does not need to know the i-score port. UDP can be used in full-duplex : i-score initiates the connection to the device knowing only its port, and then the device can just reuse the socket to write to i-score.

**Comment by bltzr** [comment]
what about this ? is there anything we can do with the current state of affairs ? or should we consider this is a intrinsic flow of Minuit (and encourage people to use OSCquery instead ?)
(I'd say yes...)

**Comment by jcelerier** [comment]
I agree
