### ISSUE TITLE
Serial devices sends out namspaces when receiving messages 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#880]
Using a minimalist example made to receive values from a button and potentiometer

```
import QtQuick 2.0
import Ossia 1.0 as Ossia

Ossia.Serial
{
    function openListening(address) {}
    function closeListening(address) {}

     function onMessage(message) { // evaluated each time a message is received
     var splitedtMessage = message.split(','); 
     // split the incoming message with every ',' received to create an array 
     return [{address: "/button", value: splitedtMessage[0]}, // assign the indexed values to namespaces in the tree
             {address: "/potentiometer", value: splitedtMessage[1]}];
	}

    function createTree() {
        return [ {
                   name: "button",
                   type:  Ossia.Type.Int,
                   access: Ossia.Access.Get,
                   repetition_filter: Ossia.Repetitions.Filtered
		  },
                  {
                    name: "potentiometer",
                    type:  Ossia.Type.Int,
                    access: Ossia.Access.Get,
                    repetition_filter: Ossia.Repetitions.Filtered
                   }
               ]; }
}
```

nothing is supposed to be sent out, only received.
Yet, the debug message shows that every time a value is assigned to a namespace in the tree, ths same namespace is folowed by a '\n' is sent out to the serial port.

This can also be seen on the arduino board. when connected to score, the rx led lights up as it is receiving data. Connecting the same board, running the same sketch to a different serial monitor (i use gtkTerm), only the tx pin lights up as the data is sent, rx remains turned off.

This has the effect of completely saturating the serial port, making a bi-directional communication impossible, as well as slowing down score, especially disconnecting the device (several seconds of freeze)

**Comment by jcelerier** [comment]
fixed in 502069eb0595e60c486c9a08751aa24dd4a66b8c

**Comment by jcelerier** [comment]
(also maybe the debug message just above in serial_protocol.cpp could be removed ? it's not very useful...)

**Comment by thibaudk** [comment]
Perfect!

**Comment by thibaudk** [comment]
I'll do a few tests with Arduino devices and see if the debug message is a problem or if it can be usefull.
