### ISSUE TITLE
conditions can't be removed

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#881]
![vokoscreen-2018-12-10_23-59-17](https://user-images.githubusercontent.com/26526517/49767216-eaaa5600-fcd7-11e8-9ca0-d43c7f705693.gif)

When creating a condition and then removing the state, the condition will reappear when creating a new state. There also seem to be no good way to only suppress only the condition and not the state

**Comment by jcelerier** [comment]
you can suppress the condition by clicking on it and pressing suppr (or backspace on mac) : 
![bug](https://user-images.githubusercontent.com/2772730/49790545-c5950200-fd2e-11e8-8430-85e8c7feb89f.gif)

**Comment by thibaudk** [comment]
Neither seem to work on Linux (Ubuntu 18.10).
Also the main issue I was trying to highlight is that after deleting a state and it's condition on the start sync, creating a new interval will have the condition show up again at the start.

**Comment by jcelerier** [comment]
> Neither seem to work on Linux (Ubuntu 18.10).

does it select the condition in the inspector when you click on it ?

**Comment by jcelerier** [comment]
> Also the main issue I was trying to highlight is that after deleting a state and it's condition on the start sync, creating a new interval will have the condition show up again at the start.

the problem here is that the first state / even can never actually be deleted, thus neither is the condition.

**Comment by thibaudk** [comment]
> does it select the condition in the inspector when you click on it ?
Yes
![condition_inspector](https://user-images.githubusercontent.com/26526517/49794737-94213400-fd38-11e8-8562-525cd0402e73.png)

but the little option wheel doesn't offer the "disable" option like a Trigger does, only "edit" shows up in the menu.

**Comment by thibaudk** [comment]
Ok great, that makes sens!

This issue should then be more about adding the disable option in the little wheel
![option_wheel](https://user-images.githubusercontent.com/26526517/49800183-2cbeb080-fd47-11e8-953b-bcadcba4725e.png)
 
if only for the sake of coherence and consistency with triggers.
If that is possible within the logic of the code.

Also, I continued trying and still can't find a Linux keyboard shortcut to remove conditions.
