### ISSUE TITLE
cables are in the way

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#885]
This example shows how wide the selection area for cables is

![vokoscreen-2018-12-11_22-13-21](https://user-images.githubusercontent.com/26526517/49830745-57822680-fd92-11e8-85f5-e22d3eb432ff.gif)

this makes it difficult if not impossible at times to select other objects in the vicinity of cables.

**Comment by jcelerier** [comment]
you can disable cables with alt+shift+G

**Comment by jcelerier** [comment]
(or in the View menu -> show cables)

**Comment by thibaudk** [comment]
Cool! That is good to know.
I would keep this issue open to keep in mind for future improvement but if that isn't necessary,
feel free to close it

**Comment by jcelerier** [comment]
I pushed the fix

**Comment by thibaudk** [comment]
Lightning bug fix!
