### ISSUE TITLE
strange behaviour with "decapsulate"

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#887]
![vokoscreen-2018-12-12_18-27-03](https://user-images.githubusercontent.com/26526517/49887624-29a5ec00-fe3d-11e8-9d70-151f7a442914.gif)

At the first decapsulation, both the parent interval and the previously encapsulated one are superimposed witch can be confusing.
I then pressed "ctrl+z" to undo the decapsulation, and then decapsulated again.
This time, the previously encapsulated interval is shrieked to the point of a single state, apparently still linked to the common sink but the connection is invisible. Moving it further to the wright and dropping it, it appears like a lone state. Trying to move it some more and the left limit of the invisible sink has moved to the dropping point.

**Comment by jcelerier** [comment]
should be fixed now
