### ISSUE TITLE
True-False remote in device-explorer validation problem

### ISSUE THREAD

**Issue by reno-** [ossia/score#89]
When I change the state of a boolean using device-explorer's True/false menu, the value is not sent before I click on another raw/parameter

**Comment by jcelerier** [comment]
I checked this but this is due to the way Qt handles it : you have to press enter after changing a value  (we don't really have control over this - we could do it by replacing a lot of Qt-specific classes but certainly not in time for 1.0).

**Comment by reno-** [comment]
ok. I didn't notice that behavior when using QComboBox in my python apps, but I guess it is due to some other stuffs in the device explorer… Thanks to have had a look

**Comment by jcelerier** [comment]
Yep, it's not QComboBox at all but the QItemDelegate for a bool QVariant provided by QTreeView / QListView / ...

**Comment by bltzr** [comment]
as we cannot really change this, should we close the issue ?
