### ISSUE TITLE
(signed) source tarball

### ISSUE THREAD

**Issue by dvzrv** [ossia/score#895]
It would be great to have a full release tarball (including the API).
To achieve this, I suggest switching to using [git subtree](https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#_subtree_merge) or creating a script, that creates the source tarball from a tag (e.g. [sc3-plugins does it that way](https://github.com/supercollider/sc3-plugins/blob/master/package/create_package.sh)).
Downstream packagers otherwise have to use the git tags directly (which could also work).

Aside from that, I generally advise to sign tags (maybe even commits) and the created assets. The above mentioned script in sc3-plugins does that (using a flag) for the source tarball and can be adapted for ossia-score.

**Comment by jcelerier** [comment]
hi ! thanks, I will look into it, it's really annoying that github doesn't include submodules in the source tarballs. (also sorry for the AUR breakage with the includes spam, looking on it asap)

**Comment by jcelerier** [comment]
hmm, just read (re-read actually) about git subtree, I really don't think that it would be adapted to score because we fairly often commit & push in the submodules (to the original repos), so I'll go the script way

**Comment by jcelerier** [comment]
the latest release tarball should now be ok, now gotta find how to sign it properly

**Comment by jcelerier** [comment]
latest releases are signed :)
