### ISSUE TITLE
weird graphic bug on MIDI pianoroll

### ISSUE THREAD

**Issue by avilleret** [ossia/score#902]
I don't how to reproduce but it looks like : 

![pianoroll-bug](https://user-images.githubusercontent.com/504914/52625889-4ea4f280-2eb2-11e9-9beb-e9bd027514f9.png)

which is nice but useless :-)

on macos fresh build from 1652bd71e

**Comment by jcelerier** [comment]
hmm interesting ! @blueyeti I suppose that this is the same problem that you saw ?
