### ISSUE TITLE
crash when opening new device in ossia-pd

### ISSUE THREAD

**Issue by avilleret** [ossia/score#906]
here is the backtrace :
https://gist.github.com/avilleret/63ecd37df56c826114d43d890e4f66ba

**Comment by jcelerier** [comment]
by any chance, is libossia at the latest commit ?

**Comment by avilleret** [comment]
certainly not

**Comment by jcelerier** [comment]
still happening ?

**Comment by jcelerier** [comment]
been using ossia-pd a few times since them without issues, let's reopen if that is still the case
