### ISSUE TITLE
crash when opening scenario while devices are not yet available

### ISSUE THREAD

**Issue by avilleret** [ossia/score#907]
https://gist.github.com/avilleret/81da9c9a5d97676a0acf1074a4e42800

**Comment by avilleret** [comment]
but the second time, it worked

**Comment by avilleret** [comment]
scenario is here : https://raw.githubusercontent.com/avilleret/FourFor/0c61cbce9b41ebe4a78b58c43b3c7a93d19d7a72/score/FourFor.score

**Comment by avilleret** [comment]
if still crashes with : 
https://gist.github.com/avilleret/cb10c02f63c2737a29326a9735d1ce52

**Comment by avilleret** [comment]
it still crashes with 4784a19c6 and API 1.0.0-b15-1136-g41388f0fe (I don't know why there is this tag as a prefix, this is returned by `git describe --always`)

https://gist.github.com/avilleret/93f46baef8b2184e787d325979956231

**Comment by jcelerier** [comment]
is it still the case ?

**Comment by jcelerier** [comment]
closing, please reopen if this still happens
