### ISSUE TITLE
crash when closing OXE fm Synth vst gui on MacOs

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#911]
here is the log :

score[1060:33742] It does not make sense to draw an image when [NSGraphicsContext currentContext] is nil.  This is a programming error. Break on void _NSWarnForDrawingImageWithNoCurrentContext(void) to debug.  This will be logged only once.  This may break in the future.
Memory fault

pluggin downloaded from :
https://oxesoft.wordpress.com/

tested on macos 10.14
score version 2.1.3

**Comment by thibaudk** [comment]
Same problem with [FM8](https://www.native-instruments.com/fr/products/komplete/synths/fm8/).
tested on score 2.4.1 release.

**Comment by jcelerier** [comment]
seems to work now, I tried to close it and reopen it tons of time and i did not get any crash
