### ISSUE TITLE
process suppression workflow is quite tedious

### ISSUE THREAD

**Issue by avilleret** [ossia/score#917]
here is what I have to do to delete a process on an interval with several processes :

- I select the interval 
- then I select the process I want to delete in the inspector, 
- and hit 'suppr' on my keyboard, 
- then the whole interval is deleted
- ctrl+z to undo
- the interval reappear without the process I want to delete

:-)

**Comment by jcelerier** [comment]
huh ? you just have to select the process and press backspace (I just pushed a commit to change it to suppr on non-apple platforms):  
![suppression](https://user-images.githubusercontent.com/2772730/55578411-239e8880-5716-11e9-8a56-30334cc7cfbb.gif)

**Comment by jcelerier** [comment]
ping

**Comment by thibaudk** [comment]
Backspace does not work anymore for deleting anything, only "suppr" does it (on Ubuntu).
witch is a problem for less usual keyboard configurations (running Linux with an apple keyboard for example). 

Maybe both should always be work ?

**Comment by jcelerier** [comment]
>  (running Linux with an apple keyboard for example).

in that case fn+backspace should produce the suppr. key

**Comment by avilleret** [comment]
it seems to be fixed
