### ISSUE TITLE
add a shortcut to remove trigger

### ISSUE THREAD

**Issue by avilleret** [ossia/score#919]
currently I have to right clic and go to events menu to disable the trigger
I used to use suppr when selecting trigger on the scenario (but that was buggy, when the trigger was selected from the inspector, suppr key didn't work)

**Comment by bltzr** [comment]
suppr seems the way to go - It used to work this way, right (when you redesigned it, 2 years ago ±), right ?

**Comment by jcelerier** [comment]
fixed in 2.2.1
