### ISSUE TITLE
Create Curve doesnt set correctly values in states

### ISSUE THREAD

**Issue by nvuaille** [ossia/score#92]
When creating curves with many address selected, the start/end state inspector display a value for only one address, even if all of them are displayed.

**Comment by theod** [comment]
I guess you are the one who can fix this @nvuaille ?

**Comment by jcelerier** [comment]
I just checked and it seems that it works as intended ?
![iscore](https://cloud.githubusercontent.com/assets/2772730/12752362/7f69a5b2-c9c2-11e5-9cfd-90c5bd789633.png)

**Comment by nvuaille** [comment]
The bug I saw isn't here anymore, nice !
