### ISSUE TITLE
Encapsulate error message 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#933]
The folowing little scenario causes error pop ups each time the pattern loops.
It was created by first making the tree conditions attached to the origin and then applaying the "put in a loop" function. This function de'synchronized the first interval from the orrigin.
This error appeared after reconnecting the loop to the origin. and can be reproduced with folowing the same steps :  
* creating intervals from origin
* putting them in a loop
* reconnecting the loop to the origin

![vokoscreen-2019-04-08_12-18-06](https://user-images.githubusercontent.com/26526517/55716917-70c17980-59f8-11e9-848b-936cb018f98d.gif)

**Comment by thibaudk** [comment]
Now works !

**Comment by jcelerier** [comment]
hmmmmmm.... very weird I did not change anything related to this

**Comment by thibaudk** [comment]
I couldn't replicate the error message with 2.2.3.

**Comment by jcelerier** [comment]
and it reliably not works with 2.2.2 ?

**Comment by thibaudk** [comment]
I'll try to pin point exactly where it stops working

**Comment by jcelerier** [comment]
thanks !

**Comment by thibaudk** [comment]
This seem to be an os specific issue related to the states of dependencies.
It is currently back on 2.5.2 but I am almost certain it worked a few days ago, before a few system updates. 
It happens both on the release and when built from source.

**Comment by thibaudk** [comment]
Ok, after a very fortunate try, I discover that the error is not prompted if the scenario is dragged and dropped onto another interval.

The issue with that scenario happens when played in it's initial interval.

**Comment by jcelerier** [comment]
ah, interesting ! thanks
