### ISSUE TITLE
Left side windows resize dosen't stick

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#934]
![vokoscreen-2019-04-08_12-21-39](https://user-images.githubusercontent.com/26526517/55717165-065d0900-59f9-11e9-912b-c037503b6c23.gif)

Strangely, It can be fixed by closing the right side windows.

**Comment by jcelerier** [comment]
huh, I tried but I cannot reproduce this one

**Comment by jcelerier** [comment]
closing because I think it's fixed, isn't it ?

**Comment by thibaudk** [comment]
Yes it is,
Well done !
