### ISSUE TITLE
Loop only sends the right messsaes the first time around 

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#938]
![vokoscreen-2019-04-27_16-40-56](https://user-images.githubusercontent.com/26526517/56851427-8945f500-690f-11e9-8fa2-9713d323adfd.gif)

Creating a sequences of states, each containing a different osc list, inside a looped scenario works every time, on the first play.
Once the sequence repeats, all messages are empty lists.
This happens every time the sequence repeats on play, weather it is finished or not.

Tested with both osx 2.2.1 release
and Ubuntu 19.04 on commit 210374a

**Comment by jcelerier** [comment]
well sh**
