### ISSUE TITLE
QML Devices not responding

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#941]
Neither ".split" nor "return" seem to work anymore inside the "onMessage" function of QML devices (WS, Serial).
  
With the [HTTP example](https://github.com/OSSIA/score-user-library/blob/master/Devices/HTTP/BordeauxWeather.qml#L23), the return function seem to work fine from inside the tree.

tested with score commit
c1d6eb55d5f3bbbf7cfb5ac1d144019359a3f2de
libossia commit
be47be9782696b0de56efa293b8cc1b968d852ef

as wel as release v2.2.3

**Comment by jcelerier** [comment]
could you fix this ?
