### ISSUE TITLE
[ui] info panel should have a fixed width

### ISSUE THREAD

**Issue by avilleret** [ossia/score#945]
or at least a minimum width, currently it's changing every time :

![score-info-panel-2019-05-09_11 49 50](https://user-images.githubusercontent.com/504914/57444731-16167a00-7251-11e9-8007-796d77d12d46.gif)

**Comment by jcelerier** [comment]
hmm, I added a minimum width, I can't set a fixed one else it would not be possible to resize the inspector anymore
