### ISSUE TITLE
Please add cmake variables allowing to use external packages

### ISSUE THREAD

**Issue by yurivict** [ossia/score#946]
I already have packages that are bundled installed as packages on FreeBSD.
Obviously, bundling isn't scaleable because if every package would bundle all its dependencies, a lot of low-level packages would be installed exponentially many times, overfilling the disk.

Please add cmake variables ```USE_EXTERNAL_xx``` to use externally installed dependency packages in ```score``` and ```libossia``` repositories.

Thank you,
Yuri

**Comment by jcelerier** [comment]
Hello,
what are you trying to do ? 
If you follow this build procedure: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ossia-score

then the install step (`cmake -DCMAKE_INSTALL_DO_STRIP=1 -DCOMPONENT=OssiaScore -P cmake_install.cmake`) will only install the ossia-score binary on your system, not the various boost & similar includes.

**Comment by yurivict** [comment]
> what are you trying to do ?

I am trying to create a FreeBSD port for ```ossia```.

**Comment by jcelerier** [comment]
that's very nice, thanks ! does the script I linked help ? on Arch Linux it only installs those files : 


    /usr/bin/ossia-score
    /usr/bin/ossia-score-vstpuppet
    /usr/share/
    /usr/share/applications/
    /usr/share/applications/ossia-score.desktop
    /usr/share/licenses/
    /usr/share/licenses/ossia-score/
    /usr/share/licenses/ossia-score/LICENSE
    /usr/share/pixmaps/
    /usr/share/pixmaps/ossia-score.png

**Comment by yurivict** [comment]
Many bundled packages exist in ports: ```gsl```, ```RtMidi```, ```tbb```, ```websocketpp```, ```pybind11```, ```rapidjson```, among others.

Some of them likely require patches to build, which need to be all redone just for this bundling.
Also what would happen if a security issue is found in one of them? We would need to look for all instances of its bundling and fix it in dozens of places? This doesn't work well.

It is also very difficult to create and maintain a port where lots of other software is bundled.

**Comment by jcelerier** [comment]
> Some of them likely require patches to build, which need to be all redone just for this bundling.

well, if you look at the veresion of rtmidi, tbb, websocketpp, weakjack, oscpack, etc... that we use, you'll note that they are patched too because they won't work as-is (in particular, rtmidi and oscpack were almost entirely rewritten) so it's not going to work either.

**Comment by jcelerier** [comment]
> Some of them likely require patches to build, which need to be all redone just for this bundling.

well, if you look at the veresion of rtmidi, tbb, websocketpp, weakjack, oscpack, etc... that we use, you'll note that they are patched too because they won't work as-is (in particular, rtmidi and oscpack were almost entirely rewritten) so it's not going to work either.

**Comment by jcelerier** [comment]
this has been done for quite some time with -DOSSIA_USE_SYSTEM_LIBRARIES=1 cmake option. see https://github.com/ossia/score/issues/1476 for all the work surrounding this :)
