### ISSUE TITLE
Dummy stuck at 44100 Hz

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#947]
A scenario is executed noticeably faster when switching from Jack audio driver running at 48 khz,
to the dummy option, even set at 48 khz as well.

**Comment by jcelerier** [comment]
hmmmm weird, I just tried the dummy and could not reproduce at any rate (but the rate parameter should be removed anyways since it is meaningless for this

**Comment by thibaudk** [comment]
Seems to be fixed.
