### ISSUE TITLE
crash on one specific trigger on this scenario

### ISSUE THREAD

**Issue by pach** [ossia/score#948]
Didn't happened all the time but about 20-30% of the time I trigger the Ascension_part3 trigger of attached scenario, score crash with attach report.

Crash and report in attach zip as Gist doesn't want to work the last days for me (405 error when trying to upload anything on it).

[asc2.3.1.zip](https://github.com/OSSIA/score/files/3170047/asc2.3.1.zip)

**Comment by jcelerier** [comment]
ok, I can reproduce it

**Comment by jcelerier** [comment]
not a simple one to fix though !

**Comment by jcelerier** [comment]
fixed by https://github.com/OSSIA/libossia/commit/06fa53462e95f444623318cc4be2fdcc80663c48
