### ISSUE TITLE
freeze when adding vst path after drawing an interval (archlinux/gnome)

### ISSUE THREAD

**Issue by pchdev** [ossia/score#953]
clicking in "Settings > Effects > Add path" works fine on startup, but it freezes after having played a scenario

note: if there are no intervals at all in the scenario, it works normally
this is on archlinux/gnome

**Comment by jcelerier** [comment]
hmm weird, I can't reproduce it. going to check with GNOME.

**Comment by jcelerier** [comment]
works fine on GNOME too... by any chance do you have any other computer that you can test on ? can you also maybe send me the list of VSTs you have ?

**Comment by pchdev** [comment]
ok, hm except for my mac, I have nothing else to test it on really
I'll send you the list asap, but I have some windows-vsts that I bridge with linvst. then again, even if they're not in the list of vst paths, I still have the same bug it seems

**Comment by pchdev** [comment]
correction: it seems that it has actually nothing to do with playing,
the 'Add path' button dialog freezes as soon as I draw an interval in the scenario
if I remove the interval, it works again

I have only the Carla stuff in /usr/lib/vst (CarlaPatchbay, CarlaRackFX, etc.)

edit: It's not really a freeze either, because pressing 'Esc' cancels the action normally, it's just that the dialog window does not show itself and the settings menu becomes grey.

**Comment by jcelerier** [comment]
hmm, that sounds a bit similar to that issue : https://bugreports.qt.io/browse/QTBUG-59184

**Comment by pchdev** [comment]
hmm yep might be it,
anyway its a really minor issue, no need to spend too much time on that, especially if it's a qt bug :)

**Comment by jcelerier** [comment]
from a comment on that issue it seems to be fixed by forcing the usage of the qt file dialog, will try setting that
