### ISSUE TITLE
Rework UI for slider-based processes

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#957]

**Comment by jcelerier** [comment]
proposal :
![sliders](https://user-images.githubusercontent.com/2772730/57980556-39011500-7a2d-11e9-8aa3-9ad2bd0b8bb3.png)

**Comment by bltzr** [comment]
so you want to make score look like live ? ;-p

**Comment by jcelerier** [comment]
it's not my proposal :p

**Comment by jcelerier** [comment]
but if anyone has ideas on how to make the slider UIs smaller... because currently it's quite bloated and inefficient

**Comment by jcelerier** [comment]
done for some processes, other will be added on a case-per-case basis
