### ISSUE TITLE
CPU spike when interals are visible

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#958]
![vokoscreen-2019-05-22_19-10-01](https://user-images.githubusercontent.com/26526517/58194686-7fbd6c00-7cc6-11e9-8e73-ca3ab32c3f0d.gif)

As shown above, there is a clear cpu spike whenever an interval is visible, even without playing and without any processes in it.
Simply scrolling down enough to hide the interval brings cpu usage back down.

**Comment by bltzr** [comment]
I gues that’s what one calls having a sharp eye!!!

**Comment by jcelerier** [comment]
thanks for noticing that one !
