### ISSUE TITLE
crashlog

### ISSUE THREAD

**Issue by avilleret** [ossia/score#96]
can't remember what i was doing, but I'm sure you will guess :-)

https://gist.github.com/avilleret/55504f9e076f99e3ad5d

**Comment by nvuaille** [comment]
I guess i found : the value field does not support non numerical entry ...

**Comment by theod** [comment]
is it relative to OSSIA::Value or to Qt ?

**Comment by nvuaille** [comment]
It was an interface bug, I fixed it in dev (8fe3c804f30a436f628c057e67dfe3d682c41085)
