### ISSUE TITLE
minimap issues

### ISSUE THREAD

**Issue by bltzr** [ossia/score#960]
since the recent improvements to the minimap (or maybe that was already there for a while ?)

- the cursor disappears when clicking into the selection
- the cursor is *very* quick
this is on the Mac

- also I find it hard to see intervals, esp. when in the selection (very low contrast between intervals and background)

**Comment by jcelerier** [comment]
fixed points 2/ and 3/ ; point 1/ is normal - the cursor is hidden because it is simulating an infinite motion (which would be very ugly to look at)
