### ISSUE TITLE
Error building score on raspberry pi 2 model B

### ISSUE THREAD

**Issue by VincentParadis** [ossia/score#964]
I have some error building score on a raspberry pi 2.

I'm following this doc to build : https://github.com/OSSIA/score/wiki/Build-and-install

When I write this line in the command  :

`sudo apt -y install git cmake wget ninja-build libqt5websockets5-dev qtbase5-dev qtdeclarative5-dev qt5-default qtbase5-dev-tools qttools5-dev libqt5svg5-dev g++-7 libportmidi0 libasound-dev mesa-common-dev libboost-dev libavahi-compat-libdnssd-dev`

I get this message :
Reading package lists.... Done
Reading state information... Done
Note, selecting 'libasound2-dev' instead of 'libasound-dev'
E: Unable to locate package g++-7
E: Coudn't find any package by regex 'g++-7'

I'm on stretch for my pi.

I tried to compile the g++ with this walkthrough but I'm having some difficulties since I'm a beginner with linux and the raspberry pie. https://solarianprogrammer.com/2018/05/06/building-gcc-cross-compiler-raspberry-pi/

Any one tried recently to build score or have any idea what is the problem?

**Comment by avilleret** [comment]
Indeed `gcc-7` is not available for armhf on stretch.
We should update the wiki.
But you can download `gcc-8` binaries for raspberry pi  here :
https://github.com/inares/gcc-for-raspberry

Then remove `gcc-7` from the `apt install` call.
And adapt the `-DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DCMAKE_C_COMPILER=/usr/bin/gcc-7` to point to `gcc-8` and `g++-8`

**Comment by jcelerier** [comment]
done, please use the sdk in there in order to build : https://github.com/OSSIA/sdk/releases/tag/embedded-sdk1

a build script is available here : https://github.com/OSSIA/score/tree/master/cmake/Deployment/Linux/Raspberry (not yet 100% reliable, but I should get there by the end of the week) and a build has been uploaded for the latest release
