### ISSUE TITLE
automation doesn't play

### ISSUE THREAD

**Issue by avilleret** [ossia/score#97]
to reproduce on a new score with a Max device :
1. select a namespace node
2. Command + Click to create an event with node values
3. change node value in Max or in namespace browser
4. create a new event with an automation box with Command + Shift + Click & Drag

This should create a box with curve and I expected to see value changing when playing.
The values stored in event are sent when the play bar reach the event but there is no interpolation between them.

**Comment by nvuaille** [comment]
Is the curve created in the view ?

**Comment by avilleret** [comment]
yes 
![image](https://cloud.githubusercontent.com/assets/504914/11714105/efe4bdf0-9f37-11e5-9e0f-9254056d798f.png)

**Comment by nvuaille** [comment]
So it's the same as #84 , fixed in dev
@theod, @jcelerier  : I think we should not close issue before fix appears in release ...

**Comment by theod** [comment]
oops ! this is my fault.
however it is possible to merge the #84 fix from dev to master as it was pretty important bug ?

**Comment by jcelerier** [comment]
@theod which commit is it ? I think that I did it this week-end.
The API in i-score/master is at API/master

**Comment by theod** [comment]
it is this one : https://github.com/OSSIA/API/commit/d91b19f98fcb14892a2c0113529c414799c39f73
