### ISSUE TITLE
Strange Ui issue somhow related to faust dependencie

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#970]
![vokoscreen-2019-08-22_00-57-28](https://user-images.githubusercontent.com/26526517/63474026-d9753400-c477-11e9-842a-1ce0efc9b87b.gif)
![vokoscreen-2019-08-22_00-58-17](https://user-images.githubusercontent.com/26526517/63474062-fad62000-c477-11e9-833a-f81bfdd43045.gif)

tested with faust commit b39c5e893f80d042e41a32a9ac200e90d44ba71b
with score 4bd5f28275e95d0fc6fa02104a8fb61e3e8c964a 
and Ubuntu 19.04

**Comment by thibaudk** [comment]
seems like the origin is reveresed
![vokoscreen-2019-08-22_22-57-47](https://user-images.githubusercontent.com/26526517/63549275-61b71000-c530-11e9-970a-ce3d8ab6093c.gif)

**Comment by jcelerier** [comment]
does it do this every time ?!

**Comment by jcelerier** [comment]
> double click on the map doesn't resize to fit but shriks evrytime

this is a separate "bug" of the minimap

**Comment by thibaudk** [comment]
Yes, this hapens every time when built with faust.
Removing the libfaust.a dependencie in the cmake fixes it evry time.

(yes the minimap shows the same behavior without faust, sorry, I have edited the comment)

**Comment by thibaudk** [comment]
closed by mistake

**Comment by thibaudk** [comment]
reverting to older faust commits, on master and master-dev dosen't seem to change anything.

**Comment by thibaudk** [comment]
The same problem still accures starting from scratch with a fresh install of ubuntu 19.04.
Could it be an issue of llvm version ?
As faust has to be built with llvm backends

**Comment by thibaudk** [comment]
commit b686672 fixed the issue along with crashes occurring when opening some lv2 UI (namely Calf's & Guiatrix's)

After running into the same problem with the previous score commit and the current libossia commit. We can conclude that libossia is not implicated here.

This issue will be closed once the cause has been properly identified

**Comment by thibaudk** [comment]
Currently works with the latest commit 
745a649

On faut master branch 
b39c5e8
and still broken master-dev 
6672150

**Comment by thibaudk** [comment]
The issue can be narrowed down to this single line:
https://github.com/OSSIA/libossia/blob/master/src/ossia/network/generic/wrapped_parameter.hpp#L164

commenting it out fixes it

**Comment by thibaudk** [comment]
accidentaly closed

**Comment by thibaudk** [comment]
Building with clang instead of gcc fixes the problem.
Closing now.
