### ISSUE TITLE
Stuck in one mode

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#972]
Among all the selection possible (states, processes, values, addresses...),
some issues arise with the loss of selected objects, or a "wrong" combination of selection.

This seems to be the cause behind impossibilities to select modes (select, create, play from here) in some cases, and in others, more rare, inabilities to perform basic tasks like drawing an interval.

This example shows first the inability to enter creation mode with "c" (icons filckering), and the "+" sign not respomding when trying to draw an interval (provided by Jean-Marie Colin)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/26526517/63794811-0192e600-c903-11e9-9090-4d2baca0fae2.gif)

trying to click away and somehow clear the selection with another may fix this sometimes.

Maybe giving some sort of priority to basic functionalities, overwriting any unrelated selection would prevent this sort of issues. 

Just a verry uninformed thought.

**Comment by thibaudk** [comment]
tested with both v 2.4.1 and 2.5.2 on osx

**Comment by jcelerier** [comment]
can you send me the score ? I have this bug sometimes but am never able to reproduce it in order to debug it

**Comment by thibaudk** [comment]
We also find it verry hard to reproduce and it dose'nt appear to be specific to a certain score.

The one we where working on is this case can be found here :
https://github.com/scrime-u-bordeaux/SoloK/blob/master/SoloK_01.score
the bug should not be present straight away but after a good few manipulations

**Comment by pach** [comment]
generally closing and reopening score correct the issue. So it seems not linked to the project file but to the apps to me.
Never been able to find any regular way to reproduce it. Just happened sometimes.

**Comment by thibaudk** [comment]
Entering into a process in "Full wiew", then going back out again seems to reset the cursor state most of the time.

**Comment by thibaudk** [comment]
It seems that mouse modes and the ability to create intervals by dragging the '+' from a state can be restored when a device or a parameter in the "Device explorer" is selected.
Could this issue be related to sequences that are looking for values in the "Device explorer" to create automatons ?

note : the issue accrued with "autos-equence" off

**Comment by jcelerier** [comment]
there's been a lot of change in these areas, if you can check the latest build (or the next release) ?

**Comment by thibaudk** [comment]
I wasn't able to reproduce it yet on v3.
Closing it, At least for now.
