### ISSUE TITLE
Opening Score causes multiple instances to launch

### ISSUE THREAD

**Issue by evanmtp** [ossia/score#975]
Opening the Score 2.5.2 application causes multiple instances of Score to launch. These are visible as distinct instances in Activity Monitor, although all but one of them is frozen:

<img width="708" alt="Screen Shot 2019-10-13 at 10 37 19 AM" src="https://user-images.githubusercontent.com/5342408/66717336-e2aebd00-eda5-11e9-8297-59d07c7b7b48.png">

This is also visible in the dock:

<img width="150" alt="Screen Shot 2019-10-13 at 10 40 13 AM" src="https://user-images.githubusercontent.com/5342408/66717334-e04c6300-eda5-11e9-8e48-80bb7f166ff8.png">

Tested on macOS 10.14.6, mid-2014 MacBook Pro.

**Comment by jcelerier** [comment]
fixed - these secondary instances were the VST scanners, they will now be hidden. Thanks !
