### ISSUE TITLE
Problem during install on Fedora

### ISSUE THREAD

**Issue by ycollet** [ossia/score#978]
I compile / install ossia score from the master branch on Fedora 30 64 bits.

On Fedora 64 bits, libraries are installed in /usr/lib64 and not in /usr/lib.

We should be able to parametrize the installation using a cmake variable llike CMAKE_LIB_DIR ..

**Comment by ycollet** [comment]
I just managed to build Ossia for Fedora 30 / 31:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/build/1089412/
The spec file can be found here:
https://github.com/ycollet/fedora-spec/tree/master/ossia

**Comment by jcelerier** [comment]
Thanks for your work ! I'll try to check the spec file if I see anything that can be improved. In particular, in a normal build no libraries should be installed at all, only the ossia-score and ossia-score-vstpuppet binaries + the stuff in /usr/share

**Comment by jcelerier** [comment]
let's track this in the meta-issue for packaging : https://github.com/ossia/score/issues/1476
