### ISSUE TITLE
Timeline is not scaled to the event position.

### ISSUE THREAD

**Issue by avilleret** [ossia/score#98]
1. set the zoom to the minimum value to see the whole score
2. create a new event
3. move it outside the timeline view
4. now it's lost, you can't zoom out more, you can't scroll to the right, you can't select the event even to delete it, the only way to remove it is to undo

**Comment by nvuaille** [comment]
Hmm. 
The auto scroll/resize is on the wishlist. 
As workaround, one can : 
- resize the main constraint (in "keep duration mode")
- resize the constraint ending on this event (set duration in constraint inspector)
- access to the event inspector (select previous constraint, click on "end state" then on "parent event".
  Object in inspector = object selected so you can now delete it.

**Comment by jcelerier** [comment]
now this should be fixed since the timeline is infinite
