### ISSUE TITLE
OSC latency when score in background

### ISSUE THREAD

**Issue by pach** [ossia/score#980]
When score is running in background, there is a latency on OSC that slowly increase. 
No issue with OSCQuery protocol (doesn't try other one) but command received from ipad are responding slower and slower with time (longer you wait, bigger is the latency).
Latency came back to correct, as soon as score is coming back on top app.

**Comment by jcelerier** [comment]
I'm wondering if this isn't a side effect of macOS's appnap feature.

do you think you could test that ? 

http://osxdaily.com/2014/05/13/disable-app-nap-mac-os-x/

**Comment by pach** [comment]
je regarde et te dis.

**Comment by jcelerier** [comment]
merci !

**Comment by pach** [comment]
Quelques tests hier avec le app-nap désactivé.
A premiere vue cela à l'air mieux, mais j'ai manqué de temps pour vraiment pousser le test. Je continue à regarder tranquille.

**Comment by pach** [comment]
ok, so it happened again today, while score was in foreground. So it's coming from something else.
i also when it happened had the issue than only one of my device was visible on the device tree (all the other where existing as score was able to control everyone but hidden somewhere).

**Comment by pach** [comment]
OK, je retrouve le soucis dans un intervalle de mapping sur le projet joint, que score soit au premier ou à l'arriere plan.
- cf interval.juke3.1 à l'interieur de interval.solo51
je n'ai pas de soucis si je sors l'interval de ce score.
https://drive.google.com/open?id=1GGYQlq3C6lgiW_e_zMriHr5b5gn8Ip41

**Comment by jcelerier** [comment]
I think I finally got it, there's an additional semi-hidden "low-latency" option to enable in macOS internals, which I just did. :)
