### ISSUE TITLE
[feature request] update states button

### ISSUE THREAD

**Issue by pach** [ossia/score#981]
One thing could be really super usefull to gain a lots of time when arriving in a new venue, being able to update all or parts of recorded nodes in a state.
For example :  I could got plenty of light level, and at each venue I want to correct them. So as I'm triggering all my state, I can correct my level from the oscquery controlled software, and then just clic update on the state and all (or only the selected nodes) inside the state updates their values to the current one in the device tree.

**Comment by pach** [comment]
eventually, could be a right clic on states node / update node.

**Comment by bltzr** [comment]
isn't that what the current update button does ?

**Comment by pach** [comment]
where is that button?

**Comment by pach** [comment]
OMG! refresh state!...

**Comment by bltzr** [comment]
RTFM: https://ossia.github.io/score/howtos/update_state/index.html

**Comment by bltzr** [comment]
:-p
