### ISSUE TITLE
midi + audio inlets on pluggins

### ISSUE THREAD

**Issue by thibaudk** [ossia/score#989]
no pluggins seem to be able to feature both a midi inlet and a audio inlet.
Enabling midi on Faust dsp's will remove the existing audio inlet.

Vsts and lv2s that feature both audio and midi inputs like samplev1 and VCVBridge are only able to receive midi in score as the audio inlet doesn't appear.

**Comment by jcelerier** [comment]
So, I can tackle this one... but this will break the save format :-/ is that ok ?

**Comment by thibaudk** [comment]
Well, scores written before V3 can't be loaded anyway so ... not a problem ;)

**Comment by jcelerier** [comment]
done !

**Comment by thibaudk** [comment]
:+1:
