### ISSUE TITLE
green bar is not rescaled when moving slot

### ISSUE THREAD

**Issue by avilleret** [ossia/score#99]
on a score, start playing, then pause
a green bar is drawn on top of played events,
try to move an event on the green line, then the line is split

**Comment by nvuaille** [comment]
Wow. 
Edition should not be enable during execution ...

**Comment by theod** [comment]
just as a side note : in the future we should be able to edit any content which is not playing (in the past or in the futur) as it is particularly useful for rehearsal situation to not ask to people on stage to stop playing when you see a problem into your scenario.

**Comment by theod** [comment]
but maybe here the solution is too properly lock the edition while scenario is playing ?

**Comment by nvuaille** [comment]
Commit 7806f19971594f07d26d27da021c022c3ff5adbb in dev lock edition during the execution.
I think that editing content (= states, curve, ...) that's not playing is not a big problem but editing past temporal structure ... I fear that's not so easy !

**Comment by jcelerier** [comment]
theod: what would happen if by dragging an event in the future it changes the position of the currently playing constraint as the CSP should do ?

**Comment by theod** [comment]
from the API point of view changing positions should be ok as everything is relative to time constraint durations. then I would say the only things you cannot do at execution is to change durations of contraints which are currently running. but this is theory and we need to make it real to raise true issues !

**Comment by jcelerier** [comment]
I'm closing this issue to continue the discussion in a more relevant task.
