### ISSUE TITLE
Application rapidly spawns and kills duplicate applications

### ISSUE THREAD

**Issue by alexdmiller** [ossia/score#992]
Operating system: macOS 10.14.5 (Mojave)
Computer: Macbook Pro, Mid 2015

Opening the Score application on macOS causes many identical-looking applications to spawn. These applications die and spawn very rapidly, causing the application (and entire computer) to be unusable.

Here's a gif showing what this looks like:

![image](http://spacefiller.space/misc/output.gif)

**Comment by jcelerier** [comment]
hello, thanks for testing ! 
the "spamming" apps are individual processes which scan the VSTs on your machine outisde of the main score process thus their short life (it is done that way because some VSTs will sometimes crash on startup). 

Ideally they should not be visible but I do not know how to make that happen on macOS... will investigate.

**Comment by alexdmiller** [comment]
Ah I see. It seemed to go on indefinitely, although I do have a lot of VSTs, so I'll try again and just wait. Will this happen every time on start up?

**Comment by jcelerier** [comment]
no, it should be only the first time (hopefully, else it's a bug)

**Comment by alexdmiller** [comment]
Okay that makes sense! I think it would help to have a loading bar or just some text that explains what's happening.

**Comment by alexdmiller** [comment]
(Just wanted to confirm that indeed this only happened the first time. I just hadn't waited long enough for the process to finish.)

**Comment by jcelerier** [comment]
right, thanks. I'll try to see if it's possible to integrate the progress in the splash screen or something like that

**Comment by jcelerier** [comment]
fixed, the "spawned processes" won't show up in the dock anymore and should be less resource intensive. thanks !
