### ISSUE TITLE
OSCQuery parameter names with spaces int hem cause score to hang

### ISSUE THREAD

**Issue by alexdmiller** [ossia/score#994]
When I click and drag a single parameter, everything works fine. If I select more than one parameter and drag them, the app temporarily hangs. I get a spinner, and then eventually get the "pointer + rectangle" cursor.

Video demonstrating this [here](http://spacefiller.space/misc/slow-example.mov).

(In this video, first I drag a single parameter to demonstrate how quickly the cursor changes. Next, I drag two parameters. Watch how long it takes for the cursor to change — during this time, the app is unusable. For part of this time, there is a spinner, but the screen recording evidently does not record spinners.)

Note that this only happens with an **OSCQuery** device. If I manually add multiple parameters to an **OSC** device, then no such hanging occurs.

Possibly related: after exiting OSCQuery device dialog, the menu bar headers don't reappear. Video [here](http://spacefiller.space/misc/no-menu.mov). If this isn't related, I can open a separate bug for it.

Machine: macOS 10.14.6, 2015 Macbook Pro
Score 2.5.2

**Comment by alexdmiller** [comment]
Further relevant information:

This bug happens when trying to add an OSCQuery connection to an openFrameworks app I built using ofxOscQuery. However, the bug does not occur with other OSCQuery enabled applications.

When I run my openFrameworks application, I see the following message:

```
[warning] Could not set TCP nodelay option
```

I'm wondering if this is the source of the issue?

**Comment by alexdmiller** [comment]
Okay, figured out the problem: my parameter names had spaces in them. Might want to consider displaying an error message in this case?

**Comment by jcelerier** [comment]
hmmm, names with spaces are supposed to be supported (there was actual work on that a year or so ago so at some point I'm sure it worked.) So this is an actual bug - thanks.

**Comment by jcelerier** [comment]
it seems that this is because some method calls go through HTTP when refreshing, and spaces aren't correctly corrected to %20 at some point.
