### ISSUE TITLE
MIDI: possibility to use JACK instead of ALSA on linux

### ISSUE THREAD

**Issue by jcelerier** [ossia/score#995]
in order to connect to other JACK MIDI apps easily.

**Comment by thibaudk** [comment]
:+1:

**Comment by jcelerier** [comment]
done ! it's now possible to choose which midi backend is gonna be used. @thibaudk can you please test all the backends thoroughly if you have some time ?

**Comment by thibaudk** [comment]
Cheers !! 
Yes I'll test it out with as many configurations as I can think of
